[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/about"
  to = "/igor-vepretski/"
  status = 301
  force = true

[[redirects]]
  from = "/about/"
  to = "/igor-vepretski/"
  status = 301
  force = true
