import {db} from '@appdeploy/sdk';
import {canonicalCorpusSeed,CanonicalCorpusQuery,CanonicalEvent,queryCanonicalCorpusItems,validateCanonicalEvent} from '../shared/canonical-corpus';
import {mergePublicRegisterIntoCanon} from '../shared/public-register-canon';
import {mergeDigitalCompendiumIntoCanon} from '../shared/digital-compendium';
const TABLE='canonical_corpus_overlay';const MAX_OVERLAY_ROWS=500;
type OverlayRecord={canonicalId:string;event:CanonicalEvent;ownerUserId:string;updatedBy:string;updatedAt:number;schemaVersion:number};
export class CorpusValidationError extends Error{}
async function overlayRows(){const page=await db.list<OverlayRecord>(TABLE,{limit:MAX_OVERLAY_ROWS});if(page.nextToken)throw new Error('canonical corpus overlay exceeded the bounded overlay safety window');return page.items}
function validLatest(rows:Array<OverlayRecord&{id:string}>){const ordered=[...rows].sort((a,b)=>Number(a.updatedAt||0)-Number(b.updatedAt||0));const latest=new Map<string,{dbId:string;event:CanonicalEvent}>();let invalidOverlayCount=0;for(const row of ordered){try{const event=validateCanonicalEvent(row.event);if(event.id!==row.canonicalId)throw new Error('canonical id mismatch');latest.set(row.canonicalId,{dbId:row.id,event})}catch{invalidOverlayCount++}}return{latest,invalidOverlayCount}}
export async function readCanonicalCorpus(query:CanonicalCorpusQuery={}){const rows=await overlayRows();const {latest,invalidOverlayCount}=validLatest(rows);const merged=new Map(canonicalCorpusSeed.map(event=>[event.id,event] as const));for(const [canonicalId,entry] of latest)merged.set(canonicalId,entry.event);const base=[...merged.values()];const withCompendium=mergeDigitalCompendiumIntoCanon(base);const digitalCompendiumCount=withCompendium.length-base.length;const unified=mergePublicRegisterIntoCanon(withCompendium);const publicRegisterCount=unified.length-withCompendium.length;const items=queryCanonicalCorpusItems(unified,query);return{items,storage:{mode:'seed+digital-compendium+public-register+db-overlay' as const,seedCount:canonicalCorpusSeed.length,digitalCompendiumCount,publicRegisterCount,overlayCount:latest.size,invalidOverlayCount,overlayLimit:MAX_OVERLAY_ROWS}}}
export async function getCanonicalCorpusEvent(id:string){const rows=await overlayRows();const {latest}=validLatest(rows);const overlay=latest.get(id)?.event;if(overlay)return overlay.visibility==='public'?overlay:undefined;const base=canonicalCorpusSeed.map(event=>latest.get(event.id)?.event||event);const event=mergePublicRegisterIntoCanon(mergeDigitalCompendiumIntoCanon(base)).find(item=>item.id===id);return event?.visibility==='public'?event:undefined}
export async function upsertCanonicalCorpus(value:unknown,ownerUserId:string,actor:string){try{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('body must be an object');const body=value as Record<string,unknown>;const event=validateCanonicalEvent(body.event);const page=await db.list<OverlayRecord>(TABLE,{filter:{ownerUserId},limit:MAX_OVERLAY_ROWS});if(page.nextToken)throw new Error('admin overlay exceeded the bounded overlay safety window');const existing=page.items.filter(row=>row.canonicalId===event.id).sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0))[0];const updatedAt=Date.now();const record:Record<string,unknown>={canonicalId:event.id,event,ownerUserId,updatedBy:actor,updatedAt,schemaVersion:2};if(existing){const [ok]=await db.update(TABLE,[{id:existing.id,record}]);if(!ok)throw new Error('failed to update canonical corpus overlay');return{operation:'updated' as const,dbId:existing.id,canonicalId:event.id,updatedAt}}const [dbId]=await db.add(TABLE,[record]);if(!dbId)throw new Error('failed to create canonical corpus overlay');return{operation:'created' as const,dbId,canonicalId:event.id,updatedAt}}catch(error){if(error instanceof CorpusValidationError)throw error;const message=error instanceof Error?error.message:'invalid canonical corpus record';if(message.startsWith('failed to ')||message.includes('bounded'))throw error;throw new CorpusValidationError(message)}}
