type UnknownRecord=Record<string,unknown>;
export type NvcfCandidate={functionId:string;versionId:string;name:string;status:string;inferenceUrl:string;functionType:string;modelName:string};
export type NvcfTarget={functionId:string;versionId:string;name:string;inferenceUrl?:string;functionType?:string;modelName?:string};
export type NvcfDiscovery={state:'ready'|'ambiguous'|'error';target?:NvcfTarget;candidates:NvcfCandidate[];error?:string};
type FetchLike=(input:string|URL|Request,init?:RequestInit)=>Promise<Response>;
const obj=(value:unknown):UnknownRecord=>value&&typeof value==='object'&&!Array.isArray(value)?value as UnknownRecord:{};
const text=(value:unknown)=>String(value??'').trim();
const rows=(value:unknown,keys:string[]):UnknownRecord[]=>{if(Array.isArray(value))return value.map(obj);const root=obj(value);for(const key of keys)if(Array.isArray(root[key]))return(root[key] as unknown[]).map(obj);return[]};
const statusRank=(status:string)=>/^(ACTIVE|READY|DEPLOYED)$/i.test(status.trim())?0:status?2:1;
const errorMessage=(value:unknown,fallback:string)=>{const root=obj(value),nested=obj(root.error);return text(nested.message||root.message||root.detail||fallback).slice(0,180)};
const jsonBody=async(response:Response)=>response.json().catch(()=>({})) as Promise<unknown>;
export const nvcfInvokeUrl=(functionId:string,versionId:string)=>'https://api.nvcf.nvidia.com/v2/nvcf/pexec/functions/'+encodeURIComponent(functionId)+'/versions/'+encodeURIComponent(versionId);
export const nvcfStatusUrl=(requestId:string)=>'https://api.nvcf.nvidia.com/v2/nvcf/pexec/status/'+encodeURIComponent(requestId);
export const functionRows=(value:unknown)=>rows(value,['functions','items','data']);
export const versionRows=(value:unknown)=>rows(value,['functionVersions','versions','items','data']);
export function candidateFrom(functionRow:unknown,versionRow:unknown):NvcfCandidate{const fn=obj(functionRow),ver=obj(versionRow);const functionId=text(fn.functionId||fn.function_id||fn.id||ver.functionId||ver.function_id);const versionId=text(ver.functionVersionId||ver.function_version_id||ver.versionId||ver.version_id||ver.id);const models=Array.isArray(ver.models)?ver.models.map(obj):Array.isArray(fn.models)?(fn.models as unknown[]).map(obj):[];const firstModel=models[0]||{};return{functionId,versionId,name:text(ver.name||fn.name),status:text(ver.status||ver.functionStatus||ver.deploymentStatus||fn.status||fn.functionStatus),inferenceUrl:text(ver.inferenceUrl||ver.inference_url||fn.inferenceUrl||fn.inference_url),functionType:text(ver.functionType||ver.function_type||fn.functionType||fn.function_type),modelName:models.length===1?text(firstModel.name):''}}
export function selectNvcfTarget(input:NvcfCandidate[]|{candidates?:NvcfCandidate[]}):NvcfTarget{const candidates=Array.isArray(input)?input:Array.isArray(input?.candidates)?input.candidates:[];const valid=candidates.filter(item=>text(item?.functionId)&&text(item?.versionId)).sort((a,b)=>statusRank(text(a.status))-statusRank(text(b.status)));const bestRank=valid.length?statusRank(text(valid[0].status)):99;const best=valid.filter(item=>statusRank(text(item.status))===bestRank);if(!best.length)throw new Error('NVCF discovery found no invocable function version');if(best.length!==1)throw new Error('NVCF discovery is ambiguous: multiple function versions are candidates');const chosen=best[0];return{functionId:text(chosen.functionId),versionId:text(chosen.versionId),name:text(chosen.name),...(text(chosen.inferenceUrl)?{inferenceUrl:text(chosen.inferenceUrl)}:{}),...(text(chosen.functionType)?{functionType:text(chosen.functionType)}:{}),...(text(chosen.modelName)?{modelName:text(chosen.modelName)}:{})}}
export function invocationRequestId(response:{headers:{get(name:string):string|null}},data:unknown){const root=obj(data);return text(response.headers.get('nvcf-reqid')||response.headers.get('NVCF-REQID')||root.requestId||root.request_id||root.reqId)}
async function getJson(key:string,url:string,fetcher:FetchLike){const response=await fetcher(url,{method:'GET',headers:{Authorization:'Bearer '+key,Accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(7000)});const data=await jsonBody(response);if(!response.ok)throw new Error(errorMessage(data,'NVCF HTTP '+response.status));return data}
export async function discoverNvcf(key:string,fetcher:FetchLike=fetch):Promise<NvcfDiscovery>{try{const candidates:NvcfCandidate[]=[];const seenFunctions=new Set<string>();for(const visibility of['private','authorized']){const listed=await getJson(key,'https://api.nvcf.nvidia.com/v2/nvcf/functions?visibility='+visibility,fetcher);for(const fn of functionRows(listed).slice(0,20)){const functionId=text(fn.functionId||fn.function_id||fn.id);if(!functionId||seenFunctions.has(functionId))continue;seenFunctions.add(functionId);const versions=await getJson(key,'https://api.nvcf.nvidia.com/v2/nvcf/functions/'+encodeURIComponent(functionId)+'/versions',fetcher);for(const version of versionRows(versions).slice(0,20))candidates.push(candidateFrom(fn,version))}}const unique=[...new Map(candidates.filter(item=>item.functionId&&item.versionId).map(item=>[item.functionId+'|'+item.versionId,item])).values()];try{return{state:'ready',target:selectNvcfTarget(unique),candidates:unique}}catch(err){const message=err instanceof Error?err.message:String(err);return{state:/ambiguous/i.test(message)?'ambiguous':'error',candidates:unique,error:message.slice(0,180)}}}catch(err){return{state:'error',candidates:[],error:(err instanceof Error?err.message:String(err)).slice(0,180)}}}
function normalizedResult(value:unknown):UnknownRecord{const root=obj(value);if(Array.isArray(root.choices))return root;for(const key of['responseBody','result','data','output']){let child=root[key];if(typeof child==='string'){try{child=JSON.parse(child)}catch{continue}}const nested=obj(child);if(Array.isArray(nested.choices))return nested}return root}
export async function invokeNvcf(key:string,target:NvcfTarget,body:Record<string,unknown>,fetcher:FetchLike=fetch):Promise<UnknownRecord>{const payload={...body,...(target.modelName?{model:target.modelName}:{})};const request=async(url:string,method:'GET'|'POST',requestBody?:Record<string,unknown>)=>fetcher(url,{method,headers:{Authorization:'Bearer '+key,Accept:'application/json','Content-Type':'application/json','NVCF-POLL-SECONDS':'5'},...(requestBody?{body:JSON.stringify(requestBody)}:{}),cache:'no-store',redirect:'manual',signal:AbortSignal.timeout(8000)});let response=await request(nvcfInvokeUrl(target.functionId,target.versionId),'POST',payload);for(let poll=0;poll<5;poll++){if(response.status===302){const location=response.headers.get('location');if(!location)throw new Error('NVCF large result missing location');const large=await fetcher(location,{headers:{Accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(8000)});const data=await jsonBody(large);if(!large.ok)throw new Error(errorMessage(data,'NVCF large result HTTP '+large.status));return normalizedResult(data)}const data=await jsonBody(response);if(response.status===200)return normalizedResult(data);if(response.status!==202)throw new Error(errorMessage(data,'NVCF invocation HTTP '+response.status));const requestId=invocationRequestId(response,data);if(!requestId)throw new Error('NVCF pending response missing request id');response=await request(nvcfStatusUrl(requestId),'GET')}throw new Error('NVCF invocation still pending after bounded polling')}
