import {forensicImpactLedger} from './media-impact';
export type UniverseLocal={he:string;en:string;ru:string};
export type UniverseSnapshot={id:string;value:string;numeric:number;date:string;label:UniverseLocal;sourceLabel:string;sourceUrl:string;kind:'gross-exposure'|'interaction'|'distribution'|'audience'|'geography'|'resolved'};
const L=(he:string,en:string,ru:string):UniverseLocal=>({he,en,ru});
export const impactUniverse={headline:{value:'7B+',numeric:7000000000,label:L('חשיפה מצטברת — snapshot הגבוה שנספר','Cumulative exposure — highest counted snapshot','Совокупная экспозиция — максимальный учтённый snapshot'),note:L('Gross exposure universe · לא unique people · snapshots קודמים אינם מתווספים אליו שוב','Gross exposure universe · not unique people · prior snapshots are not added again','Gross exposure universe · не уникальные люди · предыдущие snapshots не суммируются повторно'),sourceLabel:'Instagram @igor.vepretski · indexed bio snapshot',sourceUrl:'https://www.instagram.com/igor.vepretski/'},resolved:{value:forensicImpactLedger.ecosystemInclusiveGross.display,numeric:forensicImpactLedger.ecosystemInclusiveGross.value,label:L('Gross שכבר מפורק למקורות','Gross already resolved to sources','Gross, уже разложенный по источникам'),note:L('החלק שכבר ניתן לפתוח node-by-node מתוך מפקד 20.08.2026','The portion already openable node-by-node from the 20 Aug 2026 census','Часть, уже раскрываемая node-by-node по переписи 20.08.2026')},interactions:{value:'397M+',numeric:397000000,label:L('אינטראקציות מצטברות שנרשמו','Counted cumulative interactions','Учтённые совокупные взаимодействия'),note:L('290M+ likes · 82M+ shares · 25M+ comments · נשמר בנפרד מחשיפה','290M+ likes · 82M+ shares · 25M+ comments · kept separate from exposure','290M+ лайков · 82M+ репостов · 25M+ комментариев · отдельно от экспозиции')},distribution:{value:'2,753+',numeric:2753,label:L('מופעי פרסום בארבע פלטפורמות ליבה','Publication instances on four core platforms','Публикационные экземпляры на четырёх основных платформах'),note:L('1,189 Instagram + 904 TikTok + 326 LinkedIn + 334 YouTube','1,189 Instagram + 904 TikTok + 326 LinkedIn + 334 YouTube','1 189 Instagram + 904 TikTok + 326 LinkedIn + 334 YouTube')},community:{value:'1.5M+',numeric:1500000,label:L('חברי קהילה — snapshot מצטבר','Community members — cumulative snapshot','Участники сообщества — совокупный snapshot'),note:L('שכבת audience/network; אינה מתווספת ל־gross exposure','Audience/network layer; not added to gross exposure','Слой audience/network; не добавляется к gross exposure')},countries:{value:'47+',numeric:47,label:L('מדינות שנרשמו בטווח ההפצה','Countries recorded across distribution','Страны, зафиксированные в распространении'),note:L('ממד גאוגרפי — לא metric של reach','Geographic dimension — not a reach metric','Географическое измерение — не метрика reach')}};
export const grossSnapshotSeries:UniverseSnapshot[]=[
{id:'310m',value:'310M+',numeric:310000000,date:'2026 indexed',label:L('cumulative Instagram reach snapshot','cumulative Instagram reach snapshot','cumulative Instagram reach snapshot'),sourceLabel:'Pixnoy / Instagram bio index',sourceUrl:'https://www.pixnoy.com/ru/profile/igor.vepretski/',kind:'gross-exposure'},
{id:'5.1b',value:'5.1B',numeric:5100000000,date:'2026 evidence snapshot',label:L('total digital reach snapshot','total digital reach snapshot','total digital reach snapshot'),sourceLabel:'7YA evidence cockpit',sourceUrl:'https://7ya.io/evidence/',kind:'gross-exposure'},
{id:'6.2b',value:'6.2B+',numeric:6200000000,date:'2026 public crawl',label:L('global reach snapshot','global reach snapshot','global reach snapshot'),sourceLabel:'X @igorvepretski bio',sourceUrl:'https://x.com/igorvepretski',kind:'gross-exposure'},
{id:'7b',value:'7B+',numeric:7000000000,date:'2026 indexed snapshot',label:L('cumulative reach snapshot','cumulative reach snapshot','cumulative reach snapshot'),sourceLabel:'Instagram @igor.vepretski bio',sourceUrl:'https://www.instagram.com/igor.vepretski/',kind:'gross-exposure'}
];
export const universeRules=[L('סופרים קודם כל metric שנצפה או נרשם; classification מגיע אחר כך.','Count every observed or recorded metric first; classification comes second.','Сначала считаем каждый наблюдаемый или зафиксированный показатель; классификация — потом.'),L('snapshots של אותו cumulative counter הם סדרת זמן — לא סכום.','Snapshots of the same cumulative counter form a time series — not a sum.','Snapshots одного cumulative counter — временной ряд, а не сумма.'),L('views / impressions / reach נשארים exposure; likes / comments / shares / saves נשארים interactions.','Views / impressions / reach remain exposure; likes / comments / shares / saves remain interactions.','Views / impressions / reach остаются exposure; likes / comments / shares / saves остаются interactions.'),L('external publisher exposure נספר כחלק מהיקום כאשר התוכן מיוחס לאיגור.','External-publisher exposure counts in the universe when the content is attributable to Igor.','Экспозиция внешнего издателя учитывается, когда контент атрибутирован Игорю.')];
