import {useEffect,useMemo,useState,type SyntheticEvent} from 'react';
import {api} from '@appdeploy/client';
import {ArrowUpRight} from 'lucide-react';
import {fetchCanonicalCorpus,type CorpusEvent} from '../canonical-corpus-client';
import {canonicalCorpusSeed} from '../../shared/canonical-corpus';
import {useLocale,type Locale} from '../locale';
import {fetchVisualRegistry,type VisualRecord} from '../visual-registry';
import './cinematic-archive-rail.css';

type Local=Record<Locale,string>;
type ArchiveObject={id:string;year:string;dateKey:string;title:Local;source:string;href:string;image:string;kind:string};
type DiscoveryItem={id:string;title:string;platform:string;publisher:string;date:string;year:string;relationship:string;url:string;verification:string;origin:string;imageUrl:string};
type DiscoveryPayload={items?:DiscoveryItem[]};
const same=(value:string):Local=>({he:value,en:value,ru:value});
const yearOf=(value:string)=>value.match(/(?:19|20)\d{2}/)?.[0]||'';
const sortKey=(date:string,year:string)=>{const iso=date.match(/((?:19|20)\d{2})[-/.](\d{1,2})[-/.](\d{1,2})/);if(iso)return iso[1]+iso[2].padStart(2,'0')+iso[3].padStart(2,'0');const dmy=date.match(/(\d{1,2})[-/.](\d{1,2})[-/.]((?:19|20)\d{2})/);if(dmy)return dmy[3]+dmy[2].padStart(2,'0')+dmy[1].padStart(2,'0');return(yearOf(year)||yearOf(date)||'9999')+'0000'};
const keyUrl=(raw:string)=>{try{const url=new URL(raw);['fbclid','igshid','si','utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(key=>url.searchParams.delete(key));url.hash='';return(url.origin+url.pathname+url.search).replace(/\/$/,'').toLowerCase()}catch{return raw.trim().toLowerCase().replace(/\/$/,'')}};
const corpusObjects=(event:CorpusEvent):ArchiveObject[]=>event.sources.filter(source=>source.public&&/^https:\/\//i.test(source.url)).map((source,index)=>{const sourceKey=keyUrl(source.url);const sourceMedia=event.media.find(item=>item.kind==='image'&&item.url&&item.authenticity!=='unverified'&&keyUrl(item.sourceUrl)===sourceKey);const fallbackMedia=index===0?event.media.find(item=>item.kind==='image'&&item.url&&item.authenticity!=='unverified'):undefined;const media=sourceMedia||fallbackMedia;const sourceDate=source.publishedAt||event.canonicalDate;const year=yearOf(sourceDate)||event.period?.start||'—';return{id:'corpus-'+event.id+'-'+source.id,year,dateKey:sortKey(sourceDate,year),title:event.title,source:source.label,href:source.url,image:media?.url||'',kind:(source.kind||event.type).toUpperCase()}});
const visualObject=(item:VisualRecord):ArchiveObject|null=>item.sourceUrl?{id:'visual-'+item.id,year:item.year||'—',dateKey:sortKey('',item.year),title:same(item.label||item.chapter),source:item.source||'Public archive',href:item.sourceUrl,image:item.imageUrl||'',kind:item.origin==='social-live'?'LIVE':'VISUAL RECORD'}:null;
const discoveryObject=(item:DiscoveryItem):ArchiveObject|null=>item.url?{id:'discovery-'+item.id,year:item.year||yearOf(item.date)||'—',dateKey:sortKey(item.date,item.year),title:same(item.title||item.relationship||item.publisher||item.platform||'Public record'),source:item.publisher||item.platform||'Public source',href:item.url,image:item.imageUrl||'',kind:item.origin==='social-live'?'LIVE':'PUBLIC SOURCE'}:null;
const curate=(raw:ArchiveObject[])=>{const urls=new Set<string>();const images=new Set<string>();return raw.sort((a,b)=>a.dateKey.localeCompare(b.dateKey)||a.id.localeCompare(b.id)).filter(item=>{const href=keyUrl(item.href);const image=item.image.trim().toLowerCase();if(!href||urls.has(href)||(image&&images.has(image)))return false;urls.add(href);if(image)images.add(image);return true}).slice(0,84)};
const canonicalArchiveBootstrap=curate(canonicalCorpusSeed.flatMap(corpusObjects));
let archivePromise:Promise<ArchiveObject[]>|null=null;
function loadArchive(){if(!archivePromise)archivePromise=Promise.allSettled([fetchCanonicalCorpus(60,''),fetchVisualRegistry(),api.get('/api/discovery-library?limit=96')]).then(results=>{const raw:ArchiveObject[]=[...canonicalArchiveBootstrap];const corpus=results[0];if(corpus.status==='fulfilled')raw.push(...corpus.value.items.flatMap(corpusObjects));const visuals=results[1];if(visuals.status==='fulfilled')raw.push(...visuals.value.map(visualObject).filter((item):item is ArchiveObject=>Boolean(item)));const discovery=results[2];if(discovery.status==='fulfilled'){const payload=discovery.value.data as DiscoveryPayload;raw.push(...((payload.items||[]).map(discoveryObject).filter((item):item is ArchiveObject=>Boolean(item))))}return curate(raw)});return archivePromise}
const copy={he:{eyebrow:'ארכיון חי · מחובר למקורות',title:'עוד רגעים מתוך התקופה הזאת.',loading:'מחבר את הרשומה הציבורית…',open:'פתיחת המקור',count:'אובייקטים מחוברים'},en:{eyebrow:'LIVING ARCHIVE · SOURCE-LINKED',title:'More moments from this stretch of the life.',loading:'Connecting the public record…',open:'Open source',count:'connected objects'},ru:{eyebrow:'ЖИВОЙ АРХИВ · СВЯЗАН С ИСТОЧНИКАМИ',title:'Ещё моменты из этого периода жизни.',loading:'Соединяю публичную запись…',open:'Открыть источник',count:'связанных объектов'}} as const;
export default function CinematicArchiveRail({slot}:{slot:number}){const {locale,dir}=useLocale();const c=copy[locale];const [records,setRecords]=useState<ArchiveObject[]>(canonicalArchiveBootstrap);useEffect(()=>{let live=true;loadArchive().then(items=>{if(live)setRecords(items)});return()=>{live=false}},[]);const items=useMemo(()=>{if(!records.length)return[];const start=Math.floor(slot*records.length/7);const end=Math.max(start+1,Math.floor((slot+1)*records.length/7));const segment=records.slice(start,end);if(segment.length<=6)return segment;return Array.from({length:6},(_,index)=>segment[Math.round(index*(segment.length-1)/5)])},[records,slot]);const fail=(event:SyntheticEvent<HTMLImageElement>)=>{event.currentTarget.hidden=true;event.currentTarget.closest('figure')?.classList.add('is-source-only')};return <section className='car-rail' data-archive-slot={slot} dir={dir}><header><div><small dir='ltr'>{c.eyebrow}</small><h3>{c.title}</h3></div><p dir='ltr'><b>{records.length||'—'}</b> {c.count}</p></header>{items.length?<div className='car-strip'>{items.map((item,index)=><a className='car-object' data-documentary-object='1' href={item.href} target='_blank' rel='noreferrer' key={item.id}><figure>{item.image?<img src={item.image} alt={item.title[locale]} loading='lazy' decoding='async' referrerPolicy='no-referrer' onError={fail}/>:null}<div className='car-source-poster'><span>{item.kind}</span><strong>{item.title[locale]}</strong></div><figcaption><span dir='ltr'>{String(index+1).padStart(2,'0')} · {item.year}</span><b>{item.source}</b></figcaption></figure><span className='car-open'>{c.open}<ArrowUpRight/></span></a>)}</div>:<div className='car-loading'>{c.loading}</div>}</section>}
