import type {SyntheticEvent} from 'react';
import {ExternalLink,Play} from 'lucide-react';
import {thirdPartyAppearances,type MediaAppearance} from '../media-appearances';
import {useLocale} from '../locale';
import './life-broadcast.css';

const copy={he:{kicker:'INTERVIEWS / OTHER CAMERAS',title:'לא רק מה שאני אומר על עצמי.',body:'רגעים שבהם הסיפור יצא מהפיד שלי ונכנס לאולפן, לפודקאסט, לטלוויזיה ולערוצים של אחרים. כל פריט פותח את המקור עצמו.',all:'כל הראיונות והפודקאסטים',watch:'לצפייה במקור',verified:'מקור ציבורי'},en:{kicker:'INTERVIEWS / OTHER CAMERAS',title:'Not only what I say about myself.',body:'Moments when the story left my own feed and entered studios, podcasts, television and other people’s channels. Every frame opens the original public source.',all:'All interviews and podcasts',watch:'Open source',verified:'Public source'},ru:{kicker:'INTERVIEWS / OTHER CAMERAS',title:'Не только то, что я говорю о себе.',body:'Моменты, когда история вышла за пределы моего собственного фида — в студии, подкасты, телевидение и каналы других людей. Каждый кадр ведёт к открытому источнику.',all:'Все интервью и подкасты',watch:'Открыть источник',verified:'Публичный источник'}} as const;

const youtubeSurface=(item:MediaAppearance)=>item.primary.youtubeId?item.primary:item.mirrors.find(surface=>surface.youtubeId);
const visualItems=thirdPartyAppearances.filter(item=>youtubeSurface(item)).sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured))).slice(0,9);
const imageFor=(item:MediaAppearance)=>{const surface=youtubeSurface(item);return surface?.youtubeId?`https://i.ytimg.com/vi/${surface.youtubeId}/hqdefault.jpg`:item.image||''};
const hrefFor=(item:MediaAppearance)=>youtubeSurface(item)?.url||item.primary.url;
const fail=(event:SyntheticEvent<HTMLImageElement>)=>{event.currentTarget.hidden=true;event.currentTarget.parentElement?.classList.add('lb-media-failed')};

export default function LifeBroadcast(){const {locale}=useLocale();const c=copy[locale];return <section className='lb' id='life-broadcast' aria-labelledby='lb-title'><header className='lb-head'><div><p dir='ltr'>{c.kicker}</p><h2 id='lb-title'>{c.title}</h2></div><p>{c.body}</p></header><div className='lb-stage'>{visualItems.map((item,index)=><article className={`lb-card ${index===0?'lb-lead':''}`} key={item.id}><a className='lb-media' href={hrefFor(item)} target='_blank' rel='noreferrer' aria-label={`${c.watch}: ${item.title[locale]}`}><span className='lb-fallback' aria-hidden='true'><b>{item.publisher}</b><small>{item.kind.toUpperCase()}</small></span><img src={imageFor(item)} alt={`${item.publisher} · ${item.title[locale]}`} loading={index<3?'eager':'lazy'} decoding='async' referrerPolicy='no-referrer' onError={fail}/><span className='lb-play'><Play fill='currentColor'/></span><span className='lb-source'><b>{item.publisher}</b><small>{item.date||item.language.toUpperCase()}</small></span></a><div className='lb-copy'><p><span>{item.kind.toUpperCase()}</span></p><h3>{item.title[locale]}</h3><p>{item.dek[locale]}</p><a href={hrefFor(item)} target='_blank' rel='noreferrer'>{c.watch}<ExternalLink/></a></div></article>)}</div><footer className='lb-foot'><span dir='ltr'>{visualItems.length} INTERVIEWS · PODCASTS · TV · PUBLIC SOURCES</span><a href='?page=media'>{c.all}<ExternalLink/></a></footer></section>}
