export type EchoLocal={he:string;en:string;ru:string};
export type EchoMetric={value:string;label:EchoLocal};
export type MediaEchoItem={id:string;kind:'video'|'podcast'|'article'|'viral'|'music'|'party';publisher:string;title:EchoLocal;relation:EchoLocal;url:string;date?:string;preview?:string;metrics?:EchoMetric[];metricNote?:EchoLocal;note?:EchoLocal};
const L=(he:string,en:string,ru:string):EchoLocal=>({he,en,ru});
const yt=(id:string)=>`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
export const mediaEchoByChapterId:Record<string,MediaEchoItem[]>={
origin:[
{id:'origin-press',kind:'article',publisher:'מקור ראשון / NRG',title:L('כנגד כל הסיכויים — הרשומה הציבורית המוקדמת','Against the odds — the early public record','Вопреки всему — ранняя публичная история'),relation:L('כיסוי עיתונאי עצמאי','Independent press coverage','Независимая публикация'),url:'https://www.makorrishon.co.il/nrg/online/54/ART2/235/169.html',date:'26.04.2011',note:L('הסיפור הציבורי התחיל הרבה לפני האלגוריתמים של היום.','The public record starts long before today’s algorithms.','Публичная история началась задолго до современных алгоритмов.')},
{id:'origin-russian-fb',kind:'viral',publisher:'סטטוסים מצייצים',title:L('״רוסי מסריח״ — הסיפור יוצא מהחשבון שלי','“Stinking Russian” — the story leaves my account','«Вонючий русский» — история выходит за пределы моего аккаунта'),relation:L('הפצה חיצונית בפייסבוק','External Facebook amplification','Внешнее распространение в Facebook'),url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0VyLgUHZ6KLoY953QnCkSnWkSUtLqmV7NeeW6NmB2bABFh1R7bkRzj8Lw5imUeHckl'},
{id:'origin-russian-ig',kind:'viral',publisher:'סטטוסים מצייצים / Instagram',title:L('אותו סיפור, פלטפורמה נוספת','The same story, another platform','Та же история, другая платформа'),relation:L('ריפוסט חיצוני באינסטגרם','External Instagram repost','Внешний репост в Instagram'),url:'https://www.instagram.com/p/CsnfS5WoSw8/'},
{id:'origin-russian-li',kind:'article',publisher:'Igor Vepretski · LinkedIn',title:L('גרסת הלינקדאין בבעלותי','My owned LinkedIn version','Моя версия в LinkedIn'),relation:L('מראה מקצועית בבעלותי','Owned professional-network mirror','Собственное профессиональное зеркало'),url:'https://www.linkedin.com/posts/vepretski_%D7%91%D7%A9%D7%A0%D7%95%D7%AA-%D7%94-90-%D7%A7%D7%A8%D7%90%D7%95-%D7%9C%D7%99-%D7%A8%D7%95%D7%A1%D7%99-%D7%9E%D7%A1%D7%A8%D7%99%D7%97-%D7%9B%D7%A9%D7%A9%D7%99%D7%A8%D7%AA%D7%AA%D7%99-activity-7259518951334789120-f1MX'}],
return:[
{id:'starton-mynet',kind:'article',publisher:'mynet חולון',title:L('חוזר לשכונה כדי לבנות מרכז לנוער','Returning to the neighborhood to build for youth','Возвращение в район ради центра для молодёжи'),relation:L('כתבת עומק עצמאית','Independent feature','Независимый материал'),url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',date:'13.05.2022',preview:'https://pic1.yitweb.co.il/cdn-cgi/image/f%3Dauto%2Cw%3D1200%2Cq%3D85/picserver/mynet/crop_images/2022/05/11/r1F0NeKU9/r1F0NeKU9_0_0_640_360_0_large.jpg'},
{id:'starton-ch13',kind:'video',publisher:'חדשות 13 · העולם הבוקר',title:L('עזבתי את המשטרה כדי לבנות מרכז לנוער בסיכון','I left police work to build a youth center','Я ушёл из полиции, чтобы строить центр для подростков'),relation:L('סיקור טלוויזיוני עצמאי','Independent television coverage','Независимый телесюжет'),url:'https://prod.13tv.co.il/item/news/haolam-haboker/season-01/clips/u0uoy-903061791/?pid=44',date:'22.05.2022'},
{id:'starton-ch14',kind:'video',publisher:'ערוץ 14',title:L('משירות בכוחות הביטחון להקמת StartOn','From security service to building StartOn','От службы безопасности к созданию StartOn'),relation:L('ראיון טלוויזיה','Television interview','Телеинтервью'),url:'https://youtu.be/O3v309CA4ao',date:'2022',preview:yt('O3v309CA4ao')},
{id:'starton-mindset',kind:'podcast',publisher:'Mindset · שלומי חסטר',title:L('מנער בסיכון ליזם חברתי — פרק 102','From youth at risk to social entrepreneur — episode 102','От подростка группы риска к социальному предпринимателю — выпуск 102'),relation:L('שיחת עומק עצמאית','Independent long-form conversation','Независимый длинный разговор'),url:'https://mindset.org.il/%D7%9E%D7%A0%D7%A2%D7%A8-%D7%91%D7%A1%D7%99%D7%9B%D7%95%D7%9F-%D7%9C%D7%99%D7%96%D7%9D-%D7%97%D7%91%D7%A8%D7%AA%D7%99-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%A4/',date:'20.09.2022'},
{id:'starton-ceilings',kind:'podcast',publisher:'מנפצי תקרות הזכוכית',title:L('פרק 18 — תוויות, מסע אישי והובלת נוער','Episode 18 — labels, life journey and youth leadership','Выпуск 18 — ярлыки, личный путь и лидерство молодёжи'),relation:L('פודקאסט עצמאי','Independent podcast','Независимый подкаст'),url:'https://kaikovshahar.podbean.com/e/%D7%9E%D7%A0%D7%A4%D7%A6%D7%99%D7%AA%D7%A7%D7%A8%D7%95%D7%AA-%D7%94%D7%96%D7%9B%D7%95%D7%9B%D7%99%D7%AA%D7%A4%D7%A8%D7%A718/',date:'06.09.2022'},
{id:'starton-day',kind:'video',publisher:'פותחים יום',title:L('פרויקט חלל אינטראקטיבי לנוער בסיכון','An interactive space for youth at risk','Интерактивное пространство для подростков группы риска'),relation:L('ראיון טלוויזיה','Television interview','Телеинтервью'),url:'https://www.youtube.com/watch?v=SOpAglwkJ8I',date:'2022',preview:yt('SOpAglwkJ8I')}],
fatherhood:[
{id:'father-statuses',kind:'viral',publisher:'סטטוסים מצייצים',title:L('״אבא מושלם זה אבא ששם״ — כשהסיפור האישי הופץ מחדש','“A perfect father is a father who is there” — external redistribution','«Идеальный отец — тот, кто рядом» — внешнее распространение'),relation:L('ריפוסט חיצוני','External repost','Внешний репост'),url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0icaS4EV3EFHPbtTaexx3X4Lo9UGQD22Nvm8xzkpJRqiJSLro9D3zNp1PX6SJ26iPl',date:'2023',metrics:[{value:'≈4.1K',label:L('Reactions','Reactions','Реакции')},{value:'147',label:L('תגובות','Comments','Комментарии')}],metricNote:L('צילום מצב ציבורי · 08.06.2026 · המקור הזה בלבד','Public snapshot · 08 Jun 2026 · this source only','Публичный снимок · 08.06.2026 · только этот источник')},
{id:'father-linkedin',kind:'viral',publisher:'Igor Vepretski · LinkedIn',title:L('אותו סיפור נכנס גם לרשת המקצועית','The same story enters the professional network','Та же история входит в профессиональную сеть'),relation:L('מראה בבעלותי','Owned mirror','Собственная публикация'),url:'https://www.linkedin.com/posts/vepretski_%D7%9B%D7%A9%D7%94%D7%94%D7%95%D7%A8%D7%99%D7%9D-%D7%A9%D7%9C%D7%99-%D7%94%D7%AA%D7%92%D7%A8%D7%A9%D7%95-%D7%90%D7%91%D7%90-%D7%A9%D7%9C%D7%99-%D7%97%D7%AA%D7%9D-%D7%93%D7%99%D7%9C-activity-7032741993654988800-IRtv?trk=public_profile_like_view',date:'2023',metrics:[{value:'491',label:L('Reactions','Reactions','Реакции')},{value:'80',label:L('תגובות','Comments','Комментарии')}],metricNote:L('מדד גלוי בעמוד המקור · לא מחובר לשום פלטפורמה אחרת','Visible on the source page · never added to another platform','Видно на странице источника · не складывается с другими платформами')},
{id:'father-hidabroot',kind:'article',publisher:'הידברות',title:L('הפוסט הופך לכתבה עצמאית','The post becomes an independent article','Пост превращается в независимую статью'),relation:L('המרה למדיה','Media conversion','Переход в медиа'),url:'https://www.hidabroot.org/article/1179015',date:'20.02.2023'},
{id:'father-mial',kind:'viral',publisher:'אוהבים / Hohavim',title:L('סיפור הגן והגבולות — עותק חיצוני שהמשיך לחיות','The kindergarten and boundaries story — an external copy that kept travelling','История детского сада и границ — внешний дубль, который продолжил жить'),relation:L('סינדיקציה חיצונית · ללא תמונות ילדים כאן','External syndication · no child imagery shown here','Внешняя синдикация · без детских изображений здесь'),url:'https://www.facebook.com/Hohavim/photos/%D7%AA%D7%97%D7%99%D7%9C%D7%AA-%D7%A9%D7%91%D7%95%D7%A2-%D7%94%D7%92%D7%A0%D7%A0%D7%AA-%D7%9E%D7%AA%D7%A7%D7%A9%D7%A8%D7%AA-%D7%90%D7%A0%D7%99-%D7%9E%D7%91%D7%A7%D7%A9%D7%AA-%D7%A9%D7%AA%D7%92%D7%99%D7%A2-%D7%9C%D7%A7%D7%97%D7%AA-%D7%90%D7%AA-%D7%9E%D7%99%D7%90%D7%9C-%D7%94%D7%95%D7%90-%D7%9E%D7%A8%D7%91%D7%99%D7%A5-%D7%9C%D7%9B%D7%95%D7%9C%D7%9D-%D7%95%D7%A4%D7%A9%D7%95%D7%98-%D7%9E%D7%A1%D7%A8%D7%91-/894091596665017/',metrics:[{value:'2,259',label:L('Reactions','Reactions','Реакции')},{value:'93',label:L('תגובות','Comments','Комментарии')},{value:'63',label:L('שיתופים','Shares','Репосты')}],metricNote:L('צילום מצב מאונדקס · 08.06.2026 · העותק הזה בלבד','Indexed snapshot · 08 Jun 2026 · this copy only','Индексированный снимок · 08.06.2026 · только эта копия')},
{id:'father-zman',kind:'article',publisher:'זמן ישראל',title:L('לבן שלי אין טיקטוק!','My son does not have TikTok!','У моего сына нет TikTok!'),relation:L('טור מחבר על הורות, טכנולוגיה ופחד','Authored column on parenting, technology and fear','Авторская колонка о родительстве, технологиях и страхе'),url:'https://www.zman.co.il/350569/',date:'10.11.2022'},
{id:'father-zman2',kind:'article',publisher:'זמן ישראל',title:L('כללי המשחק השתנו — חינוך בעידן המודרני','The rules changed — education in the modern era','Правила изменились — образование в современную эпоху'),relation:L('טור מחבר על חינוך בסביבה אלגוריתמית','Authored column on education in an algorithmic environment','Авторская колонка об образовании в алгоритмической среде'),url:'https://www.zman.co.il/352289/',date:'27.11.2022'}],
voice:[
{id:'scam-statuses',kind:'viral',publisher:'סטטוסים מצייצים',title:L('סבתא שלי נפלה קורבן להונאה','My grandmother fell victim to fraud','Моя бабушка стала жертвой мошенничества'),relation:L('הפצה חיצונית שהתחילה מסלול תקשורתי','External amplification that began a media trail','Внешнее распространение, запустившее медийную цепочку'),url:'https://www.facebook.com/lan2lan.sta2sim/posts/igorvepretski-%D7%A1%D7%91%D7%AA%D7%90-%D7%A9%D7%9C%D7%99-%D7%A0%D7%A4%D7%9C%D7%94-%D7%A7%D7%95%D7%A8%D7%91%D7%9F-%D7%9C%D7%94%D7%95%D7%A0%D7%90%D7%94%D7%90%D7%91%D7%9C-%D7%9C%D7%A2%D7%95%D7%92%D7%9E%D7%AA-%D7%94%D7%A0%D7%A4%D7%A9-%D7%94%D7%A2%D7%99%D7%A7%D7%A8%D7%99%D7%AA-%D7%91%D7%9B%D7%95%D7%9C-%D7%94%D7%A1%D7%99%D7%A4%D7%95%D7%A8-%D7%94%D7%96%D7%94-/752380882924243/',date:'07.02.2023',note:L('המדדים הישנים נשארים בהסגר עד צילום מסך חדש; עצם ההפצה מאומת.','Old exact metrics remain quarantined until a fresh capture; the propagation itself is verified.','Старые точные метрики остаются в карантине до нового снимка; само распространение подтверждено.')},
{id:'scam-news13',kind:'video',publisher:'חדשות 13 · גאולה אבן סער',title:L('היעדר טיפול ראוי בקשישים שנפלו קורבן להונאה','Failure to properly support elderly fraud victims','Недостаточная помощь пожилым жертвам мошенничества'),relation:L('המשך באולפן החדשות','Television follow-up','Продолжение в телестудии'),url:'https://www.youtube.com/watch?v=AE5hDzLM5XU',date:'2023',preview:yt('AE5hDzLM5XU')},
{id:'scam-news12',kind:'video',publisher:'Public YouTube record',title:L('ראיון המשך על ההונאה והיחס לאורך התהליך','Follow-up interview on fraud and treatment through the process','Продолжение интервью о мошенничестве и отношении в процессе'),relation:L('המשך ציבורי','Public follow-up','Публичное продолжение'),url:'https://www.youtube.com/watch?v=3XxoBtSL2pg',date:'2023',preview:yt('3XxoBtSL2pg')},
{id:'voice-cost',kind:'viral',publisher:'סטטוסים מצייצים',title:L('״מרתיח אותי המצב הזה״ — יוקר המחיה','“This situation makes me furious” — cost of living','«Меня бесит эта ситуация» — стоимость жизни'),relation:L('הפצה חיצונית','External amplification','Внешнее распространение'),url:'https://www.facebook.com/lan2lan.sta2sim/posts/%D7%9E%D7%A8%D7%AA%D7%99%D7%97-%D7%90%D7%95%D7%AA%D7%99-%D7%94%D7%9E%D7%A6%D7%91-%D7%94%D7%96%D7%94%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99/667549874740678/',date:'14.10.2022'},
{id:'voice-henry',kind:'viral',publisher:'סטטוסים מצייצים',title:L('תכירו את הנרי האלוף','Meet Henry the champion','Познакомьтесь с Генри — чемпионом'),relation:L('הפצה חיצונית של סיפור ציבורי','External amplification of a public story','Внешнее распространение общественной истории'),url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0fLDvPkLmF846Jhme65ETbkcNRTcTK8z3s3XojRtfe3eCdTnmSCK4icTmn5rdxcCRl',date:'02.10.2023'}],
break:[
{id:'motion-podcast',kind:'podcast',publisher:'מוחות בתנועה',title:L('מנוער בסיכון למנהיגות מעוררת השראה בחינוך','From youth at risk to leadership in education','От подростка группы риска к лидерству в образовании'),relation:L('שיחת עומק עצמאית','Independent long-form conversation','Независимый длинный разговор'),url:'https://podtail.com/podcast/092cc570/--18/',date:'23.01.2024'},
{id:'break-longform',kind:'video',publisher:'YouTube',title:L('זהות, אחריות והחברה הישראלית — שיחה ארוכה','Identity, responsibility and Israeli society — long-form','Идентичность, ответственность и израильское общество — длинный разговор'),relation:L('וידאו ארוך','Long-form video','Длинное видео'),url:'https://www.youtube.com/watch?v=3h-oEuW8GJI',date:'2024',preview:yt('3h-oEuW8GJI')}],
culture:[
{id:'culture-bizzi',kind:'music',publisher:'YouTube',title:L('BIZZI — שיתוף פעולה וקליפ','BIZZI — collaboration and video','BIZZI — коллаборация и клип'),relation:L('יצירה מוזיקלית','Music collaboration','Музыкальная коллаборация'),url:'https://www.youtube.com/watch?v=jRjZjpqAgEw',date:'2025',preview:yt('jRjZjpqAgEw')},
{id:'culture-excel',kind:'music',publisher:'YouTube Music',title:L('מת על אקסל','מת על אקסל','מת על אקסל'),relation:L('מוזיקה · מדד ציבורי משוער','Music · approximate public metric','Музыка · приблизительная публичная метрика'),url:'https://www.youtube.com/watch?v=R58T4DQu33w',metrics:[{value:'≈129K',label:L('צפיות','Views','Просмотры')}],metricNote:L('תוצאת חיפוש ציבורית · 08.06.2026 · משוער','Public search snapshot · 08 Jun 2026 · approximate','Публичный поисковый снимок · 08.06.2026 · приблизительно'),preview:yt('R58T4DQu33w')},
{id:'culture-nawan',kind:'viral',publisher:'Nawan1 / @nawan1379',title:L('הופעה אצל יוצר חיצוני — הסרטון ממשיך הרבה מעבר לחשבון שלי','External creator appearance — the video travels far beyond my account','Появление у внешнего автора — видео живёт далеко за пределами моего аккаунта'),relation:L('הגברה חיצונית · לא העלאה בבעלותי','External amplification · not my owned upload','Внешнее усиление · не моя публикация'),url:'https://www.youtube.com/shorts/k9haTADKG3M',metrics:[{value:'5.1M',label:L('צפיות','Views','Просмотры')},{value:'82K',label:L('לייקים','Likes','Лайки')},{value:'717',label:L('תגובות','Comments','Комментарии')}],metricNote:L('צילום מסך מתוארך ומאומת · המדדים שייכים לסרטון של היוצר החיצוני','Dated verified capture · metrics belong to the external creator video','Датированный подтверждённый снимок · метрики принадлежат видео внешнего автора'),preview:yt('k9haTADKG3M')}],
now:[
{id:'now-party-he',kind:'party',publisher:'ישראל ביתנו',title:L('״איפה הניצחון המוחלט?״ — הפצה מפלגתית','“Where is the total victory?” — party distribution','«Где абсолютная победа?» — партийное распространение'),relation:L('הפצה מוסדית · לא reach בבעלותי','Institutional distribution · not owned reach','Институциональное распространение · не мой охват'),url:'https://www.facebook.com/beytenu/videos/%D7%99%D7%95%D7%A6%D7%90-%D7%9B%D7%95%D7%97%D7%95%D7%AA-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%AA%D7%92%D7%99%D7%93-%D7%99%D7%90-%D7%91%D7%99%D7%91%D7%99-%D7%90%D7%99%D7%A4%D7%94-%D7%94%D7%A0%D7%99%D7%A6%D7%97%D7%95%D7%9F-%D7%94%D7%9E%D7%95%D7%97%D7%9C%D7%98/26702411802682636/',date:'29.01.2026',metrics:[{value:'≈14K',label:L('צפיות','Views','Просмотры')}],metricNote:L('תוצאת related-video ציבורית · 08.06.2026 · משוער · הסרטון המפלגתי בלבד','Public related-video snapshot · 08 Jun 2026 · approximate · party video only','Публичный related-video снимок · 08.06.2026 · приблизительно · только партийное видео')},
{id:'now-party-ru',kind:'party',publisher:'НДИ / ישראל ביתנו ברוסית',title:L('מה לא לעשות בזמן ירי — שכבת הפצה ברוסית','What not to do during rocket fire — Russian distribution','Что нельзя делать во время обстрела — русскоязычное распространение'),relation:L('הפצה מפלגתית ברוסית','Russian-language party distribution','Русскоязычное партийное распространение'),url:'https://www.facebook.com/beytenurusskiy/videos/%D1%87%D1%82%D0%BE-%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F-%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B2%D0%BE-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D0%BE%D0%B1%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%B0/3176491592494318/'},
{id:'now-repatriation-ru',kind:'podcast',publisher:'НДИ / Facebook',title:L('להיות ילד רפטריאנט — הסיפור חוזר ברוסית','Being a repatriated child — the story returns in Russian','Что значит быть ребёнком-репатриантом'),relation:L('פודקאסט / הפצה בשפה הרוסית','Podcast / Russian-language distribution','Подкаст / русскоязычное распространение'),url:'https://www.facebook.com/vepretski/videos/%D1%87%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-%D0%B1%D1%8B%D1%82%D1%8C-%D1%80%D0%B5%D0%B1%D0%B5%D0%BD%D0%BA%D0%BE%D0%BC-%D1%80%D0%B5%D0%BF%D0%B0%D1%82%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D0%BE%D0%BC-%D0%BF%D0%BE%D0%B4%D0%BA%D0%B0%D1%81%D1%82-%D0%BD%D0%B4%D0%B8/430347856723074/'},
{id:'now-podcast-playlist',kind:'podcast',publisher:'Igor Vepretski · YouTube',title:L('ארכיון הפודקאסטים','Podcast archive','Архив подкастов'),relation:L('פלייליסט ציבורי מתמשך','Ongoing public playlist','Постоянный публичный плейлист'),url:'https://www.youtube.com/playlist?list=PLvXOwJ42abaQiQhJoGD4MkTLGzDdwE_GZ',date:'17.04.2026'}]
};
