import crypto from 'node:crypto';
import {db} from '@appdeploy/sdk';

type Locale='he'|'en'|'ru';
export type GrowthEventType='action_completed'|'artifact_created'|'skill_demonstrated'|'blocker_resolved'|'project_started'|'project_completed'|'feedback_received'|'opportunity_obtained'|'helped_other';
type GrowthPlan={title:string;promise:string;firstProof:string;steps:string[];tools:{name:string;why:string}[];prompts:string[];risks:string[];igorConnection:string};
type GrowthProfileRecord={userId:string;contactEmail:string;communicationsConsent:boolean;communicationsConsentAt:number|null;consentVersion:'growth-v1';locale:Locale;cohort:'creator_builder_phase_a';adultConfirmed:true;kind:string;outcome:string;audience:string;assets:string[];needs:string[];pace:string;help:string;plan:GrowthPlan;currentNextAction:string;profileVersion:'growth-v1';createdAt:number;updatedAt:number};
export type GrowthProfile=GrowthProfileRecord&{id:string};
type GrowthProgressRecord={userId:string;profileId:string;eventType:GrowthEventType;note:string;createdAt:number};
export type GrowthProgress=GrowthProgressRecord&{id:string};
type GrowthEventRecord={flowHash?:string;userId?:string;eventName:string;locale?:Locale;kind?:string;needsCount?:number;assetsCount?:number;pace?:string;help?:string;usefulness?:string;createdAt:number};
export class GrowthValidationError extends Error{}
const asObject=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'?value as Record<string,unknown>:{};
const clean=(value:unknown,max:number)=>String(value??'').trim().slice(0,max);
const localeOf=(value:unknown):Locale=>value==='en'||value==='ru'?value:'he';
const listOf=(value:unknown,maxItems:number,maxChars:number)=>Array.isArray(value)?value.map(item=>clean(item,maxChars)).filter(Boolean).slice(0,maxItems):[];
const eventTypes=new Set<GrowthEventType>(['action_completed','artifact_created','skill_demonstrated','blocker_resolved','project_started','project_completed','feedback_received','opportunity_obtained','helped_other']);
const eventNames=new Set(['path_started','free_plan_rendered','free_plan_feedback','save_started','profile_saved','growth_returned','progress_recorded','path_corrected']);
const usefulnessValues=new Set(['very_useful','useful','neutral','not_useful']);
const hashFlow=(value:string)=>crypto.createHash('sha256').update(value,'utf8').digest('hex');
async function listAll<T=Record<string,unknown>>(table:string,filter?:Record<string,unknown>){const items:Array<T&{id:string}>=[];let nextToken:string|undefined;do{const page=await db.list<T>(table,{...(filter?{filter}:{}),...(nextToken?{nextToken}:{})});items.push(...page.items as Array<T&{id:string}>);nextToken=page.nextToken}while(nextToken);return items}
function sanitizePlan(value:unknown):GrowthPlan{const raw=asObject(value);const title=clean(raw.title,180);const promise=clean(raw.promise,600);const firstProof=clean(raw.firstProof,500);const steps=listOf(raw.steps,7,260);const tools=Array.isArray(raw.tools)?raw.tools.map(item=>{const tool=asObject(item);return{name:clean(tool.name,100),why:clean(tool.why,240)}}).filter(item=>item.name&&item.why).slice(0,4):[];const prompts=listOf(raw.prompts,4,500);const risks=listOf(raw.risks,4,260);const igorConnection=clean(raw.igorConnection,650);if(!title||!promise||!firstProof||!steps.length)throw new GrowthValidationError('invalid plan');return{title,promise,firstProof,steps,tools,prompts,risks,igorConnection}}
export async function getGrowthProfile(userId:string):Promise<GrowthProfile|null>{const items=await listAll<GrowthProfileRecord>('growth_profiles',{userId});if(!items.length)return null;items.sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0));return items[0]}
export async function recordGrowthEvent(value:unknown,userId?:string):Promise<void>{const raw=asObject(value);const eventName=clean(raw.eventName,40);if(!eventNames.has(eventName))throw new GrowthValidationError('invalid growth event');const flowId=clean(raw.flowId,200);if(flowId&&flowId.length<20)throw new GrowthValidationError('invalid flow id');const usefulness=clean(raw.usefulness,30);if(usefulness&&!usefulnessValues.has(usefulness))throw new GrowthValidationError('invalid usefulness');const record:GrowthEventRecord={eventName,createdAt:Date.now()};if(flowId)record.flowHash=hashFlow(flowId);if(userId)record.userId=userId;const locale=clean(raw.locale,8);if(locale)record.locale=localeOf(locale);const kind=clean(raw.kind,30);if(kind)record.kind=kind;const needsCount=Math.max(0,Math.min(20,Number(raw.needsCount)||0));const assetsCount=Math.max(0,Math.min(20,Number(raw.assetsCount)||0));record.needsCount=needsCount;record.assetsCount=assetsCount;const pace=clean(raw.pace,20);if(pace)record.pace=pace;const help=clean(raw.help,20);if(help)record.help=help;if(usefulness)record.usefulness=usefulness;const [id]=await db.add('growth_events',[record]);if(!id)throw new Error('failed to record growth event')}
export async function saveGrowthProfile(userId:string,email:string|undefined,value:unknown):Promise<GrowthProfile>{const raw=asObject(value);if(raw.adultConfirmed!==true)throw new GrowthValidationError('adult confirmation required');const form=asObject(raw.form);const kind=clean(form.kind,30);const outcome=clean(form.outcome,1600);const audience=clean(form.audience,300);const assets=listOf(form.assets,8,100);const needs=listOf(form.needs,10,100);const pace=clean(form.pace,20)||'30';const help=clean(form.help,20)||'diy';if(!kind||outcome.length<20||audience.length<2||!needs.length)throw new GrowthValidationError('growth path fields missing');const plan=sanitizePlan(raw.plan);const communicationsConsent=raw.communicationsConsent===true;const now=Date.now();const existing=await getGrowthProfile(userId);const base:GrowthProfileRecord={userId,contactEmail:communicationsConsent?clean(email,200).toLowerCase():'',communicationsConsent:communicationsConsent&&Boolean(email),communicationsConsentAt:communicationsConsent&&email?now:null,consentVersion:'growth-v1',locale:localeOf(raw.locale),cohort:'creator_builder_phase_a',adultConfirmed:true,kind,outcome,audience,assets,needs,pace,help,plan,currentNextAction:plan.steps[0]||plan.firstProof,profileVersion:'growth-v1',createdAt:existing?.createdAt||now,updatedAt:now};let profile:GrowthProfile;if(existing){const [ok]=await db.update('growth_profiles',[{id:existing.id,record:base}]);if(!ok)throw new Error('failed to update growth profile');profile={id:existing.id,...base}}else{const [id]=await db.add('growth_profiles',[base]);if(!id)throw new Error('failed to save growth profile');profile={id,...base}}await recordGrowthEvent({flowId:raw.flowId,eventName:existing?'path_corrected':'profile_saved',locale:base.locale,kind,needsCount:needs.length,assetsCount:assets.length,pace,help},userId);return profile}
export async function getGrowthState(userId:string):Promise<{profile:GrowthProfile|null;progress:GrowthProgress[];mpeCount:number}>{const profile=await getGrowthProfile(userId);if(!profile)return{profile:null,progress:[],mpeCount:0};const progress=await listAll<GrowthProgressRecord>('growth_progress',{userId});progress.sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0));const completed=progress.filter(item=>item.eventType==='action_completed').length;const steps=profile.plan.steps;const next=completed<steps.length?steps[completed]:profile.plan.firstProof;return{profile:{...profile,currentNextAction:next},progress:progress.slice(0,20),mpeCount:progress.length}}
export async function recordGrowthProgress(userId:string,value:unknown):Promise<{profile:GrowthProfile;progress:GrowthProgress[];mpeCount:number}>{const raw=asObject(value);const eventType=clean(raw.eventType,40) as GrowthEventType;if(!eventTypes.has(eventType))throw new GrowthValidationError('invalid progress event');const note=clean(raw.note,500);const profile=await getGrowthProfile(userId);if(!profile)throw new GrowthValidationError('growth profile required');const [id]=await db.add('growth_progress',[{userId,profileId:profile.id,eventType,note,createdAt:Date.now()}]);if(!id)throw new Error('failed to save progress');await recordGrowthEvent({eventName:'progress_recorded',locale:profile.locale,kind:profile.kind},userId);const state=await getGrowthState(userId);if(!state.profile)throw new Error('growth profile missing after progress');return{profile:state.profile,progress:state.progress,mpeCount:state.mpeCount}}
export async function deleteGrowthData(userId:string):Promise<void>{const [profiles,progress,events]=await Promise.all([listAll<GrowthProfileRecord>('growth_profiles',{userId}),listAll<GrowthProgressRecord>('growth_progress',{userId}),listAll<GrowthEventRecord>('growth_events',{userId})]);if(progress.length)await db.delete('growth_progress',progress.map(item=>item.id));if(profiles.length)await db.delete('growth_profiles',profiles.map(item=>item.id));if(events.length)await db.delete('growth_events',events.map(item=>item.id))}
export async function getGrowthAdminStats(){const [profiles,progress,events]=await Promise.all([listAll<GrowthProfileRecord>('growth_profiles'),listAll<GrowthProgressRecord>('growth_progress'),listAll<GrowthEventRecord>('growth_events')]);const uniqueFlow=(name:string)=>new Set(events.filter(item=>item.eventName===name&&item.flowHash).map(item=>item.flowHash)).size;const pathStarted=uniqueFlow('path_started');const freePlansRendered=uniqueFlow('free_plan_rendered');const feedback=events.filter(item=>item.eventName==='free_plan_feedback'&&item.flowHash);const usefulOrVeryUseful=feedback.filter(item=>item.usefulness==='useful'||item.usefulness==='very_useful').length;const sevenDayReturners=new Set<string>();const firstActionWithinSevenDays=new Set<string>();for(const profile of profiles){const start=Number(profile.createdAt||0);const end=start+7*24*60*60*1000;if(events.some(item=>item.userId===profile.userId&&item.eventName==='growth_returned'&&Number(item.createdAt)>start+60*60*1000&&Number(item.createdAt)<=end))sevenDayReturners.add(profile.userId);if(progress.some(item=>item.userId===profile.userId&&Number(item.createdAt)>=start&&Number(item.createdAt)<=end))firstActionWithinSevenDays.add(profile.userId)}const activeHumans=new Set([...profiles.map(item=>item.userId),...progress.map(item=>item.userId)]).size;return{counts:{pathStarted,freePlansRendered,feedbackCount:feedback.length,usefulOrVeryUseful,profilesSaved:profiles.length,activeHumans,meaningfulProgressEvents:progress.length,sevenDayReturners:sevenDayReturners.size,firstActionWithinSevenDays:firstActionWithinSevenDays.size},rates:{intakeCompletion:pathStarted?freePlansRendered/pathStarted:0,firstValueUsefulness:feedback.length?usefulOrVeryUseful/feedback.length:0,saveAfterValue:freePlansRendered?profiles.length/freePlansRendered:0,mpePerActiveHuman:activeHumans?progress.length/activeHumans:0,sevenDayReturn:profiles.length?sevenDayReturners.size/profiles.length:0,firstActionWithinSevenDays:profiles.length?firstActionWithinSevenDays.size/profiles.length:0}}}
