import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import './locale.css';
export type Locale='he'|'en'|'ru';
type LocaleContextValue={locale:Locale;dir:'rtl'|'ltr';setLocale:(locale:Locale)=>void};
const LocaleContext=createContext<LocaleContextValue|null>(null);
const valid=(value:string|null):value is Locale=>value==='he'||value==='en'||value==='ru';const safeGet=(key:string)=>{try{return localStorage.getItem(key)}catch{return null}};const safeSet=(key:string,value:string)=>{try{localStorage.setItem(key,value)}catch{}};const rootPrefix=()=>{const depth=window.location.pathname.split('/').filter(Boolean).length;return depth?'../'.repeat(depth):'./'};export const rootHref=(path='')=>rootPrefix()+path.replace(/^\.\/+/, '');
const initialLocale=():Locale=>{const query=new URLSearchParams(window.location.search).get('lang');if(valid(query))return query;const stored=safeGet('7ya.locale');if(valid(stored))return stored;return 'he'};
export function LocaleProvider({children}:{children:ReactNode}){const [locale,setLocaleState]=useState<Locale>(initialLocale);const setLocale=(value:Locale)=>{setLocaleState(value);safeSet('7ya.locale',value);const url=new URL(window.location.href);url.searchParams.set('lang',value);window.history.replaceState(null,'',url.pathname+'?'+url.searchParams.toString()+url.hash)};useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==='he'?'rtl':'ltr';document.body.dataset.locale=locale;safeSet('7ya.locale',locale)},[locale]);const value=useMemo(()=>({locale,dir:locale==='he'?'rtl' as const:'ltr' as const,setLocale}),[locale]);return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>}
export function useLocale(){const value=useContext(LocaleContext);if(!value)throw new Error('LocaleProvider missing');return value}
export function LanguageSwitcher({compact=false}:{compact?:boolean}){const {locale,setLocale}=useLocale();const aria=locale==='he'?'בחירת שפה':locale==='ru'?'Выбор языка':'Select language';const label=(value:Locale)=>compact?value.toUpperCase():value==='he'?'עברית':value==='en'?'English':'Русский';return <div className={'language-switcher '+(compact?'compact':'')} role='group' aria-label={aria}>{(['he','en','ru'] as Locale[]).map(value=><button type='button' key={value} lang={value} dir={value==='he'?'rtl':'ltr'} className={locale===value?'active':''} aria-pressed={locale===value} onClick={()=>setLocale(value)}>{label(value)}</button>)}<a href={rootHref('es/')} lang='es' dir='ltr' aria-label='Español'>{compact?'ES':'Español'}</a></div>}
export const pageHref=(page:'home'|'album'|'museum'|'music'|'media'|'speaker'|'blog'|'create'|'growth'|'search'|'library',locale:Locale)=>{const params=new URLSearchParams(window.location.search);params.delete('page');params.delete('lang');params.delete('chat');params.delete('diagnostics');params.set('lang',locale);const cleanRoutes:Partial<Record<typeof page,string>>={museum:'museum/',music:'music/',media:'media/',speaker:'speaker/',blog:'blog/',create:'create/',search:'search/',library:'library/'};const clean=cleanRoutes[page];if(clean)return rootHref(clean+'?'+params.toString());if(page!=='home')params.set('page',page);return rootHref('?'+params.toString())};
const categories:Record<Locale,Record<string,string>>={he:{'הכול':'הכול','טלוויזיה':'טלוויזיה','פודקאסטים':'פודקאסטים','עיתונות':'עיתונות','כתיבה':'כתיבה','ויראלי':'ויראלי','מוזיקה':'מוזיקה','רשתות':'רשתות','StartOn':'StartOn'},en:{'הכול':'All','טלוויזיה':'Television','פודקאסטים':'Podcasts','עיתונות':'Press','כתיבה':'Writing','ויראלי':'Viral','מוזיקה':'Music','רשתות':'Social','StartOn':'StartOn'},ru:{'הכול':'Все','טלוויזיה':'Телевидение','פודקאסטים':'Подкасты','עיתונות':'Пресса','כתיבה':'Тексты','ויראלי':'Вирусное','מוזיקה':'Музыка','רשתות':'Соцсети','StartOn':'StartOn'}};
export const categoryText=(value:string,locale:Locale)=>categories[locale][value]||value;
type ItemTranslation={en:[string,string];ru:[string,string]};
const itemTranslations:Record<string,ItemTranslation>={
'fraud-13':{en:['When a personal post becomes a public campaign','A campaign against fraud targeting older people moved from a public post into a television studio, giving the issue a name, a face and continuity.'],ru:['Когда личный пост становится общественной кампанией','Борьба с мошенничеством против пожилых людей перешла из публичного поста в телестудию, дав проблеме имя, лицо и продолжение.']},
'fraud-12':{en:['The story behind the campaign against elder fraud','A follow-up interview connecting field experience, civic responsibility and protection for people society too easily leaves behind.'],ru:['История кампании против мошенничества с пожилыми','Продолжение интервью, связывающее полевой опыт, гражданскую ответственность и защиту тех, кого общество слишком легко оставляет позади.']},
'starton-14':{en:['From security service to building a youth center','An interview about moving from public service back to the neighborhood and building StartOn as a space for technology and belonging.'],ru:['От службы безопасности к созданию молодежного центра','Интервью о переходе от государственной службы к возвращению в район и созданию StartOn как пространства технологий и принадлежности.']},
'starton-day':{en:['An interactive space for youth at risk','A television presentation of the physical model: learning, creation, technology, community and a safe place.'],ru:['Интерактивное пространство для подростков группы риска','Телевизионная презентация физической модели: обучение, творчество, технологии, сообщество и безопасное место.']},
'nova-long':{en:['From escaping the Nova festival to a changed perspective','A long conversation about October 7, identity, fracture, responsibility and Israeli society without reducing it to a soundbite.'],ru:['От бегства с фестиваля Nova к переосмыслению','Долгий разговор о 7 октября, идентичности, травме, ответственности и израильском обществе без сведения к короткому лозунгу.']},
'youth-radio':{en:['If it is hard for us, what are youth at risk going through?','A conversation with Freddy Moskovitz about young people in crisis, adult responsibility and practical hope.'],ru:['Если трудно нам, что переживают подростки группы риска?','Разговор с Фредди Московицем о молодежи во время кризиса, ответственности взрослых и практической надежде.']},
'dna-710':{en:['October 7 changed Israel’s DNA','A conversation segment about national and public change after October 7 and the responsibility that followed.'],ru:['7 октября изменило ДНК Израиля','Фрагмент разговора об общественных и национальных изменениях после 7 октября и возникшей ответственности.']},
'starton-13-page':{en:['A police officer left to build a new beginning','A morning-show report about moving from public service to creating a center for youth at risk.'],ru:['Офицер полиции ушел, чтобы создать новое начало','Сюжет утренней программы о переходе от государственной службы к созданию центра для подростков группы риска.']},
'mynet-return':{en:['Returning to the neighborhood','An in-depth interview about returning to Jesse Cohen, selling the home and the vision for a youth technology center.'],ru:['Возвращение в район','Подробное интервью о возвращении в Джесси Коэн, продаже дома и видении технологического центра для молодежи.']},
'print-return':{en:['Returning to the neighborhood — print edition','The printed newspaper page, preserved as part of the StartOn documentation cluster.'],ru:['Возвращение в район — печатная версия','Страница печатной газеты, сохраненная как часть документального массива StartOn.']},
'early-2011':{en:['Against all odds','An early press record documenting the person and the journey years before TikTok, StartOn and 7YA.'],ru:['Вопреки всему','Ранняя публикация, документирующая человека и путь задолго до TikTok, StartOn и 7YA.']},
'father-hidabroot':{en:['A perfect father is a father who is present','A personal post about abandonment and fatherhood that crossed platforms and became a public article.'],ru:['Идеальный отец — тот, кто рядом','Личный пост об оставленности и отцовстве, который вышел за пределы платформ и стал публичной статьей.']},
'father-comments':{en:['The story continues in the comments','Public responses showing how a personal sentence became a wider conversation about parental presence.'],ru:['История продолжается в комментариях','Публичные реакции показывают, как личная фраза стала широкой беседой о родительском присутствии.']},
'zman-author':{en:['The writing of Igor Vepretski','An author page bringing together columns on parenting, education, networks, technology and belonging.'],ru:['Тексты Игоря Вепрецкого','Страница автора, объединяющая колонки о родительстве, образовании, сетях, технологиях и принадлежности.']},
'zman-tiktok':{en:['My son does not have TikTok!','A personal column that begins with a parenting conflict and expands into fear, belonging and digital education.'],ru:['У моего сына нет TikTok!','Личная колонка, начинающаяся с родительского конфликта и переходящая к страху, принадлежности и цифровому воспитанию.']},
'zman-rules':{en:['The rules of the game have changed','A column about education in a changed world and the need to build capability rather than only fight the screen.'],ru:['Правила игры изменились','Колонка об образовании в изменившемся мире и необходимости развивать способности, а не только бороться с экраном.']},
'medium-story':{en:['From Troubled Beginnings to Social Impact','An English essay connecting a difficult past, choice, responsibility and social entrepreneurship.'],ru:['От трудного начала к общественному влиянию','Англоязычное эссе, связывающее сложное прошлое, выбор, ответственность и социальное предпринимательство.']},
'mindset-page':{en:['From youth at risk to social entrepreneur','Episode 102: a conversation about life, choice, responsibility and turning personal experience into StartOn.'],ru:['От подростка группы риска к социальному предпринимателю','Эпизод 102: разговор о жизни, выборе, ответственности и превращении личного опыта в StartOn.']},
'igor-podcast-mindset':{en:['Igor Vepretski with Shlomi Haster on Mindset','A long-form Spotify episode about life trajectory, mindset change and social entrepreneurship.'],ru:['Игорь Вепрецкий с Шломи Хастером в Mindset','Длинный выпуск Spotify о жизненном пути, смене мышления и социальном предпринимательстве.']},
'igor-podcast-social-entrepreneur':{en:['Igor Vepretski — from youth at risk to social entrepreneur','A long-form episode from Igor’s own Spotify podcast property about the path to criminology, content creation and social entrepreneurship.'],ru:['Игорь Вепрецкий — от подростка группы риска к социальному предпринимателю','Длинный выпуск собственного Spotify-подкаста Игоря о пути к криминологии, созданию контента и социальному предпринимательству.']},
'mindset-spotify':{en:['From youth at risk to social entrepreneur — Episode 102','The Spotify audio edition of the Mindset conversation.'],ru:['От подростка группы риска к социальному предпринимателю — эпизод 102','Аудиоверсия беседы Mindset на Spotify.']},
'moving-minds':{en:['From youth at risk to inspiring leadership','An episode about education, leadership and breaking expected paths.'],ru:['От подростка группы риска к вдохновляющему лидерству','Эпизод об образовании, лидерстве и способности ломать предопределенные маршруты.']},
'glass-ceilings':{en:['Breaking glass ceilings — Episode 18','An interview about personal movement beyond labels and leadership for youth at risk.'],ru:['Разрушая стеклянные потолки — эпизод 18','Интервью о личном выходе за пределы ярлыков и лидерстве для молодежи группы риска.']},
'nadlan-interview':{en:['Freddy Moskovitz interviews Igor Vepretski','Episode 29: criminology, social entrepreneurship and public responsibility.'],ru:['Фредди Московиц беседует с Игорем Вепрецким','Эпизод 29: криминология, социальное предпринимательство и общественная ответственность.']},
'nitzotzot':{en:['How a TikTok creator changes the world','A public education page about a life story, virality, safe use and responsible creation.'],ru:['Как автор TikTok меняет мир','Публичная образовательная страница о жизненном пути, вирусности, безопасном использовании и ответственном творчестве.']},
'spotify-artist':{en:['Ido Vepretski — artist catalog','The public artist page for the musical identity Ido Vepretski.'],ru:['Ido Vepretski — каталог артиста','Публичная страница музыкальной идентичности Ido Vepretski.']},
'apple-artist':{en:['Ido Vepretski — Apple Music','The public song catalog on Apple Music.'],ru:['Ido Vepretski — Apple Music','Публичный каталог песен в Apple Music.']},
'soundcloud':{en:['Recording archive','Works and recordings preserved in the public music archive.'],ru:['Архив записей','Работы и записи, сохраненные в публичном музыкальном архиве.']},
'excel':{en:['Crazy about Excel','A musical work that became a cultural memory point in the video catalog.'],ru:['Без ума от Excel','Музыкальная работа, ставшая культурной точкой памяти в видеокаталоге.']},
'hazinor-hit':{en:['It is beginning to look like the next hit','A playful moment of music, group energy and humor that continued across music surfaces and artist identity.'],ru:['Похоже, рождается новый хит','Игровой момент музыки, групповой энергии и юмора, продолжившийся на музыкальных платформах и в идентичности артиста.']},
'instagram-reel':{en:['The special ingredient #israel','A dated snapshot of short-form video preserved as evidence rather than only a passing algorithmic moment.'],ru:['Особый ингредиент #israel','Датированный снимок короткого видео, сохраненный как свидетельство, а не только как мимолетный алгоритмический момент.']},
'police-reel':{en:['The superheroes of this period','A reel created during public fear that recognized people acting on the ground.'],ru:['Супергерои этого времени','Ролик, созданный во время общественного страха и выразивший благодарность людям, действовавшим на месте.']},
'tiktok-engine':{en:['The documented publishing engine','A dated snapshot of continuous creation; account metrics are context, not a substitute for item-level evidence.'],ru:['Документированный издательский двигатель','Датированный снимок непрерывного творчества; метрики аккаунта дают контекст, но не заменяют доказательства отдельных публикаций.']},
'youtube-channel':{en:['The public video channel','Long-form video, interviews, podcasts and music under one public channel.'],ru:['Публичный видеоканал','Длинные видео, интервью, подкасты и музыка в одном публичном канале.']},
'linkedin-starton':{en:['How digital innovation hubs empower communities','StartOn translated into the professional language of infrastructure, community, skills and opportunity.'],ru:['Как цифровые инновационные хабы усиливают сообщества','Видение StartOn на профессиональном языке инфраструктуры, сообщества, навыков и возможностей.']},
'linkedin-media':{en:['TikTok marketing and digital influence','Practical experience in creation and distribution shaped into a professional framework for digital influence.'],ru:['TikTok-маркетинг и цифровое влияние','Практический опыт создания и распространения, оформленный в профессиональную модель цифрового влияния.']},
'political-video':{en:['Where is the complete victory?','A concise public question distributed on a party page; metrics remain separately labeled as an indexed snapshot.'],ru:['Где полная победа?','Короткий общественный вопрос, распространенный на партийной странице; метрика отдельно обозначена как снимок индексации.']},
'safety-ru':{en:['What not to do during shelling','Russian-language public-service content showing that multilingual communication expands access rather than decorating it.'],ru:['Что нельзя делать во время обстрела','Общественно полезный материал на русском языке, показывающий, что многоязычие расширяет доступ, а не служит украшением.']},
'wikimedia':{en:['Open public portrait','A public visual asset supporting consistent identification across media, research and systems.'],ru:['Открытый публичный портрет','Публичный визуальный материал для последовательной идентификации в медиа, исследованиях и системах.']},
'platform-instagram':{en:['Instagram public profile','The canonical Instagram surface for reels, public portrait, creation and mission.'],ru:['Публичный профиль Instagram','Каноническая поверхность Instagram для Reels, публичного образа, творчества и миссии.']},
'platform-linkedin':{en:['LinkedIn professional profile','The professional authority surface for leadership, StartOn, systems, media and digital influence.'],ru:['Профессиональный профиль LinkedIn','Профессиональная поверхность лидерства, StartOn, систем, медиа и цифрового влияния.']},
'platform-linkedin-newsletter':{en:['LinkedIn long-form writing and newsletter','The public long-form layer connecting personal experience to professional frameworks.'],ru:['Статьи и рассылка LinkedIn','Публичная длинная форма, связывающая личный опыт с профессиональными моделями.']},
'platform-x':{en:['X public profile','The indexed public profile for real-time response, politics, news and ideas.'],ru:['Публичный профиль X','Индексированный публичный профиль для реакции в реальном времени, политики, новостей и идей.']},
'platform-threads':{en:['Threads public profile','The canonical Threads surface for short conversation and community continuity.'],ru:['Публичный профиль Threads','Каноническая поверхность Threads для коротких сообщений и продолжения сообщества.']},
'platform-telegram':{en:['Telegram community route','A canonical direct-community invite outside feed algorithms.'],ru:['Маршрут сообщества Telegram','Каноническое приглашение в прямое сообщество вне алгоритмов ленты.']},
'platform-medium':{en:['Medium author profile','Public English-language essays on journey, responsibility and social impact.'],ru:['Профиль автора Medium','Публичные англоязычные эссе о пути, ответственности и общественном влиянии.']},
'platform-academia':{en:['Academia.edu research library','The public research surface for identity, media, governance, algorithms and theory.'],ru:['Исследовательская библиотека Academia.edu','Публичная исследовательская поверхность об идентичности, медиа, управлении, алгоритмах и теории.']},
'platform-starton':{en:['StartOn official site','The canonical organization site for technology, creation, mentoring and belonging for youth.'],ru:['Официальный сайт StartOn','Канонический сайт организации о технологиях, творчестве, наставничестве и принадлежности молодежи.']},
'platform-linktree':{en:['Public master link index','A verified quick index for profiles, articles, interviews and viral moments.'],ru:['Публичный мастер-индекс ссылок','Подтвержденный быстрый индекс профилей, статей, интервью и вирусных моментов.']},
'platform-izi':{en:['IZI public profile','An additional canonical profile and link surface in the Israeli ecosystem.'],ru:['Публичный профиль IZI','Дополнительная каноническая профильная и ссылочная поверхность в израильской экосистеме.']}}
export function itemText(id:string,locale:Locale,title:string,summary:string){if(locale==='he')return{title,summary};const value=itemTranslations[id]?.[locale];return value?{title:value[0],summary:value[1]}:{title,summary}}
const metricTranslations:Record<string,{en:string;ru:string}>={'4.1K תגובות רגש בנקודת האינדוקס':{en:'4.1K reactions at the indexed snapshot',ru:'4,1 тыс. реакций на момент индексации'},'כ־129K צפיות באינדוקס מתוארך':{en:'About 129K views in a dated index',ru:'Около 129 тыс. просмотров в датированном индексе'},'כ־1.5K תגובות רגש באינדוקס':{en:'About 1.5K reactions in the public index',ru:'Около 1,5 тыс. реакций в публичном индексе'},'213K צפיות · 7.4K לייקים · 1.1K תגובות':{en:'213K views · 7.4K likes · 1.1K comments',ru:'213 тыс. просмотров · 7,4 тыс. отметок · 1,1 тыс. комментариев'},'904 פריטים · 12,655 עוקבים · 273,860 לייקים':{en:'904 items · 12,655 followers · 273,860 likes',ru:'904 публикации · 12 655 подписчиков · 273 860 отметок'},'כ־14K צפיות באינדוקס ציבורי':{en:'About 14K views in a public index',ru:'Около 14 тыс. просмотров в публичном индексе'}};
export const metricText=(metric:string|undefined,locale:Locale)=>!metric||locale==='he'?metric:metricTranslations[metric]?.[locale]||metric;
export const yearText=(year:string,locale:Locale)=>locale==='he'?year:year==='פעיל'?(locale==='en'?'Active':'Активно'):year==='ארכיון'?(locale==='en'?'Archive':'Архив'):year;
