import {useState} from 'react';
import {ArrowDown,ArrowUpRight,ExternalLink,MessageCircle,Sparkles} from 'lucide-react';
import {pageHref,rootHref,useLocale,type Locale} from '../locale';
import {albumChapters,coverMedia,signalMoments,type AlbumChapter,type AlbumDepth,type AlbumMedia} from './album-data';
import ConnectedPlatforms from '../platforms/ConnectedPlatforms';
import './album.css';

const copy={
he:{coverTitle:'החיים שלי. העבודה שלי. למה זה חשוב עכשיו.',coverBody:'מחרקוב לחולון, משירות ציבורי ל־StartOn, מפוסט לאולפן, ממוזיקה למחקר. לא קורות חיים — אלבום אישי של דרך שהפכה למערכות.',enter:'להיכנס לסיפור',talk:'לדבר / לשתף פעולה',opening:'חיים שהפכו למערכות',openingBody:'חמש תחנות מספיקות כדי להבין את הקשת. אחר כך אפשר להיכנס לעומק, לראיות ולארכיון.',value:'מה זה בנה בי',source:'למקור',depth:'להעמיק',echo:'מה יצא ממני והמשיך הלאה',echoBody:'לא “reach כולל”. שלושה מסלולים שבהם סיפור, רעיון או פעולה קיבלו חיים מחוץ לחשבון שלי.',now:'מה בונים מכאן?',closing:'האלבום הזה לא אמור להסתיים בצפייה.',closingBody:'בחרו את סוג הקשר שמתאים לכם. כל מסלול ממשיך עם ההקשר שכבר ראיתם — לא לדף צור קשר גנרי.',talkIntent:'לדבר / ראיון / הזמנה',partnerIntent:'שותפות / לבנות משהו',createIntent:'ליצור עם 7YA',evidenceIntent:'לראיות / לארכיון',fallback:'אין כאן תמונה מומצאת. המקור נשאר גלוי גם כשהפריים החזותי אינו מאומת.'},
en:{coverTitle:'My life. My work. Why it matters now.',coverBody:'From Kharkiv to Holon, from public service to StartOn, from a post to a studio, from music to research. Not a résumé — a personal album of a life that became systems.',enter:'Enter the story',talk:'Talk / collaborate',opening:'A LIFE THAT BECAME SYSTEMS',openingBody:'Five beats are enough to understand the range. Then you can go deeper into sources, evidence and the archive.',value:'WHAT THIS BUILT IN ME',source:'Open source',depth:'Go deeper',echo:'WHAT MOVED BEYOND ME',echoBody:'Not one “total reach” number. Three documented paths where a story, idea or action kept moving outside my own account.',now:'WHAT DO WE BUILD FROM HERE?',closing:'This album should not end with watching.',closingBody:'Choose the relationship that fits. Each path carries the context you already saw instead of dropping you into a generic contact page.',talkIntent:'Talk / interview / invite',partnerIntent:'Partner / build something',createIntent:'Create with 7YA',evidenceIntent:'Explore evidence / archive',fallback:'No invented image here. The source stays visible when the visual frame is not verified.'},
ru:{coverTitle:'Моя жизнь. Моя работа. Почему это важно сейчас.',coverBody:'От Харькова до Холона, от государственной службы до StartOn, от поста до студии, от музыки до исследований. Не резюме — личный альбом пути, который стал системами.',enter:'Войти в историю',talk:'Поговорить / сотрудничать',opening:'ЖИЗНЬ, КОТОРАЯ СТАЛА СИСТЕМАМИ',openingBody:'Пяти точек достаточно, чтобы увидеть диапазон. Затем можно углубиться в источники, доказательства и архив.',value:'ЧТО ЭТО ВО МНЕ СОЗДАЛО',source:'Открыть источник',depth:'Углубиться',echo:'ЧТО ПРОДОЛЖИЛО ЖИТЬ ВНЕ МЕНЯ',echoBody:'Не одно число «total reach». Три документированных маршрута, где история, идея или действие продолжили движение за пределами моего аккаунта.',now:'ЧТО МЫ СТРОИМ ДАЛЬШЕ?',closing:'Этот альбом не должен заканчиваться просмотром.',closingBody:'Выберите подходящий тип связи. Каждый маршрут сохраняет контекст, который вы уже увидели.',talkIntent:'Разговор / интервью / приглашение',partnerIntent:'Партнерство / создать вместе',createIntent:'Создать с 7YA',evidenceIntent:'Доказательства / архив',fallback:'Никакой выдуманной фотографии. Источник остаётся видимым, если визуальный кадр не подтверждён.'}
} as const;

const depthHref=(depth:AlbumDepth,locale:Locale)=>depth==='media'?pageHref('media',locale):depth==='music'?pageHref('music',locale):depth==='research'?rootHref('research/?lang='+locale):depth==='starton'?rootHref('starton/'):depth==='evidence'?rootHref('evidence/'):depth==='archive'?rootHref('restoration/'):pageHref('create',locale);

function MediaFrame({media,chapter,locale,fallback}:{media?:AlbumMedia;chapter:AlbumChapter;locale:Locale;fallback:string}){const [broken,setBroken]=useState(false);if(!media||broken)return <div className='album-media-fallback' role='img' aria-label={chapter.title[locale]}><small dir='ltr'>EDITORIAL SOURCE FRAME · {chapter.era}</small><strong>{chapter.title[locale]}</strong><p>{fallback}</p><a href={chapter.sourceUrl} target='_blank' rel='noreferrer'>{chapter.sourceLabel[locale]} <ExternalLink/></a></div>;return <figure className='album-media-frame'><img src={media.src} alt={media.alt[locale]} loading={chapter.id==='service'?'eager':'lazy'} decoding='async' referrerPolicy='no-referrer' style={{objectPosition:media.objectPosition||'50% 50%'}} onError={()=>setBroken(true)}/><figcaption><span>{media.caption[locale]}</span><a href={media.sourceUrl} target='_blank' rel='noreferrer'>{media.sourceLabel} <ExternalLink/></a></figcaption></figure>}

function CoverFrame({locale}:{locale:Locale}){const [broken,setBroken]=useState(false);if(broken)return <div className='album-cover-fallback'><b>IGOR VEPRETSKI</b><span>{copy[locale].fallback}</span><a href={coverMedia.sourceUrl} target='_blank' rel='noreferrer'>WIKIMEDIA COMMONS ↗</a></div>;return <figure className='album-cover-frame'><img src={coverMedia.src} alt={coverMedia.alt[locale]} decoding='async' referrerPolicy='no-referrer' style={{objectPosition:coverMedia.objectPosition}} onError={()=>setBroken(true)}/><figcaption><b>IGOR VEPRETSKI</b><span>{coverMedia.caption[locale]}</span><a href={coverMedia.sourceUrl} target='_blank' rel='noreferrer'>SOURCE ↗</a></figcaption></figure>}

export default function AlbumHome(){const {locale,dir}=useLocale();const c=copy[locale];const home=pageHref('home',locale);const talkHref=home+'&chat=open&journeyChapter=build&journeyChoice=collaborate';const openingIds=['origin','service','voice','starton','research'] as const;return <main className='album-home' dir={dir}>
<section className='album-cover' id='album-cover'><div className='album-cover-copy'><p className='album-eyebrow' dir='ltr'>PERSONAL ALBUM / IGOR VEPRETSKI</p><h1>{c.coverTitle}</h1><p className='album-cover-body'>{c.coverBody}</p><div className='album-actions'><a className='album-action-primary' href='#album-journey'>{c.enter}<ArrowDown/></a><a className='album-action-secondary' href={talkHref}>{c.talk}<MessageCircle/></a></div><small className='album-cover-proof' dir='ltr'>REAL PERSON · PUBLIC SOURCES · STORY → VALUE → PROOF → ACTION</small></div><CoverFrame locale={locale}/></section>
<section className='album-opening' id='album-journey'><header><p dir='ltr'>{locale==='en'?'A LIFE THAT BECAME SYSTEMS':'7YA / LIFE → SYSTEMS'}</p><h2>{c.opening}</h2><p>{c.openingBody}</p></header><div className='album-opening-grid'>{openingIds.map((id,index)=>{const chapter=albumChapters.find(item=>item.id===id)!;return <a href={'#album-'+chapter.id} key={id}><span dir='ltr'>{String(index+1).padStart(2,'0')} / {chapter.era}</span><strong>{chapter.kicker[locale]}</strong><p>{chapter.publicValue[locale]}</p><ArrowUpRight/></a>})}</div></section>
<section className='album-chapters' aria-label='Personal album chapters'>{albumChapters.map((chapter,index)=><article className={'album-chapter '+(index%2?'is-flipped':'')} id={'album-'+chapter.id} key={chapter.id}><div className='album-chapter-media'><MediaFrame media={chapter.media} chapter={chapter} locale={locale} fallback={c.fallback}/></div><div className='album-chapter-copy'><div className='album-chapter-meta'><span dir='ltr'>{chapter.index} / {chapter.era}</span><b>{chapter.kicker[locale]}</b></div><h2>{chapter.title[locale]}</h2><p className='album-story'>{chapter.story[locale]}</p><aside className='album-value'><small dir='ltr'>{locale==='en'?'WHAT THIS BUILT IN ME':c.value.toUpperCase()}</small><strong>{chapter.capability[locale]}</strong><p>{chapter.publicValue[locale]}</p></aside><nav className='album-chapter-actions'><a href={chapter.sourceUrl} target='_blank' rel='noreferrer'>{c.source}<ExternalLink/></a><a href={depthHref(chapter.depth,locale)}>{chapter.depthLabel[locale]}<ArrowUpRight/></a>{chapter.id==='now'&&<a href={talkHref}>{c.talk}<MessageCircle/></a>}</nav></div></article>)}</section>
<section className='album-signal' id='album-echo'><header><p dir='ltr'>PUBLIC SIGNAL / SOURCE-LOCAL</p><h2>{c.echo}</h2><p>{c.echoBody}</p></header><div className='album-signal-grid'>{signalMoments.map(item=><a href={item.href} target='_blank' rel='noreferrer' key={item.id}><small dir='ltr'>{item.eyebrow}</small><strong>{item.title[locale]}</strong><p>{item.body[locale]}</p><span>{c.source} <ExternalLink/></span></a>)}</div><nav><a href={pageHref('media',locale)}>{locale==='he'?'למדיה ולראיונות':locale==='ru'?'Медиа и интервью':'Media & interviews'}<ArrowUpRight/></a><a href={rootHref('evidence/')}>{c.evidenceIntent}<ArrowUpRight/></a></nav></section>
<ConnectedPlatforms/>
<section className='album-research-bridge' id='album-research'><div><p dir='ltr'>IDEAS / RESEARCH / BUILD</p><h2>{albumChapters.find(item=>item.id==='research')?.title[locale]}</h2></div><p>{albumChapters.find(item=>item.id==='research')?.publicValue[locale]}</p><a href={rootHref('research/?lang='+locale)}>{locale==='he'?'למפת המחקר':locale==='ru'?'К карте исследований':'Open research map'}<ArrowUpRight/></a></section>
<section className='album-closing' id='album-closing'><div className='album-closing-copy'><p dir='ltr'>{c.now}</p><h2>{c.closing}</h2><p>{c.closingBody}</p></div><div className='album-intents'><a href={talkHref}><span>01</span><strong>{c.talkIntent}</strong><MessageCircle/></a><a href={rootHref('contact/')}><span>02</span><strong>{c.partnerIntent}</strong><ArrowUpRight/></a><a href={pageHref('create',locale)}><span>03</span><strong>{c.createIntent}</strong><Sparkles/></a><a href={rootHref('evidence/')}><span>04</span><strong>{c.evidenceIntent}</strong><ArrowUpRight/></a></div><footer><b dir='ltr'>#7YA🥷</b><span>IGOR VEPRETSKI · LIFE → WORK → PROOF → NEXT MOVE</span></footer></section>
</main>}
