import type {Locale} from '../locale';

export type L10n=Record<Locale,string>;
export type AlbumDepth='media'|'music'|'research'|'starton'|'evidence'|'archive'|'create';
export type AlbumMedia={id:string;src:string;kind:'photo'|'video-poster'|'press'|'document';alt:L10n;caption:L10n;sourceUrl:string;sourceLabel:string;authenticity:'original'|'public-source'|'source-thumbnail';objectPosition?:string};
export type AlbumChapter={id:'origin'|'service'|'voice'|'create'|'starton'|'research'|'now';index:string;era:string;kicker:L10n;title:L10n;story:L10n;capability:L10n;publicValue:L10n;media?:AlbumMedia;sourceUrl:string;sourceLabel:L10n;depth:AlbumDepth;depthLabel:L10n};

const l=(he:string,en:string,ru:string):L10n=>({he,en,ru});
const thumb=(id:string)=>'https://i.ytimg.com/vi/'+id+'/hqdefault.jpg';
const WIKIMEDIA='https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png/960px-Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png';
const MYNET='https://pic1.yitweb.co.il/cdn-cgi/image/f%3Dauto%2Cw%3D740%2Cq%3D75/picserver/mynet/crop_images/2022/05/11/r1F0NeKU9/r1F0NeKU9_0_0_640_360_0_large.jpg';
const HIDABROOT='https://storage.hidabroot.org/articles_new/327351_tumb_730X500.jpg';

export const coverMedia:AlbumMedia={id:'cover-wikimedia',src:WIKIMEDIA,kind:'photo',alt:l('איגור ופרצקי — דיוקן ציבורי','Igor Vepretski — public portrait','Игорь Вепрецкий — публичный портрет'),caption:l('דיוקן ציבורי · Wikimedia Commons','Public portrait · Wikimedia Commons','Публичный портрет · Wikimedia Commons'),sourceUrl:'https://commons.wikimedia.org/wiki/File:Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png',sourceLabel:'WIKIMEDIA COMMONS · PUBLIC PORTRAIT',authenticity:'public-source',objectPosition:'50% 24%'};

export const albumChapters:AlbumChapter[]=[
{id:'origin',index:'01',era:'1990—2011',kicker:l('מקור / שייכות','ORIGIN / BELONGING','ИСТОК / ПРИНАДЛЕЖНОСТЬ'),title:l('לפני המותג היה אדם.','Before the brand, there was a person.','До бренда был человек.'),story:l('חרקוב, עלייה לישראל, בת־ים, חולון וג׳סי כהן הם לא רק רקע. הם המקום שממנו צמחו השאלות על שייכות, הזדמנות ומי רואים בזמן. אין כאן צילום ילדות מומצא; נקודת העוגן הציבורית הראשונה היא רשומת עיתונות מ־2011.','Kharkiv, immigration to Israel, Bat Yam, Holon and Jesse Cohen are not background copy. They are where the questions about belonging, opportunity and who gets seen in time began. There is no invented childhood photo here; the first public anchor is a 2011 press record.','Харьков, переезд в Израиль, Бат-Ям, Холон и Джесси Коэн — не фон. Здесь появились вопросы о принадлежности, возможностях и о том, кого замечают вовремя. Выдуманной детской фотографии здесь нет; первая публичная опора — публикация 2011 года.'),capability:l('לקרוא אדם בתוך הקשר','Read a person inside context','Видеть человека в контексте'),publicValue:l('לבנות מערכות שמתחילות לפני שהבעיה מתפוצצת.','Build systems that arrive before the problem explodes.','Создавать системы, которые появляются до того, как проблема взрывается.'),sourceUrl:'https://www.makorrishon.co.il/nrg/online/54/ART2/235/169.html',sourceLabel:l('מקור ראשון / NRG · 2011','Makor Rishon / NRG · 2011','Makor Rishon / NRG · 2011'),depth:'archive',depthLabel:l('לציר החיים המלא','Open the full life record','Открыть полный жизненный архив')},
{id:'service',index:'02',era:'2008—2021',kicker:l('שירות / אחריות','SERVICE / RESPONSIBILITY','СЛУЖБА / ОТВЕТСТВЕННОСТЬ'),title:l('מהשטח למדתי לקרוא מערכות.','The field taught me to read systems.','Поле научило меня читать системы.'),story:l('צה״ל, עבודה בנציגויות בחו״ל ומשטרת ישראל נתנו מסגרת, משמעת ואחריות. הפריים כאן הוא ראיון ציבורי מאוחר יותר על המעבר מהשירות למשימה חברתית — הקשר מתועד, לא צילום מומצא מן השירות.','Military service, overseas public work and the Israel Police built discipline, responsibility and systems awareness. The frame here is a later public interview about moving from service into a social mission — documented context, not invented service photography.','Армия, работа за рубежом и полиция Израиля дали дисциплину, ответственность и понимание систем. Кадр здесь — более позднее публичное интервью о переходе от службы к общественной миссии, а не выдуманное фото службы.'),capability:l('אחריות תחת לחץ','Responsibility under pressure','Ответственность под давлением'),publicValue:l('להבין איפה מערכת פוגשת אדם — ואיפה היא מפספסת אותו.','Understand where institutions meet people — and where they miss them.','Понимать, где система встречает человека — и где упускает его.'),media:{id:'service-channel14',src:thumb('O3v309CA4ao'),kind:'video-poster',alt:l('איגור ופרצקי בראיון ערוץ 14','Igor Vepretski in a Channel 14 interview','Игорь Вепрецкий в интервью Channel 14'),caption:l('פריים מקור · ערוץ 14 · 2022','Source frame · Channel 14 · 2022','Кадр источника · Channel 14 · 2022'),sourceUrl:'https://youtu.be/O3v309CA4ao',sourceLabel:'CHANNEL 14 · PUBLIC INTERVIEW · 2022',authenticity:'source-thumbnail'},sourceUrl:'https://youtu.be/O3v309CA4ao',sourceLabel:l('ראיון ציבורי · ערוץ 14','Public interview · Channel 14','Публичное интервью · Channel 14'),depth:'media',depthLabel:l('לראיונות ולמדיה','Open interviews & media','Открыть интервью и медиа')},
{id:'voice',index:'03',era:'2022—2024',kicker:l('קול / הד','VOICE / SIGNAL','ГОЛОС / СИГНАЛ'),title:l('חוויה פרטית יצאה מהפיד.','Private experience moved beyond the feed.','Личный опыт вышел за пределы ленты.'),story:l('אבהות, הונאות קשישים, חינוך וזהות הפכו מפוסטים אישיים לכתבות, ריפוסטים ושיחות באולפן. הנקודה השיווקית אינה “ויראליות”; היא היכולת לתרגם חוויה למסגור שאנשים ומערכות ממשיכים איתו.','Fatherhood, elder fraud, education and identity moved from personal posts into articles, reposts and studio conversations. The point is not vanity virality; it is the ability to translate lived experience into a frame that people and institutions carry forward.','Отцовство, мошенничество против пожилых, образование и идентичность перешли из личных постов в статьи, репосты и студийные разговоры. Важна не «вирусность», а способность переводить опыт в рамку, которую продолжают люди и институты.'),capability:l('לנסח אמת שאנשים זוכרים','Frame an experience people remember','Формулировать опыт так, чтобы его запоминали'),publicValue:l('להפוך תשומת לב לשיחה ציבורית אחראית, בלי לאבד את מקור הטענה.','Turn attention into responsible public conversation without losing provenance.','Превращать внимание в ответственную общественную беседу, не теряя происхождение утверждений.'),media:{id:'voice-hidabroot',src:HIDABROOT,kind:'press',alt:l('כתבת הידברות על הסיפור אבא מושלם','Hidabroot article on A Perfect Father','Статья Hidabroot об истории «Идеальный отец»'),caption:l('מקור מערכת · הידברות · 2023','Publisher source · Hidabroot · 2023','Источник издателя · Hidabroot · 2023'),sourceUrl:'https://www.hidabroot.org/article/1179015',sourceLabel:'HIDABROOT · PUBLIC ARTICLE · 2023',authenticity:'public-source',objectPosition:'50% 20%'},sourceUrl:'https://www.hidabroot.org/article/1179015',sourceLabel:l('הידברות · מקור ציבורי','Hidabroot · public source','Hidabroot · публичный источник'),depth:'media',depthLabel:l('למפת ההד והמדיה','Open the media echo','Открыть медийное эхо')},
{id:'create',index:'04',era:'2020—2026',kicker:l('יצירה / תרבות','CREATE / CULTURE','ТВОРЧЕСТВО / КУЛЬТУРА'),title:l('החלק שקורות חיים מפספסים.','The part a résumé misses.','То, что резюме обычно упускает.'),story:l('מוזיקה, קליפים, הומור ושיתופי פעולה אינם הפסקה מהאדם “הרציני”. הם המקום שבו קול, קצב וזהות יוצאים בלי פילטר של תפקיד ציבורי.','Music, videos, humour and collaborations are not a break from the “serious” person. They are where voice, rhythm and identity leave the filter of a formal role.','Музыка, клипы, юмор и коллаборации — не пауза от «серьёзного» человека. Здесь голос, ритм и идентичность выходят без фильтра официальной роли.'),capability:l('לנוע בין שפות וקהל','Move across forms and audiences','Переключаться между формами и аудиториями'),publicValue:l('לחבר אנשים גם דרך תרבות, לא רק דרך מסמך או נאום.','Connect people through culture, not only through documents or speeches.','Соединять людей через культуру, а не только через документы и речи.'),media:{id:'create-bizzi',src:thumb('jRjZjpqAgEw'),kind:'video-poster',alt:l('NAWAN ft. VEPRETSKI — BIZZI','NAWAN ft. VEPRETSKI — BIZZI','NAWAN ft. VEPRETSKI — BIZZI'),caption:l('קליפ רשמי · 2025','Official video · 2025','Официальный клип · 2025'),sourceUrl:'https://www.youtube.com/watch?v=jRjZjpqAgEw',sourceLabel:'YOUTUBE · OFFICIAL VIDEO · 2025',authenticity:'source-thumbnail'},sourceUrl:'https://www.youtube.com/watch?v=jRjZjpqAgEw',sourceLabel:l('BIZZI · הקליפ הרשמי','BIZZI · official video','BIZZI · официальный клип'),depth:'music',depthLabel:l('לכל המוזיקה','Open all music','Открыть всю музыку')},
{id:'starton',index:'05',era:'2022—NOW',kicker:l('חזרה / StartOn','RETURN / STARTON','ВОЗВРАЩЕНИЕ / STARTON'),title:l('הקושי הפך לתשתית.','Hardship became infrastructure.','Трудность стала инфраструктурой.'),story:l('החזרה לג׳סי כהן סגרה מעגל: לא עוד הרצאה על מוטיבציה, אלא ניסיון לבנות מקום שבו טכנולוגיה, יצירה, מנטורינג ושייכות פוגשים צעיר לפני שהמערכת מגדירה אותו דרך משבר.','Returning to Jesse Cohen closed a loop: not another motivational talk, but an attempt to build a place where technology, creation, mentoring and belonging meet a young person before crisis becomes their definition.','Возвращение в Джесси Коэн замкнуло круг: не очередная мотивационная лекция, а попытка создать место, где технологии, творчество, наставничество и принадлежность встречают молодого человека до того, как кризис определит его.'),capability:l('להפוך ניסיון למודל פעולה','Turn experience into an operating model','Превращать опыт в рабочую модель'),publicValue:l('לבנות הזדמנות מוחשית במקום שבו קל יותר למדוד כשל.','Build tangible opportunity where systems too often measure failure.','Создавать реальную возможность там, где системы чаще измеряют неудачу.'),media:{id:'starton-mynet',src:MYNET,kind:'press',alt:l('איגור ופרצקי בכתבת mynet על החזרה לג׳סי כהן','Igor Vepretski in the mynet story about returning to Jesse Cohen','Игорь Вепрецкий в материале mynet о возвращении в Джесси Коэн'),caption:l('צילום עיתונות ציבורי · mynet · 13.05.2022','Public press photograph · mynet · 13.05.2022','Публичная пресс-фотография · mynet · 13.05.2022'),sourceUrl:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',sourceLabel:'MYNET · PUBLIC PRESS PHOTO · 13.05.2022',authenticity:'public-source',objectPosition:'50% 28%'},sourceUrl:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',sourceLabel:l('mynet · חוזר לשכונה','mynet · Returning to the neighborhood','mynet · Возвращение в район'),depth:'starton',depthLabel:l('להיכנס ל־StartOn','Enter StartOn','Открыть StartOn')},
{id:'research',index:'06',era:'2025—2026',kicker:l('מעבדה / מחקר','LAB / RESEARCH','ЛАБОРАТОРИЯ / ИССЛЕДОВАНИЕ'),title:l('ניסיון הפך לשאלות שאפשר לבדוק.','Experience became questions that can be tested.','Опыт стал вопросами, которые можно проверять.'),story:l('המחקר נועד להפריד בין תחושה, השערה, מסורת פרשנית וטענה אמפירית. המסגרות המקוריות מוצגות עם סטטוס ומגבלות — לא כאקדמיה מדומיינת ולא כקונצנזוס שהן עוד לא הרוויחו.','Research forces a separation between feeling, hypothesis, interpretive tradition and empirical claim. Original frameworks are shown with status and limits — not as imagined authority or consensus they have not earned.','Исследование заставляет разделять чувство, гипотезу, интерпретационную традицию и эмпирическое утверждение. Авторские модели показываются со статусом и ограничениями — без выдуманного авторитета.'),capability:l('למסגר בלי לנפח סמכות','Frame ideas without inflating authority','Формулировать идеи без раздувания авторитета'),publicValue:l('לחבר ניסיון, מקורות ומגבלות למסגרת שאפשר לבקר ולשפר.','Connect experience, sources and limitations into frameworks that can be challenged and improved.','Соединять опыт, источники и ограничения в рамки, которые можно критиковать и улучшать.'),sourceUrl:'https://igorvepretski.academia.edu/',sourceLabel:l('ספריית מחקר ציבורית · Academia.edu','Public research library · Academia.edu','Публичная исследовательская библиотека · Academia.edu'),depth:'research',depthLabel:l('לספריית המחקר','Open the research library','Открыть библиотеку исследований')},
{id:'now',index:'07',era:'RIGHT NOW',kicker:l('עכשיו / לבנות','NOW / BUILD','СЕЙЧАС / СОЗДАВАТЬ'),title:l('האלבום לא נגמר בעבר.','The album does not end in the past.','Альбом не заканчивается прошлым.'),story:l('7YA מחבר עכשיו חיים, תוכן, מחקר, StartOn ומערכות עבודה. ההווה לא מקבל צילום ישן שמתחזה ל“עכשיו”; כשהמקור החי זמין נכנסים אליו, וכשלא — הטקסט נשאר גלוי וכנה.','7YA now connects life, content, research, StartOn and operating systems. The present does not get an old photo pretending to be “now”; when a live source exists we open it, and when it does not the editorial frame stays explicit and honest.','7YA сегодня соединяет жизнь, контент, исследования, StartOn и рабочие системы. Настоящее не получает старую фотографию под видом «сейчас»: когда есть живой источник, мы открываем его; когда нет — редакционная рамка остаётся честной.'),capability:l('לחבר חלקים למערכת אחת','Connect separate parts into one operating system','Соединять части в одну работающую систему'),publicValue:l('לעבור מסיפור מתועד לשיתוף פעולה, בנייה ותוצאה חדשה.','Move from documented story into collaboration, building and new outcomes.','Переходить от документированной истории к сотрудничеству, созданию и новым результатам.'),sourceUrl:'https://www.instagram.com/igor.vepretski/',sourceLabel:l('הפיד הציבורי החי','Live public feed','Живая публичная лента'),depth:'create',depthLabel:l('לבנות משהו יחד','Build something together','Создать что-то вместе')}
];

export const signalMoments=[
{id:'fraud',eyebrow:'POST → TV',title:l('פוסט אישי נכנס לאולפן חדשות.','A personal post entered a news studio.','Личный пост оказался в новостной студии.'),body:l('סיפור על הונאת קשישים יצא מהפיד וקיבל המשך טלוויזיוני.','An elder-fraud story moved beyond the feed into television coverage.','История о мошенничестве против пожилых вышла из ленты в телевидение.'),href:'https://www.youtube.com/watch?v=AE5hDzLM5XU'},
{id:'father',eyebrow:'STORY → ARTICLE',title:l('משפט על אבהות קיבל חיים אצל אחרים.','A sentence about fatherhood acquired a life elsewhere.','Фраза об отцовстве получила жизнь у других.'),body:l('הפצה חיצונית וכתבה הפכו סיפור אישי לשיחה רחבה יותר.','External distribution and coverage turned a personal story into a wider conversation.','Внешнее распространение и статья превратили личную историю в более широкий разговор.'),href:'https://www.hidabroot.org/article/1179015'},
{id:'starton',eyebrow:'ATTENTION → INSTITUTION',title:l('הסיפור חזר לשכונה כ־StartOn.','The story returned to the neighborhood as StartOn.','История вернулась в район как StartOn.'),body:l('תשומת לב נבחנה מול שאלה קשה יותר: האם אפשר לבנות מקום ממשי.','Attention faced a harder test: can it become a real place and operating model?','Внимание столкнулось с более сложным тестом: можно ли превратить его в реальное место и рабочую модель?'),href:'https://starton.org.il/'}
] as const;
