import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { ExternalLink, Music2, Play, Search, ShieldCheck } from 'lucide-react';
import './press.css';

type Item={title:string;category:string;source:string;year:string;url:string;status:string;summary:string};
const categories=['הכול','וידאו','תקשורת','פודקאסטים','מוזיקה','רשתות','StartOn','מערכות'];
const items:Item[]=[
{title:'7YA.IO — הבית הציבורי',category:'מערכות',source:'7YA',year:'2026',url:'https://7ya.io/',status:'CANONICAL',summary:'המערכת הציבורית המרכזית לזהות, השפעה, ראיות ופעולה.'},
{title:'Linktree — מפת הקישורים הציבורית',category:'מערכות',source:'Linktree',year:'2024–2026',url:'https://linktr.ee/igor.vepretski',status:'OFFICIAL LINK',summary:'מפת קישורים מרוכזת לראיונות, כתבות, רשתות, מוזיקה ו־StartOn.'},
{title:'Igor Vepretski #7YA',category:'וידאו',source:'YouTube',year:'2015–2026',url:'https://www.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',status:'OFFICIAL CHANNEL',summary:'ערוץ הווידאו המרכזי: חברה, זהות, פוליטיקה, יוזמה, מוזיקה והשפעה.'},
{title:'Igor Vepretski — TikTok',category:'רשתות',source:'TikTok',year:'פעיל',url:'https://www.tiktok.com/@igor.vepretski',status:'OFFICIAL LINK',summary:'תוכן קצר, LIVE ושיחה ישירה עם הקהל.'},
{title:'Igor Vepretski — Instagram',category:'רשתות',source:'Instagram',year:'פעיל',url:'https://www.instagram.com/igor.vepretski/',status:'OFFICIAL LINK',summary:'וידאו, פעילות ציבורית, StartOn ורגעים מן השטח.'},
{title:'Vepretski Igor — Instagram',category:'רשתות',source:'Instagram',year:'פעיל',url:'https://www.instagram.com/vepretski.igor/',status:'OFFICIAL LINK',summary:'חשבון Instagram רשמי נוסף בבעלות איגור ופרצקי.'},
{title:'Igor Vepretski — Threads',category:'רשתות',source:'Threads',year:'פעיל',url:'https://www.threads.net/@igor.vepretski',status:'OFFICIAL LINK',summary:'מחשבות קצרות ושיח ציבורי שוטף.'},
{title:'Igor Vepretski — X',category:'רשתות',source:'X',year:'פעיל',url:'https://x.com/igorvepretski',status:'OFFICIAL LINK',summary:'עמדות, חדשות ועדכונים ציבוריים.'},
{title:'Igor Vepretski — Facebook',category:'רשתות',source:'Facebook',year:'פעיל',url:'https://www.facebook.com/igor7ya',status:'OFFICIAL LINK',summary:'פוסטים, שיתופים ותכנים שהגיעו לקהלים רחבים.'},
{title:'Igor Vepretski — LinkedIn',category:'רשתות',source:'LinkedIn',year:'פעיל',url:'https://www.linkedin.com/in/vepretski/',status:'PROFESSIONAL PROFILE',summary:'StartOn, ניסיון מקצועי, יזמות חברתית וטכנולוגיה.'},
{title:'Igor Vepretski — Medium',category:'תקשורת',source:'Medium',year:'2024',url:'https://medium.com/@igor.vepretski/igor-vepretski-from-troubled-beginnings-to-social-impact-a-journey-of-resilience-and-purpose-253aa8af266d',status:'AUTHORED',summary:'סיפור חיים באנגלית: resilience, purpose and social impact.'},
{title:'Igor Vepretski — Academia',category:'מערכות',source:'Academia.edu',year:'2026',url:'https://igorvepretski.academia.edu/',status:'AUTHORED',summary:'מחקר וכתיבה על מנהיגות בעידן האלגוריתמי.'},
{title:'Igor Vepretski — GitHub',category:'מערכות',source:'GitHub',year:'פעיל',url:'https://github.com/vepretski',status:'PUBLIC CODE',summary:'קוד, מערכות ותשתיות ציבוריות הקשורות ל־7YA.'},
{title:'StartOn — חדשנות קהילתית',category:'StartOn',source:'StartOn',year:'2022–2026',url:'https://starton.org.il/',status:'ORGANIZATION SOURCE',summary:'בית טכנולוגי בטוח לנוער בסיכון: למידה, קהילה, יצירה ושייכות.'},
{title:'הזמן של איגור ופרצקי',category:'תקשורת',source:'זמן ישראל',year:'2022–2023',url:'https://www.zman.co.il/writer/20815/',status:'PUBLISHER SOURCE',summary:'עמוד הכותב והטורים על חינוך, רשתות, הורות וחברה.'},
{title:'קצין משטרה עזב הכול למען נוער בסיכון',category:'תקשורת',source:'חדשות 13',year:'2022',url:'https://prod.13tv.co.il/item/news/haolam-haboker/season-01/clips/u0uoy-903061791/?pid=44',status:'INDEPENDENT SOURCE',summary:'כתבת טלוויזיה על המעבר משירות ציבורי להקמת StartOn.'},
{title:'חוזר לשכונה: מרכז לנוער בג׳סי כהן',category:'תקשורת',source:'Mynet חולון',year:'2022',url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',status:'INDEPENDENT SOURCE',summary:'ראיון עומק על החזרה לשכונה והחזון למרכז טכנולוגי.'},
{title:'נגד כל הסיכויים',category:'תקשורת',source:'מקור ראשון / NRG',year:'2011',url:'https://www.makorrishon.co.il/nrg/online/54/ART2/235/169.html',status:'ARCHIVE SOURCE',summary:'פרופיל מוקדם המתעד פרק משמעותי במסע החיים.'},
{title:'אבא מושלם — זה אבא ששם',category:'תקשורת',source:'הידברות',year:'2023',url:'https://www.hidabroot.org/article/1179015',status:'INDEPENDENT SOURCE',summary:'סיפור אישי שצמח מפוסט ציבורי וזכה לחשיפה רחבה.'},
{title:'מנער בסיכון ליזם חברתי',category:'פודקאסטים',source:'Mindset',year:'2022',url:'https://mindset.org.il/%D7%9E%D7%A0%D7%A2%D7%A8-%D7%91%D7%A1%D7%99%D7%9B%D7%95%D7%9F-%D7%9C%D7%99%D7%96%D7%9D-%D7%97%D7%91%D7%A8%D7%AA%D7%99-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%A4/',status:'PODCAST SOURCE',summary:'שיחה על מסע החיים, בחירות, אחריות ויזמות חברתית.'},
{title:'מנוער בסיכון למנהיגות מעוררת השראה',category:'פודקאסטים',source:'מוחות בתנועה',year:'2023',url:'https://podtail.com/podcast/092cc570/--18/',status:'PODCAST SOURCE',summary:'פרק על חינוך, מנהיגות והיכולת לשבור מסלולים צפויים.'},
{title:'מהבריחה מפסטיבל הנובה להתפכחות',category:'פודקאסטים',source:'YouTube',year:'2024',url:'https://www.youtube.com/watch?v=3h-oEuW8GJI',status:'VIDEO SOURCE',summary:'שיחה על 7 באוקטובר, זהות, חיים והחברה הישראלית.'},
{title:'אם לנו קשה, מה עובר על נוער בסיכון',category:'פודקאסטים',source:'YouTube',year:'2023',url:'https://www.youtube.com/watch?v=U2d_hulZAC0',status:'VIDEO SOURCE',summary:'ראיון אצל פרדי מוסקוביץ׳ על אחריות כלפי צעירים בזמן משבר.'},
{title:'אירועי 7/10 שינו את ה־DNA הישראלי',category:'פודקאסטים',source:'YouTube',year:'2024',url:'https://www.youtube.com/watch?v=3mG7qVapcII',status:'VIDEO SOURCE',summary:'קטע שיחה על השינוי הציבורי והלאומי לאחר 7 באוקטובר.'},
{title:'Ido Vepretski — Spotify',category:'מוזיקה',source:'Spotify',year:'2020–2026',url:'https://open.spotify.com/artist/0fgRoQ6PoCHlVCIr8a5d6u',status:'ARTIST PAGE',summary:'קטלוג המוזיקה של הזהות היצירתית Ido Vepretski.'},
{title:'Ido Vepretski — Apple Music',category:'מוזיקה',source:'Apple Music',year:'2020–2026',url:'https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he',status:'ARTIST PAGE',summary:'עמוד אמן וקטלוג שירים ב־Apple Music.'},
{title:'Ido Vepretski — SoundCloud',category:'מוזיקה',source:'SoundCloud',year:'ארכיון',url:'https://soundcloud.com/idovepretski',status:'ARTIST PAGE',summary:'יצירות והקלטות מן הארכיון המוזיקלי.'},
{title:'Igor Vepretski — Topic',category:'מוזיקה',source:'YouTube Music',year:'ארכיון',url:'https://www.youtube.com/channel/UClTu42Biy2tu8Ety5-6NoIQ',status:'TOPIC CHANNEL',summary:'ערוץ Topic מוזיקלי תחת השם Igor Vepretski.'},
{title:'Ido Vepretski — Topic',category:'מוזיקה',source:'YouTube Music',year:'ארכיון',url:'https://www.youtube.com/channel/UCrT7rwWGkDbrCSMH7JXLkXw',status:'TOPIC CHANNEL',summary:'ערוץ Topic מוזיקלי תחת הזהות Ido Vepretski.'},
{title:'מסמך ציבורי — StartOn',category:'StartOn',source:'GuideStar',year:'פעיל',url:'https://www.guidestar.org.il/sfc/servlet.shepherd/document/download/0690800000fu29fAAA',status:'PUBLIC REGISTRY',summary:'מסמך ציבורי של העמותה מתוך מאגר GuideStar.'},
{title:'פרופיל הכותב איגור ופרצקי',category:'תקשורת',source:'זמן ישראל',year:'2022–2023',url:'https://www.zman.co.il/writer/20815/',status:'PUBLISHER SOURCE',summary:'עמוד הכותב המרכז את הטורים על הורות, חינוך, רשתות וחברה.'},
{title:'איך כוכב טיקטוק משנה את העולם',category:'StartOn',source:'ניצוצות',year:'פעיל',url:'https://www.nitzotzot.org.il/spark/%D7%90%D7%99%D7%9A-%D7%9B%D7%95%D7%9B%D7%91-%D7%98%D7%99%D7%A7%D7%98%D7%95%D7%A7-%D7%9E%D7%A9%D7%A0%D7%94-%D7%90%D7%AA-%D7%94%D7%A2%D7%95%D7%9C%D7%9D/',status:'VERIFIED SOURCE',summary:'עמוד הרצאה ציבורי על סיפור חיים, טיקטוק, ויראליות ושימוש בטוח.'},
{title:'סטארט און — חלל אינטראקטיבי בטוח',category:'StartOn',source:'כל שירות',year:'פעיל',url:'https://www.kolsherut.org.il/at_risk_teens/education',status:'PUBLIC DIRECTORY',summary:'רישום ציבורי של שירותי הרצאה ופיתוח לנוער.'},
{title:'לבן שלי אין טיקטוק!',category:'תקשורת',source:'זמן ישראל',year:'10.11.2022',url:'https://www.zman.co.il/350569/',status:'AUTHORED COLUMN',summary:'טור אישי על הורות, טכנולוגיה והשתייכות חברתית.'},
{title:'כללי המשחק השתנו — חינוך בעידן המודרני',category:'תקשורת',source:'זמן ישראל',year:'27.11.2022',url:'https://www.zman.co.il/352289/',status:'AUTHORED COLUMN',summary:'טור אישי על חינוך, רשתות וסביבת החיים הדיגיטלית.'},
{title:'חוזר לשכונה — המהדורה המודפסת',category:'תקשורת',source:'ידיעות חולון־בת ים',year:'13.05.2022',url:'https://user-oqw6j7d.cld.bz/khvlvn-13-05-22/10',status:'PRINT EDITION',summary:'עמוד הכתבה במהדורה המודפסת.'},
{title:'מנער בסיכון ליזם חברתי — פרק 102',category:'פודקאסטים',source:'Spotify / Mindset',year:'20.09.2022',url:'https://open.spotify.com/episode/0t2lzatmzK8RJP5B88sOUw',status:'AUDIO SOURCE',summary:'עמוד הפרק בפלטפורמת Spotify.'},
{title:'מנפצי תקרות הזכוכית — פרק 18',category:'פודקאסטים',source:'Podbean',year:'06.09.2022',url:'https://kaikovshahar.podbean.com/e/%D7%9E%D7%A0%D7%A4%D7%A6%D7%99%D7%AA%D7%A7%D7%A8%D7%95%D7%AA-%D7%94%D7%96%D7%9B%D7%95%D7%9B%D7%99%D7%AA%D7%A4%D7%A8%D7%A718/',status:'PODCAST SOURCE',summary:'ראיון על מסע אישי והובלת נוער בסיכון.'},
{title:'פרדי מוסקוביץ מראיין את איגור ופרצקי',category:'פודקאסטים',source:'נדל״ן וירושה',year:'30.10.2023',url:'https://www.nadlanveyerusha.co.il/%D7%93%D7%99%D7%A8%D7%95%D7%AA-%D7%99%D7%A8%D7%95%D7%A9%D7%94/',status:'PODCAST SOURCE',summary:'פרק 29: קרימינולוג, יזם חברתי ואחריות ציבורית.'},
{title:'חוזר לשכונה: משירות בכוחות הביטחון למרכז נוער',category:'וידאו',source:'ערוץ 14 / YouTube',year:'2022',url:'https://youtu.be/O3v309CA4ao',status:'VIDEO SOURCE',summary:'ראיון על StartOn והחזרה לשכונה.'},
{title:'פרויקט חלל אינטראקטיבי לנוער בסיכון',category:'וידאו',source:'פותחים יום / YouTube',year:'2022',url:'https://www.youtube.com/watch?v=SOpAglwkJ8I',status:'VIDEO SOURCE',summary:'ראיון על הקמת החלל האינטראקטיבי.'},
{title:'ראיון עם גאולה אבן סער על הונאות קשישים',category:'וידאו',source:'חדשות 13 / YouTube',year:'16.01.2024',url:'https://www.youtube.com/watch?v=AE5hDzLM5XU',status:'VIDEO SOURCE',summary:'ראיון על היעדר טיפול ראוי בקשישים שנפלו קורבן להונאה.'},
{title:'ראיון על הונאת קשישים ויחס מזלזל',category:'וידאו',source:'YouTube',year:'2023',url:'https://www.youtube.com/watch?v=3XxoBtSL2pg',status:'VIDEO SOURCE',summary:'ראיון המשך בנושא הונאות קשישים.'},
{title:'דיוקן ציבורי של איגור ופרצקי',category:'מערכות',source:'Wikimedia Commons',year:'20.07.2024',url:'https://commons.wikimedia.org/wiki/File:Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png',status:'CC0 SOURCE',summary:'קובץ דיוקן ציבורי שהועלה ל־Wikimedia Commons.'}
];
const tilts=['-1.2deg','.8deg','-.45deg','1.15deg','0deg','-.8deg'];
const previewFor=(item:Item)=>{const youtube=item.url.match(/(?:v=|youtu\.be\/)([\w-]{11})/);if(youtube)return `https://img.youtube.com/vi/${youtube[1]}/hqdefault.jpg`;if(item.category==='רשתות'||item.category==='מוזיקה')return './resources/igor-hero.jpg';return `https://s.wordpress.com/mshots/v1/${encodeURIComponent(item.url)}?w=900`;};
const toneFor=(item:Item,index:number)=>item.category==='תקשורת'?'paper':item.category==='וידאו'||item.category==='פודקאסטים'?'oxide':item.category==='מוזיקה'?'ink':item.category==='StartOn'?'sand':index%2?'charcoal':'paper';

export default function Archive(){
 const [category,setCategory]=useState('הכול');
 const [query,setQuery]=useState('');
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(item=>(category==='הכול'||item.category===category)&&(!q||`${item.title} ${item.source} ${item.summary}`.toLowerCase().includes(q)));},[category,query]);
 return <section id="archive" className="press-wall relative overflow-hidden border-t border-white/10 py-24 sm:py-32">
  <div className="press-grain" aria-hidden="true"/>
  <div className="pointer-events-none absolute inset-y-0 left-0 hidden w-[38%] lg:block"><img src="./resources/igor-hero.jpg" alt="" className="h-full w-full object-cover object-top opacity-[.12] grayscale"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-[#07090d]/70 to-[#07090d]"/></div>
  <div className="relative mx-auto max-w-[1480px] px-5 sm:px-8 lg:px-12">
   <div className="grid gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><div><span className="section-label">04 / MATTE PRESS WALL</span><h2 className="mt-5 text-5xl font-black leading-[.88] tracking-[-.06em] sm:text-7xl">הכול שלי.<br/><span className="text-[#e8ad45]">מחובר למקור.</span></h2></div><div><p className="max-w-2xl text-lg leading-8 text-white/55">כל פרסום ציבורי שאותר — כתבה, טור, טלוויזיה, פודקאסט, רשת, מוזיקה, StartOn או מערכת — הופך לגזיר חי ולחיץ שמוביל אל המקור עצמו.</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-emerald-300"><ShieldCheck size={16}/>מקור, תאריך וסטטוס מוצגים בנפרד. תוכן פרטי ורגיש אינו משוכפל.</div></div></div>
   <div className="press-ledger mt-10"><div><strong>{items.length}</strong><span>מקורות ציבוריים</span></div><div><strong>2011</strong><span>הרשומה המוקדמת</span></div><div><strong>8</strong><span>שכבות תוכן</span></div><div><strong>∞</strong><span>APPEND ONLY</span></div></div>
   <div className="mt-14 grid gap-4 lg:grid-cols-2"><div className="overflow-hidden rounded-3xl border border-white/10 bg-black"><div className="aspect-video"><iframe className="h-full w-full" src="https://www.youtube-nocookie.com/embed/3h-oEuW8GJI" title="מהבריחה מפסטיבל הנובה להתפכחות" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><div className="p-5"><Play size={18} className="text-[#e8ad45]"/><strong className="mt-3 block">שיחה: מהבריחה מפסטיבל הנובה להתפכחות</strong></div></div><div className="grid gap-4"><iframe className="h-[352px] w-full rounded-3xl border border-white/10" src="https://open.spotify.com/embed/artist/0fgRoQ6PoCHlVCIr8a5d6u?utm_source=generator" title="Ido Vepretski on Spotify" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"/><a href="https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/[.03] p-6 transition hover:border-[#e8ad45]/50"><div><Music2 className="text-[#e8ad45]"/><strong className="mt-3 block text-xl">Ido Vepretski ב־Apple Music</strong><span className="mt-1 block text-sm text-white/40">פתחו את קטלוג המוזיקה המלא</span></div><ExternalLink size={20}/></a></div></div>
   <div className="press-control mt-16 rounded-3xl border border-white/10 bg-[#0b0e14]/90 p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full lg:max-w-md"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-white/35" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="חיפוש בארכיון: כתבה, פודקאסט, StartOn..." aria-label="חיפוש בארכיון" className="w-full rounded-full border border-white/10 bg-black/30 py-3.5 pl-4 pr-12 text-sm outline-none transition placeholder:text-white/25 focus:border-[#e8ad45]/60"/></div><div className="flex flex-wrap gap-2">{categories.map(value=><button key={value} onClick={()=>setCategory(value)} className={`rounded-full border px-4 py-2 text-xs font-extrabold transition ${category===value?'border-[#e8ad45] bg-[#e8ad45] text-black':'border-white/10 text-white/55 hover:border-white/30'}`}>{value}</button>)}</div></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 text-xs font-bold text-white/35"><span>{filtered.length} פריטים מוצגים</span><span>{items.length} מקורות בארכיון הציבורי</span></div></div>
   {filtered.length?<div className="press-columns mt-8">{filtered.map((item,index)=>{const style={'--tilt':tilts[index%tilts.length]} as CSSProperties;return <a key={`${item.source}-${item.title}`} href={item.url} target="_blank" rel="noreferrer" className={`press-card press-${toneFor(item,index)} group`} style={style}><div className="press-visual"><img src={previewFor(item)} alt="" loading="lazy" referrerPolicy="no-referrer" onError={event=>{event.currentTarget.style.display='none';}}/><span className="press-source-mark">{item.source}</span></div><div className="press-body"><div className="press-kicker"><span>{item.category}</span><span>{item.year}</span></div><h3>{item.title}</h3><p>{item.summary}</p><div className="press-footer"><span>{item.status}</span><ExternalLink size={15}/></div></div></a>;})}</div>:<div className="mt-8 rounded-2xl border border-dashed border-white/15 p-12 text-center text-white/45">לא נמצאו גזירים. נסו חיפוש או קטגוריה אחרת.</div>}
   <div className="press-manifesto relative mt-20 overflow-hidden rounded-[2rem] border border-[#e8ad45]/25 bg-gradient-to-l from-[#151006] to-[#090c12] p-7 sm:p-12"><img src="./resources/igor-hero.jpg" alt="" className="absolute bottom-0 left-0 hidden h-[145%] w-[42%] object-contain object-bottom opacity-35 grayscale md:block"/><div className="relative z-10 max-w-3xl"><span className="section-label">ARCHIVE PRINCIPLE</span><h3 className="mt-4 text-4xl font-black leading-tight sm:text-6xl">לא לבלוע את האינטרנט.<br/><span className="text-[#e8ad45]">לבנות ממנו זיכרון ציבורי.</span></h3><p className="mt-5 text-base leading-7 text-white/55">הארכיון יתרחב רק באמצעות מקור ציבורי, תאריך, הקשר וסטטוס. כמות אינה גוברת על אמינות.</p></div></div>
  </div>
 </section>;
}
