import {deepMedia,type DeepMediaItem} from './deep-media-data';
export type VisualMethod='video-frame'|'publisher-image'|'source-capture'|'public-portrait'|'site-asset';
export type ContentCluster='media'|'starton'|'social'|'music'|'writing'|'journey';
export type ManagedContent=DeepMediaItem&{visualMethod:VisualMethod;cluster:ContentCluster;priority:number};
const preferred=['fraud-13','fraud-12','starton-14','starton-day','nova-long','youth-radio','dna-710','father-hidabroot','father-comments','mynet-return','zman-tiktok','zman-rules','early-2011','mindset-page','moving-minds','glass-ceilings','nadlan-interview','nitzotzot','medium-story','linkedin-starton','linkedin-media','spotify-artist','apple-artist','soundcloud','wikimedia'];
const MYNET='https://pic1.yitweb.co.il/cdn-cgi/image/f%3Dauto%2Cw%3D740%2Cq%3D75/picserver/mynet/crop_images/2022/05/11/r1F0NeKU9/r1F0NeKU9_0_0_640_360_0_large.jpg';
const WIKIMEDIA='https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png/960px-Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png';
const overrides:Record<string,string>={'mynet-return':MYNET,'wikimedia':WIKIMEDIA};
const sourceCapture=(url:string)=>'https://s.wordpress.com/mshots/v1/'+encodeURIComponent(url)+'?w=1200';
const managedImage=(item:DeepMediaItem)=>overrides[item.id]||(item.image.startsWith('./resources/')&&item.url.startsWith('http')?sourceCapture(item.url):item.image);
const method=(item:DeepMediaItem,image:string):VisualMethod=>item.id==='wikimedia'?'public-portrait':item.youtubeId?'video-frame':image===MYNET||image.includes('storage.hidabroot.org')?'publisher-image':image.includes('s.wordpress.com/mshots')?'source-capture':image.startsWith('./resources/')?'site-asset':'publisher-image';
const cluster=(item:DeepMediaItem):ContentCluster=>item.category==='StartOn'?'starton':item.category==='מוזיקה'?'music':item.category==='רשתות'||item.category==='ויראלי'?'social':item.category==='כתיבה'?'writing':item.category==='עיתונות'?'journey':'media';
export const contentRegistry:ManagedContent[]=deepMedia.map(item=>{const image=managedImage(item);const index=preferred.indexOf(item.id);return {...item,image,visualMethod:method(item,image),cluster:cluster(item),priority:index<0?999:index}}).sort((a,b)=>a.priority-b.priority);
const uniqueByVisual=(items:ManagedContent[])=>{const seen=new Set<string>();return items.filter(item=>{if(seen.has(item.image))return false;seen.add(item.image);return true})};
export const selectHomeMedia=(limit=20)=>uniqueByVisual(contentRegistry.filter(item=>item.priority<999&&item.visualMethod!=='site-asset')).slice(0,limit);
export const selectVisualArchive=(limit=16)=>uniqueByVisual(contentRegistry.filter(item=>item.priority<999&&item.visualMethod!=='site-asset')).slice(0,limit);
export const selectFeaturedVideos=(limit=2)=>uniqueByVisual(contentRegistry.filter(item=>Boolean(item.youtubeId))).slice(0,limit);
export const selectCluster=(value:ContentCluster,limit=4)=>uniqueByVisual(contentRegistry.filter(item=>item.cluster===value)).slice(0,limit);
export const findManagedContent=(id:string)=>contentRegistry.find(item=>item.id===id);
