import {useState} from 'react';
import {ExternalLink,ShieldCheck,X} from 'lucide-react';
import {mediaBrands,partnerships,startonMedia,voiceMedia,type MediaItem} from './media-catalog';
import MediaEvidenceVisual from './MediaEvidenceVisual';
import './home-media-flow.css';
import './media-experience.css';
const Tile=({item,index,onPlay}:{item:MediaItem;index:number;onPlay:(item:MediaItem)=>void})=>{const body=<><MediaEvidenceVisual kind={item.youtubeId?'video':'post'} mode='tile' source={item.source} title={item.title} year={item.meta} image={item.youtubeId?item.image:undefined} tone={item.theme} index={index} disclosure={item.youtubeId?'ORIGINAL VIDEO THUMBNAIL':'7YA EDITORIAL EVIDENCE POSTER'}/>{item.youtubeId&&<i aria-hidden='true'/>}<div className='media-feature-copy'><small>{item.source}</small><b>{item.title}</b><span>{item.meta}</span></div>{item.youtubeId?null:<ExternalLink/>}</>;return item.youtubeId?<button type='button' className={index===0?'media-feature hero-media':'media-feature'} onClick={()=>onPlay(item)}>{body}</button>:<a className={index===0?'media-feature hero-media':'media-feature'} href={item.url} target='_blank' rel='noreferrer'>{body}</a>};
const Player=({item,onClose}:{item:MediaItem;onClose:()=>void})=><div className='media-player-modal' role='dialog' aria-modal='true' aria-label={item.title} onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><article><button type='button' onClick={onClose} aria-label='סגירת הנגן'><X/></button><div className='player-frame'><iframe src={`https://www.youtube-nocookie.com/embed/${item.youtubeId}?autoplay=1&rel=0`} title={item.title} allow='autoplay; encrypted-media; picture-in-picture' allowFullScreen/></div><footer><div><small>{item.source}</small><b>{item.title}</b><span>{item.meta}</span></div><a href={item.url} target='_blank' rel='noreferrer'>למקור המלא <ExternalLink/></a></footer></article></div>;
export function MediaLogoRail(){return <section className='media-logo-rail' id='media' aria-labelledby='media-logo-title'><header><span>MEDIA RECORD</span><h2 id='media-logo-title'>התארחתי, סוקרתי וכתבתי.</h2><p>מותגי המדיה מוצגים כמפתח לרשומות מקור — לא כשותפים ולא כקישוט.</p></header><div className='media-logo-track'>{mediaBrands.map(brand=><a key={brand.name} href={brand.url} target='_blank' rel='noreferrer'><strong className='media-mark'>{brand.mark}</strong><span><b>{brand.name}</b><small>{brand.label}</small></span><ExternalLink/></a>)}</div></section>}
export function MediaChapter({variant}:{variant:'voice'|'starton'}){const [active,setActive]=useState<MediaItem|null>(null);const items=(variant==='voice'?voiceMedia:startonMedia).slice(0,3);return <section className={`media-chapter ${variant==='voice'?'voice-media':'starton-media'}`} aria-labelledby={`${variant}-media-title`}><header><span>{variant==='voice'?'PUBLIC VOICE · TV · PODCAST':'STARTON · PRESS · LONG FORM'}</span><h2 id={`${variant}-media-title`}>{variant==='voice'?'כשהקול עבר מהפיד אל האולפן.':'השליחות קיבלה פנים, קול ומסך.'}</h2><p>{variant==='voice'?'ראיון מרכזי ושני פרקי עומק בתוך הסיפור — בלי להציף את דף הבית.':'המדיה ממוקמת ליד הפרק שהיא מסבירה, עם צפייה באתר וקישור למקור.'}</p></header><div className='media-feature-grid'>{items.map((item,index)=><Tile key={item.url} item={item} index={index} onPlay={setActive}/>)}</div><a className='media-archive-link' href='?page=media'>לכל הראיונות והפודקאסטים <ExternalLink/></a>{active&&<Player item={active} onClose={()=>setActive(null)}/>}</section>}
export function PartnershipRail(){return <section className='partnership-rail' id='partnerships' aria-labelledby='partnership-title'><header><span>RELATIONSHIPS · FRAMEWORKS · PIPELINE</span><h2 id='partnership-title'>כל קשר<br/>מוצג בשמו.</h2><p>פעילות שבוצעה, מסגרת, תהליך והצעה עתידית מקבלים תוויות קצרות ומדויקות.</p></header><div className='partnership-grid'>{partnerships.map(item=><a key={item.name} className={`partner-${item.group}`} href={item.url} target='_blank' rel='noreferrer'><div className='partner-logo'><strong>{item.name.slice(0,2)}</strong><b>{item.name}</b></div><small>{item.status}</small><h3>{item.title}</h3><p>{item.note}</p><span>לפתיחת הגוף <ExternalLink/></span></a>)}</div><div className='partnership-rule'><ShieldCheck/><p>הסטטוס הוא חלק מהעיצוב: גוף תקשורת אינו שותף, חברות אינה הסכם, והצעה אינה אישור.</p></div></section>}