import { useMemo, useState } from 'react';
import { ArrowUpLeft, BadgeCheck, ExternalLink, Heart, Play, Share2, Sparkles } from 'lucide-react';
import './influence.css';

type Theme='הכול'|'זהות'|'חברה'|'StartOn'|'מדיה'|'כתיבה';
type Story={theme:Exclude<Theme,'הכול'>;platform:string;date:string;title:string;url:string;signal:string;why:string;how:string;after:string};
const stories:Story[]=[
  {theme:'חברה',platform:'Facebook · ישראל ביתנו',date:'29.01.2026',title:'תגיד יא ביבי, איפה הניצחון המוחלט?',url:'https://www.facebook.com/beytenu/videos/%D7%99%D7%95%D7%A6%D7%90-%D7%9B%D7%95%D7%97%D7%95%D7%AA-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%AA%D7%92%D7%99%D7%93-%D7%99%D7%90-%D7%91%D7%99%D7%91%D7%99-%D7%90%D7%99%D7%A4%D7%94-%D7%94%D7%A0%D7%99%D7%A6%D7%97%D7%95%D7%9F-%D7%94%D7%9E%D7%95%D7%97%D7%9C%D7%98/26702411802682636/',signal:'14,000 צפיות · נתון מאונדקס',why:'שאלה אחת חדה החליפה נאום שלם. היא נתנה לקהל משפט שאפשר לזכור, לצטט ולהעביר הלאה.',how:'פתיחה ללא הקדמה, ניסוח בדיבור טבעי, עימות בין הבטחה למציאות ופורמט וידאו קצר.',after:'הקטע קיבל הפצה בעמוד מפלגתי והפך קול אישי לחלק משיחה פוליטית רחבה יותר.'},
  {theme:'מדיה',platform:'Facebook · הצינור',date:'ארכיון',title:'זה מתחיל להסתמן כלהיט החדש',url:'https://www.facebook.com/hazinor/videos/%D7%96%D7%94-%D7%9E%D7%AA%D7%97%D7%99%D7%9C-%D7%9C%D7%94%D7%A1%D7%AA%D7%9E%D7%9F-%D7%9B%D7%9C%D7%94%D7%99%D7%98-%D7%94%D7%97%D7%93%D7%A9dennis-charkov-igor-vepretski-david-goldenberg-vlad-jh/10153274636619662/',signal:'1,500 תגובות רגש · מתועד',why:'מוזיקה, הומור וקבוצה של יוצרים הורידו הגנות. הקהל לא קיבל “מסר”; הוא קיבל רגע שרצה להיות חלק ממנו.',how:'שיתוף פעולה, קצב מהיר, פרצופים מזוהים ורעיון שמובן גם בלי הסבר ארוך.',after:'הפצה אצל מפרסם חיצוני הראתה שהאות יכול לצאת מהעמוד האישי ולהמשיך לחיות ברשת אחרת.'},
  {theme:'זהות',platform:'TikTok · @igor.vepretski',date:'21.06.2026',title:'פוסט ציבורי מתוך מנוע TikTok',url:'https://www.tiktok.com/@igor.vepretski/video/7653793755757169941',signal:'קישור ישיר · מדדים ממתינים ללכידה',why:'הפורמט הקצר עובד כשהוא מרגיש כמו שיחה ולא כמו קמפיין. הנוכחות קודמת להפקה.',how:'כניסה מיד לנושא, גוף ראשון, חיתוך מהיר ושפה שמתאימה למסך אנכי.',after:'הפוסט מייצג מנוע יצירה מתמשך; הוא חשוב כחלק מהשיטה, גם בלי להציג מספר שלא נשמר.'},
  {theme:'חברה',platform:'Instagram Reel',date:'17.10.2023',title:'משטרת ישראל הם גיבורי העל של התקופה האחרונה',url:'https://www.instagram.com/reel/CyhEU1kMUuH/',signal:'Reel וכיתוב מאומתים',why:'ברגע של פחד ציבורי, הכרת תודה ברורה נתנה שם לאנשים שפעלו בשטח.',how:'מסר אחד, הקשר מיידי, רגש גלוי וחיבור בין ניסיון אישי לשירות ציבורי.',after:'הפוסט נשאר כעדות לזמן ולנקודת מבט—לא רק כיחידת תוכן שנועדה לצבור צפיות.'},
  {theme:'חברה',platform:'YouTube',date:'2024',title:'מהבריחה מפסטיבל הנובה להתפכחות',url:'https://www.youtube.com/watch?v=3h-oEuW8GJI',signal:'וידאו ציבורי מאומת',why:'הקהל פוגש אדם שמנסה להבין שינוי לאומי דרך חוויה אנושית, לא פרשן שמביט מבחוץ.',how:'פורמט שיחה ארוך מאפשר מתח, שתיקה, סתירה והתפתחות—הדברים שסרטון קצר משטיח.',after:'השיחה הרחיבה את השפה של 7YA מזהות דיגיטלית לעדות, אחריות וזיכרון ציבורי.'},
  {theme:'StartOn',platform:'LinkedIn',date:'2025',title:'How digital innovation hubs empower communities',url:'https://www.linkedin.com/posts/vepretski_discover-how-digital-innovation-hubs-are-activity-7336995936314834944-escP',signal:'22 תגובות רגש · תגובה אחת',why:'הפוסט תרגם חזון חברתי לשפה מקצועית: תשתית, קהילה, מיומנויות והזדמנות.',how:'בעיה מוחשית, מודל שניתן להסביר, שפה שמחברת בין אנשים לטכנולוגיה וקריאה לשותפות.',after:'StartOn הוצגה לא רק כסיפור אישי אלא כמערכת שאפשר ללמוד, לתמוך ולשכפל.'},
  {theme:'מדיה',platform:'LinkedIn',date:'2025',title:'TikTok marketing / digital influence',url:'https://www.linkedin.com/posts/vepretski_tiktokmarketing-digitalinfluence-personalbranding-activity-7316474020063760384-0aAl',signal:'7 תגובות רגש · תגובה אחת',why:'ניסיון מהשטח קיבל מסגרת מקצועית. במקום “הייתי ויראלי” הופיעה שאלה: מה למדתי על הפצה?',how:'פירוק הפרקטיקה לעקרונות, מעבר מפלטפורמה אחת לאחרת ושימוש בזהות אישית כמקרה מבחן.',after:'הפוסט חיבר בין היוצר, היזם החברתי ובונה המערכות—שלוש זהויות שבדרך כלל מופרדות.'},
  {theme:'כתיבה',platform:'Medium',date:'2024',title:'From Troubled Beginnings to Social Impact',url:'https://medium.com/@igor.vepretski/igor-vepretski-from-troubled-beginnings-to-social-impact-a-journey-of-resilience-and-purpose-253aa8af266d',signal:'מאמר מחבר ציבורי',why:'המאמר נותן לקורא את מה שפוסט קצר לא יכול: סיבתיות. הוא מחבר בין עבר מורכב, בחירה ואחריות.',how:'קשת סיפורית של לפני–נקודת מפנה–פעולה, כתיבה בגוף ראשון ומעבר מפצע אישי למשימה ציבורית.',after:'נוצר מקור באנגלית שמאפשר להבין את Igor, 7YA ו־StartOn כחלק מאותו מסלול.'},
  {theme:'כתיבה',platform:'זמן ישראל',date:'10.11.2022',title:'לבן שלי אין טיקטוק!',url:'https://www.zman.co.il/350569/',signal:'טור מחבר · מקור מערכת',why:'הכותרת מתחילה בהתנגשות שכל הורה מכיר. מתחתיה נמצאת שאלה רחבה יותר על שייכות, פחד וחינוך.',how:'סיפור משפחתי קטן, פרדוקס בכותרת, ידע של יוצר רשת והימנעות מתשובה פשטנית.',after:'החוויה הפרטית הפכה לטקסט ציבורי שמחבר בין הורות, טכנולוגיה ואחריות.'},
  {theme:'כתיבה',platform:'זמן ישראל',date:'27.11.2022',title:'כללי המשחק השתנו — חינוך בעידן המודרני',url:'https://www.zman.co.il/352289/',signal:'טור מחבר · מקור מערכת',why:'הטור לא שואל איך להחזיר את העולם לאחור, אלא איך להכין צעירים לעולם שכבר השתנה.',how:'מסגור של שינוי מערכת, דוגמאות מהחיים הדיגיטליים וחיבור בין ביקורת להצעת פעולה.',after:'הרעיון המשיך לקו של StartOn: לא להילחם במסך בלבד, אלא לבנות סביבו יכולת, קהילה וקול.'},
  {theme:'זהות',platform:'הידברות',date:'2023',title:'אבא מושלם — זה אבא ששם',url:'https://www.hidabroot.org/article/1179015',signal:'סיפור שצמח מפוסט ציבורי',why:'המשפט נוגע מפני שהוא מוריד את הרף משלמות לנוכחות. זו אמת פשוטה שאנשים יכולים לקחת לחיים שלהם.',how:'וידוי אישי, ניסוח קצר שאפשר לזכור ותמונה אנושית שאינה מנסה להיראות חסינה.',after:'פוסט אישי קיבל חיים חדשים ככתבה אצל גוף תקשורת—דוגמה למעבר מפיד לסיפור מתועד.'},
  {theme:'StartOn',platform:'Mynet חולון',date:'2022',title:'חוזר לשכונה: מרכז לנוער בג׳סי כהן',url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',signal:'ראיון עומק · מקור עצמאי',why:'הסיפור משלים מעגל: לא רק “יצאתי משם”, אלא “חזרתי לבנות שם”.',how:'מקום ספציפי, עבר אישי, תוכנית מוחשית וקול שמסביר למה טכנולוגיה יכולה להיות שייכות.',after:'המסר עבר מהצהרה לפעולה מקומית והפך את StartOn לחלק מהסיפור הציבורי של השכונה.'}
];
const tiktok=[['07.03.2022','36,694'],['24.03.2024','8,720'],['16.06.2024','7,628'],['11.11.2024','7,466'],['01.07.2024','7,343'],['28.04.2024','6,605'],['01.08.2024','6,098'],['23.11.2023','4,942'],['20.11.2023','4,902'],['26.11.2023','4,762']];
const themes:Theme[]=['הכול','זהות','חברה','StartOn','מדיה','כתיבה'];

export default function InfluenceArticle(){
  const [theme,setTheme]=useState<Theme>('הכול');
  const [open,setOpen]=useState(0);
  const filtered=useMemo(()=>theme==='הכול'?stories:stories.filter(story=>story.theme===theme),[theme]);
  return <article className="influence-article" id="influence">
    <header className="influence-hero"><div><span className="eyebrow"><span/>THE INFLUENCE JOURNAL</span><h2>הפוסטים<br/>ששינו מסלול.</h2></div><div className="influence-lead"><p>ויראליות היא לא רגע שבו מספר עולה. היא הרגע שבו משפט עוזב את מי שכתב אותו, נכנס לחיים של אנשים אחרים—וחוזר כתגובה, שיחה, כתבה, שיתוף פעולה או מוסד.</p><div><BadgeCheck/><span>מקורות פתוחים · קישורים ישירים · חוסרים מסומנים</span></div></div></header>
    <section className="article-body"><p className="dropcap">במשך שנים איגור ופרצקי פרסם בין עולמות: אבא ויוצר, קצין לשעבר ויזם חברתי, אדם שגדל בתוך סיכון ואדם שחזר לבנות הזדמנות. הפוסטים המשפיעים ביותר לא היו בהכרח המלוטשים ביותר. הם עבדו כשהיה בהם חיכוך אמיתי—בין הבטחה למציאות, בין מסך לילד, בין יציאה מהשכונה לחזרה אליה.</p><blockquote>הדפוס שחוזר שוב ושוב: אמת אישית → משפט חד → פורמט נכון → הפצה חיצונית → פעולה בעולם.</blockquote><p>היומן שלפניכם אינו טוען שכל קישור הוא “הכי גדול”. הוא מציג את הפוסטים והטקסטים החזקים ביותר שאפשר כרגע לחבר למקור ציבורי, ומסביר את מנגנון ההשפעה שלהם. היכן שיש מדד שמור—הוא מוצג עם מעמדו. היכן שאין—הסיפור נשאר, והמספר לא מומצא.</p></section>
    <nav className="influence-filters" aria-label="סינון המאמר">{themes.map(value=><button key={value} className={theme===value?'active':''} onClick={()=>{setTheme(value);setOpen(0);}}>{value}</button>)}</nav>
    <section className="story-index"><div className="story-list">{filtered.map((story,index)=><button key={story.title} onClick={()=>setOpen(index)} className={open===index?'active':''}><span>{String(index+1).padStart(2,'0')}</span><div><small>{story.platform} · {story.date}</small><b>{story.title}</b></div><ArrowUpLeft/></button>)}</div>{filtered[open]&&<div className="story-deep"><div className="story-label"><span>{filtered[open].theme}</span><em>{filtered[open].signal}</em></div><h3>{filtered[open].title}</h3><section><h4><Heart/>למה זה נגע</h4><p>{filtered[open].why}</p></section><section><h4><Play/>איך זה נבנה</h4><p>{filtered[open].how}</p></section><section><h4><Share2/>מה קרה אחר כך</h4><p>{filtered[open].after}</p></section><a href={filtered[open].url} target="_blank" rel="noreferrer">לפתיחת המקור <ExternalLink/></a></div>}</section>
    <section className="tiktok-ledger"><div><span className="eyebrow"><span/>TIKTOK EXPORT</span><h3>עשרת אותות<br/>ההתפשטות.</h3><p>לפי export מתועד, אלה עשרת הפוסטים המובילים לפי לייקים. הקישורים הישירים לא נשמרו בכל הרשומות ולכן הם אינם מומצאים; הכפתור מוביל לפרופיל המקור.</p><a href="https://www.tiktok.com/@igor.vepretski" target="_blank" rel="noreferrer">לפרופיל TikTok <ExternalLink/></a></div><div className="tiktok-bars">{tiktok.map(([date,likes],index)=><div key={date}><span>{String(index+1).padStart(2,'0')}</span><div><i style={{width:Math.max(14,Math.round(Number(likes.replace(',',''))/36694*100))+'%'}}/><b>{date}</b></div><strong>{likes}</strong></div>)}</div></section>
    <footer className="article-conclusion"><Sparkles/><div><h3>מה הופך פוסט לדגל?</h3><p>לא הלוגו ולא הסיסמה. דגל נוצר כשאדם יכול לזהות את עצמו בתוך הסיפור—ואז לקבל דרך להצטרף. זו הסיבה שהשלב הבא של 7YA אינו רק ארכיון: הוא עוזר שמחבר כל קורא לרעיון, כלי חינמי וצעד שאפשר לבצע.</p><a href="./?chat=open&lang=he">להמשיך לשיחה האחידה <ArrowUpLeft/></a></div></footer>
  </article>;
}
