export type CorpusPlatform='Facebook'|'Instagram'|'TikTok'|'YouTube'|'LinkedIn';
export type CorpusItem={id:string;platform:CorpusPlatform;kind:'post'|'video'|'profile';label:string;title:string;summary:string;date:string;url:string;proof:string;metric?:string;metricStatus:'verified'|'snapshot'|'none';image?:string;priority:number};
const rows:CorpusItem[]=[
{id:'fb-fatherhood',platform:'Facebook',kind:'post',label:'סטטוסים מצייצים · מקור מאונדקס',title:'אבא מושלם — זה אבא ששם',summary:'סיפור אישי על אבהות שעבר מהפרופיל להפצה ציבורית ולסיקור חיצוני.',date:'2023',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0icaS4EV3EFHPbtTaexx3X4Lo9UGQD22Nvm8xzkpJRqiJSLro9D3zNp1PX6SJ26iPl',proof:'PUBLIC INDEXED',metric:'4.1K תגובות־רגש · 148 תגובות',metricStatus:'verified',image:'https://storage.hidabroot.org/Graphics/Storage/327341.png',priority:100},
{id:'ig-story',platform:'Instagram',kind:'video',label:'@vepretski.igor · Reel קנוני',title:'שלום שבת | #7YA — הסיפור מתחיל',summary:'ריל אישי עם permalink ציבורי ו־Insights מתוארכים של בעל החשבון.',date:'31.07.2026',url:'https://www.instagram.com/reel/DbDfpb6orUt/',proof:'OWNER INSIGHTS + DIRECT LINK',metricStatus:'none',priority:99},
{id:'yt-fraud',platform:'YouTube',kind:'video',label:'חדשות 13 · וידאו ציבורי',title:'כשהמאבק בהונאות קשישים עובר למסך',summary:'פוסט ציבורי שהפך לשיחה תקשורתית ולדרישה לאחריות.',date:'2023',url:'https://www.youtube.com/watch?v=AE5hDzLM5XU',proof:'PUBLIC VIDEO',metricStatus:'none',image:'https://i.ytimg.com/vi/AE5hDzLM5XU/hqdefault.jpg',priority:98},
{id:'tt-export',platform:'TikTok',kind:'profile',label:'@igor.vepretski · Owner export',title:'904 פריטים בייצוא המתוארך',summary:'Snapshot מ־02.06.2026. זהו מדד כיסוי של הייצוא — לא 904 כרטיסים שמתחזים להיות טעונים באתר.',date:'02.06.2026',url:'https://www.tiktok.com/@igor.vepretski',proof:'OWNER EXPORT SNAPSHOT',metric:'904 פריטים · 12,655 עוקבים · 273,860 לייקים',metricStatus:'snapshot',priority:97},
{id:'li-fatherhood',platform:'LinkedIn',kind:'post',label:'Igor Vepretski · mirror מקצועי',title:'אבא מושלם זה אבא ששם — LinkedIn',summary:'אותו סיפור הגיע גם לרשת המקצועית, עם מקור ומדד נפרדים.',date:'2023',url:'https://www.linkedin.com/posts/vepretski_%D7%9B%D7%A9%D7%94%D7%94%D7%94%D7%95%D7%A8%D7%99%D7%9D-%D7%A9%D7%9C%D7%99-%D7%94%D7%AA%D7%92%D7%A8%D7%A9%D7%95-%D7%90%D7%91%D7%90-%D7%A9%D7%9C%D7%99-%D7%97%D7%AA%D7%9D-%D7%93%D7%99%D7%9C-activity-7032741993654988800-IRtv',proof:'PUBLIC INDEXED',metric:'491 תגובות־רגש',metricStatus:'verified',priority:96},
{id:'fb-russian',platform:'Facebook',kind:'post',label:'סטטוסים מצייצים · permalink',title:'בשנות ה־90 קראו לי ״רוסי מסריח״',summary:'פוסט על עלייה, זהות, מבטא והדרך להפוך עלבון ישן לקול ציבורי.',date:'2023',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0VyLgUHZ6KLoY953QnCkSnWkSUtLqmV7NeeW6NmB2bABFh1R7bkRzj8Lw5imUeHckl',proof:'PUBLIC INDEXED',metricStatus:'none',priority:95},
{id:'yt-nova',platform:'YouTube',kind:'video',label:'וידאו ארוך · מקור ציבורי',title:'מהבריחה מפסטיבל הנובה להתפכחות',summary:'שיחה ארוכה על שבר, זהות, אחריות והחברה הישראלית.',date:'2024',url:'https://www.youtube.com/watch?v=3h-oEuW8GJI',proof:'DIRECT PUBLIC VIDEO',metricStatus:'none',image:'https://i.ytimg.com/vi/3h-oEuW8GJI/hqdefault.jpg',priority:94},
{id:'ig-scam',platform:'Instagram',kind:'post',label:'סטטוסים מצייצים · Instagram',title:'סבתא שלי נפלה קורבן להונאה',summary:'הד ציבורי של הסיפור שהמשיך אחר כך לראיונות ולשיחה על הגנה על קשישים.',date:'07.02.2023',url:'https://www.instagram.com/p/CoXykBwq3Zr/',proof:'PUBLIC INDEXED',metric:'1,489 לייקים',metricStatus:'verified',priority:93},
{id:'li-7ya',platform:'LinkedIn',kind:'post',label:'#7YA · LinkedIn',title:'We’re hiring: Brand Manager for #7YA',summary:'פוסט מקצועי שממקם את 7YA כמערכת של מותג, תרבות ויצירה.',date:'23.08.2025',url:'https://www.linkedin.com/posts/vepretski_7ya-7ya-7ya-activity-7365005730061414400-ivAD',proof:'DIRECT PUBLIC POST',metricStatus:'none',priority:92},
{id:'fb-kindergarten',platform:'Facebook',kind:'post',label:'סטטוסים מצייצים · permalink',title:'תחילת שבוע, הגננת מתקשרת',summary:'רגע הורי יומיומי שהפך לסיפור ציבורי על אמפתיה ואחריות.',date:'2023',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid02FW4Q9ZWvN8K1Q6vpSy9ndnDiXPYgRbEs59JC2XANo2dSnhufQJbxRVWoXzdkcfa9l',proof:'PUBLIC INDEXED',metricStatus:'none',priority:91},
{id:'yt-starton',platform:'YouTube',kind:'video',label:'ערוץ 14 · StartOn',title:'משירות ציבורי להקמת מרכז לנוער',summary:'ראיון על המעבר לשכונה ועל בניית StartOn כמרחב טכנולוגיה ושייכות.',date:'2022',url:'https://youtu.be/O3v309CA4ao',proof:'DIRECT PUBLIC VIDEO',metricStatus:'none',image:'https://i.ytimg.com/vi/O3v309CA4ao/hqdefault.jpg',priority:90},
{id:'ig-russian',platform:'Instagram',kind:'post',label:'סטטוסים מצייצים · Instagram',title:'״רוסי מסריח״ — ההד באינסטגרם',summary:'עותק ציבורי שממחיש כיצד סיפור הזהות נע בין פלטפורמות בלי לאחד את המדדים שלהן.',date:'24.05.2023',url:'https://www.instagram.com/p/CsnfS5WoSw8/',proof:'PUBLIC INDEXED',metric:'42 תגובות נראות',metricStatus:'verified',priority:89},
{id:'fb-scam',platform:'Facebook',kind:'post',label:'סטטוסים מצייצים · permalink',title:'סבתא שלי נפלה קורבן להונאה',summary:'הפוסט הציבורי שהניע מסלול של שיח, סיקור וראיונות בנושא הונאות קשישים.',date:'2023',url:'https://www.facebook.com/lan2lan.sta2sim/posts/752380882924243/',proof:'PUBLIC INDEXED',metricStatus:'none',priority:88},
{id:'yt-russian',platform:'YouTube',kind:'video',label:'YouTube · Russian long form',title:'Что такое быть ребенком-репатриантом',summary:'שיחת עומק ברוסית על עלייה, ילדות וזהות.',date:'2024',url:'https://www.youtube.com/watch?v=EsaD-lVsKHc',proof:'DIRECT PUBLIC VIDEO',metricStatus:'none',image:'https://i.ytimg.com/vi/EsaD-lVsKHc/hqdefault.jpg',priority:87},
{id:'li-russian',platform:'LinkedIn',kind:'post',label:'Igor Vepretski · LinkedIn',title:'״רוסי מסריח״ — mirror מקצועי',summary:'אותו ציר של עלייה וזהות מופיע גם בשכבה המקצועית, עם מקור נפרד.',date:'2024',url:'https://www.linkedin.com/posts/vepretski_%D7%91%D7%A9%D7%A0%D7%95%D7%AA-%D7%94-90-%D7%A7%D7%A8%D7%90%D7%95-%D7%9C%D7%99-%D7%A8%D7%95%D7%A1%D7%99-%D7%9E%D7%A1%D7%A8%D7%99%D7%97-%D7%9B%D7%A9%D7%A9%D7%99%D7%A8%D7%AA%D7%AA%D7%99-activity-7259518951334789120-f1MX',proof:'PUBLIC INDEXED',metricStatus:'none',priority:86}
];
const canonical=(url:string)=>url.trim().replace(/[?#].*$/,'').replace(/\/$/,'').toLowerCase();
const seen=new Set<string>();
export const mediaCorpus=rows.filter(item=>{const key=canonical(item.url);if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>b.priority-a.priority);
export const corpusPlatforms:CorpusPlatform[]=['Facebook','Instagram','TikTok','YouTube','LinkedIn'];
export const corpusStats={records:mediaCorpus.length,platforms:corpusPlatforms.length,verifiedMetrics:mediaCorpus.filter(item=>item.metricStatus==='verified').length,tiktokOwnerExportItems:904};