import type {SyntheticEvent} from 'react';
import {Play,ShieldCheck} from 'lucide-react';
import './media-evidence-system.css';
export type EvidenceVisualKind='post'|'video'|'portrait'|'editorial';
type Props={kind:EvidenceVisualKind;mode?:'stage'|'card'|'tile'|'wall';source:string;title:string;year?:string;metric?:string;status?:string;image?:string;tone?:string;index?:number;disclosure?:string};
const pools={starton:['./resources/chapter-starton.webp','./resources/7ya-starton.webp','./resources/hero-story.webp'],music:['./resources/chapter-music.webp','./resources/7ya-launch.webp','./resources/igor-hero.jpg'],voice:['./resources/chapter-voice.webp','./resources/igor-hero.jpg','./resources/hero-story.webp'],research:['./resources/7ya-research.webp','./resources/igor-hero.jpg','./resources/hero-story.webp'],social:['./resources/igor-hero.jpg','./resources/7ya-launch.webp','./resources/hero-story.webp'],default:['./resources/igor-hero.jpg','./resources/hero-story.webp','./resources/chapter-voice.webp']};
const art=(tone='',index=0)=>{const value=tone.toLowerCase();const key=value.includes('starton')?'starton':value.includes('מוז')||value.includes('music')?'music':value.includes('טלו')||value.includes('פוד')||value.includes('voice')||value.includes('broadcast')?'voice':value.includes('כת')||value.includes('עית')||value.includes('research')?'research':value.includes('ויר')||value.includes('רשת')||value.includes('social')?'social':'default';const group=pools[key];return group[Math.abs(index)%group.length]};
const fail=(fallback:string,event:SyntheticEvent<HTMLImageElement>)=>{const image=event.currentTarget;const local=new URL(fallback,window.location.href).href;if(image.src!==local)image.src=fallback;else image.style.opacity='.22'};
const code=(source:string)=>source.replace(/[^A-Za-z0-9א-ת]/g,'').slice(0,2).toUpperCase()||'7Y';
export default function MediaEvidenceVisual({kind,mode='card',source,title,year='',metric,status,image,tone='',index=0,disclosure}:Props){const fallback=art(tone,index);const src=(kind==='video'||kind==='portrait')&&image?image:fallback;const label=disclosure||(kind==='video'?'ORIGINAL VIDEO THUMBNAIL':kind==='portrait'?'IGOR VEPRETSKI · APPROVED / EDITORIAL FRAME':kind==='post'?'7YA EDITORIAL EVIDENCE POSTER · SOURCE LINKED':'7YA EDITORIAL VISUAL');return <div className={`media-evidence-visual mode-${mode} kind-${kind} visual-${index%6}`} data-visual-kind={kind}><img className='mev-art' src={src} alt={kind==='video'?`פריים וידאו: ${title}`:kind==='portrait'?title:`פוסטר ראיה עריכתי עבור ${title}`} loading={mode==='stage'?'eager':'lazy'} decoding='async' referrerPolicy='no-referrer' onError={event=>fail(fallback,event)}/><div className='mev-wash'/><div className='mev-grid'/><div className='mev-nameplate'><img src='./resources/igor-hero.jpg' alt='' aria-hidden='true'/><span><small>THE HUMAN THREAD</small><b>IGOR VEPRETSKI</b></span></div><div className='mev-source'><span>{code(source)}</span><div><small>{year||'#7YA'}</small><b>{source}</b></div></div>{kind!=='video'&&<div className='mev-poster-copy'><small>{kind==='portrait'?'IGOR / PORTRAIT':'POST / EVIDENCE'}</small><strong>{title}</strong>{metric&&<em>{metric}</em>}</div>}{kind==='video'&&<div className='mev-video-mark'><Play fill='currentColor'/><span>PUBLIC VIDEO</span></div>}<div className='mev-disclosure'><ShieldCheck/><span>{label}</span></div>{status&&<div className='mev-status'>{status}</div>}<div className='mev-signature'>IGOR VEPRETSKI · #7YA</div></div>}