import {ExternalLink,Play} from 'lucide-react';
import {rootHref,useLocale,type Locale} from './locale';
import './music-spotlight.css';

type Clip={title:string;role:string;year:string;url:string;image:string};
const clips:Clip[]=[
 {title:'NAWAN ft. VEPRETSKI — BIZZI',role:'קליפ רשמי · איגור כאמן אורח',year:'2025',url:'https://www.youtube.com/watch?v=jRjZjpqAgEw',image:'https://i.ytimg.com/vi/jRjZjpqAgEw/hqdefault.jpg'},
 {title:'רון נשר & Igor Vepretski — מת על אקסל',role:'קליפ רשמי · שיתוף פעולה',year:'2020',url:'https://www.youtube.com/watch?v=2HGMUN2jDwQ',image:'https://i.ytimg.com/vi/2HGMUN2jDwQ/hqdefault.jpg'},
 {title:'Igor Vepretski — פרח במדבר',role:'קליפ רשמי · הפקה: צביקה ברנד',year:'2022',url:'https://www.youtube.com/watch?v=rQbAXagOZBU',image:'https://i.ytimg.com/vi/rQbAXagOZBU/hqdefault.jpg'}
];
const copy:Record<Locale,{eyebrow:string;title:string;body:string;all:string;open:string;roles:[string,string,string]}>={he:{eyebrow:'MUSIC & CLIPS · IDO / IGOR VEPRETSKI',title:'המוזיקה היא לא הערת שוליים.',body:'קליפים ושיתופי פעולה רשמיים שמחזיקים צד אחר של איגור: קול, הומור, זהות והופעה. כל פריט מוביל למקור המקורי ולקרדיט המדויק שלו.',all:'לכל המוזיקה והקליפים',open:'לצפייה בקליפ',roles:['קליפ רשמי · איגור כאמן אורח','קליפ רשמי · שיתוף פעולה','קליפ רשמי · הפקה: צביקה ברנד']},en:{eyebrow:'MUSIC & CLIPS · IDO / IGOR VEPRETSKI',title:'Music is not a footnote.',body:'Official videos and collaborations that hold another side of Igor: voice, humour, identity and performance. Each item keeps its original source and precise credit.',all:'All music and clips',open:'Watch the official video',roles:['Official video · featured artist','Official video · collaboration','Official video · produced by Zvika Brand']},ru:{eyebrow:'MUSIC & CLIPS · IDO / IGOR VEPRETSKI',title:'Музыка — не сноска.',body:'Официальные клипы и коллаборации, раскрывающие другую сторону Игоря: голос, юмор, идентичность и сцену. У каждого материала есть оригинальный источник и точный кредит.',all:'Вся музыка и клипы',open:'Смотреть официальный клип',roles:['Официальный клип · приглашённый артист','Официальный клип · коллаборация','Официальный клип · продюсер: Цвика Бранд']}};

export default function MusicSpotlight(){const {locale,dir}=useLocale();const c=copy[locale];return <section id='music' className='music-spotlight' dir={dir} aria-labelledby='music-spotlight-title'><div className='music-spotlight-wrap'><header><div><span>{c.eyebrow}</span><h2 id='music-spotlight-title'>{c.title}</h2></div><p>{c.body}</p><a className='music-all-link' href={rootHref('music/')}>{c.all}<ExternalLink/></a></header><figure><img src={rootHref('resources/chapter-music.webp')} alt={locale==='he'?'איגור ופרצקי באולפן מוזיקה':'Igor Vepretski in a music studio'}/><figcaption>IDO / IGOR VEPRETSKI · MUSIC</figcaption></figure><div className='music-clip-list'>{clips.map((clip,index)=><a href={clip.url} target='_blank' rel='noreferrer' key={clip.url}><span className='music-clip-number'>{String(index+1).padStart(2,'0')}</span><img src={clip.image} alt={clip.title} loading='lazy'/><div><small>{clip.year} · {c.roles[index]}</small><h3>{clip.title}</h3><b>{c.open}<Play/></b></div></a>)}</div></div></section>}