import {useMemo,useState} from 'react';
import {AtSign,BookOpen,ExternalLink,FileText,Globe,MessageCircle,Music2,Newspaper,Search,ShieldCheck,Youtube} from 'lucide-react';
import {pageHref,useLocale,type Locale} from './locale';
import type {DeepMediaCategory,DeepMediaItem} from './deep-media-data';
import './platform-universe.css';

type Localized=Record<Locale,string>;
type Category='social'|'video'|'music'|'writing'|'research'|'community'|'media'|'web';
type FilterCategory='all'|Category;
type Evidence='verified'|'dated-export'|'external-index'|'canonical'|'owner-report'|'public-profile'|'mixed';
type PlatformItem={id:string;name:string;handle:string;category:Category;url:string;role:Localized;metric:Localized;evidence:Evidence;archiveCategory?:DeepMediaCategory};
const l=(he:string,en:string,ru:string):Localized=>({he,en,ru});
const platforms:PlatformItem[]=[
{id:'7ya',name:'7YA.io',handle:'7ya.io',category:'web',url:'https://7ya.io',role:l('הבית הקנוני המחבר אדם, עשייה, ראיות ופעולה','Canonical home connecting person, work, evidence and action','Канонический дом, связывающий человека, работу, доказательства и действие'),metric:l('בית ציבורי רב־לשוני · HE / EN / RU','Multilingual public home · HE / EN / RU','Многоязычный публичный дом · HE / EN / RU'),evidence:'canonical'},
{id:'facebook',name:'Facebook',handle:'/vepretski · /igor7vepretski',category:'social',url:'https://www.facebook.com/vepretski',role:l('שכבת המקור ההיסטורית: פרופיל, דף, פוסטים, שיתופים ושרשראות הפצה','Historical source layer: profile, page, posts, reposts and distribution chains','Исторический слой: профиль, страница, посты, репосты и цепочки распространения'),metric:l('2 נכסים בבעלות · 15 צומתי אינדוקס · 2008→ בדיווח בעלים','2 owned surfaces · 15 indexed nodes · 2008→ owner timeline','2 собственные поверхности · 15 индексированных узлов · 2008→ по данным владельца'),evidence:'mixed'},
{id:'tiktok-legacy',name:'TikTok · Legacy',handle:'@igor_vepretski',category:'video',url:'https://tikbuddy.com/tiktok/igor_vepretski',role:l('החשבון הוויראלי הישן שנחסם — נשמר באמצעות עקבות חיצוניים','Blocked legacy viral account preserved through external traces','Заблокированный старый вирусный аккаунт, сохраненный внешними следами'),metric:l('66.7K באינדקס חיצוני · 352 סרטונים · 2.9M לייקים · כ־80K בשיא בדיווח בעלים','66.7K external index · 352 videos · 2.9M likes · approx. 80K peak owner report','66,7K во внешнем индексе · 352 видео · 2,9M лайков · около 80K на пике по данным владельца'),evidence:'mixed'},
{id:'tiktok-current',name:'TikTok · Current',handle:'@igor.vepretski',category:'video',url:'https://www.tiktok.com/@igor.vepretski',role:l('מנוע הפרסום הנוכחי וקו ההמשך של זהות היוצר','Current publishing engine and continuation of the creator identity','Текущий издательский двигатель и продолжение идентичности автора'),metric:l('12,655 עוקבים · 904 פריטים · 273,860 לייקים · 02.06.2026','12,655 followers · 904 items · 273,860 likes · 2 Jun 2026','12 655 подписчиков · 904 материала · 273 860 лайков · 02.06.2026'),evidence:'dated-export'},
{id:'instagram',name:'Instagram',handle:'@igor.vepretski',category:'social',url:'https://www.instagram.com/igor.vepretski/',role:l('דיוקן ציבורי, רילס, משפחה, שירות, יצירה ומשימה','Public portrait, reels, family, service, creation and mission','Публичный образ, Reels, семья, служба, творчество и миссия'),metric:l('8.1K+ עוקבים · 1,189 פוסטים · 209 נעקבים · 08.06.2026','8.1K+ followers · 1,189 posts · 209 following · 8 Jun 2026','8,1K+ подписчиков · 1 189 публикаций · 209 подписок · 08.06.2026'),evidence:'dated-export',archiveCategory:'רשתות'},
{id:'instagram-secondary',name:'Instagram',handle:'@vepretski.igor',category:'social',url:'https://www.instagram.com/vepretski.igor/',role:l('חשבון Instagram רשמי נוסף בבעלות איגור ופרצקי','Second official Instagram account owned by Igor Vepretski','Второй официальный аккаунт Instagram Игоря Вепрецкого'),metric:l('חשבון פעיל · קישור רשמי · ללא מדדים לא מאומתים','Active account · official link · no unverified metrics','Активный аккаунт · официальная ссылка · без неподтвержденных метрик'),evidence:'canonical',archiveCategory:'רשתות'},
{id:'linkedin',name:'LinkedIn',handle:'/in/vepretski',category:'writing',url:'https://www.linkedin.com/in/vepretski/',role:l('הסמכות המקצועית: מנהיגות, StartOn, מערכות, מדיה והשפעה דיגיטלית','Professional authority: leadership, StartOn, systems, media and digital influence','Профессиональный авторитет: лидерство, StartOn, системы, медиа и цифровое влияние'),metric:l('4,283 עוקבים · 326 פוסטים · 5 מאמרים · 500+ קשרים · 08.06.2026','4,283 followers · 326 posts · 5 articles · 500+ connections · 8 Jun 2026','4 283 подписчика · 326 публикаций · 5 статей · 500+ контактов · 08.06.2026'),evidence:'dated-export',archiveCategory:'כתיבה'},
{id:'linkedin-newsletter',name:'LinkedIn Newsletter',handle:'Weekly professional writing',category:'writing',url:'https://www.linkedin.com/in/vepretski/recent-activity/articles/',role:l('שכבת כתיבה ארוכה המחברת ניסיון אישי למסגרות מקצועיות','Long-form layer connecting personal experience to professional frameworks','Длинная форма, связывающая личный опыт с профессиональными моделями'),metric:l('ניוזלטר שבועי נראה בצילום המצב הציבורי','Weekly newsletter visible in the public profile snapshot','Еженедельная рассылка видна в публичном снимке профиля'),evidence:'public-profile',archiveCategory:'כתיבה'},
{id:'youtube',name:'YouTube',handle:'@IgorVepretski',category:'video',url:'https://www.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',role:l('וידאו ארוך, ראיונות, פודקאסטים, מוזיקה וארכיון','Long-form video, interviews, podcasts, music and archive','Длинные видео, интервью, подкасты, музыка и архив'),metric:l('2.57K מנויים · 334 סרטונים · 08.06.2026','2.57K subscribers · 334 videos · 8 Jun 2026','2,57K подписчиков · 334 видео · 08.06.2026'),evidence:'dated-export'},
{id:'youtube-music',name:'YouTube Music',handle:'Ido Vepretski',category:'music',url:'https://music.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',role:l('קטלוג מוזיקלי וזהות היוצר Ido Vepretski','Music catalog and the Ido Vepretski creator identity','Музыкальный каталог и творческая идентичность Ido Vepretski'),metric:l('כ־129K צפיות בשיר המוביל באינדוקס מתוארך','Approx. 129K views on the indexed leading song','Около 129K просмотров у ведущей песни в датированном индексе'),evidence:'external-index'},
{id:'x',name:'X',handle:'@igorvepretski',category:'social',url:'https://x.com/igorvepretski',role:l('תגובה ציבורית, פוליטיקה, חדשות ורעיונות בזמן אמת','Public response, politics, news and ideas in real time','Общественная реакция, политика, новости и идеи в реальном времени'),metric:l('פרופיל ציבורי מאומת באינדקס · ללא מספר לא מבוסס','Verified indexed public profile · no unsupported count','Публичный профиль подтвержден индексом · без неподтвержденных цифр'),evidence:'verified',archiveCategory:'רשתות'},
{id:'threads',name:'Threads',handle:'@igor.vepretski',category:'social',url:'https://www.threads.net/@igor.vepretski',role:l('שיחה קצרה, מחשבות, קהילה והמשך נוכחות Meta','Short conversation, ideas, community and Meta continuity','Короткие сообщения, мысли, сообщество и продолжение присутствия Meta'),metric:l('פרופיל ציבורי קנוני · המדדים דורשים רענון ידני','Canonical public profile · metrics require manual refresh','Канонический публичный профиль · метрики требуют ручного обновления'),evidence:'canonical',archiveCategory:'רשתות'},
{id:'telegram',name:'Telegram',handle:'7YA community',category:'social',url:'https://t.me/+RFNzCZzbCa42MjQ0',role:l('ערוץ קהילה ישיר מחוץ לאלגוריתם של הפיד','Direct community route outside feed algorithms','Прямой маршрут сообщества вне алгоритмов ленты'),metric:l('קישור הזמנה קנוני · ללא ספירת חברים לא מאומתת','Canonical invite link · no unverified member count','Каноническая ссылка-приглашение · без неподтвержденного числа участников'),evidence:'canonical',archiveCategory:'רשתות'},
{id:'spotify',name:'Spotify',handle:'Ido Vepretski',category:'music',url:'https://open.spotify.com/artist/0fgRoQ6PoCHlVCIr8a5d6u',role:l('קטלוג האמן והפצת מוזיקה בסטרימינג','Artist catalog and streaming distribution','Каталог артиста и музыкальная дистрибуция'),metric:l('עמוד אמן ציבורי מתועד','Documented public artist page','Документированная публичная страница артиста'),evidence:'public-profile'},
{id:'apple-music',name:'Apple Music',handle:'Ido Vepretski',category:'music',url:'https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he',role:l('הפצת קטלוג השירים במערכת Apple','Song-catalog distribution across Apple Music','Распространение каталога песен в Apple Music'),metric:l('עמוד אמן ציבורי מתועד','Documented public artist page','Документированная публичная страница артиста'),evidence:'public-profile'},
{id:'soundcloud',name:'SoundCloud',handle:'idovepretski',category:'music',url:'https://soundcloud.com/idovepretski',role:l('ארכיון הקלטות, סקיצות ויצירות ציבוריות','Archive of recordings, drafts and public works','Архив записей, набросков и публичных работ'),metric:l('ארכיון אודיו ציבורי מתועד','Documented public audio archive','Документированный публичный аудиоархив'),evidence:'public-profile'},
{id:'medium',name:'Medium',handle:'@igor.vepretski',category:'writing',url:'https://medium.com/@igor.vepretski',role:l('מאמרים באנגלית על מסע, אחריות והשפעה חברתית','English essays on journey, responsibility and social impact','Англоязычные эссе о пути, ответственности и общественном влиянии'),metric:l('פרופיל כותב ציבורי ומאמר מאונדקס','Public author profile and indexed article','Публичный профиль автора и индексированная статья'),evidence:'verified',archiveCategory:'כתיבה'},
{id:'academia',name:'Academia.edu',handle:'Independent Researcher',category:'research',url:'https://igorvepretski.academia.edu/',role:l('ספריית המחקר: זהות, מדיה, ממשל, אלגוריתמים ותיאוריה','Research library: identity, media, governance, algorithms and theory','Исследовательская библиотека: идентичность, медиа, управление, алгоритмы и теория'),metric:l('11 מאמרים + 4 ספרים נראו בצילום הפרופיל; הספירה עשויה להשתנות','11 papers + 4 books visible in the profile snapshot; count may vary','11 статей + 4 книги видны в снимке профиля; число может меняться'),evidence:'public-profile',archiveCategory:'כתיבה'},
{id:'zman',name:'זמן ישראל',handle:'Author page',category:'writing',url:'https://www.zman.co.il/writer/20815/',role:l('טורים על הורות, חינוך, טכנולוגיה, רשתות ושייכות','Columns on parenting, education, technology, networks and belonging','Колонки о родительстве, образовании, технологиях, сетях и принадлежности'),metric:l('עמוד כותב · לפחות 2 טורים מאונדקסים','Author page · at least 2 indexed columns','Страница автора · не менее 2 индексированных колонок'),evidence:'verified'},
{id:'podcasts',name:'Podcasts',handle:'Independent long-form conversations',category:'media',url:'https://www.youtube.com/playlist?list=PLvXOwJ42abaQiQhJoGD4MkTLGzDdwE_GZ',role:l('שיחות עומק על מסע חיים, StartOn, נוער, אחריות וזהות','Long-form conversations on life, StartOn, youth, responsibility and identity','Глубокие разговоры о жизни, StartOn, молодежи, ответственности и идентичности'),metric:l('4 פרקים עצמאיים מאונדקסים + פלייליסט ציבורי','4 indexed independent episodes + public playlist','4 индексированных независимых эпизода + публичный плейлист'),evidence:'verified'},
{id:'press-tv',name:'Press & Television',handle:'Media source cluster',category:'media',url:'?page=media',role:l('כתבות, אולפנים, ראיונות ומעבר מפוסט לסדר יום ציבורי','Articles, studios, interviews and post-to-public-agenda trails','Статьи, студии, интервью и путь от поста к общественной повестке'),metric:l('7 רשומות מדיה מאונדקסות בצילום 08.06.2026','7 indexed media rows in the 8 Jun 2026 snapshot','7 индексированных медийных записей в снимке 08.06.2026'),evidence:'verified'},
{id:'starton',name:'StartOn',handle:'starton.org.il',category:'community',url:'https://starton.org.il',role:l('המשימה החברתית: טכנולוגיה, יצירה, חונכות ושייכות לנוער','Social mission: technology, creation, mentoring and belonging for youth','Социальная миссия: технологии, творчество, наставничество и принадлежность молодежи'),metric:l('אתר ארגון רשמי וקנוני','Official canonical organization site','Официальный канонический сайт организации'),evidence:'canonical',archiveCategory:'StartOn'},
{id:'linktree',name:'Linktree',handle:'igor.vepretski',category:'web',url:'https://linktr.ee/igor.vepretski',role:l('אינדקס ציבורי מהיר לפרופילים, כתבות, ראיונות ורגעים ויראליים','Quick public index for profiles, articles, interviews and viral moments','Быстрый публичный индекс профилей, статей, интервью и вирусных моментов'),metric:l('אינדקס מאסטר ציבורי מאומת','Verified public master index','Подтвержденный публичный мастер-индекс'),evidence:'verified',archiveCategory:'רשתות'},
{id:'izi',name:'IZI',handle:'vepretski',category:'web',url:'https://www.izi.co.il/site/vepretski',role:l('משטח פרופיל וקישורים נוסף בתוך האקו־סיסטם הישראלי','Additional profile and link surface in the Israeli ecosystem','Дополнительная профильная и ссылочная поверхность в израильской экосистеме'),metric:l('פרופיל ציבורי קנוני','Canonical public profile','Канонический публичный профиль'),evidence:'canonical',archiveCategory:'רשתות'},
{id:'wikimedia',name:'Wikimedia Commons',handle:'Open public portrait',category:'media',url:'https://commons.wikimedia.org/wiki/File:Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png',role:l('נכס זיהוי פתוח לתקשורת, מחקר ומערכות ציבוריות','Open identity asset for media, research and public systems','Открытый идентификационный материал для медиа, исследований и публичных систем'),metric:l('דיוקן ציבורי CC0 · 20.07.2024','CC0 public portrait · 20 Jul 2024','Публичный портрет CC0 · 20.07.2024'),evidence:'verified'}
];
const archivePlatforms=platforms.filter((item):item is PlatformItem&{archiveCategory:DeepMediaCategory}=>Boolean(item.archiveCategory));
export const platformArchiveItems:DeepMediaItem[]=archivePlatforms.map(item=>({id:`platform-${item.id}`,category:item.archiveCategory,source:item.name,title:item.name,year:'Public surface',url:item.url,summary:`Public platform surface: ${item.handle}.`,status:`PLATFORM SURFACE · ${item.evidence.toUpperCase()}`,image:'./resources/igor-hero.jpg',fallback:'./resources/igor-hero.jpg'}));
const copy={he:{eyebrow:'ALL PLATFORMS · ONE PUBLIC MEMORY',title:'לא חשבון אחד.',em:'מערכת נוכחות שלמה.',intro:'25 משטחים ציבוריים מחברים את הסיפור, היצירה, המחקר, המוזיקה, הקהילה וההשפעה. כל כרטיס מוביל למקור ומבדיל בין נתון מתוארך, אינדקס חיצוני, דיווח בעלים וקישור קנוני.',all:'הכול',social:'רשתות',video:'וידאו',music:'מוזיקה',writing:'כתיבה',research:'מחקר',community:'קהילה',media:'מדיה',web:'אתרים',search:'חיפוש בכל הפלטפורמות',surfaces:'משטחים ציבוריים',languages:'שפות פעילות',since:'זיכרון היסטורי',open:'פתיחת המשטח',shown:'תוצאות',more:'להציג את כל הפלטפורמות',less:'לצמצם',empty:'לא נמצאה פלטפורמה מתאימה.',guard:'מספרים מוצגים רק כאשר קיים צילום מצב, export, אינדקס חיצוני או מקור ציבורי מתועד.'},en:{eyebrow:'ALL PLATFORMS · ONE PUBLIC MEMORY',title:'Not one account.',em:'A complete presence system.',intro:'Twenty-five public surfaces connect story, creation, research, music, community and influence. Every card opens a source and separates dated exports, external indexes, owner reports and canonical links.',all:'All',social:'Social',video:'Video',music:'Music',writing:'Writing',research:'Research',community:'Community',media:'Media',web:'Web',search:'Search every platform',surfaces:'public surfaces',languages:'active languages',since:'historical memory',open:'Open surface',shown:'results',more:'Show all platforms',less:'Collapse',empty:'No matching platform found.',guard:'Numbers appear only when supported by a dated snapshot, export, external index or documented public source.'},ru:{eyebrow:'ALL PLATFORMS · ONE PUBLIC MEMORY',title:'Не один аккаунт.',em:'Полная система присутствия.',intro:'Двадцать пять публичных поверхностей соединяют историю, творчество, исследования, музыку, сообщество и влияние. Каждая карточка ведет к источнику и разделяет датированный экспорт, внешний индекс, данные владельца и каноническую ссылку.',all:'Все',social:'Соцсети',video:'Видео',music:'Музыка',writing:'Тексты',research:'Исследования',community:'Сообщество',media:'Медиа',web:'Сайты',search:'Поиск по всем платформам',surfaces:'публичных поверхностей',languages:'активных языка',since:'историческая память',open:'Открыть поверхность',shown:'результатов',more:'Показать все платформы',less:'Свернуть',empty:'Подходящая платформа не найдена.',guard:'Цифры публикуются только при наличии датированного снимка, экспорта, внешнего индекса или документированного публичного источника.'}};
const evidenceLabels:Record<Locale,Record<Evidence,string>>={he:{verified:'מאומת ציבורית','dated-export':'צילום מצב / export','external-index':'אינדקס חיצוני',canonical:'קישור קנוני','owner-report':'דיווח בעלים','public-profile':'פרופיל ציבורי',mixed:'ראיות משולבות'},en:{verified:'Publicly verified','dated-export':'Dated snapshot / export','external-index':'External index',canonical:'Canonical link','owner-report':'Owner report','public-profile':'Public profile',mixed:'Mixed evidence'},ru:{verified:'Публично подтверждено','dated-export':'Датированный снимок / экспорт','external-index':'Внешний индекс',canonical:'Каноническая ссылка','owner-report':'Данные владельца','public-profile':'Публичный профиль',mixed:'Смешанные доказательства'}};
const filters:FilterCategory[]=['all','social','video','music','writing','research','community','media','web'];
function icon(category:Category){if(category==='social')return <AtSign/>;if(category==='video')return <Youtube/>;if(category==='music')return <Music2/>;if(category==='writing')return <FileText/>;if(category==='research')return <BookOpen/>;if(category==='community')return <MessageCircle/>;if(category==='media')return <Newspaper/>;return <Globe/>}const resultWord=(locale:Locale,count:number,fallback:string)=>locale!=='ru'?fallback:count%10===1&&count%100!==11?'результат':count%10>=2&&count%10<=4&&(count%100<12||count%100>14)?'результата':'результатов';
export default function PlatformUniverse(){const {locale}=useLocale();const c=copy[locale];const [filter,setFilter]=useState<FilterCategory>('all');const [query,setQuery]=useState('');const filtered=useMemo(()=>platforms.filter(item=>(filter==='all'||item.category===filter)&&(!query||[item.name,item.handle,item.role[locale],item.metric[locale]].join(' ').toLowerCase().includes(query.toLowerCase()))),[filter,query,locale]);return <section className='platform-universe' id='platforms' aria-labelledby='platform-universe-title'><header><div><span className='platform-eyebrow'><Globe/>{c.eyebrow}</span><h2 id='platform-universe-title'>{c.title}<br/><em>{c.em}</em></h2></div><p>{c.intro}</p></header><div className='platform-summary'><div><b>{platforms.length}</b><span>{c.surfaces}</span></div><div><b>HE · EN · RU</b><span>{c.languages}</span></div><div><b>2008 → 2026</b><span>{c.since}</span></div><div><ShieldCheck/><span>{c.guard}</span></div></div><div className='platform-tools'><nav aria-label={c.eyebrow}>{filters.map(value=><button type='button' key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value!=='all'&&icon(value)}{c[value]}</button>)}</nav><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.search} aria-label={c.search}/></label></div><div className='platform-result-count'>{filtered.length} {resultWord(locale,filtered.length,c.shown)}</div><div className='platform-grid'>{filtered.map(item=>{const href=item.id==='press-tv'?pageHref('media',locale):item.url;const external=href.startsWith('http');return <article key={item.id} className={`platform-card platform-${item.category}`}><div className='platform-card-top'><span>{icon(item.category)}{item.name}</span><small>{evidenceLabels[locale][item.evidence]}</small></div><code>{item.handle}</code><h3>{item.role[locale]}</h3><p>{item.metric[locale]}</p><a href={href} {...(external?{target:'_blank',rel:'noreferrer'}:{})}>{c.open}<ExternalLink/></a></article>})}</div>{!filtered.length&&<div className='platform-empty'>{c.empty}</div>}</section>}
