import {useState} from 'react';
import {ArrowUpLeft,BadgeCheck,ExternalLink,Pause,Play,ShieldCheck,Sparkles} from 'lucide-react';
import './story-stage.css';

type Story={key:string;chapter:string;year:string;platform:string;title:string;summary:string;why:string;signal:string;status:string;kind:'youtube'|'instagram'|'tiktok';embed:string;source:string;poster?:string};
const stories:Story[]=[
  {key:'return',chapter:'CHAPTER 03',year:'2022',platform:'ערוץ 14',title:'לחזור לשכונה — ולבנות מקום להתחיל בו',summary:'הרגע שבו הסיפור האישי עבר מהישרדות למערכת פעולה: StartOn, טכנולוגיה, שייכות והזדמנות לצעירים.',why:'סגירת המעגל ברורה לעין: לא רק לצאת ממקום מורכב, אלא לחזור אליו עם מבנה שאפשר להשתמש בו.',signal:'ראיון ציבורי · StartOn · מקור פתוח',status:'VIDEO SOURCE · VERIFIED',kind:'youtube',embed:'https://www.youtube-nocookie.com/embed/O3v309CA4ao?autoplay=1&rel=0',source:'https://youtu.be/O3v309CA4ao',poster:'https://img.youtube.com/vi/O3v309CA4ao/hqdefault.jpg'},
  {key:'fraud13',chapter:'CHAPTER 04',year:'2023',platform:'חדשות 13',title:'כשעוול פוגש פעולה',summary:'תיעוד תקשורתי של מאבק בהונאה והחזרת קול לאנשים שנפגעו — בלי להציג פרטים מבצעיים או להפוך כאב לסנסציה.',why:'הצופה פוגש אחריות מעשית: זיהוי בעיה, עמידה מול מערכת וניסיון לייצר תיקון נראה לעין.',signal:'חדשות 13 · שירות ואחריות',status:'BROADCAST RECORD · VERIFIED',kind:'youtube',embed:'https://www.youtube-nocookie.com/embed/AE5hDzLM5XU?autoplay=1&rel=0',source:'https://www.youtube.com/watch?v=AE5hDzLM5XU',poster:'https://img.youtube.com/vi/AE5hDzLM5XU/hqdefault.jpg'},
  {key:'fraud12',chapter:'CHAPTER 04',year:'2023',platform:'חדשות 12',title:'המאבק בהונאות קשישים',summary:'פריים ציבורי שמחבר ניסיון שטח, אחריות אזרחית והגנה על מי שקל מדי להשאיר מאחור.',why:'ההשפעה אינה נמדדת רק בצפייה; היא מתחילה כשהסיפור נותן שם לבעיה ומציג אדם שמוכן לפעול.',signal:'חדשות 12 · מקור וידאו',status:'BROADCAST RECORD · VERIFIED',kind:'youtube',embed:'https://www.youtube-nocookie.com/embed/3XxoBtSL2pg?autoplay=1&rel=0',source:'https://www.youtube.com/watch?v=3XxoBtSL2pg',poster:'https://img.youtube.com/vi/3XxoBtSL2pg/hqdefault.jpg'},
  {key:'nova',chapter:'CHAPTER 05',year:'2024',platform:'פודקאסט',title:'מהבריחה — אל היכולת להבין שינוי',summary:'שיחה ארוכה מאפשרת לעדות, שבר, סתירה והתפתחות להישאר בתוך אותו פריים — בלי לדחוס חוויה לאמירה אחת.',why:'הקהל מקבל זמן לפגוש אדם חושב, לא רק עמדה. זהו מעבר מתוכן קצר לזיכרון ציבורי מורכב.',signal:'שיחה ארוכה · זיכרון ואחריות',status:'PUBLIC VIDEO · VERIFIED',kind:'youtube',embed:'https://www.youtube-nocookie.com/embed/3h-oEuW8GJI?autoplay=1&rel=0',source:'https://www.youtube.com/watch?v=3h-oEuW8GJI',poster:'https://img.youtube.com/vi/3h-oEuW8GJI/hqdefault.jpg'},
  {key:'police',chapter:'CHAPTER 04',year:'2023',platform:'Instagram',title:'משטרת ישראל הם גיבורי העל של התקופה',summary:'ריל ציבורי שנוצר בזמן של פחד ואי־ודאות והעניק הכרת תודה ברורה לאנשים שפעלו בשטח.',why:'מסר אחד, הקשר מיידי ורגש גלוי. הניסיון האישי אינו משמש להאדרה, אלא להסביר למה השירות חשוב.',signal:'Reel מתועד · 17.10.2023',status:'PUBLIC REEL · SOURCE LINKED',kind:'instagram',embed:'https://www.instagram.com/reel/CyhEU1kMUuH/embed/captioned/',source:'https://www.instagram.com/reel/CyhEU1kMUuH/'},
  {key:'tiktok',chapter:'CHAPTER 06',year:'2026',platform:'TikTok',title:'קול ישיר בתוך מנוע יצירה מתמשך',summary:'פוסט קצר מתוך ארכיון TikTok הציבורי. המדד הישיר נשאר ממתין ללכידה; המקור עצמו קיים ונגיש.',why:'הפורמט עובד כשהוא מרגיש כמו שיחה ולא כמו קמפיין: כניסה מיד לנושא, גוף ראשון ושפה שמתאימה למסך.',signal:'קישור ישיר · מדדים לא הומצאו',status:'PUBLIC POST · METRICS PENDING',kind:'tiktok',embed:'https://www.tiktok.com/player/v1/7653793755757169941?autoplay=1&music_info=1&description=1',source:'https://www.tiktok.com/@igor.vepretski/video/7653793755757169941'}
];

export default function StoryStage(){
  const [active,setActive]=useState(0);
  const [playing,setPlaying]=useState(false);
  const story=stories[active];
  const select=(index:number)=>{setActive(index);setPlaying(false)};
  return <section className="story-stage" id="story-player" aria-labelledby="story-player-title">
    <header className="story-stage-head"><div><span><Sparkles/>THE LIVING STORY PLAYER</span><h2 id="story-player-title">לא קיר של לינקים.<br/><em>סיפור שנפתח מולך.</em></h2></div><p>פריט אחד בכל רגע. לוחצים רק כשרוצים לצפות; עד אז האתר נשאר מהיר, נקי ומכבד פרטיות.</p></header>
    <div className="story-player-shell">
      <div className="story-frame">
        {playing?<><iframe src={story.embed} title={story.title} loading="lazy" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/><button className="story-stop" type="button" onClick={()=>setPlaying(false)}><Pause/>לעצור ולחזור לסיפור</button></>:<div className={'story-poster platform-'+story.kind}>{story.poster&&<img src={story.poster} alt={`${story.platform}: ${story.title}`}/>}<span className="story-overlay"/><div className="story-platform-mark"><small>{story.chapter} · {story.year}</small><b>{story.platform}</b></div><button type="button" className="story-play" onClick={()=>setPlaying(true)} aria-label={`להפעיל כאן: ${story.title}`}><Play fill="currentColor"/><span>להפעיל כאן</span></button><div className="story-frame-caption"><small>{story.status}</small><strong>{story.title}</strong></div></div>}
      </div>
      <aside className="story-context"><div className="story-context-top"><span>{story.chapter}</span><em>{story.year}</em></div><h3>{story.title}</h3><p>{story.summary}</p><div className="story-why"><Sparkles/><div><small>למה זה חשוב בתוך הסיפור</small><span>{story.why}</span></div></div><div className="story-signal"><BadgeCheck/><div><small>אות הראיה</small><b>{story.signal}</b></div></div><a href={story.source} target="_blank" rel="noreferrer">לפתיחת המקור המלא <ExternalLink/></a><div className="story-privacy"><ShieldCheck/><span>ה־embed נטען רק לאחר פעולה יזומה. אין autoplay ואין טענה מעבר למקור.</span></div></aside>
    </div>
    <nav className="story-selector" aria-label="בחירת פרק">{stories.map((item,index)=><button type="button" key={item.key} className={index===active?'active':''} onClick={()=>select(index)} aria-pressed={index===active}><span>{String(index+1).padStart(2,'0')}</span>{item.poster?<img src={item.poster} alt=""/>:<i className={'mini-platform '+item.kind}>{item.platform}</i>}<div><small>{item.platform} · {item.year}</small><b>{item.title}</b></div><ArrowUpLeft/></button>)}</nav>
  </section>;
}
