import { useMemo, useState } from 'react';
import { AlertTriangle, BadgeCheck, BarChart3, ChevronLeft, ChevronRight, ExternalLink, Eye, Heart, MessageCircle, Music2, Network, Play, Radio, Share2 } from 'lucide-react';
import './viral.css';

type Status='verified'|'indexed'|'documented'|'pending';
type Platform='Facebook'|'TikTok'|'Instagram'|'YouTube'|'LinkedIn'|'X'|'Threads'|'Spotify'|'Apple Music'|'SoundCloud'|'Medium'|'Academia'|'StartOn';
type Metric={icon:'views'|'likes'|'comments'|'shares'|'posts';label:string;value:string};
type Post={id:string;platform:Platform;publisher:string;title:string;date:string;url:string;kind:'facebook-video'|'instagram'|'tiktok'|'youtube'|'spotify'|'apple'|'soundcloud'|'link';embedId?:string;metrics:Metric[];status:Status;note:string};
type Node={name:string;url:string;summary:string;metrics:string[];status:Status};

const nodes:Node[]=[
{name:'TikTok',url:'https://www.tiktok.com/@igor.vepretski',summary:'מנוע הפרסום המתועד החזק ביותר.',metrics:['12,655 עוקבים','273,860 לייקים','904 פוסטים מיוצאים'],status:'verified'},
{name:'Instagram · @igor.vepretski',url:'https://www.instagram.com/igor.vepretski/',summary:'Reels, פעילות ציבורית ו־StartOn.',metrics:['8.1K+ עוקבים','1,189 פוסטים','נלכד 08.06.2026'],status:'indexed'},
{name:'Instagram · @vepretski.igor',url:'https://www.instagram.com/vepretski.igor/',summary:'החשבון שבו הסיפור החדש מופץ כעת.',metrics:['5K צפיות','801 חשבונות','29.88 שניות צפייה ממוצעת · 01.08.2026'],status:'verified'},
{name:'YouTube',url:'https://www.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',summary:'וידאו ארוך, פודקאסטים ומוזיקה.',metrics:['2.57K מנויים','334 סרטונים','Playlist ציבורי'],status:'indexed'},
{name:'Facebook',url:'https://www.facebook.com/igor7ya',summary:'עמוד בבעלות ורשת הגברה חיצונית.',metrics:['14,000 צפיות לפוסט מפלגתי','1,500 reactions בהצינור'],status:'verified'},
{name:'LinkedIn',url:'https://www.linkedin.com/in/vepretski/',summary:'הסמכות המקצועית והכתיבה הארוכה.',metrics:['4,283 עוקבים','326 פוסטים','5 מאמרים'],status:'verified'},
{name:'X',url:'https://x.com/igorvepretski',summary:'עדכונים ועמדות בזמן אמת.',metrics:['פרופיל מחובר','מדדים ממתינים ללכידה'],status:'pending'},
{name:'Threads',url:'https://www.threads.net/@igor.vepretski',summary:'שיחה קצרה והפצת מחשבות.',metrics:['פרופיל מחובר','מדדים ממתינים ללכידה'],status:'pending'},
{name:'Spotify',url:'https://open.spotify.com/artist/0fgRoQ6PoCHlVCIr8a5d6u',summary:'קטלוג מוזיקה תחת Ido Vepretski.',metrics:['עמוד אמן ציבורי','Embed פעיל'],status:'documented'},
{name:'Apple Music',url:'https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he',summary:'קטלוג המוזיקה במערכת Apple.',metrics:['עמוד אמן ציבורי','Embed פעיל'],status:'documented'},
{name:'SoundCloud',url:'https://soundcloud.com/idovepretski',summary:'ארכיון הקלטות ויצירות.',metrics:['עמוד אמן ציבורי','Widget פעיל'],status:'documented'},
{name:'Medium',url:'https://medium.com/@igor.vepretski/igor-vepretski-from-troubled-beginnings-to-social-impact-a-journey-of-resilience-and-purpose-253aa8af266d',summary:'כתיבה באנגלית על resilience ו־impact.',metrics:['מאמר מחבר ציבורי'],status:'documented'},
{name:'Academia',url:'https://igorvepretski.academia.edu/',summary:'מחקר עצמאי על זהות ואלגוריתמים.',metrics:['11 papers','4 books','פרופיל ציבורי'],status:'verified'},
{name:'StartOn',url:'https://starton.org.il/',summary:'המעבר מהשפעה דיגיטלית לתשתית חברתית.',metrics:['אתר רשמי','LinkedIn ארגוני','מערכת שותפים'],status:'verified'}
];

const posts:Post[]=[
{id:'instagram-story-20260801',platform:'Instagram',publisher:'@vepretski.igor',title:'שלום שבת | #7YA — הסיפור מתחיל',date:'31.07.2026',url:'https://www.instagram.com/reel/DbDfpb6orUt/',kind:'instagram',embedId:'DbDfpb6orUt',metrics:[{icon:'views',label:'צפיות',value:'5K'},{icon:'views',label:'חשבונות שנחשפו',value:'801'},{icon:'views',label:'זמן צפייה ממוצע',value:'29.88s'}],status:'verified',note:'צילום מצב של Insights מ־01.08.2026 בשעה 10:33. נתון הצפיות מעוגל כפי שהוצג ב־Instagram; הקישור מוביל לריל הקנוני.'},
{id:'political',platform:'Facebook',publisher:'ישראל ביתנו',title:'תגיד יא ביבי, איפה הניצחון המוחלט?',date:'29.01.2026',url:'https://www.facebook.com/beytenu/videos/%D7%99%D7%95%D7%A6%D7%90-%D7%9B%D7%95%D7%97%D7%95%D7%AA-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%AA%D7%92%D7%99%D7%93-%D7%99%D7%90-%D7%91%D7%99%D7%91%D7%99-%D7%90%D7%99%D7%A4%D7%94-%D7%94%D7%A0%D7%99%D7%A6%D7%97%D7%95%D7%9F-%D7%94%D7%9E%D7%95%D7%97%D7%9C%D7%98/26702411802682636/',kind:'facebook-video',metrics:[{icon:'views',label:'צפיות',value:'14,000'}],status:'indexed',note:'נתון מתוצאת חיפוש ציבורית; צילום מסך חי עדיין מומלץ.'},
{id:'hazinor',platform:'Facebook',publisher:'הצינור',title:'זה מתחיל להסתמן כלהיט החדש',date:'ארכיון',url:'https://www.facebook.com/hazinor/videos/%D7%96%D7%94-%D7%9E%D7%AA%D7%97%D7%99%D7%9C-%D7%9C%D7%94%D7%A1%D7%AA%D7%9E%D7%9F-%D7%9B%D7%9C%D7%94%D7%99%D7%98-%D7%94%D7%97%D7%93%D7%A9dennis-charkov-igor-vepretski-david-goldenberg-vlad-jh/10153274636619662/',kind:'facebook-video',metrics:[{icon:'likes',label:'תגובות רגש',value:'1,500'}],status:'verified',note:'וידאו ויראלי חיצוני עם איגור ויוצרים נוספים.'},
{id:'tiktok',platform:'TikTok',publisher:'@igor.vepretski',title:'פוסט ציבורי מתוך מנוע TikTok',date:'21.06.2026',url:'https://www.tiktok.com/@igor.vepretski/video/7653793755757169941',kind:'tiktok',embedId:'7653793755757169941',metrics:[],status:'documented',note:'הפוסט מזוהה; מדדי הפוסט ממתינים לצילום מסך מתוארך.'},
{id:'instagram',platform:'Instagram',publisher:'@igor.vepretski',title:'משטרת ישראל הם גיבורי העל של התקופה האחרונה',date:'17.10.2023',url:'https://www.instagram.com/reel/CyhEU1kMUuH/',kind:'instagram',embedId:'CyhEU1kMUuH',metrics:[],status:'verified',note:'ה־Reel והכיתוב הציבורי אומתו; מדדים ממתינים ללכידה.'},
{id:'youtube',platform:'YouTube',publisher:'Igor Vepretski #7YA',title:'מהבריחה מפסטיבל הנובה להתפכחות',date:'2024',url:'https://www.youtube.com/watch?v=3h-oEuW8GJI',kind:'youtube',embedId:'3h-oEuW8GJI',metrics:[],status:'verified',note:'וידאו ציבורי מוטמע ישירות מ־YouTube.'},
{id:'linkedin-starton',platform:'LinkedIn',publisher:'Igor Vepretski',title:'How digital innovation hubs empower communities',date:'2025',url:'https://www.linkedin.com/posts/vepretski_discover-how-digital-innovation-hubs-are-activity-7336995936314834944-escP',kind:'link',metrics:[{icon:'likes',label:'תגובות רגש',value:'22'},{icon:'comments',label:'תגובות',value:'1'}],status:'verified',note:'פוסט מקצועי על מערכת StartOn.'},
{id:'linkedin-tiktok',platform:'LinkedIn',publisher:'Igor Vepretski',title:'TikTok marketing / digital influence',date:'2025',url:'https://www.linkedin.com/posts/vepretski_tiktokmarketing-digitalinfluence-personalbranding-activity-7316474020063760384-0aAl',kind:'link',metrics:[{icon:'likes',label:'תגובות רגש',value:'7'},{icon:'comments',label:'תגובות',value:'1'}],status:'verified',note:'מומחיות מקצועית כיוצר ומפיץ.'},
{id:'x',platform:'X',publisher:'@igorvepretski',title:'הזרם הציבורי ב־X',date:'פעיל',url:'https://x.com/igorvepretski',kind:'link',metrics:[],status:'pending',note:'פרופיל מחובר; פוסטים ומדדים ממתינים ללכידה ייעודית.'},
{id:'threads',platform:'Threads',publisher:'@igor.vepretski',title:'השיחה הציבורית ב־Threads',date:'פעיל',url:'https://www.threads.net/@igor.vepretski',kind:'link',metrics:[],status:'pending',note:'פרופיל מחובר; פוסטים ומדדים ממתינים ללכידה ייעודית.'},
{id:'spotify',platform:'Spotify',publisher:'Ido Vepretski',title:'קטלוג המוזיקה ב־Spotify',date:'2020–2026',url:'https://open.spotify.com/artist/0fgRoQ6PoCHlVCIr8a5d6u',kind:'spotify',metrics:[],status:'documented',note:'עמוד אמן ציבורי ו־embed פעיל.'},
{id:'apple',platform:'Apple Music',publisher:'Ido Vepretski',title:'קטלוג המוזיקה ב־Apple Music',date:'2020–2026',url:'https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he',kind:'apple',metrics:[],status:'documented',note:'עמוד אמן ציבורי ו־embed פעיל.'},
{id:'soundcloud',platform:'SoundCloud',publisher:'Ido Vepretski',title:'ארכיון ההקלטות ב־SoundCloud',date:'ארכיון',url:'https://soundcloud.com/idovepretski',kind:'soundcloud',metrics:[],status:'documented',note:'עמוד אמן ציבורי ו־widget פעיל.'},
{id:'medium',platform:'Medium',publisher:'Igor Vepretski',title:'From Troubled Beginnings to Social Impact',date:'2024',url:'https://medium.com/@igor.vepretski/igor-vepretski-from-troubled-beginnings-to-social-impact-a-journey-of-resilience-and-purpose-253aa8af266d',kind:'link',metrics:[],status:'documented',note:'מאמר מחבר ציבורי באנגלית.'},
{id:'academia',platform:'Academia',publisher:'Igor Vepretski',title:'Independent Researcher — papers and books',date:'2025–2026',url:'https://igorvepretski.academia.edu/',kind:'link',metrics:[{icon:'posts',label:'Papers',value:'11'},{icon:'posts',label:'Books',value:'4'}],status:'verified',note:'מחקר עצמאי; אינו מוצג כ־peer reviewed ללא מקור.'},
{id:'starton',platform:'StartOn',publisher:'StartOn',title:'המערכת החברתית שממשיכה את ההשפעה',date:'2022–2026',url:'https://starton.org.il/',kind:'link',metrics:[],status:'verified',note:'אתר רשמי, משימה וקישורי הפצה.'}
];

const topTikTok=[['07.03.2022','36,694'],['24.03.2024','8,720'],['16.06.2024','7,628'],['11.11.2024','7,466'],['01.07.2024','7,343'],['28.04.2024','6,605'],['01.08.2024','6,098'],['23.11.2023','4,942'],['20.11.2023','4,902'],['26.11.2023','4,762']];
const choices:['הכול',...Platform[]]=['הכול','Facebook','TikTok','Instagram','YouTube','LinkedIn','X','Threads','Spotify','Apple Music','SoundCloud','Medium','Academia','StartOn'];
const labels:Record<Status,string>={verified:'מאומת',indexed:'מאונדקס',documented:'מתועד',pending:'ממתין ללכידה'};
const Icon=({name}:{name:Metric['icon']})=>name==='views'?<Eye/>:name==='comments'?<MessageCircle/>:name==='shares'?<Share2/>:name==='posts'?<BarChart3/>:<Heart/>;
function src(post:Post){if(post.kind==='facebook-video')return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(post.url)}&show_text=false&width=500`;if(post.kind==='instagram')return `https://www.instagram.com/reel/${post.embedId}/embed/`;if(post.kind==='tiktok')return `https://www.tiktok.com/player/v1/${post.embedId}?description=1&music_info=1&autoplay=0`;if(post.kind==='youtube')return `https://www.youtube-nocookie.com/embed/${post.embedId}`;if(post.kind==='spotify')return 'https://open.spotify.com/embed/artist/0fgRoQ6PoCHlVCIr8a5d6u?utm_source=generator';if(post.kind==='apple')return 'https://embed.music.apple.com/il/artist/ido-vepretski/1527248864?l=he';if(post.kind==='soundcloud')return `https://w.soundcloud.com/player/?url=${encodeURIComponent('https://soundcloud.com/idovepretski')}&color=%23e8ad45&auto_play=false&show_comments=true&show_user=true`;return '';}
function visual(post:Post){if(post.platform==='Facebook')return './resources/hero-story.webp';if(post.platform==='TikTok')return './resources/7ya-launch.webp';if(post.platform==='YouTube')return './resources/chapter-voice.webp';if(post.platform==='Instagram')return './resources/igor-hero.jpg';if(post.platform==='Spotify'||post.platform==='Apple Music'||post.platform==='SoundCloud')return './resources/chapter-music.webp';if(post.platform==='StartOn')return './resources/chapter-starton.webp';return './resources/7ya-research.webp';}

export default function ViralFeed(){
 const [platform,setPlatform]=useState<(typeof choices)[number]>('הכול');const [activeId,setActiveId]=useState(posts[0].id);const [embedOpen,setEmbedOpen]=useState(false);
 const filtered=useMemo(()=>platform==='הכול'?posts:posts.filter(post=>post.platform===platform),[platform]);const active=filtered.find(post=>post.id===activeId)??filtered[0]??posts[0];const index=filtered.findIndex(post=>post.id===active.id);
 const choose=(value:(typeof choices)[number])=>{setPlatform(value);setEmbedOpen(false);const first=value==='הכול'?posts[0]:posts.find(post=>post.platform===value);if(first)setActiveId(first.id);};const move=(step:number)=>{const next=(index+step+filtered.length)%filtered.length;setEmbedOpen(false);setActiveId(filtered[next].id);};
 return <section id="viral-live" className="viral-stage relative overflow-hidden border-y border-white/10 py-24 sm:py-32"><div className="viral-noise"/><img src="./resources/igor-hero.jpg" alt="" className="viral-hero-copy"/>
 <div className="relative z-10 mx-auto max-w-[1480px] px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><span className="section-label">02 / VIRAL SIGNAL</span><h2 className="mt-5 text-5xl font-black leading-[.88] tracking-[-.06em] sm:text-7xl">לא לספר<br/><span className="text-[#e8ad45]">שהיה ויראלי.</span><br/>לשדר את זה.</h2></div><div><p className="max-w-2xl text-lg leading-8 text-white/58">הפוסטים, ההפצה והמדדים שנלכדו. כל מספר מחובר למקור; כל חוסר מסומן בגלוי.</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-emerald-300"><BadgeCheck size={16}/>TikTok מתוארך ל־02.06.2026; פרופילים נוספים ל־08.06.2026.</div></div></div>
 <div className="viral-platform-rail mt-12">{choices.map(value=><button key={value} onClick={()=>choose(value)} className={platform===value?'active':''}>{value}</button>)}</div>
 <div className="viral-broadcast mt-8"><div className="viral-screen"><div className="viral-screen-top"><div><span className="viral-live"><Radio size={13}/>ON AIR</span><span className="viral-platform-name">{active.platform}</span></div><div><button onClick={()=>move(-1)} aria-label="הקודם"><ChevronRight/></button><span>{index+1} / {filtered.length}</span><button onClick={()=>move(1)} aria-label="הבא"><ChevronLeft/></button></div></div><div className="viral-embed">{active.kind==='link'?<a className="viral-link-preview" href={active.url} target="_blank" rel="noreferrer"><img src={visual(active)} alt=""/><div><span>{active.platform} · {active.publisher}</span><strong>{active.title}</strong><p>{active.note}</p><b>פתיחת המקור <ExternalLink size={16}/></b></div></a>:embedOpen?<iframe src={src(active)} title={active.title} loading="eager" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen/>:<div className="viral-embed-poster" style={{backgroundImage:`linear-gradient(90deg,rgba(5,6,8,.12),rgba(5,6,8,.86)),url(${visual(active)})`}}><div><span>{active.platform} · {active.publisher}</span><strong>{active.title}</strong><p>{active.note}</p><button type="button" onClick={()=>setEmbedOpen(true)}><Play/>נגן כאן</button></div></div>}</div><div className="viral-caption"><div><span>{active.publisher} · {active.date}</span><h3>{active.title}</h3><p>{active.note}</p></div><a href={active.url} target="_blank" rel="noreferrer">למקור <ExternalLink size={16}/></a></div></div>
 <aside className="viral-console"><div className="viral-status"><span className={`status-${active.status}`}>{labels[active.status]}</span><small>Evidence status</small></div><div className="viral-metrics">{active.metrics.length?active.metrics.map(metric=><div key={metric.label}><Icon name={metric.icon}/><strong>{metric.value}</strong><span>{metric.label}</span></div>):<div className="viral-no-metric"><AlertTriangle/><strong>אין מספר מאומת</strong><span>ממתין ללכידה מתוארכת.</span></div>}</div><div className="viral-source-list"><span>פוסטים בערוץ</span>{filtered.slice(0,7).map(post=><button key={post.id} onClick={()=>{setEmbedOpen(false);setActiveId(post.id)}} className={post.id===active.id?'active':''}><i>{post.platform.slice(0,2).toUpperCase()}</i><b>{post.title}</b><em>{post.metrics[0]?.value??'—'}</em></button>)}</div></aside></div>
 <div className="platform-matrix mt-16"><div className="platform-matrix-head"><div><span className="section-label">PLATFORM MATRIX</span><h3>כול הפלטפורמות. סטטוס אחד ברור.</h3></div><Network/></div><div className="platform-node-grid">{nodes.map(node=><a key={node.name} href={node.url} target="_blank" rel="noreferrer" className={`platform-node node-${node.status}`}><div><span>{node.name}</span><b>{labels[node.status]}</b></div><p>{node.summary}</p><ul>{node.metrics.map(metric=><li key={metric}>{metric}</li>)}</ul><ExternalLink/></a>)}</div></div>
 <div className="viral-depth mt-16"><div className="tiktok-rank"><div className="viral-block-title"><div><span className="section-label">TIKTOK TOP 10</span><h3>עשרת הפוסטים המובילים לפי לייקים</h3></div><strong>273,737</strong></div><div className="rank-list">{topTikTok.map(([date,value],idx)=>{const width=Math.max(14,Math.round(Number(value.replace(',',''))/36694*100));return <div key={date}><span>{String(idx+1).padStart(2,'0')}</span><div><i style={{width:`${width}%`}}/><b>{date}</b></div><strong>{value}</strong></div>})}</div><small>מבוסס export מתועד. אין המצאת URLs לפוסטים שלא נשמר להם קישור ציבורי.</small></div><div className="propagation-map"><div className="viral-block-title"><div><span className="section-label">PROPAGATION</span><h3>אות אחד. רשת שלמה.</h3></div><Share2/></div><div className="propagation-core"><img src="./resources/igor-hero.jpg" alt="איגור ופרצקי"/><strong>IGOR</strong></div><div className="propagation-lines"><span>Owned</span><span>סטטוסים</span><span>LinkedIn</span><span>הצינור</span><span>ישראל ביתנו</span><span>Instagram</span><span>YouTube</span></div><p>הגרף מציג הפצה בין מפרסמים, לא סכום reach מלאכותי.</p></div></div>
 <div className="verification-queue mt-10"><AlertTriangle/><div><span>תור אימות גלוי</span><strong>בן כספית — שיתוף דווח, אך הקישור המדויק טרם אותר.</strong><p>השם נשמר במערכת ולא מוצג כהישג מאומת עד לחיבור הפוסט המקורי.</p></div></div></div></section>;
}
