export type ContentWorld='LIFE'|'SERVICE'|'CIVIC'|'BUILD'|'IMPACT'|'CULTURE'|'RECORD';
export type ContentCTA='READ_STORY'|'VIEW_EVIDENCE'|'VIEW_RECORD'|'COLLABORATE'|'WATCH_LISTEN'|'INSPECT_SOURCES';
type Localized={he:string;en:string;ru:string};
export type OperatingEvent={id:string;canonicalDate:string;type:string;surfaces:string[];title:Localized;summary:Localized;visibility:string;verification:{state:string;note:string};sources:Array<{public:boolean;platform?:string;url:string;label:string}>;tags:string[]};
export type OperatingRecord={canonicalId:string;canonicalDate:string;primaryWorld:ContentWorld;secondaryWorlds:ContentWorld[];title:Localized;summary:Localized;verification:string;audiences:string[];locales:Array<'he'|'en'|'ru'>;distribution:string[];cta:ContentCTA;canonicalApiUrl:string;sourceUrls:string[]};
const ORDER:ContentWorld[]=['LIFE','SERVICE','CIVIC','BUILD','IMPACT','CULTURE','RECORD'];
const WORLD_META:Record<ContentWorld,{label:Localized;audiences:string[];distribution:string[];cta:ContentCTA}>={LIFE:{label:{he:'חיים',en:'Life',ru:'Жизнь'},audiences:['public','community','media'],distribution:['Instagram','TikTok','YouTube','Facebook'],cta:'READ_STORY'},SERVICE:{label:{he:'שירות',en:'Service',ru:'Служба'},audiences:['public','institutions','employers','media'],distribution:['LinkedIn','Facebook','YouTube'],cta:'VIEW_EVIDENCE'},CIVIC:{label:{he:'ציבור ואזרחות',en:'Civic',ru:'Общество'},audiences:['public','institutions','media'],distribution:['X','Facebook','LinkedIn','YouTube'],cta:'VIEW_RECORD'},BUILD:{label:{he:'בנייה',en:'Build',ru:'Создание'},audiences:['builders','institutions','employers','media'],distribution:['LinkedIn','X','GitHub','YouTube'],cta:'COLLABORATE'},IMPACT:{label:{he:'השפעה',en:'Impact',ru:'Влияние'},audiences:['youth','institutions','partners','media'],distribution:['LinkedIn','Facebook','YouTube','Instagram'],cta:'COLLABORATE'},CULTURE:{label:{he:'תרבות',en:'Culture',ru:'Культура'},audiences:['public','creators','media'],distribution:['Instagram','TikTok','YouTube','Spotify'],cta:'WATCH_LISTEN'},RECORD:{label:{he:'רקורד',en:'Record',ru:'Архив'},audiences:['researchers','journalists','institutions'],distribution:['7ya.io','Search','AI'],cta:'INSPECT_SOURCES'}};
const has=(event:OperatingEvent,value:string)=>event.surfaces.includes(value);
const words=(event:OperatingEvent)=>[event.id,event.type,...event.surfaces,...event.tags].join(' ').toLowerCase();
export function primaryWorldOf(event:OperatingEvent):ContentWorld{const text=words(event);if(event.type==='service')return'SERVICE';if(has(event,'starton'))return'IMPACT';if(event.type==='music'||has(event,'music'))return'CULTURE';if(event.type==='research'||has(event,'research')||event.type==='system'||event.type==='project')return'BUILD';if(/politic|civic|public action|public-action|cost of living|election|party|government|municipal/.test(text))return'CIVIC';if(has(event,'life')||event.type==='identity'||event.type==='post')return'LIFE';return'RECORD'}
function secondaryWorlds(event:OperatingEvent,primary:ContentWorld){const result:ContentWorld[]=[];if(has(event,'archive')&&primary!=='RECORD')result.push('RECORD');if(has(event,'influence')&&primary!=='CIVIC'&&/civic|public|politic|government|party|municipal/.test(words(event)))result.push('CIVIC');return result}
function recordOf(event:OperatingEvent):OperatingRecord{const primaryWorld=primaryWorldOf(event),meta=WORLD_META[primaryWorld];return{canonicalId:event.id,canonicalDate:event.canonicalDate,primaryWorld,secondaryWorlds:secondaryWorlds(event,primaryWorld),title:event.title,summary:event.summary,verification:event.verification.state,audiences:[...meta.audiences],locales:['he','en','ru'],distribution:[...meta.distribution],cta:meta.cta,canonicalApiUrl:'/api/corpus/'+encodeURIComponent(event.id),sourceUrls:event.sources.filter(source=>source.public).map(source=>source.url)}}
export function projectContentOperatingMap(events:OperatingEvent[]){const publicEvents=events.filter(event=>event.visibility==='public'&&event.sources.some(source=>source.public));const records=publicEvents.map(recordOf).sort((a,b)=>a.canonicalDate.localeCompare(b.canonicalDate)||a.canonicalId.localeCompare(b.canonicalId));const worlds=ORDER.map(id=>({...WORLD_META[id],id,count:records.filter(record=>record.primaryWorld===id).length}));return{release:'CONTENT-OPERATING-MAP-20260907-1',schemaVersion:1,generatedAt:new Date().toISOString(),policy:{source:'canonical-corpus',publicOnly:true,privateAutoPublish:false,automaticDistribution:false,evidenceStatePreserved:true},flow:['CAPTURE','INGEST','CLASSIFY','VERIFY','CANONICALIZE','PUBLISH_7YA','LOCALIZE','REPURPOSE','DISTRIBUTE','MEASURE','ARCHIVE','LEARN','REUSE'],worlds,stats:{publicRecords:records.length,privateExcluded:events.length-publicEvents.length},records}}