import {useMemo,useState} from 'react';
import {ArrowUpRight,MessageCircle,Network,Radio,ShieldCheck} from 'lucide-react';
import {impactEras,impactSignals,platformFootprint,quarantinedImpactClaims} from '../../shared/impact-broadcast';
import {echoStories,type EchoStory} from '../echo-records';
import {pageHref,useLocale,type Locale} from '../locale';
import './impact-front-door.css';

type Copy={eyebrow:string;title:string;lead:string;years:string;timeline:string;propagation:string;propagationLead:string;platforms:string;platformLead:string;evidence:string;boundary:string;open:string;archive:string;talk:string;metricScope:string;quarantine:string};
const copy:Record<Locale,Copy>={he:{eyebrow:'IMPACT BROADCAST · 2011—2026',title:'לא כמה עוקבים.\nכמה רחוק הסיפור נסע.',lead:'חמש־עשרה שנים של עקבה ציבורית — מעיתונות מוקדמת, דרך פוסטים ויראליים ו־StartOn, ועד מיליוני צפיות אצל יוצרים אחרים. כל מספר נשאר עם המקור, התאריך וההגדרה שלו.',years:'15 YEARS · PUBLIC TRAIL',timeline:'ציר ההשפעה',propagation:'כך הסיפור עבר הלאה',propagationLead:'בחרו רגע וראו איך מקור אחד עבר להפצה, תגובה, תקשורת או פעולה — בלי לספור את אותה תנועה פעמיים.',platforms:'הנוכחות אינה מספר אחד',platformLead:'כל פלטפורמה נשארת snapshot נפרד. עוקבים, פוסטים, לייקים וצפיות אינם מחוברים ל־reach מלאכותי.',evidence:'גבול הראיה',boundary:'המספרים הגדולים ביותר אינם בהכרח המספרים הכי חזקים. טענה שאין לה חבילת מקור והגדרה ניתנת להגנה נשארת בהסגר.',open:'פתיחת המקור',archive:'לארכיון ההשפעה',talk:'לשאול את Digital Igor',metricScope:'מקור · תאריך · היקף',quarantine:'לא מאומת כ־total reach'},en:{eyebrow:'IMPACT BROADCAST · 2011—2026',title:'Not follower count.\nHow far the story travelled.',lead:'Fifteen years of public trail — from early press through viral posts and StartOn to millions of views on other creators’ channels. Every number keeps its source, date and definition.',years:'15 YEARS · PUBLIC TRAIL',timeline:'Impact timeline',propagation:'How the story moved',propagationLead:'Choose a moment and follow one source through redistribution, response, media or action — without counting the same movement twice.',platforms:'Presence is not one number',platformLead:'Every platform remains a separate snapshot. Followers, posts, likes and views are never collapsed into synthetic reach.',evidence:'Evidence boundary',boundary:'The biggest number is not automatically the strongest number. A claim without a defensible source package and definition stays quarantined.',open:'Open source',archive:'Impact-first archive',talk:'Ask Digital Igor',metricScope:'source · date · scope',quarantine:'not verified as total reach'},ru:{eyebrow:'IMPACT BROADCAST · 2011—2026',title:'Не число подписчиков.\nКак далеко ушла история.',lead:'Пятнадцать лет публичного следа — от ранней прессы через вирусные посты и StartOn до миллионов просмотров у других авторов. Каждое число сохраняет источник, дату и определение.',years:'15 YEARS · PUBLIC TRAIL',timeline:'Хронология влияния',propagation:'Как история распространялась',propagationLead:'Выберите момент и проследите путь от источника к распространению, реакции, медиа или действию — без двойного счёта.',platforms:'Присутствие — не одно число',platformLead:'Каждая платформа остаётся отдельным снимком. Подписчики, посты, лайки и просмотры не складываются в синтетический reach.',evidence:'Граница доказательств',boundary:'Самое большое число не обязательно самое сильное. Утверждение без защищаемого пакета источников и определения остаётся в карантине.',open:'Открыть источник',archive:'Архив влияния',talk:'Спросить Digital Igor',metricScope:'источник · дата · охват',quarantine:'не подтверждено как total reach'}};
const storyIds=['nawan-coappearance','fatherhood','miel','elder-fraud'];
const storyLabel:Record<string,Record<Locale,string>>={
'nawan-coappearance':{he:'5.1M אצל Nawan',en:'5.1M with Nawan',ru:'5,1M у Nawan'},fatherhood:{he:'אבא ששם',en:'A father who is present',ru:'Отец, который рядом'},miel:{he:'כשהגננת מתקשרת',en:'When kindergarten calls',ru:'Когда звонит воспитательница'},'elder-fraud':{he:'מהונאה לתקשורת',en:'From scam to newsroom',ru:'От мошенничества к медиа'}};
function cleanMetric(story:EchoStory,metric?:string){if(!metric)return'';if(story.id!=='fatherhood')return metric;return metric.split(' · ').filter(part=>!part.toLowerCase().includes('share')).join(' · ')}
export default function ImpactFrontDoor(){const {locale}=useLocale();const c=copy[locale];const [eraId,setEraId]=useState('era-2026');const [storyId,setStoryId]=useState('nawan-coappearance');const era=impactEras.find(item=>item.id===eraId)||impactEras[impactEras.length-1];const stories=useMemo(()=>storyIds.map(id=>echoStories.find(item=>item.id===id)).filter((item):item is EchoStory=>Boolean(item)),[]);const story=stories.find(item=>item.id===storyId)||stories[0];const archive=pageHref('library',locale);const talk=pageHref('home',locale)+'&chat=open';return <section className='ib' id='impact' aria-labelledby='impact-broadcast-title' data-impact-broadcast='1'>
<header className='ib-head'><div><p>{c.eyebrow}</p><span>{c.years}</span><h2 id='impact-broadcast-title'>{c.title.split('\n').map((line,index)=><span key={line}>{line}{index===0&&<br/>}</span>)}</h2></div><p className='ib-lead'>{c.lead}</p></header>
<section className='ib-signal' aria-label={c.metricScope}>{impactSignals.map((item,index)=><article key={item.id} className={'ib-signal-card '+item.tone+(index===0?' hero':'')}><small>{item.verification} · {item.date}</small><strong dir='ltr'>{item.value}</strong><h3>{item.label[locale]}</h3><p>{item.note[locale]}</p><footer><span dir='ltr'>{item.scope}</span><a href={item.sourceUrl} target='_blank' rel='noreferrer' aria-label={item.sourceLabel}>{c.open}<ArrowUpRight/></a></footer></article>)}</section>
<section className='ib-era' aria-labelledby='ib-era-title'><header><div><Radio/><span>{c.timeline}</span></div><p>{c.metricScope.toUpperCase()}</p></header><nav className='ib-era-nav' aria-label={c.timeline}>{impactEras.map(item=><button type='button' key={item.id} className={item.id===era.id?'active':''} aria-pressed={item.id===era.id} onClick={()=>setEraId(item.id)}><b>{item.year}</b><span>{item.kicker[locale]}</span></button>)}</nav><article className='ib-era-stage' aria-live='polite'><div className='ib-era-visual'>{era.image?<img src={era.image} alt='' loading='lazy' referrerPolicy='no-referrer'/>:<div className='ib-era-poster'><span>{era.year}</span><Network/><b>{era.kicker[locale]}</b></div>}<i/></div><div className='ib-era-copy'><small>{era.sourceLabel}</small><h3>{era.title[locale]}</h3><p>{era.body[locale]}</p>{era.metrics.length>0&&<div className='ib-era-metrics'>{era.metrics.map(item=><div key={item.value+item.label.en}><strong dir='ltr'>{item.value}</strong><span>{item.label[locale]}</span></div>)}</div>}<footer><p><ShieldCheck/>{era.boundary[locale]}</p><a href={era.sourceUrl} target='_blank' rel='noreferrer'>{c.open}<ArrowUpRight/></a></footer></div></article></section>
<section className='ib-propagation' aria-labelledby='ib-propagation-title'><header><div><small>PUBLIC ECHO · SOURCE → RESPONSE</small><h3 id='ib-propagation-title'>{c.propagation}</h3></div><p>{c.propagationLead}</p></header><nav className='ib-story-tabs' aria-label={c.propagation}>{stories.map(item=><button type='button' key={item.id} className={item.id===story.id?'active':''} aria-pressed={item.id===story.id} onClick={()=>setStoryId(item.id)}>{storyLabel[item.id]?.[locale]||item.title[locale]}</button>)}</nav><article className='ib-story-stage'><figure>{story.visual.image?<img src={story.visual.image} alt={story.visual.caption[locale]} loading='lazy' referrerPolicy='no-referrer'/>:<div className='ib-story-poster'><Network/><b>{story.visual.source}</b></div>}<figcaption>{story.visual.source}</figcaption></figure><div className='ib-story-copy'><h4>{story.title[locale]}</h4><p>{story.summary[locale]}</p><div className='ib-story-route'>{story.nodes.map((node,index)=>{const metric=cleanMetric(story,node.metric);return <div className='ib-route-node' key={node.id}><i>{String(index+1).padStart(2,'0')}</i><small>{node.kind.toUpperCase()} · {node.evidence.toUpperCase()}</small><b>{node.label[locale]}</b>{metric&&<strong dir='ltr'>{metric}</strong>}<span>{node.source} · {node.date}</span>{node.url&&<a href={node.url} target='_blank' rel='noreferrer'>{c.open}<ArrowUpRight/></a>}</div>})}</div></div></article></section>
<section className='ib-platforms' aria-labelledby='ib-platform-title'><header><div><small>PLATFORM FOOTPRINT · DATED SNAPSHOTS</small><h3 id='ib-platform-title'>{c.platforms}</h3></div><p>{c.platformLead}</p></header><div className='ib-platform-rail'>{platformFootprint.map(item=><a href={item.sourceUrl} target='_blank' rel='noreferrer' key={item.platform}><small>{item.evidence} · {item.date}</small><h4>{item.platform}</h4><span>{item.handle}</span><div>{item.metrics.map(metric=><b key={metric.value+metric.label.en}><strong dir='ltr'>{metric.value}</strong><em>{metric.label[locale]}</em></b>)}</div><footer>{c.open}<ArrowUpRight/></footer></a>)}</div></section>
<section className='ib-boundary' aria-labelledby='ib-boundary-title'><div className='ib-boundary-copy'><ShieldCheck/><div><small>SOURCE ≠ INTERPRETATION ≠ TOTAL</small><h3 id='ib-boundary-title'>{c.evidence}</h3><p>{c.boundary}</p></div></div><div className='ib-quarantine'>{quarantinedImpactClaims.map(item=><article key={item.value}><small>{item.status}</small><strong dir='ltr'>{item.value}</strong><b>{c.quarantine}</b><p>{item.note[locale]}</p></article>)}</div><nav><a href={archive}>{c.archive}<ArrowUpRight/></a><a href={talk}>{c.talk}<MessageCircle/></a></nav></section>
</section>}
