import type {Locale} from '../locale';
export type L10n=Record<Locale,string>;
export type PlatformCategory='hub'|'social'|'video'|'music'|'writing'|'research'|'community'|'media';
export type EmbedAspect='video'|'portrait'|'audio';
export type PlatformEmbed={src:string;aspect:EmbedAspect;label:L10n};
export type ConnectedPlatform={id:string;name:string;handle:string;url:string;category:PlatformCategory;role:L10n;status:'canonical'|'verified'|'dated'|'archive';embed?:PlatformEmbed};
const l=(he:string,en:string,ru:string):L10n=>({he,en,ru});
const fb='https://www.facebook.com/hazinor/videos/%D7%96%D7%94-%D7%9E%D7%AA%D7%97%D7%99%D7%9C-%D7%9C%D7%94%D7%A1%D7%AA%D7%9E%D7%9F-%D7%9B%D7%9C%D7%94%D7%99%D7%98-%D7%94%D7%97%D7%93%D7%A9dennis-charkov-igor-vepretski-david-goldenberg-vlad-jh/10153274636619662/';
export const connectedPlatforms:ConnectedPlatform[]=[
{id:'7ya',name:'7YA.io',handle:'7ya.io',url:'https://7ya.io',category:'hub',role:l('הבית שמחבר את כל השכבות','The home connecting every layer','Дом, соединяющий все слои'),status:'canonical'},
{id:'instagram',name:'Instagram',handle:'@igor.vepretski',url:'https://www.instagram.com/igor.vepretski/',category:'social',role:l('רילס, רגעים, זהות ציבורית ויצירה','Reels, moments, public identity and creation','Reels, моменты, публичная идентичность и творчество'),status:'verified',embed:{src:'https://www.instagram.com/reel/CyhEU1kMUuH/embed/',aspect:'portrait',label:l('ריל ציבורי נבחר','Selected public Reel','Выбранный публичный Reel')}},
{id:'instagram-secondary',name:'Instagram',handle:'@vepretski.igor',url:'https://www.instagram.com/vepretski.igor/',category:'social',role:l('חשבון Instagram רשמי נוסף','Second official Instagram surface','Второй официальный Instagram'),status:'canonical',embed:{src:'https://www.instagram.com/reel/DbDfpb6orUt/embed/',aspect:'portrait',label:l('ריל ציבורי נבחר','Selected public Reel','Выбранный публичный Reel')}},
{id:'tiktok',name:'TikTok',handle:'@igor.vepretski',url:'https://www.tiktok.com/@igor.vepretski',category:'video',role:l('מנוע וידאו קצר נוכחי','Current short-form video engine','Текущий двигатель короткого видео'),status:'dated',embed:{src:'https://www.tiktok.com/player/v1/7653793755757169941?description=1&music_info=1&autoplay=0',aspect:'portrait',label:l('פוסט ציבורי נבחר','Selected public post','Выбранная публичная публикация')}},
{id:'tiktok-legacy',name:'TikTok · Legacy',handle:'@igor_vepretski',url:'https://tikbuddy.com/tiktok/igor_vepretski',category:'video',role:l('חשבון עבר חסום — מוצג כארכיון בלבד','Blocked former account — archive only','Заблокированный прежний аккаунт — только архив'),status:'archive'},
{id:'youtube',name:'YouTube',handle:'@IgorVepretski',url:'https://www.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',category:'video',role:l('וידאו ארוך, ראיונות, פודקאסטים ומוזיקה','Long-form video, interviews, podcasts and music','Длинные видео, интервью, подкасты и музыка'),status:'dated',embed:{src:'https://www.youtube-nocookie.com/embed/3h-oEuW8GJI?playsinline=1&rel=0',aspect:'video',label:l('וידאו ציבורי נבחר','Selected public video','Выбранное публичное видео')}},
{id:'podcasts',name:'Podcasts',handle:'Long-form playlist',url:'https://www.youtube.com/playlist?list=PLvXOwJ42abaQiQhJoGD4MkTLGzDdwE_GZ',category:'media',role:l('שיחות עומק ופרקים ארוכים','Long-form conversations and episodes','Длинные разговоры и выпуски'),status:'verified',embed:{src:'https://www.youtube-nocookie.com/embed?listType=playlist&list=PLvXOwJ42abaQiQhJoGD4MkTLGzDdwE_GZ&playsinline=1',aspect:'video',label:l('פלייליסט ציבורי','Public playlist','Публичный плейлист')}},
{id:'facebook',name:'Facebook',handle:'/vepretski',url:'https://www.facebook.com/vepretski',category:'social',role:l('היסטוריה, פוסטים ורשתות הפצה','History, posts and distribution trails','История, публикации и цепочки распространения'),status:'verified',embed:{src:'https://www.facebook.com/plugins/video.php?href='+encodeURIComponent(fb)+'&show_text=true&width=700',aspect:'video',label:l('וידאו ציבורי חיצוני עם איגור','Public external video featuring Igor','Публичное внешнее видео с Игорем')}},
{id:'linkedin',name:'LinkedIn',handle:'/in/vepretski',url:'https://www.linkedin.com/in/vepretski/',category:'writing',role:l('מנהיגות, StartOn, מערכות וכתיבה מקצועית','Leadership, StartOn, systems and professional writing','Лидерство, StartOn, системы и профессиональные тексты'),status:'dated'},
{id:'linkedin-newsletter',name:'LinkedIn Newsletter',handle:'Long-form writing',url:'https://www.linkedin.com/in/vepretski/recent-activity/articles/',category:'writing',role:l('שכבת הכתיבה המקצועית הארוכה','Professional long-form writing layer','Слой профессиональных длинных текстов'),status:'verified'},
{id:'x',name:'X',handle:'@igorvepretski',url:'https://x.com/igorvepretski',category:'social',role:l('תגובות, חדשות ורעיונות בזמן אמת','Public reactions, news and ideas in real time','Реакции, новости и идеи в реальном времени'),status:'verified'},
{id:'threads',name:'Threads',handle:'@igor.vepretski',url:'https://www.threads.net/@igor.vepretski',category:'social',role:l('מחשבות קצרות ושיחה קהילתית','Short thoughts and community conversation','Короткие мысли и разговор с сообществом'),status:'canonical'},
{id:'telegram',name:'Telegram',handle:'7YA community',url:'https://t.me/+RFNzCZzbCa42MjQ0',category:'community',role:l('ערוץ קשר ישיר מחוץ לאלגוריתם','Direct community route outside feed algorithms','Прямой канал вне алгоритмов ленты'),status:'canonical'},
{id:'spotify',name:'Spotify',handle:'Ido Vepretski',url:'https://open.spotify.com/artist/0fgRoQ6PoCHlVCIr8a5d6u',category:'music',role:l('קטלוג האמן בסטרימינג','Artist streaming catalog','Стриминговый каталог артиста'),status:'verified',embed:{src:'https://open.spotify.com/embed/artist/0fgRoQ6PoCHlVCIr8a5d6u?utm_source=generator',aspect:'audio',label:l('נגן אמן','Artist player','Плеер артиста')}},
{id:'apple-music',name:'Apple Music',handle:'Ido Vepretski',url:'https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he',category:'music',role:l('קטלוג מוזיקה במערכת Apple','Music catalog across Apple Music','Музыкальный каталог Apple Music'),status:'verified',embed:{src:'https://embed.music.apple.com/il/artist/ido-vepretski/1527248864?l=he',aspect:'audio',label:l('נגן אמן','Artist player','Плеер артиста')}},
{id:'soundcloud',name:'SoundCloud',handle:'idovepretski',url:'https://soundcloud.com/idovepretski',category:'music',role:l('הקלטות, סקיצות וארכיון אודיו','Recordings, drafts and audio archive','Записи, наброски и аудиоархив'),status:'verified',embed:{src:'https://w.soundcloud.com/player/?url='+encodeURIComponent('https://soundcloud.com/idovepretski')+'&auto_play=false&show_comments=true&show_user=true',aspect:'audio',label:l('נגן אודיו','Audio player','Аудиоплеер')}},
{id:'youtube-music',name:'YouTube Music',handle:'Ido Vepretski',url:'https://music.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',category:'music',role:l('זהות המוזיקה בתוך YouTube Music','Music identity inside YouTube Music','Музыкальная идентичность в YouTube Music'),status:'verified'},
{id:'medium',name:'Medium',handle:'@igor.vepretski',url:'https://medium.com/@igor.vepretski',category:'writing',role:l('מאמרים באנגלית על מסע והשפעה','English essays on journey and impact','Англоязычные эссе о пути и влиянии'),status:'verified'},
{id:'academia',name:'Academia.edu',handle:'Independent Researcher',url:'https://igorvepretski.academia.edu/',category:'research',role:l('ספריית מחקר עצמאית','Independent research library','Независимая исследовательская библиотека'),status:'verified'},
{id:'zman',name:'זמן ישראל',handle:'Author page',url:'https://www.zman.co.il/writer/20815/',category:'writing',role:l('טורים על הורות, חינוך, רשתות ושייכות','Columns on parenting, education, networks and belonging','Колонки о родительстве, образовании, сетях и принадлежности'),status:'verified'},
{id:'press-tv',name:'Press & Television',handle:'Media room',url:'?page=media',category:'media',role:l('כתבות, אולפנים וראיונות','Articles, studios and interviews','Статьи, студии и интервью'),status:'verified'},
{id:'starton',name:'StartOn',handle:'starton.org.il',url:'https://starton.org.il',category:'community',role:l('המשימה החברתית והבנייה בשטח','Social mission and real-world building','Социальная миссия и работа на месте'),status:'canonical'},
{id:'linktree',name:'Linktree',handle:'igor.vepretski',url:'https://linktr.ee/igor.vepretski',category:'hub',role:l('אינדקס קישורים היסטורי','Historical link index','Исторический индекс ссылок'),status:'verified'},
{id:'izi',name:'IZI',handle:'vepretski',url:'https://www.izi.co.il/site/vepretski',category:'hub',role:l('משטח פרופיל ישראלי נוסף','Additional Israeli profile surface','Дополнительная израильская профильная поверхность'),status:'canonical'},
{id:'wikimedia',name:'Wikimedia Commons',handle:'Open public portrait',url:'https://commons.wikimedia.org/wiki/File:Igor_vepretski-_Israeli_entrepreneur_and_founder_of_Starton_nonprofit_organisation.png',category:'media',role:l('נכס זיהוי פתוח לתקשורת ולמחקר','Open identity asset for media and research','Открытый материал для медиа и исследований'),status:'verified'}
];