'use strict';

const LINKS = {
  identity: { label: 'איגור ופרצקי', href: '/igor-vepretski/' }, journey: { label: 'המסע', href: '/journey/' }, museum: { label: 'הספרייה הציבורית', href: '/museum/' }, create: { label: '7YA Create', href: '/create/' }, starton: { label: 'StartOn', href: '/starton/' }, systems: { label: 'מערכות 7YA', href: '/7ya/' }, evidence: { label: 'Evidence Wall', href: '/evidence/' }, influence: { label: 'מדיה והשפעה', href: '/influence/' }, research: { label: 'מחקר ורעיונות', href: '/research/' }, speaker: { label: 'הרצאות ובמה', href: '/speaker/' }, contact: { label: 'יצירת קשר', href: '/contact/' },
};
const RATE_LIMIT = 18, MAX_MESSAGE_LENGTH = 2400, buckets = new Map();
const anchors = {
  renewal: { title: 'בריאה מחודשת', text: 'היום אינו חייב להמשיך את אתמול. בחרו פעולה אחת שמוכיחה מי אתם רוצים להיות עכשיו.' }, courage: { title: 'גיבור שמתגבר', text: 'אומץ הוא הקטנת הצעד עד שהפחד כבר אינו מנהל את ההחלטה.' }, covenant: { title: 'ברית של מחויבות', text: 'שמרו על בחירה קטנה לאורך שבעה ימים. לא שלמות — נאמנות לכיוון.' }, kindness: { title: 'חסד שמקבל גוף', text: 'כוונה טובה הופכת להשפעה כשהיא פוגשת אדם, צורך, הסכמה ופעולה.' }, truth: { title: 'אמת לפני הגברה', text: 'אל תשנו סיפור כדי שיראו אותו. תנו לאמת צורה חזקה.' },
};
function clientKey(request) { return String(request.headers?.['x-forwarded-for'] || request.socket?.remoteAddress || 'anonymous').split(',')[0].trim().slice(0, 128); }
function withinRateLimit(request) { const key = clientKey(request), now = Date.now(), bucket = buckets.get(key); if (!bucket || now - bucket.startedAt > 60000) { buckets.set(key, { startedAt: now, count: 1 }); return true; } bucket.count += 1; return bucket.count <= RATE_LIMIT; }
function sanitizePath(value) { const path = typeof value === 'string' ? value : '/'; return /^\/[a-z0-9/_-]*$/i.test(path) ? path.slice(0, 180) : '/'; }
function infoAnswer(message) {
  const q = message.toLowerCase();
  if (/ספרי|ארכיון|museum|פוסטים|צילומי מסך/.test(q)) return { answer: 'הספרייה מחברת את ליבת 66 הרשומות, Public Universe ושכבת Drive פורנזית. כל פריט מסומן כמקור, thumbnail, צילום קיים או צילום בהמתנה.', links: [LINKS.museum, LINKS.influence, LINKS.evidence] };
  if (/starton|נוער|youth|מרחב/.test(q)) return { answer: 'StartOn הוא החזון החברתי של איגור למרחבי טכנולוגיה, יצירה ושייכות לנוער. האתר מפריד בין מודל, פיילוט, מקור ותוצאה.', links: [LINKS.starton, LINKS.evidence, LINKS.contact] };
  if (/ראי|evidence|proof|מקור|אימות/.test(q)) return { answer: 'Evidence Wall מפריד בין VERIFIED, DOCUMENTED, SOURCE PENDING ו־PRIVATE. קישור אינו מוכיח אוטומטית היקף או תוצאה.', links: [LINKS.evidence, LINKS.museum] };
  if (/מערכ|system|oracle|ledger|merkle|radar/.test(q)) return { answer: '7YA מארגנת זהות, תוכן, ראיות, AI ופעולה. איגור הוא הליבה האנושית, StartOn היא השליחות והספרייה היא הזיכרון.', links: [LINKS.systems, LINKS.evidence, LINKS.create] };
  if (/יציר|פוסט|וידאו|מטרה|הגשמ|תקוע|פחד/.test(q)) return { answer: '7YA Create הוא אח גדול דיגיטלי שמתרגם כוונה למצפן, 15 דקות, שבעה ימים וחבילת פלטפורמות. הוא אינו איגור ואינו מבטיח הצלחה.', links: [LINKS.create, LINKS.museum, LINKS.evidence] };
  if (/מחקר|supernoah|gastocratic/.test(q)) return { answer: 'שכבת המחקר מציגה מסגרות עצמאיות עם גילוי נאות. SUPERNOAH מוצג כ־preprint שלא עבר ביקורת עמיתים.', links: [LINKS.research, LINKS.evidence] };
  if (/איגור|igor|מסע|ביוגר/.test(q)) return { answer: 'איגור ופרצקי הוא יזם חברתי, יוצר ובונה מערכות ציבוריות. 7YA מחבר את המסע, StartOn, המדיה והראיות.', links: [LINKS.identity, LINKS.journey, LINKS.museum] };
  if (/הרצאה|ראיון|speaker|contact|פאנל/.test(q)) return { answer: 'להרצאה, ראיון, פאנל או שותפות עברו לעמוד הבמה או ליצירת קשר.', links: [LINKS.speaker, LINKS.contact] };
  return { answer: 'אני מדריך 7YA. אפשר לשאול על איגור, הספרייה, StartOn, יצירה, מחקר, ראיות או מדיה.', links: [LINKS.create, LINKS.museum, LINKS.evidence] };
}
function anchorFor(q, mode) { if (/פחד|ביקורת|תקוע|אומץ/.test(q) || mode === 'momentum') return anchors.courage; if (/לעזור|קהיל|נוער|חסד|השפעה/.test(q) || mode === 'impact') return anchors.kindness; if (/מחויב|הרגל|שבוע|ברית/.test(q)) return anchors.covenant; if (/מקור|עובדה|ראיה|אמת|טענה|מספר/.test(q)) return anchors.truth; return anchors.renewal; }
function platformPack(goal, hook, angle) { return [
  { platform: 'TikTok', role: 'עצירה', rule: 'Hook, סצנה ופעולה ב־20–35 שניות.', draft: `${hook}\n[סצנה] → [שינוי] → [פעולה]` }, { platform: 'Instagram', role: 'חוויה', rule: 'Reel או carousel עם הקשר.', draft: `Slide 1: ${hook}\nרגע → מתח → בחירה → משמעות\nCaption: ${angle}` }, { platform: 'Facebook', role: 'שיחה', rule: 'סיפור מלא וקהילה.', draft: `${hook}\n\nרגע → בחירה → משמעות → שאלה.` }, { platform: 'LinkedIn', role: 'משמעות מקצועית', rule: 'בעיה, תהליך, לקח ומקור.', draft: `${goal}\nבעיה → תהליך → לקח → מקור.` }, { platform: 'YouTube', role: 'עומק וזיכרון', rule: 'וידאו או שיחה מלאה.', draft: `כותרת: ${goal}\nפתיחה: ${hook}\nסיפור → הבנה → צעד.` }, { platform: 'X / Threads', role: 'רעיון חד', rule: 'טענה, גבול ומקור.', draft: `${hook} ${angle} [מקור]` },
]; }
function localCreatorCoach(message, creatorMode = 'clarify') {
  const text = message.trim(), q = text.toLowerCase(), isBlocked = /פחד|חושש|תקוע|מחסום|ביקורת/.test(q), isImpact = /לעזור|קהיל|נוער|חברתי|השפעה|מיזם/.test(q), isVideo = /וידאו|סרטון|reel|tiktok|youtube/.test(q), isArchive = /ארכיון|ספרייה|מקור של איגור|עבר/.test(q), isTech = /nvidia|microsoft|openai|github|ai|טכנולוג/.test(q), goal = text.split(/[.!?\n]/).find(Boolean)?.trim() || 'להפוך כוונה לכיוון ולצעד.';
  let reflection = 'יש כאן משהו אמיתי שמבקש צורה. לא פותרים הכול; בוחרים את הכיוון הבא.', next_step = 'השלימו: “אחרי הצעד הזה אדם אחד יוכל להבין, להרגיש או לעשות ___”.', fifteen_minutes = 'הפעילו טיימר ל־15 דקות, הקליטו קול חופשי והוציאו משפט אחד שאי אפשר לזייף.', today = 'צרו טיוטה אחת ושמרו אותה עם תאריך.', hook = 'יש רגע שבו מפסיקים לחכות לאישור ומתחילים לבנות.', angle = 'סיפור קצר שמוביל לבחירה מעשית.', outline = ['רגע', 'חסר', 'בחירה', 'פעולה'], links = [LINKS.museum, LINKS.influence, LINKS.evidence]; const evidence_notes = [];
  if (isBlocked || creatorMode === 'momentum') { reflection = 'הביקורת קיבלה זכות וטו לפני שהיצירה נולדה. מחזירים שליטה דרך ניסוי קטן.'; next_step = 'כתבו גרסה פרטית של 120 מילים שאסור לפרסם.'; fifteen_minutes = 'כתבו עשר דקות ללא מחיקה וסמנו משפט אחד ששווה להציל.'; hook = 'כמעט לא פרסמתי את זה — לא כי אין לי מה לומר, אלא כי ידעתי שתהיה ביקורת.'; angle = 'פחד → גבול → פעולה.'; }
  if (isVideo) { next_step = 'צלמו 25 שניות: Hook, דוגמה ופעולה.'; fifteen_minutes = 'צלמו שלוש גרסאות קצרות ואל תערכו.'; outline = ['0–3 עצירה', '3–12 מה קרה', '12–20 הבנה', '20–30 פעולה']; }
  if (isImpact || creatorMode === 'impact') { reflection = 'השפעה מתחילה באדם אחד ובצורך מאומת — לא בכלי.'; next_step = 'השלימו: “אני רוצה לעזור ל___ שמתמודד/ת עם ___ באמצעות ניסוי של ___”.'; fifteen_minutes = 'כתבו שלוש שאלות אימות וקיימו שיחה אחת לפני פתרון.'; today = 'אמתו מה ייחשב שיפור מבחינת האדם עצמו.'; hook = 'טכנולוגיה לא עושה טוב מעצמה. אנשים בוחרים איזו בעיה היא תשרת.'; angle = 'אדם → צורך → ניסוי → למידה.'; links = [LINKS.starton, LINKS.evidence, LINKS.contact]; evidence_notes.push('רצון טוב אינו הוכחת השפעה. תעדו גם תוצאה שלא הצליחה.'); }
  if (isArchive) { reflection = 'העבר אינו מחסן. הוא חומר גלם — עם קרדיט, הקשר ותאריך.'; next_step = 'בחרו מקור מהספרייה וכתבו מה הוא מלמד היום, בלי לחקות את איגור.'; fifteen_minutes = 'פתחו את /museum/ ורשמו: מקור, רגע, עיקרון ופעולה.'; hook = 'הפוסט נכתב בעבר, אבל השאלה עדיין חיה.'; angle = 'מקור → משמעות → פעולה.'; }
  if (isTech) evidence_notes.push('גישה לכלי או תוכנית אינה שותפות רשמית. תנו קרדיט וציינו סטטוס לפי תיעוד.'); if (/\d/.test(text)) evidence_notes.push('כל מספר ציבורי צריך מקור ותאריך observation.');
  const seven_day_path = ['יום 1 — מצפן.', 'יום 2 — אמת.', `יום 3 — חומר: ${fifteen_minutes}`, 'יום 4 — טיוטה.', 'יום 5 — מראה מאדם אמין.', 'יום 6 — פרסום במקום אחד.', 'יום 7 — תיעוד ותיקון.'];
  return { reflection, compass: { north: goal, why: isImpact ? 'להועיל באופן שניתן ללמוד ממנו.' : 'לתת לקול אמיתי צורה שמובילה לפעולה.', boundary: isImpact ? 'לא להבטיח תוצאה לפני ניסוי.' : 'לא לשנות אמת כדי להשיג תשומת לב.' }, spiritual_anchor: anchorFor(q, creatorMode), goal, next_step, fifteen_minutes, today, this_week: 'השלימו גרסה, הראו לאדם אחד, פרסמו במקום אחד ותעדו למידה.', seven_day_path, content_seed: { hook, angle, outline }, platform_pack: platformPack(goal, hook, angle), evidence_notes, handoffs: ['gmail','calendar','notion','github','download'].map(id => ({ id, status: 'user-confirmed-handoff' })), credits: [{ role: 'Creator', name: 'The visitor' }, { role: 'Method', name: 'Igor Vepretski / 7YA' }, { role: 'System', name: '7YA Create' }], links, mode: 'local-coach', generated_at: new Date().toISOString() };
}
function creatorInstructions() { return ['You are 7YA Big Brother, a positive and practical creator companion.','The experience is shaped by the public method and work of Igor Vepretski, but you are not Igor.','Act like a steady older brother: listen, encourage action, set boundaries and reduce the next step.','Return a compass, spiritual anchor, fifteen-minute action, seven-day path and platform pack.','Use spiritual ideas only as metaphors for renewal, courage, commitment, kindness and truth. Never claim divine certainty, prophecy or religious authority.','For impact start with one beneficiary and one validated need, consent, privacy and a human signal.','Do not diagnose mental health conditions. Never claim to be Igor Vepretski or speak on his behalf.','Never invent achievements, metrics, partners, roles, dates or outcomes.','Handoffs are web or clipboard handoffs, not direct OAuth writes.','Return only JSON with reflection, compass, spiritual_anchor, goal, next_step, fifteen_minutes, today, this_week, seven_day_path, content_seed, platform_pack, evidence_notes, handoffs, credits, links, mode and generated_at.'].join(' '); }
function guideInstructions() { return 'You are 7YA AI, the public guide for Igor Vepretski, StartOn and 7YA. Never claim to be Igor, invent facts or reveal private data. People are the mission; AI is a tool; evidence comes first.'; }
function cleanJson(text) { const parsed = JSON.parse(String(text || '').replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim()); if (!parsed?.next_step || !parsed?.compass || !parsed?.spiritual_anchor) throw new Error('Creator JSON missing rich contract'); return parsed; }
async function timed(task) { const controller = new AbortController(), timeout = setTimeout(() => controller.abort(), 18000); try { return await task(controller.signal); } finally { clearTimeout(timeout); } }
async function callNvidia(context) { const key = process.env.NVIDIA_API_KEY || process.env.NVIDIA_NIM_API_KEY; if (!key) return null; const model = process.env.NVIDIA_MODEL || 'nvidia/nemotron-3-nano-30b-a3b'; const text = await timed(async signal => { const response = await fetch('https://integrate.api.nvidia.com/v1/chat/completions', { method: 'POST', signal, headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model, messages: [{ role: 'system', content: context.mode === 'creator' ? creatorInstructions() : guideInstructions() }, { role: 'user', content: `Route: ${context.currentPath}\nMode: ${context.creatorMode}\nVisitor: ${context.message}` }], temperature: .25, max_tokens: context.mode === 'creator' ? 1400 : 500 }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || response.status); return data?.choices?.[0]?.message?.content?.trim(); }); return text ? { text, provider: 'nvidia', model } : null; }
async function callOpenAI(context) { if (!process.env.OPENAI_API_KEY) return null; const model = process.env.OPENAI_MODEL || 'gpt-5.6'; const text = await timed(async signal => { const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', signal, headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model, store: false, instructions: context.mode === 'creator' ? creatorInstructions() : guideInstructions(), input: `Route: ${context.currentPath}\nMode: ${context.creatorMode}\nVisitor: ${context.message}`, max_output_tokens: context.mode === 'creator' ? 1300 : 480 }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || response.status); if (data.output_text) return data.output_text.trim(); return (data.output || []).flatMap(item => item.content || []).find(item => item.type === 'output_text')?.text?.trim(); }); return text ? { text, provider: 'openai', model } : null; }
async function callProvider(context) { const order = String(process.env.AI_PROVIDER_ORDER || 'nvidia,openai').split(',').map(x => x.trim()); for (const name of order) { try { const result = name === 'openai' ? await callOpenAI(context) : name === 'nvidia' ? await callNvidia(context) : null; if (result) return result; } catch (error) { console.error(`7YA AI ${name} fallback`, error.message); } } return null; }
module.exports = async (request, response) => {
  response.setHeader('Content-Type', 'application/json; charset=utf-8'); response.setHeader('Cache-Control', 'no-store'); response.setHeader('X-Content-Type-Options', 'nosniff');
  if (request.method !== 'POST') { response.statusCode = 405; response.end(JSON.stringify({ error: 'Method Not Allowed' })); return; }
  if (!withinRateLimit(request)) { response.statusCode = 429; response.end(JSON.stringify({ error: 'Too many requests' })); return; }
  const message = typeof request.body?.message === 'string' ? request.body.message.trim() : '', currentPath = sanitizePath(request.body?.path), mode = request.body?.mode === 'creator' ? 'creator' : 'guide', creatorMode = ['clarify', 'create', 'momentum', 'impact'].includes(request.body?.creator_mode) ? request.body.creator_mode : 'clarify';
  if (!message || message.length > MAX_MESSAGE_LENGTH) { response.statusCode = 422; response.end(JSON.stringify({ error: `message must be 1-${MAX_MESSAGE_LENGTH} characters` })); return; }
  const fallback = mode === 'creator' ? localCreatorCoach(message, creatorMode) : { ...infoAnswer(message), mode: 'local-evidence-guide' }, result = await callProvider({ message, currentPath, mode, creatorMode });
  if (!result) { response.end(JSON.stringify({ ...fallback, provider: 'local', model: mode === 'creator' ? 'deterministic-big-brother-v2' : 'deterministic-evidence-guide' })); return; }
  try { if (mode === 'creator') { const parsed = cleanJson(result.text); response.end(JSON.stringify({ ...fallback, ...parsed, handoffs: fallback.handoffs, credits: fallback.credits, links: fallback.links, mode: `${result.provider}-big-brother-creator`, provider: result.provider, model: result.model, generated_at: new Date().toISOString() })); } else response.end(JSON.stringify({ answer: result.text, links: fallback.links, mode: `${result.provider}-guide`, provider: result.provider, model: result.model })); }
  catch (error) { console.error('7YA AI response contract fallback', error.message); response.end(JSON.stringify({ ...fallback, provider: 'local', model: 'deterministic-big-brother-v2' })); }
};
