import type {SyntheticEvent} from 'react';
import {ExternalLink} from 'lucide-react';
import {useLocale} from '../locale';
import './personal-archive.css';
type Local={he:string;en:string;ru:string};type Frame={id:string;label:string;image:string;focus:string;source:string;href:string;body:Local};
const L=(he:string,en:string,ru:string):Local=>({he,en,ru});const thumb=(id:string)=>`https://drive.google.com/thumbnail?id=${id}&sz=w1800`;
const frames:Frame[]=[
{id:'quiet',label:'QUIET',image:thumb('1Q4wmnXQ5YXqvvyfeZVGSYsXQXQ-tVi8T'),focus:'50% 42%',source:'PUBLIC INSTAGRAM RETROSPECTIVE · POSTED 28.10.2024 · CAPTURE DATE UNASSERTED',href:'https://drive.google.com/file/d/1Q4wmnXQ5YXqvvyfeZVGSYsXQXQ-tVi8T/view',body:L('לפני תפקידים, כותרות ומערכות — יש אדם. הפריים הזה מתוך “My - 20’s” נשאר כאן דווקא משום שהוא לא מנסה להוכיח כלום: רגע שקט מתוך החיים עצמם.','Before titles, institutions and public roles, there is a person. This frame from “My - 20’s” stays precisely because it is not trying to prove anything: a quiet lived moment.','До должностей, заголовков и систем есть человек. Этот кадр из «My - 20’s» остаётся именно потому, что ничего не пытается доказать: тихий момент реальной жизни.')},
{id:'service',label:'SERVICE',image:thumb('1LgFem3q4jOmCBHHFblkL4QVu8W4mbbte'),focus:'50% 32%',source:'PUBLIC INSTAGRAM ARCHIVE · SERVICE / FIELD · RETROSPECTIVE POST 27.08.2025',href:'https://drive.google.com/file/d/1LgFem3q4jOmCBHHFblkL4QVu8W4mbbte/view',body:L('השירות והשטח נתנו לכאוס מסגרת. זה צילום אמיתי שחזר בפוסט רטרוספקטיבי על שנות המשטרה — לא תמונת תדמית שנבנתה בדיעבד ולא תאריך צילום מומצא.','Service and field work gave structure to chaos. This is an authentic photograph resurfaced in a retrospective post about the police years — not a later brand image and not an invented capture date.','Служба и поле дали хаосу структуру. Это подлинная фотография, вернувшаяся в ретроспективном посте о годах в полиции — не поздний имиджевый кадр и не выдуманная дата съёмки.')},
{id:'return',label:'RETURN',image:'https://pic1.yitweb.co.il/cdn-cgi/image/f%3Dauto%2Cw%3D1200%2Cq%3D85/picserver/mynet/crop_images/2022/05/11/r1F0NeKU9/r1F0NeKU9_0_0_640_360_0_large.jpg',focus:'50% 50%',source:'PUBLIC PRESS PHOTO · MYNET · 13.05.2022',href:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',body:L('החזרה לג׳סי כהן היא הציר שמחבר ילדות לעשייה. כאן הסיפור כבר יוצא מהזיכרון הפרטי ונכנס למקור עיתונאי: לחזור למקום שממנו באתי ולנסות לבנות בו הזדמנות שלא הייתה לי.','The return to Jesse Cohen connects childhood to action. Here the story leaves private memory and enters a public press record: return to where I came from and try to build an opportunity I did not have.','Возвращение в Джесси Коэн соединяет детство с действием. Здесь история выходит из личной памяти в публичную прессу: вернуться туда, откуда я пришёл, и попытаться построить возможность, которой у меня не было.')},
{id:'voice',label:'VOICE',image:thumb('1M1LCw-9IqVLcf0dkF-2MaJhaHmPkqvvw'),focus:'50% 36%',source:'PUBLIC INSTAGRAM PHOTO · PUBLIC LIFE / POLITICAL WORK · POSTED 05.11.2024',href:'https://drive.google.com/file/d/1M1LCw-9IqVLcf0dkF-2MaJhaHmPkqvvw/view',body:L('הקול הציבורי אינו שכבה נפרדת מהחיים. הוא גדל מתוך השירות, הכעס, השאלות והניסיון להזיז מערכות — ואז נכנס גם למרחב הציבורי והפוליטי. כאן מוצג תיעוד אמיתי, בלי להמציא אירוע שאינו מתועד.','Public voice is not separate from the life behind it. It grew from service, anger, questions and attempts to move systems — then entered civic and political space. This is authentic public-life documentation without inventing an event that is not documented.','Публичный голос не отделён от прожитой жизни. Он вырос из службы, злости, вопросов и попыток двигать системы — а затем вошёл в общественное и политическое пространство. Здесь показан реальный документальный кадр без выдуманного события.')},
{id:'create',label:'CREATE',image:'https://i.ytimg.com/vi/jRjZjpqAgEw/hqdefault.jpg',focus:'50% 50%',source:'OFFICIAL VIDEO FRAME · NAWAN FT. VEPRETSKI — BIZZI · YOUTUBE · 2025',href:'https://www.youtube.com/watch?v=jRjZjpqAgEw',body:L('גם היצירה היא ביוגרפיה. מוזיקה, קליפים, הומור ושיתופי פעולה הם הדרך שבה חלקים אחרים בי יוצאים החוצה — לא נספח שמסתתר בתחתית אתר “רציני”.','Creation is biography too. Music, videos, humour and collaborations are how other parts of me move outward — not an appendix buried under a “serious” public profile.','Творчество — тоже биография. Музыка, клипы, юмор и коллаборации выводят наружу другие части меня — это не приложение, спрятанное под «серьёзным» публичным профилем.')},
{id:'now',label:'NOW',image:thumb('1n8eFERhkuHB_7StwJk74e6xDpDSdIzb2'),focus:'50% 42%',source:'PUBLIC INSTAGRAM PHOTO · IN BETWEEN ALARMS · 19.07.2025',href:'https://drive.google.com/file/d/1n8eFERhkuHB_7StwJk74e6xDpDSdIzb2/view',body:L('הסיפור עדיין לא סגור. החיים ממשיכים להיכנס ל־7YA בזמן אמת — עבודה, משפחה, יצירה, עשייה ציבורית, מחקר, טעויות ותיקונים. הפריים הזה הוא גשר להווה, לא טענה שהוא צולם היום.','The story is still open. Life keeps entering 7YA in real time — work, family, creation, public action, research, mistakes and corrections. This frame bridges into the present; it is not presented as a photograph taken today.','История ещё не закрыта. Жизнь продолжает входить в 7YA в реальном времени — работа, семья, творчество, общественная деятельность, исследования, ошибки и исправления. Этот кадр ведёт к настоящему, но не выдаётся за сегодняшнюю фотографию.')}];
const copy={he:{title:'שישה פריימים. אותו אדם, בלי לקצר אותו לתפקיד אחד.',body:'הפתיחה עכשיו עוברת בכוונה בין חיים שקטים, שירות, החזרה לג׳סי כהן, קול ציבורי, יצירה וההווה. כל פריים הוא מקור אמיתי אחר; אין תמונת סטוק, אין אדם חלופי ואין ניסיון להפוך רגע אחד לכל הזהות.',source:'למקור הציבורי',note:'DISTINCT SOURCES · DATES ASSERTED ONLY WHERE DOCUMENTED'},en:{title:'Six frames. One person, without reducing him to one role.',body:'The opening deliberately moves through quiet life, service, the return to Jesse Cohen, public voice, creation and the present. Every frame is a different real source; no stock portrait, substitute person or single moment stands in for the whole identity.',source:'Public source',note:'DISTINCT SOURCES · DATES ASSERTED ONLY WHERE DOCUMENTED'},ru:{title:'Шесть кадров. Один человек — не сведённый к одной роли.',body:'Начало намеренно проходит через тихую жизнь, службу, возвращение в Джесси Коэн, публичный голос, творчество и настоящее. Каждый кадр — отдельный реальный источник; без стока, чужого лица и попытки превратить один момент во всю идентичность.',source:'Публичный источник',note:'DISTINCT SOURCES · DATES ASSERTED ONLY WHERE DOCUMENTED'}} as const;
const fail=(e:SyntheticEvent<HTMLImageElement>)=>{e.currentTarget.hidden=true;e.currentTarget.parentElement?.classList.add('pa-failed')};
export default function PersonalArchive(){const {locale}=useLocale();const c=copy[locale];const total=String(frames.length).padStart(2,'0');return <section className='pa' id='personal-memory' aria-labelledby='pa-title'><header className='pa-head'><p className='pa-marker' dir='ltr'>OPENING IDENTITY · 06 DISTINCT REAL FRAMES</p><h2 id='pa-title'>{c.title}</h2><div><p>{c.body}</p><small dir='ltr'>{c.note}</small></div></header><div className='pa-flow'>{frames.map((frame,index)=><article className='pa-frame' data-personal-frame={frame.id} key={frame.id}><figure><div className='pa-fallback'><b>{String(index+1).padStart(2,'0')}</b><strong>{frame.label}</strong><span>{frame.source}</span></div><img src={frame.image} alt={`${frame.label} · Igor Vepretski`} loading={index<2?'eager':'lazy'} decoding='async' referrerPolicy='no-referrer' style={{objectPosition:frame.focus}} onError={fail}/></figure><div className='pa-copy'><div className='pa-no'><span>{String(index+1).padStart(2,'0')} / {total}</span><b dir='ltr'>{frame.label}</b></div><p>{frame.body[locale]}</p><small dir='ltr'>{frame.source}</small><a href={frame.href} target='_blank' rel='noreferrer'>{c.source}<ExternalLink/></a></div></article>)}</div></section>}
