const routes=require('../routes.json');
const portrait='https://raw.githubusercontent.com/7guard-io/7ya.io/main/assets/igor-home-portrait-20260712.jpg';
const nav=[['/','בית'],['/igor-vepretski/','איגור'],['/journey/','המסע'],['/starton/','StartOn'],['/evidence/','ראיות'],['/speaker/','במה'],['/contact/','קשר']];
const esc=v=>String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function pathOf(v){let p=String(v||'/');if(!p.startsWith('/'))p='/'+p;if(p!=='/'&&!p.endsWith('/'))p+='/';return p}
function navigation(path){return nav.map(([h,l])=>`<a href="${h}"${h===path?' aria-current="page"':''}>${esc(l)}</a>`).join('')}
function cards(items){return items.map(([s,t],i)=>`<a class="card" href="${i===0?'/journey/':i===1?'/starton/':'/evidence/'}"><div><span>${esc(s)}</span><b>0${i+1}</b></div><h2>${esc(t)}</h2><p>מהרעיון אל פעולה שאפשר לבדוק.</p></a>`).join('')}
function page(path,data){const home=path==='/';const canonical='https://7ya.io'+path;const title=home?'<span>FIX THE WORLD</span><em>WITH AI.</em>':esc(data.heading);return `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(data.title)}</title><meta name="description" content="${esc(data.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="theme-color" content="#050505"><meta name="7ya-release" content="2026-07-14.3-ai"><link rel="canonical" href="${canonical}"><link rel="stylesheet" href="/site.css"><meta property="og:type" content="profile"><meta property="og:site_name" content="7YA.IO"><meta property="og:title" content="${esc(data.title)}"><meta property="og:description" content="${esc(data.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${portrait}"><meta name="twitter:card" content="summary_large_image"></head><body data-route="${path}" class="${home?'is-home':''}"><a class="skip" href="#main">דלג לתוכן</a><header><a class="brand" href="/"><span>7</span><b>IGOR VEPRETSKI</b></a><nav>${navigation(path)}</nav><button class="ai-top" type="button" data-open-ai>ASK 7YA AI</button></header><main id="main"><section class="hero ${home?'home-hero':'inner-hero'}"><figure class="portrait"><img src="${portrait}" alt="איגור ופרצקי" width="1600" height="1600" fetchpriority="high"></figure><div class="hero-shade"></div><div class="copy"><p class="eyebrow">${esc(data.eyebrow)}</p><h1>${title}</h1><p class="lead">${esc(data.lead)}</p><div class="actions"><button class="primary" type="button" data-open-ai>דברו עם 7YA AI</button><a href="${home?'/journey/':'/evidence/'}">${home?'המסע שלי':'לראיות'}</a></div><div class="signal"><i></i><span>HUMAN FIRST · AI FOR REAL-WORLD IMPACT</span></div></div><div class="mission-rail">IGOR × AI × ACTION</div></section><section class="statement"><p>AI IS NOT THE HERO.</p><h2>PEOPLE ARE.</h2><span>הטכנולוגיה היא מכפיל כוח. המשימה היא אנושית.</span></section><section class="map"><div class="map-head"><small>THE PUBLIC SYSTEM</small><h2>${home?'שלושה יעדים. משימה אחת.':'מקורות, הקשר ופעולה.'}</h2></div><div class="cards">${cards(data.cards)}</div></section><section class="final"><small>FIX THE WORLD WITH AI</small><h2>לא מחכים לעתיד.<br>בונים אותו.</h2><button type="button" data-open-ai>התחילו שיחה</button></section></main><footer><b>IGOR VEPRETSKI / 7YA.IO</b><span>Release 2026-07-14.3-ai</span></footer><script src="/ai-guide.js" defer></script></body></html>`}
module.exports=(req,res)=>{const path=pathOf(req.query.route||'/');const data=routes[path];res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, must-revalidate');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Robots-Tag',data?'index, follow':'noindex');res.statusCode=data?200:404;res.end(data?page(path,data):'<!doctype html><html><head><meta name="robots" content="noindex"><title>404</title></head><body><h1>404</h1></body></html>')};
