import type {CanonicalEvent} from './canonical-corpus';

export const DIGITAL_COMPENDIUM_RELEASE='DIGITAL-COMPENDIUM-20260909-1';
export const DIGITAL_COMPENDIUM_CONTRACT='7ya-digital-compendium-public-v1';
export type CompendiumPublicSafety='PUBLIC_SAFE'|'RESTRICTED'|'PRIVATE';
export type CompendiumMetric={metricType:string;value:number|string;unit:string;snapshotDate:string;sourceId:string};
export type CompendiumSource={id:string;title:string;sourceType:string;platform:string;url:string;verificationStatus:string;publicSafety:CompendiumPublicSafety};
export type CompendiumActivity={id:string;recordType:'activity';activityType:string;title:string;startDate:string;entity:string;project:string;sourceIds:string[];contentIds:string[];assetIds:string[];publicSafety:CompendiumPublicSafety;verificationStatus:string;metrics?:CompendiumMetric[]};
export type CompendiumContent={id:string;recordType:'content';title:string;contentType:string;language:string;createdDate:string;author:string;originalPlatform:string;originalUrl:string;nativePlatformId:string;sourceIds:string[];activityIds:string[];assetIds:string[];rights:string;publicSafety:CompendiumPublicSafety;verificationStatus:string;canonicalStatus:string;metrics?:CompendiumMetric[]};
export type CompendiumAsset={id:string;recordType:'asset';assetType:string;originalLocation:string;platformFileId:string;canonicalUrl:string;sourceIds:string[];activityIds:string[];project:string;rights:string;publicSafety:CompendiumPublicSafety;verificationStatus:string;metrics?:CompendiumMetric[]};
export type CompendiumRelation={id:string;recordType:'relation';subjectId:string;predicate:string;objectId:string;sourceIds:string[];publicSafety:CompendiumPublicSafety;verificationStatus:string;confidence:string};
export type DigitalCompendiumSnapshot={contract:string;release:string;schemaVersion:number;status:'VERIFIED_READBACK';generatedAt:string;authorities:{narrative:string;catalog:string;publicProjection:string};sourceLedger:{spreadsheetId:string;sourceSystem:string;ingestionId:string};sources:CompendiumSource[];activities:CompendiumActivity[];content:CompendiumContent[];assets:CompendiumAsset[];relations:CompendiumRelation[]};

const isObject=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const text=(value:unknown,max=2400)=>typeof value==='string'&&value.trim().length>0&&value.length<=max;
const httpsUrl=(value:string)=>{try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password}catch{return false}};
const stableId=(value:string,prefix:string)=>new RegExp('^'+prefix+'-[A-Z0-9-]+$').test(value);
const blockedVerification=(value:string)=>/VERIFY_BEFORE_PUBLISHING|QUARANTIN|CONTRADICTED/i.test(value);
const assertMetrics=(metrics:CompendiumMetric[]|undefined,sourceIds:Set<string>,recordId:string)=>{for(const metric of metrics||[]){if(!text(metric.metricType,120)||!text(metric.unit,80)||!text(metric.snapshotDate,32)||!text(metric.sourceId,120)||!sourceIds.has(metric.sourceId))throw new Error('invalid dated metric provenance: '+recordId)}};
const assertPublishable=(record:{id:string;publicSafety:CompendiumPublicSafety;verificationStatus:string;sourceIds:string[];metrics?:CompendiumMetric[]},sourceIds:Set<string>)=>{if(record.publicSafety!=='PUBLIC_SAFE')throw new Error('public projection requires PUBLIC_SAFE: '+record.id);if(!text(record.verificationStatus,120)||blockedVerification(record.verificationStatus))throw new Error('record is not publish-compatible: '+record.id);if(!Array.isArray(record.sourceIds)||record.sourceIds.length<1||record.sourceIds.some(id=>!sourceIds.has(id)))throw new Error('public projection requires valid provenance: '+record.id);assertMetrics(record.metrics,sourceIds,record.id)};

export function validateDigitalCompendiumSnapshot(value:unknown):DigitalCompendiumSnapshot{if(!isObject(value))throw new Error('digital compendium snapshot must be an object');const snapshot=JSON.parse(JSON.stringify(value)) as DigitalCompendiumSnapshot;if(snapshot.contract!==DIGITAL_COMPENDIUM_CONTRACT||snapshot.release!==DIGITAL_COMPENDIUM_RELEASE||snapshot.schemaVersion!==1||snapshot.status!=='VERIFIED_READBACK')throw new Error('invalid digital compendium contract');if(!Array.isArray(snapshot.sources)||!Array.isArray(snapshot.activities)||!Array.isArray(snapshot.content)||!Array.isArray(snapshot.assets)||!Array.isArray(snapshot.relations))throw new Error('digital compendium collections required');const sourceIds=new Set<string>();for(const source of snapshot.sources){if(!stableId(source.id,'SRC')||!text(source.title,500)||!httpsUrl(source.url)||source.publicSafety!=='PUBLIC_SAFE'||blockedVerification(source.verificationStatus))throw new Error('invalid public compendium source: '+source.id);if(sourceIds.has(source.id))throw new Error('duplicate source id: '+source.id);sourceIds.add(source.id)}const objectIds=new Set<string>(sourceIds);for(const record of snapshot.activities){if(!stableId(record.id,'ACT')||record.recordType!=='activity'||!text(record.title,500)||!text(record.startDate,32))throw new Error('invalid activity: '+record.id);assertPublishable(record,sourceIds);if(objectIds.has(record.id))throw new Error('duplicate object id: '+record.id);objectIds.add(record.id)}for(const record of snapshot.content){if(!stableId(record.id,'CNT')||record.recordType!=='content'||!text(record.title,500)||!httpsUrl(record.originalUrl)||!text(record.createdDate,32))throw new Error('invalid content: '+record.id);assertPublishable(record,sourceIds);if(objectIds.has(record.id))throw new Error('duplicate object id: '+record.id);objectIds.add(record.id)}for(const record of snapshot.assets){if(!stableId(record.id,'AST')||record.recordType!=='asset'||!httpsUrl(record.canonicalUrl)||!httpsUrl(record.originalLocation))throw new Error('invalid asset: '+record.id);assertPublishable(record,sourceIds);if(objectIds.has(record.id))throw new Error('duplicate object id: '+record.id);objectIds.add(record.id)}for(const relation of snapshot.relations){if(!stableId(relation.id,'REL')||relation.recordType!=='relation'||relation.publicSafety!=='PUBLIC_SAFE'||blockedVerification(relation.verificationStatus)||!Array.isArray(relation.sourceIds)||relation.sourceIds.length<1||relation.sourceIds.some(id=>!sourceIds.has(id))||!objectIds.has(relation.subjectId)||!objectIds.has(relation.objectId)||!text(relation.predicate,120))throw new Error('invalid relation: '+relation.id);if(objectIds.has(relation.id))throw new Error('duplicate object id: '+relation.id);objectIds.add(relation.id)}return snapshot}

const seed:DigitalCompendiumSnapshot={contract:DIGITAL_COMPENDIUM_CONTRACT,release:DIGITAL_COMPENDIUM_RELEASE,schemaVersion:1,status:'VERIFIED_READBACK',generatedAt:'2026-09-09T00:00:00+03:00',authorities:{narrative:'IGOR VEPRETSKI — MASTER CANON v1.0 — LIVING SOURCE OF TRUTH',catalog:'IGOR VEPRETSKI — MASTER EVIDENCE LEDGER v1.0',publicProjection:'7ya.io / AppDeploy validated projection'},sourceLedger:{spreadsheetId:'1GTqVhy8iLGW6tvM5wwwso5hFd3JcA6iKz1GYX0CEF3I',sourceSystem:'MASTER_EVIDENCE_LEDGER',ingestionId:'ING-20260909-001'},sources:[{id:'SRC-006',title:'Personal interview — StartOn origin story',sourceType:'Autobiographical video',platform:'YouTube',url:'https://www.youtube.com/watch?v=hDcKJ46PBJ4',verificationStatus:'VERIFIED_PUBLIC_SOURCE',publicSafety:'PUBLIC_SAFE'}],activities:[{id:'ACT-2022-000001',recordType:'activity',activityType:'INTERVIEW',title:'Personal interview — StartOn origin story',startDate:'2022-09-09',entity:'Igor Vepretski',project:'StartOn',sourceIds:['SRC-006'],contentIds:['CNT-000001'],assetIds:['AST-000001'],publicSafety:'PUBLIC_SAFE',verificationStatus:'VERIFIED_PUBLIC_SOURCE'}],content:[{id:'CNT-000001',recordType:'content',title:'Personal interview — StartOn origin story',contentType:'VIDEO',language:'HE',createdDate:'2022-09-09',author:'Igor Vepretski',originalPlatform:'YouTube',originalUrl:'https://www.youtube.com/watch?v=hDcKJ46PBJ4',nativePlatformId:'hDcKJ46PBJ4',sourceIds:['SRC-006'],activityIds:['ACT-2022-000001'],assetIds:['AST-000001'],rights:'OWNED_SURFACE_PUBLIC',publicSafety:'PUBLIC_SAFE',verificationStatus:'VERIFIED_PUBLIC_SOURCE',canonicalStatus:'CANONICAL_SEED'}],assets:[{id:'AST-000001',recordType:'asset',assetType:'VIDEO_REMOTE',originalLocation:'https://www.youtube.com/watch?v=hDcKJ46PBJ4',platformFileId:'hDcKJ46PBJ4',canonicalUrl:'https://www.youtube.com/watch?v=hDcKJ46PBJ4',sourceIds:['SRC-006'],activityIds:['ACT-2022-000001'],project:'StartOn',rights:'OWNED_SURFACE_PUBLIC',publicSafety:'PUBLIC_SAFE',verificationStatus:'VERIFIED_PUBLIC_SOURCE'}],relations:[{id:'REL-000001',recordType:'relation',subjectId:'ACT-2022-000001',predicate:'produced_content',objectId:'CNT-000001',sourceIds:['SRC-006'],publicSafety:'PUBLIC_SAFE',verificationStatus:'VERIFIED',confidence:'HIGH'},{id:'REL-000002',recordType:'relation',subjectId:'CNT-000001',predicate:'represented_by_asset',objectId:'AST-000001',sourceIds:['SRC-006'],publicSafety:'PUBLIC_SAFE',verificationStatus:'VERIFIED',confidence:'HIGH'},{id:'REL-000003',recordType:'relation',subjectId:'AST-000001',predicate:'derived_from_source',objectId:'SRC-006',sourceIds:['SRC-006'],publicSafety:'PUBLIC_SAFE',verificationStatus:'VERIFIED',confidence:'HIGH'}]};
export const digitalCompendiumPublicSnapshot=validateDigitalCompendiumSnapshot(seed);

const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value)) as T;
const rejected=(mutate:(value:DigitalCompendiumSnapshot)=>void)=>{const candidate=clone(seed);mutate(candidate);try{validateDigitalCompendiumSnapshot(candidate);return false}catch{return true}};
export function digitalCompendiumCanary(){const checks={validSnapshot:Boolean(validateDigitalCompendiumSnapshot(seed)),rejectsMissingProvenance:rejected(value=>{value.activities[0].sourceIds=[]}),rejectsNonPublicSafe:rejected(value=>{value.content[0].publicSafety='RESTRICTED'}),rejectsVerifyBeforePublishing:rejected(value=>{value.assets[0].verificationStatus='VERIFY_BEFORE_PUBLISHING'}),rejectsUndatedMetric:rejected(value=>{value.activities[0].metrics=[{metricType:'views',value:1,unit:'views',snapshotDate:'',sourceId:'SRC-006'}]}),relationsResolve:rejected(value=>{value.relations[0].objectId='CNT-NOT-FOUND'})};return{status:Object.values(checks).every(Boolean)?'PASS':'FAIL',contract:DIGITAL_COMPENDIUM_CONTRACT,release:DIGITAL_COMPENDIUM_RELEASE,checks,publicRecordCount:seed.activities.length+seed.content.length+seed.assets.length+seed.relations.length,sourceCount:seed.sources.length,writesPerformed:false}}

const urlKey=(value:string)=>value.trim().replace(/[?#].*$/,'').replace(/\/$/,'').toLowerCase();
export function mergeDigitalCompendiumIntoCanon(base:CanonicalEvent[]){const snapshot=digitalCompendiumPublicSnapshot;const urls=new Set(base.flatMap(event=>event.sources.filter(source=>source.public).map(source=>urlKey(source.url))));const ids=new Set(base.map(event=>event.id));const extras:CanonicalEvent[]=[];snapshot.activities.forEach((activity,index)=>{const source=snapshot.sources.find(item=>activity.sourceIds.includes(item.id));const content=snapshot.content.find(item=>activity.contentIds.includes(item.id));const asset=snapshot.assets.find(item=>activity.assetIds.includes(item.id));if(!source||!content||!asset||urls.has(urlKey(source.url)))return;const id='compendium-'+activity.id.toLowerCase();if(ids.has(id))return;const event:CanonicalEvent={id,storyOrder:42+index,canonicalDate:activity.startDate,datePrecision:'exact-day',dateBasis:'document',dateNote:'Projected from the canonical Digital Compendium after VERIFIED_READBACK, provenance and PUBLIC_SAFE validation.',type:'media',surfaces:['life','starton','media','archive'],title:{he:'ראיון אישי — סיפור המקור של StartOn',en:'Personal interview — StartOn origin story',ru:'Личное интервью — история происхождения StartOn'},summary:{he:'ראיון ציבורי אוטוביוגרפי המתעד במקור ראשון את הדרך שהובילה ל־StartOn. הרשומה מוצגת מתוך האוגדן הקאנוני ונשארת קשורה למקור הציבורי.',en:'A public autobiographical interview documenting in first person the road that led to StartOn. The record is projected from the canonical compendium and remains bound to its public source.',ru:'Публичное автобиографическое интервью от первого лица о пути, который привёл к StartOn. Запись проецируется из канонического сборника и остаётся привязанной к публичному источнику.'},visibility:'public',verification:{state:'verified',note:'Imported from the Digital Compendium public snapshot after PUBLIC_SAFE, provenance, publish-state and relation validation.'},sources:[{id:source.id,label:source.title,url:source.url,kind:'public-video',public:true,platform:source.platform,publishedAt:activity.startDate}],media:[{kind:'video',url:'https://i.ytimg.com/vi/'+content.nativePlatformId+'/hqdefault.jpg',sourceUrl:source.url,authenticity:'source-object',label:'Public YouTube video object',publicationDate:activity.startDate}],impact:{state:'verified-signals',signals:['Canonical Digital Compendium source record']},tags:['DIGITAL COMPENDIUM','STARTON','INTERVIEW','PUBLIC SOURCE','PUBLIC_SAFE']};extras.push(event);urls.add(urlKey(source.url));ids.add(id)});return[...base,...extras]}
export const digitalCompendiumBootVerification=(()=>{const canary=digitalCompendiumCanary();const projected=mergeDigitalCompendiumIntoCanon([]);const activity=projected.find(event=>event.id==='compendium-act-2022-000001');const checks={canaryPass:canary.status==='PASS',projectionMaterialized:Boolean(activity),projectionSourceBound:Boolean(activity?.sources.some(source=>source.id==='SRC-006'&&source.public)),projectionPublic:activity?.visibility==='public'};if(!Object.values(checks).every(Boolean))throw new Error('DIGITAL_COMPENDIUM_BOOT_VERIFICATION_FAILED '+JSON.stringify(checks));return{status:'PASS' as const,release:DIGITAL_COMPENDIUM_RELEASE,contract:DIGITAL_COMPENDIUM_CONTRACT,checks,canary}})();
