import type {CanonicalEvent,DatePrecision,LocaleText,MediaKind} from './canonical-corpus';
export const LIFE_SCENES_RELEASE='LIFE-SCENES-20260823-1';
export type SceneTrust='canonical'|'verified-public'|'supported-public'|'discovery';
export type SceneKind='life'|'service'|'education'|'starton'|'media'|'public-action'|'creator'|'music'|'research'|'politics'|'7ya'|'relationship'|'now';
export type SceneLens='home'|'museum'|'media'|'music'|'research'|'starton'|'politics'|'influence'|'speaker'|'blog'|'create'|'archive';
export type SceneSourceRef={id:string;label:string;url:string;kind:string;platform?:string};
export type SceneMediaRef={kind:MediaKind;url:string;sourceUrl:string;authenticity:string;label:string};
export type ScenePersonRef={entityId:string;displayName:string;role:'igor'|'co-creator'|'host'|'guest'|'interviewer'|'publisher'|'partner'|'institution'|'public-figure'|'participant'|'distributor'|'subject';evidenceUrl?:string};
export type SceneAftermath={kind:'media-pickup'|'repost'|'public-discussion'|'follow-up-work'|'project'|'research-question'|'political-action'|'collaboration'|'institutional-response'|'unknown';label:string;url?:string;relatedSceneId?:string;trust:SceneTrust};
export type SceneCoverageSummary={totalScenes:number;canonicalRepresented:number;verifiedPublicRepresented:number;supportedOrDiscovery:number;scenesWithoutVisual:number;scenesWithoutDate:number;byKind:Record<string,number>;byTrust:Record<string,number>;dimensions:Record<string,boolean>};
export type LifeScene={id:string;canonicalEventId:string;storyOrder:number;date:string;datePrecision:DatePrecision;trust:SceneTrust;kind:SceneKind;lenses:SceneLens[];title:LocaleText;summary:LocaleText;topics:string[];people:ScenePersonRef[];sources:SceneSourceRef[];media:SceneMediaRef[];aftermath:SceneAftermath[];relatedSceneIds:string[];verificationNote:string};
export type LifeSceneCompilerInput={events:CanonicalEvent[]};
export type LifeSceneQuery={lens?:SceneLens;from?:string;to?:string;kind?:SceneKind;topic?:string;trust?:SceneTrust;limit?:number};
export type LifeSceneProjection={scenes:LifeScene[];coverage:SceneCoverageSummary};
const safeUrl=(value:string)=>/^https:\/\//i.test(value.trim());
const normalizedUrl=(value:string)=>{try{const url=new URL(value);['fbclid','igshid','si','utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(key=>url.searchParams.delete(key));url.hash='';return(url.origin+url.pathname+url.search).replace(/\/$/,'').toLowerCase()}catch{return value.trim().replace(/\/$/,'').toLowerCase()}};
const trustFor=(event:CanonicalEvent):SceneTrust=>{if(!event.id.startsWith('register-'))return'canonical';if(event.verification.state==='verified')return'verified-public';if(event.verification.state==='unresolved'||event.verification.state==='contradicted'||event.verification.state==='quarantined')return'discovery';return'supported-public'};
const textFor=(event:CanonicalEvent)=>[event.id,event.type,...event.surfaces,...event.tags,event.title.he,event.title.en,event.title.ru,event.summary.he,event.summary.en,event.summary.ru].join(' ').toLowerCase();
const kindFor=(event:CanonicalEvent):SceneKind=>{const text=textFor(event);if(/politic|election|municipal|party|knesset|yisrael beiteinu|ישראל ביתנו|בחירות|כנסת|פוליט/.test(text))return'politics';if(event.type==='system'||/\b7ya\b|#7ya/.test(text))return'7ya';if(event.surfaces.includes('starton')||/starton/.test(text))return'starton';if(event.type==='service')return'service';if(event.type==='research')return'research';if(event.type==='music'||event.surfaces.includes('music'))return'music';if(event.type==='identity'&&/hebrew university|criminology|אוניברסיטה|קרימינולוג/.test(text))return'education';if(event.type==='post')return'public-action';if(event.type==='writing')return'public-action';if(event.type==='media')return'media';if(event.type==='project')return'public-action';return'life'};
const lensesFor=(event:CanonicalEvent,kind:SceneKind):SceneLens[]=>{const set=new Set<SceneLens>(['home','museum','archive']);for(const surface of event.surfaces){if(surface==='media')set.add('media');if(surface==='music')set.add('music');if(surface==='research')set.add('research');if(surface==='starton')set.add('starton');if(surface==='influence')set.add('influence');if(surface==='writing')set.add('blog')}if(kind==='media'){set.add('media');set.add('speaker')}if(kind==='music'||kind==='creator'){set.add('music');set.add('create')}if(kind==='research'){set.add('research');set.add('blog');set.add('create')}if(kind==='starton'){set.add('starton');set.add('create')}if(kind==='politics'){set.add('politics');set.add('media');set.add('influence')}if(kind==='public-action'){set.add('media');set.add('influence');set.add('blog')}if(kind==='7ya'||kind==='now')set.add('create');return[...set]};
const aftermathFor=(event:CanonicalEvent,trust:SceneTrust):SceneAftermath[]=>event.impact.signals.map(label=>({kind:/repost|amplification|distribution|syndication/i.test(label)?'repost':/media|television|broadcast|press/i.test(label)?'media-pickup':/research/i.test(label)?'research-question':/project|nonprofit|starton/i.test(label)?'project':'public-discussion',label,trust}));
const toScene=(event:CanonicalEvent):LifeScene|null=>{if(event.visibility!=='public')return null;const sources=event.sources.filter(source=>source.public&&safeUrl(source.url)).map(source=>({id:source.id,label:source.label,url:source.url,kind:source.kind,...(source.platform?{platform:source.platform}:{})}));if(!sources.length)return null;const trust=trustFor(event);const kind=kindFor(event);const media=event.media.filter(item=>item.authenticity!=='unverified'&&safeUrl(item.url||item.sourceUrl)).map(item=>({kind:item.kind,url:item.url||item.sourceUrl,sourceUrl:item.sourceUrl,authenticity:item.authenticity,label:item.label}));return{id:'life-'+event.id,canonicalEventId:event.id,storyOrder:event.storyOrder,date:event.canonicalDate,datePrecision:event.datePrecision,trust,kind,lenses:lensesFor(event,kind),title:event.title,summary:event.summary,topics:[...new Set([...event.tags,event.type,...event.surfaces])],people:[{entityId:'igor-vepretski',displayName:'Igor Vepretski',role:'igor',evidenceUrl:sources[0].url}],sources,media,aftermath:aftermathFor(event,trust),relatedSceneIds:(event.relatedEventIds||[]).map(id=>'life-'+id),verificationNote:event.verification.note}};
const dimensionSummary=(scenes:LifeScene[])=>{const text=scenes.map(scene=>[scene.canonicalEventId,scene.kind,...scene.topics,scene.title.he,scene.title.en,scene.title.ru].join(' ').toLowerCase()).join('\n');const has=(pattern:RegExp)=>pattern.test(text);return{origin:has(/origin|childhood|immigration|belonging|ילדות|עלייה|שייכות/),service:scenes.some(scene=>scene.kind==='service'),education:scenes.some(scene=>scene.kind==='education'),starton:scenes.some(scene=>scene.kind==='starton'),writing:has(/writing|authored|כתיבה|טור/),socialCreation:has(/tiktok|instagram|youtube|viral|ויראל|public-action/),longform:has(/podcast|broadcast|longform|ראיון|פודקאסט/),creatorMusic:scenes.some(scene=>scene.kind==='music'||scene.kind==='creator'),research:scenes.some(scene=>scene.kind==='research'),politics:scenes.some(scene=>scene.kind==='politics'),sevenYa:scenes.some(scene=>scene.kind==='7ya'),now:has(/7ya-now|\bnow\b|snapshot-2026/)}};
const coverageFor=(scenes:LifeScene[]):SceneCoverageSummary=>{const byKind:Record<string,number>={};const byTrust:Record<string,number>={};for(const scene of scenes){byKind[scene.kind]=(byKind[scene.kind]||0)+1;byTrust[scene.trust]=(byTrust[scene.trust]||0)+1}return{totalScenes:scenes.length,canonicalRepresented:scenes.filter(scene=>scene.trust==='canonical').length,verifiedPublicRepresented:scenes.filter(scene=>scene.trust==='verified-public').length,supportedOrDiscovery:scenes.filter(scene=>scene.trust==='supported-public'||scene.trust==='discovery').length,scenesWithoutVisual:scenes.filter(scene=>!scene.media.some(media=>media.kind==='image'||media.kind==='video'||media.kind==='document')).length,scenesWithoutDate:scenes.filter(scene=>scene.date==='undated'||scene.datePrecision==='unknown').length,byKind,byTrust,dimensions:dimensionSummary(scenes)}};
export function compileLifeScenes(input:LifeSceneCompilerInput):LifeSceneProjection{const ordered=input.events.map(toScene).filter((scene):scene is LifeScene=>Boolean(scene)).sort((a,b)=>a.storyOrder-b.storyOrder||a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const seenIds=new Set<string>();const strongUrls=new Set<string>();const scenes=ordered.filter(scene=>{if(seenIds.has(scene.id))return false;seenIds.add(scene.id);const urls=scene.sources.map(source=>normalizedUrl(source.url)).filter(Boolean);if(scene.trust!=='canonical'&&urls.length&&urls.every(url=>strongUrls.has(url)))return false;if(scene.trust==='canonical')urls.forEach(url=>strongUrls.add(url));return true});return{scenes,coverage:coverageFor(scenes)}}
export function projectLifeScenes(scenes:LifeScene[],query:LifeSceneQuery={}){const requested=Number(query.limit);const limit=Number.isFinite(requested)&&requested>0?Math.min(200,Math.floor(requested)):50;const topic=(query.topic||'').trim().toLowerCase();let filtered=scenes.filter(scene=>(!query.lens||scene.lenses.includes(query.lens))&&(!query.kind||scene.kind===query.kind)&&(!query.trust||scene.trust===query.trust)&&(!query.from||scene.date==='undated'||scene.date>=query.from)&&(!query.to||scene.date==='undated'||scene.date<=query.to)&&(!topic||[...scene.topics,scene.title.he,scene.title.en,scene.title.ru,scene.summary.he,scene.summary.en,scene.summary.ru].join(' ').toLowerCase().includes(topic)));return filtered.slice(0,limit)}