export type RecoveryMediaType='video'|'playlist'|'source';
export type RecoveredPublicationSeed={id:string;title:string;url?:string;platform:string;mediaType:RecoveryMediaType;archiveStatus:'RECOVERED'|'KNOWN_ENTITY_URL_PENDING';metadataStatus:'PENDING'|'PARTIAL';collectionStatus?:'CURATED_HISTORICAL_COLLECTION';youtubeId?:string;playlistId?:string;tags:string[]};
export const recoveredYouTubeIds=['AE5hDzLM5XU','3XxoBtSL2pg','SOpAglwkJ8I','c6ueWxKXNg0','kS2CRiqRaXo','NX5NHRfDNUQ','D8E876SaWpI','KFbjQv243x8','3mG7qVapcII','v7158BaZkiQ','xyNS6o07uEo','hDcKJ46PBJ4','UfvyxFbILHc','5th6T8wIYWk','tL8ofb9d2dY','qj6HcVSw8_Q','iJyEgWnGA5M','jRjZjpqAgEw','2HGMUN2jDwQ','0O3tpLwJg4Y','OlRQXxjvTfA','vgIdB58f8QA','5qxA4hgUhV8','zKe8u4HdGXE','U2d_hulZAC0','H9tn761ou3Y','ASlpxqylMSg'] as const;
export const recoveredYouTubePublications:RecoveredPublicationSeed[]=recoveredYouTubeIds.map(youtubeId=>({id:'youtube-recovery-'+youtubeId,title:'Recovered YouTube video · '+youtubeId,url:'https://www.youtube.com/watch?v='+youtubeId,platform:'YouTube',mediaType:'video',archiveStatus:'RECOVERED',metadataStatus:'PENDING',youtubeId,tags:['YOUTUBE RECOVERY','RECOVERED VIDEO','METADATA PENDING']}));
export const historicalPlaylistPublications:RecoveredPublicationSeed[]=[
{id:'youtube-playlist-PLvXOwJ42abaROQ2aWxZJNH8HlJmON5caA',title:'Curated historical YouTube collection · PLvXOwJ42abaROQ2aWxZJNH8HlJmON5caA',url:'https://www.youtube.com/playlist?list=PLvXOwJ42abaROQ2aWxZJNH8HlJmON5caA',platform:'YouTube',mediaType:'playlist',archiveStatus:'RECOVERED',metadataStatus:'PENDING',collectionStatus:'CURATED_HISTORICAL_COLLECTION',playlistId:'PLvXOwJ42abaROQ2aWxZJNH8HlJmON5caA',tags:['YOUTUBE','PLAYLIST','CURATED HISTORICAL COLLECTION']},
{id:'youtube-playlist-PLvXOwJ42abaQQ3JIwCUundzdXSUJCBMv8',title:'Curated historical YouTube collection · PLvXOwJ42abaQQ3JIwCUundzdXSUJCBMv8',url:'https://www.youtube.com/playlist?list=PLvXOwJ42abaQQ3JIwCUundzdXSUJCBMv8',platform:'YouTube',mediaType:'playlist',archiveStatus:'RECOVERED',metadataStatus:'PENDING',collectionStatus:'CURATED_HISTORICAL_COLLECTION',playlistId:'PLvXOwJ42abaQQ3JIwCUundzdXSUJCBMv8',tags:['YOUTUBE','PLAYLIST','CURATED HISTORICAL COLLECTION']}
];
export const urlPendingPublications:RecoveredPublicationSeed[]=[
{id:'pending-channel14-publisher',title:'Channel 14 publisher page',platform:'Channel 14',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','PUBLISHER PAGE','CHANNEL 14']},
{id:'pending-news12-publisher',title:'חדשות 12 original publisher page',platform:'News 12',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','PUBLISHER PAGE','NEWS 12']},
{id:'pending-opening-day-publisher',title:'פותחים יום publisher page',platform:'TV',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','PUBLISHER PAGE','פותחים יום']},
{id:'pending-103fm-publisher',title:'103FM publisher page',platform:'103FM',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','PUBLISHER PAGE','103FM']},
{id:'pending-apple-podcasts-legacy',title:'Apple Podcasts legacy show',platform:'Apple Podcasts',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','LEGACY','APPLE PODCASTS']},
{id:'pending-linkedin-newsletter',title:'LinkedIn Newsletter',platform:'LinkedIn',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','LINKEDIN','NEWSLETTER']},
{id:'pending-soundcloud-secondary',title:'SoundCloud secondary archive',platform:'SoundCloud',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','SOUNDCLOUD','LEGACY']},
{id:'pending-facebook-history',title:'Historical Facebook posts',platform:'Facebook',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','FACEBOOK','HISTORICAL POSTS']},
{id:'pending-instagram-history',title:'Historical Instagram posts',platform:'Instagram',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','INSTAGRAM','HISTORICAL POSTS']},
{id:'pending-tiktok-legacy',title:'TikTok legacy account',platform:'TikTok',mediaType:'source',archiveStatus:'KNOWN_ENTITY_URL_PENDING',metadataStatus:'PARTIAL',tags:['URL PENDING','TIKTOK','LEGACY ACCOUNT']}
];
export const recoveredPublicationRegistry:RecoveredPublicationSeed[]=[...recoveredYouTubePublications,...historicalPlaylistPublications,...urlPendingPublications];
