import {useState} from 'react';
import {pageHref,rootHref,useLocale,type Locale} from '../locale';
type PortalKey='life'|'impact'|'starton'|'media'|'research'|'create';
const PORTRAIT='./resources/igor-hero.jpg';
const portalOrder:PortalKey[]=['life','impact','starton','media','research','create'];
const portalText:Record<Locale,Record<PortalKey,readonly [string,string]>>={he:{life:['LIFE','החיים והדרך'],impact:['IMPACT','הד, קהל והשפעה'],starton:['STARTON','להפוך ניסיון להזדמנות'],media:['MEDIA','ראיונות, כתבות ופודקאסטים'],research:['RESEARCH','שאלות, מסגרות ומקורות'],create:['CREATE','מוזיקה, יצירה והצעד הבא']},en:{life:['LIFE','The life and the path'],impact:['IMPACT','Echo, audience and impact'],starton:['STARTON','Turning experience into opportunity'],media:['MEDIA','Interviews, press and podcasts'],research:['RESEARCH','Questions, frameworks and sources'],create:['CREATE','Music, creation and the next move']},ru:{life:['LIFE','Жизнь и путь'],impact:['IMPACT','Эхо, аудитория и влияние'],starton:['STARTON','Превращать опыт в возможность'],media:['MEDIA','Интервью, пресса и подкасты'],research:['RESEARCH','Вопросы, модели и источники'],create:['CREATE','Музыка, творчество и следующий шаг']}};
const copy={he:{kicker:'1990 → עכשיו · החיים שלי',title:'אני איגור. זה הסיפור שלי — כמו שהוא קרה.',body:'חרקוב, ישראל, ג׳סי כהן, שירות, אבהות, StartOn, יצירה, מחקר והחיים ברשת. לא תקציר ולא תדמית: נכנסים דרך הרגעים עצמם.',choose:'להמשיך בסיפור',press:'PRESS / BOOKING',sources:'למקורות',portrait:'איגור ופרצקי'},en:{kicker:'1990 → NOW · MY LIFE',title:'I’m Igor. This is my life — as it happened.',body:'Kharkiv, Israel, Jesse Cohen, service, fatherhood, StartOn, creation, research and a life online. Not a résumé or campaign image: enter through the moments themselves.',choose:'Continue the story',press:'PRESS / BOOKING',sources:'Sources',portrait:'Igor Vepretski'},ru:{kicker:'1990 → СЕЙЧАС · МОЯ ЖИЗНЬ',title:'Я Игорь. Это моя жизнь — такой, какой она была.',body:'Харьков, Израиль, Джесси Коэн, служба, отцовство, StartOn, творчество, исследования и жизнь в сети. Не резюме и не витрина: входите через сами моменты.',choose:'Продолжить историю',press:'PRESS / BOOKING',sources:'Источники',portrait:'Игорь Вепрецкий'}} as const;
const portalHref=(key:PortalKey,locale:Locale)=>key==='life'?'#life-moments':key==='impact'?'#pi-echo':key==='starton'?'#pi-starton':key==='media'?pageHref('media',locale):key==='research'?rootHref('research/?lang='+locale):pageHref('create',locale);
export default function LivingPulse(){const {locale,dir}=useLocale();const c=copy[locale];const [broken,setBroken]=useState(false);return <section className='pi-section pi-pulse pi-world-gateway' id='pi-pulse' dir={dir} aria-labelledby='pi-pulse-title'><figure className={'pi-world-backdrop'+(broken?' is-broken':'')} aria-label={c.portrait}>{!broken&&<img src={PORTRAIT} alt={c.portrait} fetchPriority='high' decoding='async' onError={()=>setBroken(true)}/>}<div aria-hidden='true'/><figcaption dir='ltr'>REAL PHOTO · CANONICAL 7YA ASSET</figcaption></figure><div className='pi-world-copy'><p className='pi-world-kicker' dir='ltr'>{c.kicker}</p><div className='pi-world-identity'><strong dir='ltr'>IGOR VEPRETSKI</strong><span lang='he' dir='rtl'>איגור ופרצקי</span><span lang='ru' dir='ltr'>ИГОРЬ ВЕПРЕЦКИЙ</span></div><h1 id='pi-pulse-title'>{c.title}</h1><p className='pi-world-lead'>{c.body}</p><div className='pi-world-signal' dir='ltr'><i aria-hidden='true'/><span>HUMAN · CREATOR · STARTON · RESEARCH · PUBLIC SYSTEMS</span></div></div><nav className='pi-world-portals' aria-label={c.choose}>{portalOrder.map((key,index)=>{const [label,title]=portalText[locale][key];return <a href={portalHref(key,locale)} key={key} data-portal={key}><small dir='ltr'>{String(index+1).padStart(2,'0')}</small><b dir='ltr'>{label}</b><span>{title}</span><em aria-hidden='true'>↗</em></a>})}</nav><footer className='pi-world-footer'><span>{c.choose} ↓</span><div><a href={pageHref('speaker',locale)}>{c.press}</a><a href={rootHref('evidence/')}>{c.sources}</a></div></footer></section>}
