import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Building2,Link2,MapPin,Users} from 'lucide-react';
import {fetchEntities,type CanonicalEntity,type EntityKind,type EntityTruth} from '../entity-client';
import {rootHref,useLocale,type Locale} from '../locale';
const copy={he:{kicker:'PEOPLE / PLACES / INSTITUTIONS',title:'החיים לא קרו לבד ולא קרו בשום־מקום.',body:'ישויות נכנסות לכאן רק כשהקשר שלהן מופיע במקור ציבורי. אין רשימת קשרים פרטית ואין השלמת חורים בדמיון. כל כרטיס מחזיר לרגעים הקנוניים שבהם הקשר מתועד.',person:'אנשים',place:'מקומות',institution:'מוסדות',source:'מקור',moments:'רגעים קשורים',loading:'טוען את מפת הקשרים…',failed:'מפת הישויות אינה זמינה כרגע; לא מוצג תחליף מומצא.'},en:{kicker:'PEOPLE / PLACES / INSTITUTIONS',title:'The life did not happen alone, and it did not happen nowhere.',body:'Entities appear here only when their relationship is present in a public source. There is no private contact list and no gap-filling by invention. Every card routes back to the canonical moments where the relationship is documented.',person:'People',place:'Places',institution:'Institutions',source:'Source',moments:'Related moments',loading:'Loading the relationship map…',failed:'The entity map is unavailable right now; no invented substitute is shown.'},ru:{kicker:'PEOPLE / PLACES / INSTITUTIONS',title:'Эта жизнь происходила не в одиночку и не в пустоте.',body:'Сущности появляются здесь только если связь присутствует в публичном источнике. Здесь нет частного списка контактов и выдуманного заполнения пробелов. Каждая карточка ведет к каноническим моментам, где связь документирована.',person:'Люди',place:'Места',institution:'Институции',source:'Источник',moments:'Связанные моменты',loading:'Загружаю карту связей…',failed:'Карта сущностей сейчас недоступна; выдуманная замена не показывается.'}} as const;
const labels:Record<Locale,Record<EntityTruth,string>>={he:{VERIFIED:'VERIFIED',STRONGLY_INFERRED:'STRONGLY INFERRED',REQUIRES_CONFIRMATION:'REQUIRES CONFIRMATION'},en:{VERIFIED:'VERIFIED',STRONGLY_INFERRED:'STRONGLY INFERRED',REQUIRES_CONFIRMATION:'REQUIRES CONFIRMATION'},ru:{VERIFIED:'VERIFIED',STRONGLY_INFERRED:'STRONGLY INFERRED',REQUIRES_CONFIRMATION:'REQUIRES CONFIRMATION'}};
const icon=(kind:EntityKind)=>kind==='person'?Users:kind==='place'?MapPin:Building2;
const eventHref=(locale:Locale,id:string)=>rootHref('?'+new URLSearchParams({page:'search',lang:locale,q:id}).toString());
export default function PeoplePlacesAtlas(){const {locale,dir}=useLocale();const c=copy[locale];const [entities,setEntities]=useState<CanonicalEntity[]>([]);const [state,setState]=useState<'loading'|'ready'|'failed'>('loading');useEffect(()=>{let live=true;fetchEntities().then(data=>{if(live){setEntities(data.entities);setState('ready')}}).catch(()=>{if(live)setState('failed')});return()=>{live=false}},[]);const groups=useMemo(()=>((['person','place','institution'] as EntityKind[]).map(kind=>({kind,items:entities.filter(entity=>entity.kind===kind)}))),[entities]);if(state!=='ready')return <section id='pi-atlas' className='pi-section pi-atlas' dir={dir}><p className='pi-kicker' dir='ltr'>{c.kicker}</p><div className={'pi-reality-state '+(state==='failed'?'is-failed':'')}>{state==='failed'?c.failed:c.loading}</div></section>;return <section id='pi-atlas' className='pi-section pi-atlas' dir={dir} aria-labelledby='pi-atlas-title'><header className='pi-section-head'><p className='pi-kicker' dir='ltr'>{c.kicker}</p><h2 id='pi-atlas-title'>{c.title}</h2><p>{c.body}</p></header>{groups.map(group=>{const Icon=icon(group.kind);const heading=group.kind==='person'?c.person:group.kind==='place'?c.place:c.institution;return <div className='pi-atlas-group' key={group.kind}><div className='pi-atlas-group-head'><Icon/><h3>{heading}</h3><span>{String(group.items.length).padStart(2,'0')}</span></div><div className='pi-atlas-grid'>{group.items.map(entity=><article className={'pi-atlas-card status-'+entity.truthStatus.toLowerCase().replaceAll('_','-')} key={entity.id}><header><small>{labels[locale][entity.truthStatus]}</small><h4>{entity.label[locale]}</h4></header><p>{entity.relation[locale]}</p><div className='pi-atlas-tags'>{entity.tags.slice(0,4).map(tag=><span key={tag}>{tag}</span>)}</div><footer><div>{entity.sources.slice(0,2).map(source=><a href={source.url} target='_blank' rel='noreferrer' key={source.id}>{c.source}<Link2/></a>)}</div>{entity.relatedEventIds.length>0&&<div><a href={eventHref(locale,entity.relatedEventIds[0])}>{c.moments}<ArrowUpRight/></a></div>}</footer></article>)}</div></div>})}</section>}
