import type {Locale} from '../locale';
export type L10n=Record<Locale,string>;
export type LaneKind='instagram'|'starton'|'research'|'create';
export type LivingLane={id:string;code:string;title:L10n;body:L10n;kind:LaneKind};
export type EchoPath={id:string;eyebrow:string;source:L10n;transition:L10n;destination:L10n;body:L10n;href:string;image:string};
export type GraphTarget='pulse'|'album-origin'|'album-service'|'album-voice'|'starton'|'media'|'music'|'research'|'create'|'album';
export type GraphNode={id:string;label:L10n;relation:L10n;target:GraphTarget;core?:boolean};
export type StartOnRoom={id:string;index:string;name:L10n;action:L10n;capability:L10n};
export type FutureState='NOW'|'BUILDING'|'TARGET'|'OPEN QUESTION';
export type FutureTarget='home'|'starton'|'research'|'create';
export type FutureItem={id:string;state:FutureState;title:L10n;desired:L10n;constraint:L10n;target:FutureTarget};
const l=(he:string,en:string,ru:string):L10n=>({he,en,ru});
export const livingLanes:LivingLane[]=[
{id:'now',code:'01 / NOW',title:l('קול ציבורי חי','LIVE PUBLIC VOICE','ЖИВОЙ ПУБЛИЧНЫЙ ГОЛОС'),body:l('המקורות החיים נשארים מחוץ לאתר ונפתחים ישירות, בלי להמציא מדד “לייב”.','Live sources stay at their public origin and open directly, without inventing a live metric.','Живые источники остаются на публичных площадках и открываются напрямую — без выдуманной live-метрики.'),kind:'instagram'},
{id:'starton',code:'02 / FIELD',title:l('StartOn / הזדמנות','STARTON / OPPORTUNITY','STARTON / ВОЗМОЖНОСТЬ'),body:l('להפוך ניסיון חיים לסביבה שבה צעיר יכול לפגוש כלים, יצירה ושייכות.','Turning lived experience into an environment where a young person can meet tools, creation and belonging.','Превращение жизненного опыта в среду, где молодой человек встречает инструменты, творчество и принадлежность.'),kind:'starton'},
{id:'research',code:'03 / LAB',title:l('מחקר / מסגור','RESEARCH / FRAMING','ИССЛЕДОВАНИЯ / РАМКА'),body:l('להפריד בין תחושה, השערה, מקור וטענה שאפשר לבדוק.','Separating feeling, hypothesis, source and a claim that can actually be tested.','Отделять чувство, гипотезу, источник и утверждение, которое можно проверить.'),kind:'research'},
{id:'create',code:'04 / CREATE',title:l('יצירה / מערכת','CREATE / SYSTEM','ТВОРЧЕСТВО / СИСТЕМА'),body:l('להפוך סיפור, קול ורעיון לצעד שאפשר לבצע ולשתף.','Turning story, voice and an idea into an executable, shareable next move.','Превращать историю, голос и идею в следующий шаг, который можно выполнить и разделить.'),kind:'create'}
];
export const reactionVocabulary=[l('הזדהות','RESONANCE','РЕЗОНАНС'),l('שיחה','CONVERSATION','РАЗГОВОР'),l('שיתוף','SHARING','РАСПРОСТРАНЕНИЕ'),l('מחלוקת','DISAGREEMENT','НЕСОГЛАСИЕ')];
export const echoPaths:EchoPath[]=[
{id:'fatherhood',eyebrow:'STORY → ARTICLE',source:l('חוויה אישית על אבהות','A personal fatherhood story','Личная история об отцовстве'),transition:l('יצאה מהפיד','MOVED BEYOND THE FEED','ВЫШЛА ЗА ПРЕДЕЛЫ ЛЕНТЫ'),destination:l('כתבה ושיחה רחבה יותר','ARTICLE + WIDER CONVERSATION','СТАТЬЯ + БОЛЕЕ ШИРОКИЙ РАЗГОВОР'),body:l('המשמעות אינה מספר אחד של reach אלא המעבר מסיפור אישי למסגור שאנשים אחרים המשיכו איתו.','The meaning is not one reach number; it is the movement from lived experience into a frame others carried forward.','Смысл не в одном числе охвата, а в переходе от личного опыта к рамке, которую продолжили другие.'),href:'https://www.hidabroot.org/article/1179015',image:'https://storage.hidabroot.org/articles_new/327351_tumb_730X500.jpg'},
{id:'fraud',eyebrow:'POST → TV',source:l('סיפור ציבורי על הונאות קשישים','A public story about elder fraud','Публичная история о мошенничестве против пожилых'),transition:l('קיבל המשך','GAINED A SECOND LIFE','ПОЛУЧИЛА ПРОДОЛЖЕНИЕ'),destination:l('שידור טלוויזיוני','TELEVISION COVERAGE','ТЕЛЕВИЗИОННЫЙ ЭФИР'),body:l('המקור עבר ממסך אישי למסך ציבורי. כל מדד, כשמוצג, חייב להישאר צמוד למקור שממנו הגיע.','The source moved from a personal screen into a public broadcast. Any metric shown must stay attached to its source context.','Источник перешёл с личного экрана в публичный эфир. Любая метрика должна оставаться привязанной к своему источнику.'),href:'https://www.youtube.com/watch?v=AE5hDzLM5XU',image:'https://i.ytimg.com/vi/AE5hDzLM5XU/hqdefault.jpg'},
{id:'starton',eyebrow:'STORY → INSTITUTION',source:l('החזרה לג׳סי כהן','RETURN TO JESSE COHEN','ВОЗВРАЩЕНИЕ В ДЖЕССИ КОЭН'),transition:l('הפכה לשאלה מעשית','BECAME AN OPERATING QUESTION','СТАЛА ПРАКТИЧЕСКИМ ВОПРОСОМ'),destination:l('StartOn / מודל הזדמנות','STARTON / OPPORTUNITY MODEL','STARTON / МОДЕЛЬ ВОЗМОЖНОСТЕЙ'),body:l('הד נבחן כאן מול שאלה קשה יותר: האם תשומת לב יכולה להפוך למקום, תהליך וכלי עבודה.','Echo meets a harder test here: can attention become a place, a process and practical tools?','Здесь эхо проходит более сложную проверку: может ли внимание стать местом, процессом и практическими инструментами?'),href:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',image:'https://pic1.yitweb.co.il/cdn-cgi/image/f%3Dauto%2Cw%3D740%2Cq%3D75/picserver/mynet/crop_images/2022/05/11/r1F0NeKU9/r1F0NeKU9_0_0_640_360_0_large.jpg'}
];
export const graphNodes:GraphNode[]=[
{id:'igor',label:l('איגור','IGOR','ИГОРЬ'),relation:l('האדם שמחבר בין כל השכבות','The human connecting every layer','Человек, соединяющий все слои'),target:'pulse',core:true},
{id:'origin',label:l('חרקוב / מקור','KHARKIV / ORIGIN','ХАРЬКОВ / ИСТОК'),relation:l('מקור, הגירה ושאלת השייכות','Origin, migration and belonging','Исток, миграция и принадлежность'),target:'album-origin'},
{id:'holon',label:l('חולון / ג׳סי כהן','HOLON / JESSE COHEN','ХОЛОН / ДЖЕССИ КОЭН'),relation:l('המקום שהפך הקשר למשימה','The place where context became mission','Место, где контекст стал миссией'),target:'starton'},
{id:'service',label:l('שירות ציבורי','PUBLIC SERVICE','ОБЩЕСТВЕННАЯ СЛУЖБА'),relation:l('אחריות, שטח וקריאת מערכות','Responsibility, fieldwork and systems','Ответственность, поле и системы'),target:'album-service'},
{id:'voice',label:l('אבהות / קול','FATHERHOOD / VOICE','ОТЦОВСТВО / ГОЛОС'),relation:l('חוויה פרטית שהפכה לשיחה ציבורית','Private experience becoming public conversation','Личный опыт, ставший публичным разговором'),target:'album-voice'},
{id:'starton',label:l('StartOn','STARTON','STARTON'),relation:l('ניסיון חיים → תשתית הזדמנות','Lived experience → opportunity infrastructure','Жизненный опыт → инфраструктура возможностей'),target:'starton'},
{id:'media',label:l('מדיה','MEDIA','МЕДИА'),relation:l('ראיונות, כתבות ושידורים','Interviews, articles and broadcasts','Интервью, статьи и эфиры'),target:'media'},
{id:'music',label:l('מוזיקה','MUSIC','МУЗЫКА'),relation:l('זהות וקצב מחוץ לתפקיד הרשמי','Identity and rhythm beyond formal roles','Идентичность и ритм вне официальной роли'),target:'music'},
{id:'research',label:l('מחקר','RESEARCH','ИССЛЕДОВАНИЯ'),relation:l('ניסיון שהפך לשאלות שניתן לבקר','Experience turned into challengeable questions','Опыт, превращённый в проверяемые вопросы'),target:'research'},
{id:'sevenya',label:l('7YA','7YA','7YA'),relation:l('זיכרון, הוכחה, AI ופעולה','Memory, evidence, AI and action','Память, доказательства, AI и действие'),target:'create'},
{id:'memory',label:l('זיכרון','MEMORY','ПАМЯТЬ'),relation:l('האלבום והארכיון כמסד הנתונים','The album and archive as the database','Альбом и архив как база данных'),target:'album'}
];
export const startOnRooms:StartOnRoom[]=[
{id:'play',index:'01',name:l('Play / Create','PLAY / CREATE','PLAY / CREATE'),action:l('לגעת בטכנולוגיה דרך משחק, יצירה והתנסות.','Meet technology through play, making and experimentation.','Встречать технологии через игру, создание и эксперимент.'),capability:l('סקרנות וביטוי','Curiosity and expression','Любопытство и самовыражение')},
{id:'learn',index:'02',name:l('Learn / Tools','LEARN / TOOLS','LEARN / TOOLS'),action:l('לקבל מחשב, כלים ומסלול למידה שאפשר להתקדם בו.','Access computers, tools and a learning path with visible progression.','Получать компьютеры, инструменты и понятный путь обучения.'),capability:l('מסוגלות וכלים','Capability and tools','Навыки и инструменты')},
{id:'studio',index:'03',name:l('Transparent Studio','TRANSPARENT STUDIO','TRANSPARENT STUDIO'),action:l('ליצור, להקליט ולפרסם יחד תוך שמירה על קרדיט והסכמה.','Create, record and publish together with credit and consent protected.','Создавать, записывать и публиковать вместе, сохраняя авторство и согласие.'),capability:l('קול ויצירה','Voice and creation','Голос и творчество')},
{id:'social',index:'04',name:l('Social / Mentoring','SOCIAL / MENTORING','SOCIAL / MENTORING'),action:l('להיות במרחב עם מבוגרים ועמיתים שמייצרים שייכות ולא רק פיקוח.','Share a space with adults and peers who create belonging, not only supervision.','Быть рядом со взрослыми и сверстниками, создающими принадлежность, а не только контроль.'),capability:l('שייכות וקשר','Belonging and connection','Принадлежность и связь')},
{id:'progress',index:'05',name:l('Progress','PROGRESS','PROGRESS'),action:l('לראות שימוש, למידה ויצירה כצעדים מצטברים — לא כתווית על הילד.','See use, learning and creation as accumulating steps rather than labels on the young person.','Видеть использование, обучение и творчество как накапливающиеся шаги, а не ярлыки.'),capability:l('רצף והתקדמות','Continuity and progress','Непрерывность и прогресс')}
];
export const futureItems:FutureItem[]=[
{id:'personal-internet',state:'NOW',title:l('7YA Personal Internet','7YA PERSONAL INTERNET','7YA PERSONAL INTERNET'),desired:l('להפוך זיכרון, תוכן, מחקר ופעולה לממשק חי אחד.','Turn memory, content, research and action into one living interface.','Соединить память, контент, исследования и действие в одном живом интерфейсе.'),constraint:l('האתגר הוא לשמור עומק בלי להפוך שוב לארכיון צפוף.','The constraint is keeping depth without turning the experience back into a dense archive.','Ограничение — сохранить глубину, не превратив опыт снова в плотный архив.'),target:'home'},
{id:'starton-space',state:'BUILDING',title:l('מרחב הזדמנות של StartOn','STARTON OPPORTUNITY SPACE','ПРОСТРАНСТВО ВОЗМОЖНОСТЕЙ STARTON'),desired:l('לחבר טכנולוגיה, יצירה, מנטורינג ושייכות למקום שניתן להפעיל ולמדוד בזהירות.','Connect technology, creation, mentoring and belonging into an operable space that can be measured carefully.','Соединить технологии, творчество, наставничество и принадлежность в работающем пространстве с осторожным измерением.'),constraint:l('מודל ותהליך קיימים; תוצאה אנושית עדיין דורשת הפעלה, הסכמה ומדידה אמיתית.','The model and process exist; human outcomes still require operation, consent and real measurement.','Модель и процесс существуют; человеческие результаты всё ещё требуют работы, согласия и реального измерения.'),target:'starton'},
{id:'opportunity-research',state:'BUILDING',title:l('מחקר הזדמנויות','OPPORTUNITY RESEARCH','ИССЛЕДОВАНИЕ ВОЗМОЖНОСТЕЙ'),desired:l('לבדוק אילו תנאים הופכים פוטנציאל בשכונות מוחלשות להזדמנות מעשית.','Test which conditions turn potential in underserved neighborhoods into practical opportunity.','Проверять, какие условия превращают потенциал в уязвимых районах в практическую возможность.'),constraint:l('יש שאלות ומסגרות; הסמכות מגיעה רק ממקורות, מתודולוגיה וביקורת.','There are questions and frameworks; authority comes only from sources, method and criticism.','Есть вопросы и модели; авторитет возможен только через источники, метод и критику.'),target:'research'},
{id:'creator-tools',state:'OPEN QUESTION',title:l('כלים ציבוריים ליוצרים ובונים','PUBLIC TOOLS FOR CREATORS & BUILDERS','ПУБЛИЧНЫЕ ИНСТРУМЕНТЫ ДЛЯ СОЗДАТЕЛЕЙ'),desired:l('להפוך את שיטת העבודה לכלים שאנשים אחרים יכולים להשתמש בהם בלי לחקות אדם.','Turn the working method into tools others can use without impersonating a person.','Превратить рабочий метод в инструменты, которыми другие могут пользоваться без имитации личности.'),constraint:l('צריך להוכיח שימושיות לפני שמרחיבים מוצר, AI או אוטומציה.','Utility must be proven before expanding product, AI or automation.','Нужно доказать полезность до расширения продукта, AI или автоматизации.'),target:'create'}
];