import {useState} from 'react';
import {Activity,ChevronDown,ChevronUp,MapPinned,Network,Search} from 'lucide-react';
import {useLocale} from '../locale';
import RealityIndex from './RealityIndex';
import IgorGraph from './IgorGraph';
import PeoplePlacesAtlas from './PeoplePlacesAtlas';
import ContentGraphPortal from '../ContentGraphPortal';
import './system-lens-deck.css';
const copy={he:{kicker:'DEPTH LENSES / ON DEMAND',title:'החיים קודם. המערכת רק כשצריך.',body:'הנתונים, הקאנון, הקשרים והישויות נשארים כאן — אבל הם לא צריכים לעמוד בין אדם לבין הסיפור שלו. פותחים אותם כשבאמת רוצים לחקור.',open:'לפתוח עדשות עומק',close:'לסגור עדשות עומק',reality:'מציאות',realityText:'מדדים ורשומות קנוניות',canon:'Canon',canonText:'חיפוש בכל הקורפוס',graph:'קשרים',graphText:'איך שכבות החיים מתחברות',atlas:'אנשים ומקומות',atlasText:'ישויות עם מקור ציבורי'},en:{kicker:'DEPTH LENSES / ON DEMAND',title:'Life first. System only when needed.',body:'Metrics, canon, relationships and entities remain here, but they no longer stand between a person and the story. Open them when you actually want to investigate.',open:'Open depth lenses',close:'Close depth lenses',reality:'Reality',realityText:'Canonical records and metrics',canon:'Canon',canonText:'Search the full corpus',graph:'Relations',graphText:'How the life layers connect',atlas:'People & places',atlasText:'Entities with public sources'},ru:{kicker:'DEPTH LENSES / ON DEMAND',title:'Сначала жизнь. Система — когда нужна.',body:'Метрики, канон, связи и сущности остаются здесь, но больше не стоят между человеком и его историей. Открывайте их, когда действительно хотите исследовать.',open:'Открыть глубинные слои',close:'Закрыть глубинные слои',reality:'Реальность',realityText:'Канонические записи и метрики',canon:'Canon',canonText:'Поиск по всему корпусу',graph:'Связи',graphText:'Как соединяются слои жизни',atlas:'Люди и места',atlasText:'Сущности с публичными источниками'}} as const;
export default function SystemLensDeck(){const {locale,dir}=useLocale();const c=copy[locale];const [open,setOpen]=useState(false);const lenses=[{key:'reality',title:c.reality,text:c.realityText,Icon:Activity},{key:'canon',title:c.canon,text:c.canonText,Icon:Search},{key:'graph',title:c.graph,text:c.graphText,Icon:Network},{key:'atlas',title:c.atlas,text:c.atlasText,Icon:MapPinned}];return <section className={'pi-section pi-lens-deck '+(open?'is-open':'')} id='pi-lenses' dir={dir} aria-labelledby='pi-lenses-title'><header className='pi-lens-head'><div><p className='pi-kicker' dir='ltr'>{c.kicker}</p><h2 id='pi-lenses-title'>{c.title}</h2></div><p>{c.body}</p></header><div className='pi-lens-preview'>{lenses.map(({key,title,text,Icon},index)=><article key={key}><span dir='ltr'>{String(index+1).padStart(2,'0')}</span><Icon/><div><strong>{title}</strong><small>{text}</small></div></article>)}</div><button className='pi-lens-toggle' type='button' aria-expanded={open} aria-controls='pi-lens-depth' onClick={()=>setOpen(value=>!value)}>{open?c.close:c.open}{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className='pi-lens-depth' id='pi-lens-depth'><RealityIndex/><ContentGraphPortal/><IgorGraph/><PeoplePlacesAtlas/></div>}</section>}
