import {useEffect,useMemo,useState,type SyntheticEvent} from 'react';
import {api} from '@appdeploy/client';
import {ArrowDown,ArrowUpRight,BookOpen,ChevronLeft,ChevronRight,MessageCircle,Play,Search,X} from 'lucide-react';
import {LanguageSwitcher,pageHref,rootHref,useLocale,type Locale} from '../locale';import {SiteThemeToggle,useSiteTheme} from '../site-theme';
import './documentary-home.css';
import ImpactFrontDoor from './ImpactFrontDoor';
import {homeVisualCorpus} from './visual-corpus';
import NarrativeChapters from './NarrativeChapters';
import './documentary-accessibility.css';

type Local=Record<Locale,string>;
type Layer='CANON'|'DISCOVERY'|'LIVE'|'LEGACY'|'PENDING';
type ProjectionItem={id:string;layer:Layer;title:Local;date:string;year:string;platform:string;publisher:string;mediaType:string;sourceKind:string;sourceUrl:string;imageUrl:string;screenshotUrl:string;trust:string;metrics?:Array<{label:string;value:string;unit:string;date:string}>};
type ProjectionPayload={knownTotal?:number;items?:ProjectionItem[]};
type Frame=ProjectionItem;
const L=(he:string,en:string,ru:string):Local=>({he,en,ru});
const fallback:Frame[]=homeVisualCorpus;
const copy={
he:{eyebrow:'#7YA🥷 · איגור ופרצקי',title:'מחרקוב לג׳סי כהן.\nמשירות ל־StartOn.',lead:'אני איגור. זה הסיפור שלי — מילדות ועלייה, דרך שירות, אבהות וחזרה לשכונה, ועד StartOn, יצירה, מחקר והשפעה דיגיטלית. קודם רואים את הדרך; אחר כך סופרים אותה.',watch:'Watch · רגעים נבחרים',story:'להתחיל ב־1990',archive:'לכל הארכיון',talk:'Digital Igor · כלי AI של 7YA',contact:'לתיאום שיחה',evidence:'לצפייה בראיות',framesK:'לא לקרוא עליי. לראות אותי.',framesT:'הסיפור, דרך הפריימים עצמם.',framesP:'16 רגעים חזותיים נבחרים מתוך קורפוס רחב יותר — ויראלי, טלוויזיה, StartOn, פודקאסטים, כתיבה ומוזיקה. כל פריים נשאר מחובר למקור ולסטטוס שלו.',source:'למקור',lifeK:'1990 → עכשיו',lifeT:'החיים בקו אחד.',lifeP:'לא כל שנה צריכה מערכת. מספיק לראות את המעבר: שייכות, שירות, חזרה, קול ציבורי, יצירה, מחקר — וההווה.',humanK:'אבא · אדם · עכשיו',humanT:'החיים לא נשארים מחוץ לפריים.',humanP:'משפחה, חזרה לשכונה ורגעים אנושיים הם חלק מהסיפור הציבורי — לא קישוט מסביבו.',nowK:'עכשיו · 2026',nowT:'מה אני בונה היום.',nowP:'ארבעה כיוונים, בלי לנסות להפוך אותם לארבעה אתרים.',starton:'StartOn',startonP:'נוער, טכנולוגיה, יצירה, ליווי והזדמנות.',public:'עשייה ציבורית',publicP:'ניסיון ממערכות ציבוריות שממשיך לעבודה, שיח ויוזמות בהווה.',media:'מדיה ויצירה',mediaP:'וידאו, ראיונות, כתיבה, מוזיקה ושיתופי פעולה.',research:'מחקר ורעיונות',researchP:'מסגרות חשיבה עצמאיות עם מקורות, סטטוס ומגבלות.',deepK:'הכול נשמר.',deepT:'הארכיון המלא נמצא שכבה אחת עמוק יותר.',deepP:'פוסטים, וידאו, כתבות, ראיונות, מוזיקה, מחקר ומקורות צד־ג׳ — ממוין לפי השפעה, זמן ושכבת אימות.',openArchive:'לפתוח את הארכיון',openMedia:'מדיה',openResearch:'מחקר',viewer:'צפייה בתוך 7YA',close:'סגירה',prev:'הקודם',next:'הבא',openSource:'פתיחת המקור',verification:'שכבת מקור'},
en:{eyebrow:'#7YA🥷 · IGOR VEPRETSKI',title:'Kharkiv to Jesse Cohen.\nService to StartOn.',lead:'I’m Igor. This is my story — childhood and immigration, service, fatherhood and a return to the neighborhood, then StartOn, creation, research and digital impact. See the path first; count it second.',watch:'Watch · selected moments',story:'Start in 1990',archive:'Open the archive',talk:'Digital Igor · 7YA AI tool',contact:'Book a conversation',evidence:'View evidence',framesK:'Do not read about me. See me.',framesT:'The story, through the frames themselves.',framesP:'Sixteen visual moments are selected from a wider corpus — viral records, television, StartOn, podcasts, writing and music. Every frame stays connected to its source and evidence status.',source:'Open source',lifeK:'1990 → NOW',lifeT:'The life in one line.',lifeP:'Not every year needs a system. The movement is enough: belonging, service, return, public voice, creation, research — and the present.',humanK:'FATHER · HUMAN · NOW',humanT:'Life does not stay outside the frame.',humanP:'Family, the return to the neighborhood and human moments belong to the public story rather than decorating its edges.',nowK:'RIGHT NOW · 2026',nowT:'What I am building now.',nowP:'Four directions, without turning them into four different websites.',starton:'StartOn',startonP:'Youth, technology, creation, guidance and opportunity.',public:'Public work',publicP:'Experience from public systems carried into current initiatives and public conversation.',media:'Media & creation',mediaP:'Video, interviews, writing, music and collaboration.',research:'Research & ideas',researchP:'Independent frameworks with sources, status and explicit limits.',deepK:'Everything stays.',deepT:'The full archive lives one layer deeper.',deepP:'Posts, video, press, interviews, music, research and third-party sources — sortable by impact, time and evidence layer.',openArchive:'Open the archive',openMedia:'Media',openResearch:'Research',viewer:'Watch inside 7YA',close:'Close',prev:'Previous',next:'Next',openSource:'Open source',verification:'Source layer'},
ru:{eyebrow:'#7YA🥷 · ИГОРЬ ВЕПРЕЦКИЙ',title:'Из Харькова в Джесси Коэн.\nОт службы к StartOn.',lead:'Я — Игорь. Это моя история: детство и репатриация, служба, отцовство и возвращение в район, затем StartOn, творчество, исследования и цифровое влияние. Сначала путь — потом цифры.',watch:'Смотреть · избранные моменты',story:'Начать с 1990',archive:'Открыть архив',talk:'Digital Igor · AI-инструмент 7YA',contact:'Назначить разговор',evidence:'Открыть доказательства',framesK:'Не читать обо мне. Увидеть меня.',framesT:'История — через сами кадры.',framesP:'Шестнадцать визуальных моментов выбраны из более широкого корпуса: вирусные записи, телевидение, StartOn, подкасты, тексты и музыка. Каждый кадр сохраняет связь с источником и статусом доказательства.',source:'Открыть источник',lifeK:'1990 → СЕЙЧАС',lifeT:'Жизнь одной линией.',lifeP:'Не каждому году нужна система. Достаточно увидеть движение: принадлежность, служба, возвращение, публичный голос, творчество, исследования и настоящее.',humanK:'ОТЕЦ · ЧЕЛОВЕК · СЕЙЧАС',humanT:'Жизнь не остаётся за пределами кадра.',humanP:'Семья, возвращение в район и человеческие моменты — часть публичной истории, а не украшение вокруг неё.',nowK:'СЕЙЧАС · 2026',nowT:'Что я строю сегодня.',nowP:'Четыре направления — без превращения их в четыре разных сайта.',starton:'StartOn',startonP:'Молодёжь, технологии, творчество, сопровождение и возможности.',public:'Общественная работа',publicP:'Опыт общественных систем в текущих инициативах и публичном разговоре.',media:'Медиа и творчество',mediaP:'Видео, интервью, тексты, музыка и коллаборации.',research:'Исследования и идеи',researchP:'Независимые модели с источниками, статусом и явными ограничениями.',deepK:'Всё сохраняется.',deepT:'Полный архив — на один слой глубже.',deepP:'Посты, видео, пресса, интервью, музыка, исследования и сторонние источники — с сортировкой по влиянию, времени и уровню проверки.',openArchive:'Открыть архив',openMedia:'Медиа',openResearch:'Исследования',viewer:'Смотреть внутри 7YA',close:'Закрыть',prev:'Назад',next:'Далее',openSource:'Открыть источник',verification:'Слой источника'}
} as const;
const layerText:Record<Layer,Local>={CANON:L('מאומת','Canon','Канон'),DISCOVERY:L('גילוי ציבורי','Discovery','Discovery'),LIVE:L('חי','Live','Live'),LEGACY:L('ארכיון','Archive','Архив'),PENDING:L('ממתין','Pending','Ожидает')};
const keyUrl=(raw:string)=>{try{const u=new URL(raw);u.hash='';['utm_source','utm_medium','utm_campaign','fbclid','igshid','si'].forEach(k=>u.searchParams.delete(k));return(u.origin+u.pathname+u.search).replace(/\/$/,'').toLowerCase()}catch{return raw.toLowerCase().replace(/\/$/,'')}};
const score=(item:Frame)=>({CANON:80,LIVE:70,LEGACY:55,DISCOVERY:45,PENDING:0}[item.layer]||0)+(item.mediaType==='video'?35:item.mediaType==='article'?25:item.mediaType==='audio'?20:10)+(/broadcast|press|podcast|external-repost/.test(item.sourceKind||'')?25:0)+(item.imageUrl||item.screenshotUrl?20:0)+((item.metrics?.length||0)*12);
function diverse(items:Frame[],limit:number){const out:Frame[]=[];const platforms=new Map<string,number>();const seen=new Set<string>();for(const item of [...items].sort((a,b)=>score(b)-score(a))){const key=keyUrl(item.sourceUrl);const p=item.publisher||item.platform;if(!key||seen.has(key)||(platforms.get(p)||0)>=2)continue;seen.add(key);platforms.set(p,(platforms.get(p)||0)+1);out.push(item);if(out.length>=limit)break}return out}
function mediaSrc(item:Frame){return item.imageUrl||item.screenshotUrl||''}
function youtubeId(raw:string){try{const u=new URL(raw);if(u.hostname==='youtu.be')return u.pathname.split('/').filter(Boolean)[0]||'';return u.searchParams.get('v')||u.pathname.match(/\/(?:shorts|embed)\/([^/?#]+)/)?.[1]||''}catch{return''}}
export default function DocumentaryHome(){const {locale,dir}=useLocale();const c=copy[locale];const [payload,setPayload]=useState<ProjectionPayload|null>(null);const [hero,setHero]=useState('./resources/igor-hero.jpg');const [selected,setSelected]=useState<number|null>(null);const {theme}=useSiteTheme();useEffect(()=>{let live=true;api.get('/api/public-projection?limit=60&sort=impact').then(r=>{if(live)setPayload(r.data as ProjectionPayload)}).catch(()=>{if(live)setPayload({items:[]})});return()=>{live=false}},[]);const eligible=useMemo(()=>{const dynamic=(payload?.items||[]).filter(item=>item.layer!=='PENDING'&&/^https:\/\//i.test(item.sourceUrl)&&item.mediaType!=='profile');const merged=[...dynamic,...fallback];const seen=new Set<string>();return merged.filter(item=>{const key=keyUrl(item.sourceUrl);if(!key||seen.has(key))return false;seen.add(key);return true})},[payload]);const featured=useMemo(()=>diverse(eligible,16),[eligible]);const timeline=useMemo(()=>['2011','2022','2023','2024','2025','2026'].map(year=>eligible.filter(item=>item.year===year||item.date.startsWith(year)).sort((a,b)=>score(b)-score(a))[0]).filter((item):item is Frame=>Boolean(item)),[eligible]);const human=useMemo(()=>['visual-father-hidabroot','visual-mial-maakav-2023','visual-mynet-return'].map(id=>fallback.find(item=>item.id===id)).filter((item):item is Frame=>Boolean(item&&mediaSrc(item))).slice(0,2),[]);const archive=pageHref('library',locale);const contact=rootHref('contact/');const evidence=rootHref('evidence/');const talk=pageHref('home',locale)+'&chat=open';const current=selected===null?null:featured[selected];const hideBroken=(event:SyntheticEvent<HTMLImageElement>)=>{event.currentTarget.hidden=true;event.currentTarget.parentElement?.classList.add('dh-media-missing')};const openViewer=(index:number)=>setSelected(index);const move=(delta:number)=>setSelected(value=>value===null?0:(value+delta+featured.length)%featured.length);useEffect(()=>{if(selected===null)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelected(null);if(event.key==='ArrowRight')move(1);if(event.key==='ArrowLeft')move(-1)};document.body.classList.add('dh-viewer-open');window.addEventListener('keydown',onKey);return()=>{document.body.classList.remove('dh-viewer-open');window.removeEventListener('keydown',onKey)}},[selected,featured.length]);const currentYoutube=current?youtubeId(current.sourceUrl):'';return <main className='dh' dir={dir} data-theme={theme}>
<a className='site-skip' href='#igor'>{locale==='he'?'דלג לתוכן':locale==='ru'?'Перейти к содержанию':'Skip to content'}</a><header className='dh-nav'><a className='dh-brand' href={pageHref('home',locale)}><b>7YA</b><span>IGOR VEPRETSKI</span></a><nav><a href='#story'>STORY</a><a href={archive}>ARCHIVE</a><a href={contact}>{c.contact}</a></nav><div className='dh-nav-controls'><SiteThemeToggle className='dh-theme-toggle'/><LanguageSwitcher compact/></div></header>
<section className='dh-hero' id='igor'><figure><img src={hero} alt='Igor Vepretski' width='960' height='1280' loading='eager' fetchPriority='high' decoding='async' onError={()=>setHero('https://drive.google.com/thumbnail?id=1n8eFERhkuHB_7StwJk74e6xDpDSdIzb2&sz=w2200')}/></figure><div className='dh-hero-shade'/><div className='dh-hero-copy'><p>{c.eyebrow}</p><h1>{c.title.split('\n').map((line,index)=><span key={line}>{line}{index===0&&<br/>}</span>)}</h1><h2>{c.lead}</h2><div className='dh-actions'><a className='dh-contact-command' href={contact}>{c.contact}<ArrowUpRight/></a><a className='dh-evidence-command' href={evidence}>{c.evidence}<BookOpen/></a><button className='dh-watch-command' type='button' onClick={()=>featured.length&&openViewer(0)}><Play fill='currentColor'/>{c.watch}</button><a className='dh-story-command' href='#story'>{c.story}<ArrowDown/></a><a className='dh-talk-command' href={talk}>{c.talk}<MessageCircle/></a><a className='dh-archive-command' href={archive}>{c.archive}<Search/></a></div></div><a className='dh-scroll' href='#story' aria-label={c.story}><ArrowDown/></a></section>
<NarrativeChapters/><ImpactFrontDoor/>
<section className='dh-frames' id='legacy-story-grid'><header className='dh-section-head'><p>{c.framesK}</p><h2>{c.framesT}</h2><span>{c.framesP}</span></header><div className='dh-frame-grid'>{featured.map((item,index)=><button className='dh-frame' type='button' onClick={()=>openViewer(index)} key={item.id}><figure>{mediaSrc(item)&&<img src={mediaSrc(item)} alt={item.title[locale]} loading={index<3?'eager':'lazy'} decoding='async' referrerPolicy='no-referrer' onError={hideBroken}/>}<div className='dh-poster'><small>{item.mediaType}</small><strong>{item.publisher}</strong></div>{item.mediaType==='video'&&<i><Play fill='currentColor'/></i>}<em>{String(index+1).padStart(2,'0')}</em></figure><div className='dh-frame-copy'><div><span>{layerText[item.layer][locale]}</span><time dir='ltr'>{item.year||item.date.slice(0,4)||'—'}</time></div><h3>{item.title[locale]}</h3><p>{item.publisher}</p>{item.metrics?.[0]&&<strong className='dh-frame-metric' dir='ltr'>{item.metrics[0].value}</strong>}<b>{c.viewer}<Play/></b></div></button>)}</div></section>
<section className='dh-life'><header className='dh-section-head'><p>{c.lifeK}</p><h2>{c.lifeT}</h2><span>{c.lifeP}</span></header><div className='dh-life-strip' dir='ltr'><article><b>1990</b><span>KHARKIV</span></article><article><b>1993</b><span>ISRAEL</span></article>{timeline.map(item=><a href={item.sourceUrl} target='_blank' rel='noreferrer' key={'tl-'+item.id}><b>{item.year}</b><span>{item.title[locale]}</span><small>{item.publisher}</small></a>)}<article><b>NOW</b><span>#7YA</span></article></div></section>
{human.length>0&&<section className='dh-human'><header className='dh-section-head'><p>{c.humanK}</p><h2>{c.humanT}</h2><span>{c.humanP}</span></header><div className='dh-human-grid'>{human.map(item=>{const index=featured.findIndex(frame=>keyUrl(frame.sourceUrl)===keyUrl(item.sourceUrl));return <button type='button' onClick={()=>index>=0?openViewer(index):window.open(item.sourceUrl,'_blank','noopener,noreferrer')} key={'human-'+item.id}><img src={mediaSrc(item)} alt={item.title[locale]} loading='lazy' referrerPolicy='no-referrer' onError={hideBroken}/><div><small>{item.year} · {item.publisher}</small><strong>{item.title[locale]}</strong><span>{layerText[item.layer][locale]}</span></div></button>})}</div></section>}
<section className='dh-now' id='now'><header className='dh-section-head'><p>{c.nowK}</p><h2>{c.nowT}</h2><span>{c.nowP}</span></header><div className='dh-now-grid'><a href={rootHref('starton/?lang='+locale)}><strong>{c.starton}</strong><p>{c.startonP}</p><ArrowUpRight/></a><a href={archive+'#public'}><strong>{c.public}</strong><p>{c.publicP}</p><ArrowUpRight/></a><a href={pageHref('media',locale)}><strong>{c.media}</strong><p>{c.mediaP}</p><ArrowUpRight/></a><a href={rootHref('research/?lang='+locale)}><strong>{c.research}</strong><p>{c.researchP}</p><ArrowUpRight/></a></div></section>
<section className='dh-deep'><div><p>{c.deepK}</p><h2>{c.deepT}</h2><span>{c.deepP}</span></div><nav><a href={archive}>{c.openArchive}<BookOpen/></a><a href={pageHref('media',locale)}>{c.openMedia}<Play/></a><a href={rootHref('research/?lang='+locale)}>{c.openResearch}<ArrowUpRight/></a></nav><small dir='ltr'>{payload?.knownTotal?payload.knownTotal+' PUBLIC OBJECTS · ':''}CANON / DISCOVERY / LIVE · SOURCE-LINKED</small></section>
<footer className='dh-footer'><b>#7YA🥷</b><span>IGOR VEPRETSKI · PUBLIC STORY · 1990—NOW</span><a href={talk}>{c.talk}<MessageCircle/></a></footer>
{current&&<div className='dh-viewer' role='dialog' aria-modal='true' aria-label={c.viewer} onMouseDown={event=>{if(event.currentTarget===event.target)setSelected(null)}}><article><header><div><small>{c.verification} · {layerText[current.layer][locale]} · {current.trust}</small><strong>{current.publisher}</strong></div><button type='button' onClick={()=>setSelected(null)} aria-label={c.close}><X/><span>{c.close}</span></button></header><div className='dh-viewer-stage'>{currentYoutube?<iframe src={'https://www.youtube-nocookie.com/embed/'+currentYoutube+'?autoplay=1&rel=0'} title={current.title[locale]} allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share' allowFullScreen/>:mediaSrc(current)?<img src={mediaSrc(current)} alt={current.title[locale]} referrerPolicy='no-referrer'/>:<div className='dh-viewer-poster'><Play/><span>{current.mediaType}</span></div>}</div><section><small dir='ltr'>{current.year||current.date} · {current.platform}</small><h2>{current.title[locale]}</h2>{current.metrics?.length?<div className='dh-viewer-metrics'>{current.metrics.map(metric=><b key={metric.label+metric.value}>{metric.value}<span>{metric.label}</span></b>)}</div>:null}</section><footer><button type='button' onClick={()=>move(-1)}><ChevronLeft/>{c.prev}</button><a href={current.sourceUrl} target='_blank' rel='noreferrer'>{c.openSource}<ArrowUpRight/></a><button type='button' onClick={()=>move(1)}>{c.next}<ChevronRight/></button></footer></article></div>}
</main>}
