export type EntityKind='person'|'place'|'institution';
export type EntityTruth='VERIFIED'|'STRONGLY_INFERRED'|'REQUIRES_CONFIRMATION';
export type EntityLocale={he:string;en:string;ru:string};
export type EntitySource={id:string;label:string;url:string;kind:'press'|'broadcast'|'podcast'|'public-profile'|'official-registry'|'authored-publication'|'documented-trace'};
export type CanonicalEntity={id:string;kind:EntityKind;label:EntityLocale;relation:EntityLocale;truthStatus:EntityTruth;sources:EntitySource[];relatedEventIds:string[];tags:string[]};
const L=(he:string,en:string,ru:string):EntityLocale=>({he,en,ru});
export const CANONICAL_ENTITIES_RELEASE='CANONICAL-ENTITIES-20260822-1';
export const canonicalEntities:CanonicalEntity[]=[
{id:'place-kharkiv',kind:'place',label:L('חרקוב, אוקראינה','Kharkiv, Ukraine','Харьков, Украина'),relation:L('מקום הלידה ונקודת הפתיחה של מסע ההגירה.','Birthplace and the starting point of the migration story.','Место рождения и отправная точка истории миграции.'),truthStatus:'VERIFIED',sources:[{id:'kharkiv-2011',label:'Makor Rishon / NRG · 2011 public profile',url:'https://www.makorrishon.co.il/nrg/online/54/ART2/235/169.html',kind:'press'},{id:'kharkiv-medium',label:'Medium · authored life essay',url:'https://medium.com/@igor.vepretski/igor-vepretski-from-troubled-beginnings-to-social-impact-a-journey-of-resilience-and-purpose-253aa8af266d',kind:'authored-publication'}],relatedEventIds:['origin-belonging-1990s'],tags:['ORIGIN','UKRAINE','MIGRATION']},
{id:'place-bat-yam',kind:'place',label:L('בת ים','Bat Yam','Бат-Ям'),relation:L('תחנת החיים הראשונה בישראל לאחר העלייה.','The first documented life stop in Israel after immigration.','Первая документированная точка жизни в Израиле после репатриации.'),truthStatus:'VERIFIED',sources:[{id:'batyam-2011',label:'Makor Rishon / NRG · 2011 public profile',url:'https://www.makorrishon.co.il/nrg/online/54/ART2/235/169.html',kind:'press'},{id:'batyam-mynet',label:'mynet Holon · 2022 profile',url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',kind:'press'}],relatedEventIds:['origin-belonging-1990s'],tags:['ISRAEL','CHILDHOOD','MIGRATION']},
{id:'place-jesse-cohen',kind:'place',label:L('ג׳סי כהן / חולון','Jesse Cohen / Holon','Джесси Коэн / Холон'),relation:L('שכונת הילדות שחזרה מאוחר יותר כזירת הפעולה של StartOn.','The childhood neighborhood that later returned as the operating context for StartOn.','Район детства, позднее ставший контекстом деятельности StartOn.'),truthStatus:'VERIFIED',sources:[{id:'jesse-mynet',label:'mynet Holon · Return to the neighborhood',url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',kind:'press'},{id:'jesse-mindset',label:'Mindset · life and StartOn conversation',url:'https://mindset.org.il/%D7%9E%D7%A0%D7%A2%D7%A8-%D7%91%D7%A1%D7%99%D7%9B%D7%95%D7%9F-%D7%9C%D7%99%D7%96%D7%9D-%D7%97%D7%91%D7%A8%D7%AA%D7%99-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%A4/',kind:'podcast'}],relatedEventIds:['origin-belonging-1990s','starton-return-2022','starton-registration-2022'],tags:['HOLON','JESSE COHEN','STARTON','RETURN']},
{id:'place-miami',kind:'place',label:L('מיאמי, פלורידה','Miami, Florida','Майами, Флорида'),relation:L('LinkedIn הציבורי מציג תקופת ניסיון מקצועי במיאמי; התפקיד והטווח המדויק אינם מפורשים בצילום הציבורי ולכן אינם נטענים כאן.','The public LinkedIn profile lists a professional-experience location in Miami; the role and exact period are not explicit in the public crawl and are therefore not asserted here.','Публичный LinkedIn указывает профессиональный опыт в Майами; роль и точный период в публичном снимке не раскрыты и здесь не утверждаются.'),truthStatus:'STRONGLY_INFERRED',sources:[{id:'miami-linkedin',label:'LinkedIn · public experience locations',url:'https://il.linkedin.com/in/vepretski/iw',kind:'public-profile'}],relatedEventIds:['mfa-overseas-employment-2012-2014'],tags:['USA','MIAMI','PROFESSIONAL EXPERIENCE','CONTEXT LIMITED']},
{id:'place-chicago',kind:'place',label:L('שיקגו, אילינוי','Chicago, Illinois','Чикаго, Иллинойс'),relation:L('LinkedIn הציבורי מציג תקופת ניסיון מקצועי בשיקגו; ההקשר המלא עדיין דורש השלמת מקור.','The public LinkedIn profile lists professional experience in Chicago; the full context still needs a stronger source.','Публичный LinkedIn указывает профессиональный опыт в Чикаго; полный контекст требует более сильного источника.'),truthStatus:'STRONGLY_INFERRED',sources:[{id:'chicago-linkedin',label:'LinkedIn · public experience locations',url:'https://il.linkedin.com/in/vepretski/iw',kind:'public-profile'}],relatedEventIds:['mfa-overseas-employment-2012-2014'],tags:['USA','CHICAGO','PROFESSIONAL EXPERIENCE','CONTEXT LIMITED']},
{id:'person-shlomi-haster',kind:'person',label:L('שלומי חסטר','Shlomi Haster','Шломи Хастер'),relation:L('מארח Mindset בשיחת עומק פומבית על מסע החיים, שינוי תפיסה ו־StartOn.','Mindset host in a public long-form conversation about the life journey, mindset change and StartOn.','Ведущий Mindset в публичном длинном разговоре о жизненном пути, смене мышления и StartOn.'),truthStatus:'VERIFIED',sources:[{id:'haster-mindset',label:'Mindset · episode 102',url:'https://mindset.org.il/%D7%9E%D7%A0%D7%A2%D7%A8-%D7%91%D7%A1%D7%99%D7%9B%D7%95%D7%9F-%D7%9C%D7%99%D7%96%D7%9D-%D7%97%D7%91%D7%A8%D7%AA%D7%99-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%A4/',kind:'podcast'},{id:'haster-spotify',label:'Spotify · public episode',url:'https://open.spotify.com/episode/42PO14etZLk1D1hvkTUP1h',kind:'podcast'}],relatedEventIds:['mindset-social-entrepreneur-2022-09-20','register-igor-podcast-mindset'],tags:['PODCAST','MINDSET','PUBLIC CONVERSATION']},
{id:'person-freddy-moskovitz',kind:'person',label:L('פרדי מוסקוביץ׳','Freddy Moskovitz','Фредди Московиц'),relation:L('מראיין בשיחות ציבוריות על נוער בסיכון, אחריות ומסע החיים.','Interviewer in public conversations about youth at risk, responsibility and the life journey.','Интервьюер в публичных беседах о молодежи группы риска, ответственности и жизненном пути.'),truthStatus:'VERIFIED',sources:[{id:'freddy-youtube',label:'Public YouTube interview',url:'https://www.youtube.com/watch?v=U2d_hulZAC0',kind:'broadcast'},{id:'freddy-nadlan',label:'נדל״ן וירושה · episode 29',url:'https://www.nadlanveyerusha.co.il/%D7%93%D7%99%D7%A8%D7%95%D7%AA-%D7%99%D7%A8%D7%95%D7%A9%D7%94/',kind:'podcast'}],relatedEventIds:['register-youth-radio','register-nadlan-interview'],tags:['INTERVIEW','YOUTH','PUBLIC CONVERSATION']},
{id:'person-barak-seri',kind:'person',label:L('ברק סרי','Barak Seri','Барак Сери'),relation:L('עקבת ארכיון מתעדת ראיון אצל ברק סרי ב־2025; דף מו״ל קנוני של 103FM טרם שוחזר ולכן הקשר נשאר לאישור.','An archive trace documents a 2025 interview with Barak Seri; the canonical 103FM publisher page has not yet been recovered, so the relationship remains pending confirmation.','Архивный след фиксирует интервью у Барака Сери в 2025 году; каноническая страница 103FM пока не восстановлена, поэтому связь требует подтверждения.'),truthStatus:'REQUIRES_CONFIRMATION',sources:[{id:'seri-trace',label:'Documented interview trace · canonical publisher pending',url:'https://vepretski.blogspot.com/2025/08/103fmradio.html',kind:'documented-trace'}],relatedEventIds:['register-barak-seri-103fm-trace'],tags:['INTERVIEW TRACE','103FM','PUBLISHER PENDING']},
{id:'institution-starton',kind:'institution',label:L('StartOn','StartOn','StartOn'),relation:L('העמותה שהופכת ניסיון חיים למודל של טכנולוגיה, יצירה ושייכות לנוער.','The nonprofit translating lived experience into a youth model of technology, creation and belonging.','НКО, превращающая жизненный опыт в молодежную модель технологий, творчества и принадлежности.'),truthStatus:'VERIFIED',sources:[{id:'starton-registry',label:'GuideStar / Israeli Corporations Authority',url:'https://www.guidestar.org.il/organization/580752814',kind:'official-registry'},{id:'starton-mynet-entity',label:'mynet Holon · public profile',url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',kind:'press'}],relatedEventIds:['starton-registration-2022','starton-return-2022'],tags:['STARTON','NONPROFIT','YOUTH','TECHNOLOGY']},
{id:'institution-israel-police',kind:'institution',label:L('משטרת ישראל','Israel Police','Полиция Израиля'),relation:L('שכבת שירות ציבורי מתועדת בין 2015 ל־2021; התאריכים המדויקים מאומתים במסמך רשמי פרטי וההקשר מגובה בפומבי.','A documented public-service layer from 2015 to 2021; exact dates are privately verified by an official record and the context is publicly corroborated.','Документированный этап государственной службы с 2015 по 2021 год; точные даты подтверждены частным официальным документом, контекст — публичными источниками.'),truthStatus:'VERIFIED',sources:[{id:'police-mynet-entity',label:'mynet Holon · public profile',url:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',kind:'press'},{id:'police-channel13-entity',label:'Channel 13 · public transition story',url:'https://prod.13tv.co.il/item/news/haolam-haboker/season-01/clips/u0uoy-903061791/?pid=44',kind:'broadcast'}],relatedEventIds:['israel-police-service-2015-2021','service-field-2011-2021'],tags:['PUBLIC SERVICE','POLICE','INTELLIGENCE','INVESTIGATIONS']},
{id:'institution-hebrew-university',kind:'institution',label:L('האוניברסיטה העברית בירושלים','The Hebrew University of Jerusalem','Еврейский университет в Иерусалиме'),relation:L('עוגן אקדמי מתועד בלימודי קרימינולוגיה בשנים 2018–2020.','A documented academic anchor in Criminology studies during 2018–2020.','Документированный академический этап изучения криминологии в 2018–2020 годах.'),truthStatus:'VERIFIED',sources:[{id:'huji-linkedin-entity',label:'LinkedIn · public education record',url:'https://il.linkedin.com/in/vepretski/iw',kind:'public-profile'}],relatedEventIds:['hebrew-university-criminology-2018-2020'],tags:['ACADEMIA','CRIMINOLOGY','HEBREW UNIVERSITY']}
];
const norm=(value:string)=>value.trim().toLowerCase();
export function searchCanonicalEntities(query:{q?:string;kind?:string}={}){const q=norm(query.q||'');const kind=norm(query.kind||'');return canonicalEntities.filter(entity=>(!kind||entity.kind===kind)&&(!q||norm([entity.id,entity.label.he,entity.label.en,entity.label.ru,entity.relation.he,entity.relation.en,entity.relation.ru,...entity.tags,...entity.sources.map(source=>source.label)].join(' ')).includes(q)))}
export function entityCoverageRows(){const row=(domain:string,kind:EntityKind)=>{const matches=canonicalEntities.filter(entity=>entity.kind===kind);return{domain,known:matches.length,published:matches.filter(entity=>entity.sources.length>0).length,missing:matches.length===0,weak:matches.filter(entity=>entity.truthStatus==='STRONGLY_INFERRED').length,unverified:matches.filter(entity=>entity.truthStatus==='REQUIRES_CONFIRMATION').length}};return{People:row('People','person'),Places:row('Places','place')}}
