import type {CanonicalEvent,CanonicalSource,CorpusSurface,DateBasis,DatePrecision,VerificationState} from './canonical-corpus';
import {deepMedia,type DeepMediaItem} from '../src/deep-media-data';
import {webDiscoveryItems} from '../src/web-discovery-data';

type DateShape={canonicalDate:string;datePrecision:DatePrecision;dateBasis:DateBasis;dateNote:string;period?:{start:string;end?:string}};
const canonicalUrl=(value:string)=>value.trim().replace(/[?#].*$/,'').replace(/\/$/,'').toLowerCase();
const dateShape=(value:string):DateShape=>{const exact=value.match(/(\d{2})\.(\d{2})\.(\d{4})/);if(exact)return{canonicalDate:`${exact[3]}-${exact[2]}-${exact[1]}`,datePrecision:'exact-day',dateBasis:/snapshot/i.test(value)?'snapshot':'publication',dateNote:`Imported public-register date label: ${value}.`};const years=value.match(/(?:19|20)\d{2}/g)||[];if(years.length){const unique=[...new Set(years)];return{canonicalDate:`${unique[0]}-01-01`,datePrecision:unique.length>1?'era':'year',dateBasis:/snapshot/i.test(value)?'snapshot':'publication',dateNote:`Year/era-only public-register label: ${value}; January 1 is an ordering anchor, not a day-level claim.`,...(unique.length>1?{period:{start:unique[0],end:unique[unique.length-1]}}:{})}}return{canonicalDate:'undated',datePrecision:'unknown',dateBasis:'publication',dateNote:`Public-register item has no recoverable publication date (${value}); no date is asserted.`}};
const verification=(status:string):VerificationState=>/QUARANTIN|DISPUTED/i.test(status)?'quarantined':/PENDING/i.test(status)?'unresolved':/OWNER/i.test(status)?'owner-reported':/VERIFIED/i.test(status)?'verified':/DOCUMENTED|INDEXED|PUBLIC|OFFICIAL|SOURCE LINKED|CONNECTOR|WEB DISCOVERY/i.test(status)?'supported':'supported';
const platformOf=(item:DeepMediaItem)=>{const value=(item.url+' '+item.source).toLowerCase();if(/youtube|youtu\.be/.test(value))return'YouTube';if(/instagram/.test(value))return'Instagram';if(/facebook/.test(value))return'Facebook';if(/linkedin/.test(value))return'LinkedIn';if(/tiktok/.test(value))return'TikTok';if(/spotify/.test(value))return'Spotify';if(/apple\.com/.test(value))return'Apple Music';if(/soundcloud/.test(value))return'SoundCloud';if(/medium/.test(value))return'Medium';return undefined};
const sourceKind=(item:DeepMediaItem):CanonicalSource['kind']=>{const value=(item.url+' '+item.source).toLowerCase();if(item.category==='פודקאסטים')return'podcast';if(item.category==='טלוויזיה'||/youtube|youtu\.be|13tv/.test(value))return'broadcast';if(item.category==='עיתונות')return'press';if(item.category==='כתיבה')return'authored-column';if(item.category==='ויראלי')return'external-repost';if(item.category==='StartOn'&&/starton\.org/.test(value))return'official-site';if(/\/reel\/|\/posts\/|activity-/.test(value))return'owned-public-post';return'public-profile'};
const eventType=(item:DeepMediaItem):CanonicalEvent['type']=>item.category==='כתיבה'?'writing':item.category==='מוזיקה'?'music':item.category==='ויראלי'?'post':item.category==='StartOn'?'media':item.category==='רשתות'?'media':'media';
const surfaces=(item:DeepMediaItem):CorpusSurface[]=>item.category==='כתיבה'?['writing','media','archive']:item.category==='מוזיקה'?['music','archive']:item.category==='ויראלי'?['influence','media','archive']:item.category==='StartOn'?['starton','media','archive']:item.category==='רשתות'?['influence','archive']:['media','archive'];
const isExternalImage=(value:string)=>/^https?:\/\//i.test(value);
function toEvent(item:DeepMediaItem,index:number):CanonicalEvent{const date=dateShape(item.year);const state=verification(item.status);const platform=platformOf(item);const video=/youtube|youtu\.be/i.test(item.url);const media:CanonicalEvent['media']=isExternalImage(item.image)?[{kind:'image',url:item.image,sourceUrl:item.url,authenticity:'publisher-source',label:`Public source visual · ${item.source}`}]:video?[{kind:'video',url:item.url,sourceUrl:item.url,authenticity:'publisher-source',label:`Public video source · ${item.source}`}]:[{kind:'source-card',sourceUrl:item.url,authenticity:'source-object',label:`Public source object · ${item.source}`}];return{id:`register-${item.id}`,storyOrder:20000+index,canonicalDate:date.canonicalDate,datePrecision:date.datePrecision,dateBasis:date.dateBasis,dateNote:date.dateNote,...(date.period?{period:date.period}:{}),type:eventType(item),surfaces:surfaces(item),title:{he:item.title,en:item.title,ru:item.title},summary:{he:item.summary,en:item.summary,ru:item.summary},visibility:'public',verification:{state,note:`Migrated from the pre-canon public register. Legacy status: ${item.status}.${item.metric?' Untyped legacy metric text is intentionally not promoted into CanonicalMetric until a dated source-local snapshot is attached.':''}`},sources:[{id:`register-source-${item.id}`,label:`${item.source} · ${item.status}`,url:item.url,kind:sourceKind(item),public:true,...(platform?{platform}:{})}],media,impact:{state:'not-scored',signals:item.category==='ויראלי'?['Public-register propagation record']:[]},tags:['PUBLIC REGISTER',item.category.toUpperCase(),item.source.toUpperCase(),...(item.language?[item.language.toUpperCase()]:[]),...(item.metric?['UNTYPED METRIC HELD']:[])]}}
export const publicRegisterItems:DeepMediaItem[]=[...deepMedia,...webDiscoveryItems];
export function mergePublicRegisterIntoCanon(base:CanonicalEvent[]){const urls=new Set(base.flatMap(event=>event.sources.filter(source=>source.public).map(source=>canonicalUrl(source.url))));const ids=new Set(base.map(event=>event.id));const extras:CanonicalEvent[]=[];publicRegisterItems.forEach((item,index)=>{const url=canonicalUrl(item.url);const id=`register-${item.id}`;if(!url||urls.has(url)||ids.has(id))return;const event=toEvent(item,index);extras.push(event);urls.add(url);ids.add(id)});return[...base,...extras]}
export function publicRegisterContributionCount(base:CanonicalEvent[]){return mergePublicRegisterIntoCanon(base).length-base.length}
