import type {CanonicalEvent,CanonicalSource} from './canonical-corpus';
import type {EvidenceFirstProjection} from './evidence-first-ingestion';
import {canonicalEntities,type CanonicalEntity} from './canonical-entities';
import {historicalPlaylistPublications,recoveredPublicationRegistry,recoveredYouTubePublications,urlPendingPublications,type RecoveredPublicationSeed} from './recovered-publications';

export const PUBLIC_INTERNET_GRAPH_RELEASE='PUBLIC-INTERNET-GRAPH-20260823-3';
export type PublicInternetNodeKind='Person'|'PublicationRecord'|'ContentObject'|'Moment'|'Entity'|'Evidence';
export type PublicInternetTruth='VERIFIED'|'SUPPORTED'|'INFERRED'|'OWNER_REPORTED'|'REQUIRES_CONFIRMATION'|'QUARANTINED';
export type PublicInternetEdgeType='HAS_CONTENT'|'LIVED_MOMENT'|'PUBLISHED_AS'|'ABOUT_MOMENT'|'SUPPORTED_BY'|'EVIDENCE_POINTS_TO'|'INVOLVES'|'CONNECTED_TO'|'AMPLIFIES'|'RELATED_TO'|'RECOVERED_AS'|'AUTHORED_BY'|'PUBLISHED_BY'|'APPEARED_IN'|'INTERVIEWED_BY'|'REDISTRIBUTED_BY'|'MIRRORED_BY'|'BELONGS_TO_PROJECT'|'PART_OF_PLAYLIST'|'TRANSCRIPT_OF'|'EVIDENCES'|'CONTRADICTS'|'SUPERSEDES'|'LEGACY_OF';
export type PublicInternetNode={id:string;kind:PublicInternetNodeKind;label:string;canonicalId?:string;date?:string;truthStatus:PublicInternetTruth;url?:string;platform?:string;tags:string[];data:Record<string,unknown>};
export type PublicInternetEdge={id:string;type:PublicInternetEdgeType;from:string;to:string;truthStatus:PublicInternetTruth;sourceUrls:string[]};
export type PublicInternetGraph={release:string;schemaVersion:5;sourceSchemaVersion:2;rootPersonId:string;nodes:PublicInternetNode[];edges:PublicInternetEdge[];stats:{canonicalEvents:number;kinds:Record<PublicInternetNodeKind,number>;relationships:Record<PublicInternetEdgeType,number>;verifiedNodes:number;requiresConfirmationNodes:number;recoveryRegistryRecords:number;recoveredYouTubeRecords:number;curatedHistoricalCollections:number;knownEntityUrlPending:number}};
export type PublicInternetGraphQuery={q?:string;kind?:string;year?:string;topic?:string;platform?:string;verification?:string;limit?:number};

const rootPersonId='person:igor-vepretski';
const unique=(values:Array<string|undefined>)=>[...new Set(values.filter((value):value is string=>Boolean(value&&value.trim())).map(value=>value.trim()))];
const norm=(value:string)=>value.trim().toLowerCase();
const hash=(value:string)=>{let result=2166136261;for(let i=0;i<value.length;i++){result^=value.charCodeAt(i);result=Math.imul(result,16777619)}return(result>>>0).toString(36)};
const canonicalUrl=(value:string)=>{const input=value.trim();if(!/^https?:\/\//i.test(input))return input;try{const url=new URL(input);url.hash='';for(const key of [...url.searchParams.keys()])if(/^utm_/i.test(key)||['fbclid','gclid','mc_cid','mc_eid','igshid','si'].includes(key.toLowerCase()))url.searchParams.delete(key);url.searchParams.sort();if(url.pathname.length>1)url.pathname=url.pathname.replace(/\/+$/,'');return url.toString()}catch{return input}};
const truth=(state:string):PublicInternetTruth=>state==='verified'?'VERIFIED':state==='supported'?'SUPPORTED':state==='inferred'?'INFERRED':state==='owner-reported'?'OWNER_REPORTED':state==='quarantined'||state==='contradicted'?'QUARANTINED':'REQUIRES_CONFIRMATION';
const publicationRole=(kind:string)=>kind==='owned-public-post'?'owned-publication':kind==='external-repost'?'repost':kind==='press'||kind==='broadcast'||kind==='podcast'||kind==='authored-column'?'publisher-publication':kind==='official-site'?'institutional-source':kind==='public-profile'?'identity-mirror':'evidence-source';
const edgeId=(type:PublicInternetEdgeType,from:string,to:string)=>'edge:'+hash(type+'|'+from+'|'+to);
const addEdge=(edges:Map<string,PublicInternetEdge>,type:PublicInternetEdgeType,from:string,to:string,truthStatus:PublicInternetTruth,sourceUrls:string[])=>{const edge={id:edgeId(type,from,to),type,from,to,truthStatus,sourceUrls:unique(sourceUrls)};edges.set(edge.id,edge)};
const canonicalPublicationData=(event:CanonicalEvent,source:CanonicalSource,momentId:string)=>({person:rootPersonId,date:source.publishedAt||event.canonicalDate,era:event.period||event.subjectPeriod||null,platform:source.platform||null,sourceType:source.kind,title:source.label,url:source.url,originalRepost:publicationRole(source.kind),publisher:source.label,people:[],project:event.surfaces.includes('starton')?'StartOn':null,topics:[...event.tags],language:null,mediaType:source.kind,metrics:event.metrics||[],metricsDate:(event.metrics||[]).map(metric=>metric.snapshotDate),evidenceStatus:event.verification.state,archiveStatus:'CANONICAL_SOURCE',srtTranscript:'NOT_ATTACHED',imageThumbnail:event.media.find(media=>media.kind==='image')?.url||null,relatedMoments:[momentId],relatedSources:event.sources.filter(item=>item.public).map(item=>item.url),relatedPeople:[],relatedPosts:event.type==='post'?[event.id]:[],relatedProjects:event.type==='project'?[event.id]:[],canonicalEntity:rootPersonId,sourceId:source.id,publicationRole:publicationRole(source.kind),canonicalUrl:canonicalUrl(source.url)});
const recoveredPublicationData=(seed:RecoveredPublicationSeed)=>({person:rootPersonId,date:null,era:null,platform:seed.platform,sourceType:seed.mediaType==='video'?'video-recovery':seed.mediaType==='playlist'?'playlist-recovery':'known-public-node',title:seed.title,url:seed.url||null,originalRepost:'unknown',publisher:seed.platform,people:[],project:null,topics:[...seed.tags],language:null,mediaType:seed.mediaType,metrics:null,metricsDate:null,evidenceStatus:seed.archiveStatus==='RECOVERED'?'RECOVERED_SOURCE':'KNOWN_ENTITY_URL_PENDING',archiveStatus:seed.archiveStatus,srtTranscript:'PENDING',imageThumbnail:seed.youtubeId?'https://i.ytimg.com/vi/'+seed.youtubeId+'/hqdefault.jpg':null,relatedMoments:[],relatedSources:seed.url?[seed.url]:[],relatedPeople:[],relatedPosts:[],relatedProjects:[],canonicalEntity:rootPersonId,registryId:seed.id,metadataStatus:seed.metadataStatus,collectionStatus:seed.collectionStatus||null,youtubeId:seed.youtubeId||null,playlistId:seed.playlistId||null});

function addRecoveredRegistry(nodes:Map<string,PublicInternetNode>,edges:Map<string,PublicInternetEdge>){for(const seed of recoveredPublicationRegistry){const normalized=seed.url?canonicalUrl(seed.url):'';const publicationId=normalized?'publication:'+hash(normalized):'publication-pending:'+seed.id;const existing=nodes.get(publicationId);if(existing){nodes.set(publicationId,{...existing,tags:unique([...existing.tags,...seed.tags]),data:{...existing.data,recoveryRegistryId:seed.id,recoveryArchiveStatus:'RECOVERED_AND_CANONICAL',recoveryMetadataStatus:'SOURCE_METADATA_PRESENT',collectionStatus:seed.collectionStatus||existing.data.collectionStatus||null,youtubeId:seed.youtubeId||existing.data.youtubeId||null,playlistId:seed.playlistId||existing.data.playlistId||null}})}else{nodes.set(publicationId,{id:publicationId,kind:'PublicationRecord',label:seed.title,truthStatus:'REQUIRES_CONFIRMATION',url:seed.url,platform:seed.platform,tags:[...seed.tags],data:recoveredPublicationData(seed)})}addEdge(edges,'RECOVERED_AS',rootPersonId,publicationId,existing?.truthStatus||'REQUIRES_CONFIRMATION',seed.url?[seed.url]:[])}}

export function projectPublicInternetGraph(events:CanonicalEvent[],entities:CanonicalEntity[]=canonicalEntities):PublicInternetGraph{
  const publicEvents=events.filter(event=>event.visibility==='public'&&event.sources.some(source=>source.public));
  const eventIds=new Set(publicEvents.map(event=>event.id));
  const nodes=new Map<string,PublicInternetNode>();
  const edges=new Map<string,PublicInternetEdge>();
  nodes.set(rootPersonId,{id:rootPersonId,kind:'Person',label:'Igor Vepretski',truthStatus:'VERIFIED',tags:['IGOR VEPRETSKI','איגור ופרצקי','ИГОРЬ ВЕПРЕЦКИЙ','IDO VEPRETSKI','#7YA'],data:{aliases:['Igor Vepretski','Igor Ido Vepretski','Ido Vepretski','איגור ופרצקי','Игорь Вепрецкий'],canonicalHome:'https://7ya.io'}});
  for(const event of publicEvents){
    const status=truth(event.verification.state);const contentId='content:'+event.id;const momentId='moment:'+event.id;const sourceUrls=event.sources.filter(source=>source.public).map(source=>source.url);
    nodes.set(contentId,{id:contentId,kind:'ContentObject',label:event.title.en,canonicalId:event.id,date:event.canonicalDate,truthStatus:status,tags:[...event.tags],data:{canonicalType:event.type,title:event.title,summary:event.summary,surfaces:event.surfaces,verification:event.verification,impact:event.impact}});
    nodes.set(momentId,{id:momentId,kind:'Moment',label:event.title.en,canonicalId:event.id,date:event.canonicalDate,truthStatus:status,tags:[...event.tags],data:{title:event.title,summary:event.summary,datePrecision:event.datePrecision,dateBasis:event.dateBasis,dateNote:event.dateNote,period:event.period,subjectPeriod:event.subjectPeriod}});
    addEdge(edges,'HAS_CONTENT',rootPersonId,contentId,status,sourceUrls);addEdge(edges,'LIVED_MOMENT',rootPersonId,momentId,status,sourceUrls);addEdge(edges,'ABOUT_MOMENT',contentId,momentId,status,sourceUrls);
    for(const source of event.sources.filter(item=>item.public)){
      const normalized=canonicalUrl(source.url);const publicationId='publication:'+hash(normalized);
      if(!nodes.has(publicationId))nodes.set(publicationId,{id:publicationId,kind:'PublicationRecord',label:source.label,date:source.publishedAt,truthStatus:status,url:source.url,platform:source.platform,tags:[source.kind.toUpperCase(),publicationRole(source.kind).toUpperCase()],data:canonicalPublicationData(event,source,momentId)});
      addEdge(edges,'PUBLISHED_AS',contentId,publicationId,status,[source.url]);if(source.kind==='external-repost')addEdge(edges,'AMPLIFIES',publicationId,contentId,status,[source.url]);
      const evidenceId='evidence:'+hash(event.id+'|'+normalized);nodes.set(evidenceId,{id:evidenceId,kind:'Evidence',label:'Evidence · '+source.label,canonicalId:event.id,date:source.publishedAt||event.canonicalDate,truthStatus:status,url:source.url,platform:source.platform,tags:['EVIDENCE',source.kind.toUpperCase()],data:{verificationState:event.verification.state,verificationNote:event.verification.note,sourceId:source.id,sourceKind:source.kind,canonicalEntity:rootPersonId}});addEdge(edges,'SUPPORTED_BY',contentId,evidenceId,status,[source.url]);addEdge(edges,'EVIDENCE_POINTS_TO',evidenceId,publicationId,status,[source.url]);
    }
    for(const relatedId of event.relatedEventIds||[])if(eventIds.has(relatedId))addEdge(edges,'RELATED_TO',contentId,'content:'+relatedId,status,sourceUrls);
    const evidenceFirst=(event as CanonicalEvent&{evidenceFirst?:EvidenceFirstProjection}).evidenceFirst;
    for(const relation of evidenceFirst?.relationships||[]){const targetId=relation.target===rootPersonId?rootPersonId:eventIds.has(relation.target)?'content:'+relation.target:'entity:ingestion:'+hash(relation.target);if(!nodes.has(targetId)&&!targetId.startsWith('content:'))nodes.set(targetId,{id:targetId,kind:'Entity',label:relation.target,truthStatus:status,tags:['INGESTION-RELATION',relation.type],data:{relationshipTarget:relation.target,source:'evidence-first-ingestion'}});addEdge(edges,relation.type,contentId,targetId,status,sourceUrls)}
  }
  for(const entity of entities){const entityId='entity:'+entity.id;const entitySources=entity.sources.map(source=>source.url);const entityTruth=truth(entity.truthStatus==='VERIFIED'?'verified':entity.truthStatus==='STRONGLY_INFERRED'?'inferred':'unresolved');nodes.set(entityId,{id:entityId,kind:'Entity',label:entity.label.en,truthStatus:entityTruth,tags:[entity.kind.toUpperCase(),...entity.tags],data:{entityKind:entity.kind,label:entity.label,relation:entity.relation,entityId:entity.id}});addEdge(edges,'CONNECTED_TO',rootPersonId,entityId,entityTruth,entitySources);for(const relatedId of entity.relatedEventIds)if(eventIds.has(relatedId))addEdge(edges,'INVOLVES','moment:'+relatedId,entityId,entityTruth,entitySources)}
  addRecoveredRegistry(nodes,edges);
  const nodeList=[...nodes.values()].sort((a,b)=>a.kind.localeCompare(b.kind)||a.id.localeCompare(b.id));const edgeList=[...edges.values()].sort((a,b)=>a.type.localeCompare(b.type)||a.id.localeCompare(b.id));
  const nodeKinds:PublicInternetNodeKind[]=['Person','PublicationRecord','ContentObject','Moment','Entity','Evidence'];const edgeKinds:PublicInternetEdgeType[]=['HAS_CONTENT','LIVED_MOMENT','PUBLISHED_AS','ABOUT_MOMENT','SUPPORTED_BY','EVIDENCE_POINTS_TO','INVOLVES','CONNECTED_TO','AMPLIFIES','RELATED_TO','RECOVERED_AS','AUTHORED_BY','PUBLISHED_BY','APPEARED_IN','INTERVIEWED_BY','REDISTRIBUTED_BY','MIRRORED_BY','BELONGS_TO_PROJECT','PART_OF_PLAYLIST','TRANSCRIPT_OF','EVIDENCES','CONTRADICTS','SUPERSEDES','LEGACY_OF'];
  const kinds=Object.fromEntries(nodeKinds.map(kind=>[kind,nodeList.filter(node=>node.kind===kind).length])) as Record<PublicInternetNodeKind,number>;const relationships=Object.fromEntries(edgeKinds.map(kind=>[kind,edgeList.filter(edge=>edge.type===kind).length])) as Record<PublicInternetEdgeType,number>;
  return{release:PUBLIC_INTERNET_GRAPH_RELEASE,schemaVersion:5,sourceSchemaVersion:2,rootPersonId,nodes:nodeList,edges:edgeList,stats:{canonicalEvents:publicEvents.length,kinds,relationships,verifiedNodes:nodeList.filter(node=>node.truthStatus==='VERIFIED').length,requiresConfirmationNodes:nodeList.filter(node=>node.truthStatus==='REQUIRES_CONFIRMATION'||node.truthStatus==='QUARANTINED').length,recoveryRegistryRecords:recoveredPublicationRegistry.length,recoveredYouTubeRecords:recoveredYouTubePublications.length,curatedHistoricalCollections:historicalPlaylistPublications.length,knownEntityUrlPending:urlPendingPublications.length}};
}

export function searchPublicInternetGraph(events:CanonicalEvent[],query:PublicInternetGraphQuery={},entities:CanonicalEntity[]=canonicalEntities){const graph=projectPublicInternetGraph(events,entities);const q=norm(query.q||'');const kind=norm(query.kind||'');const year=(query.year||'').trim();const topic=norm(query.topic||'');const platform=norm(query.platform||'');const verification=norm(query.verification||'');const requested=Number(query.limit);const limit=Number.isFinite(requested)&&requested>0?Math.min(60,Math.floor(requested)):20;let matches=graph.nodes.filter(node=>(!kind||norm(node.kind)===kind)&&(!year||String(node.date||'').startsWith(year))&&(!topic||node.tags.some(tag=>norm(tag).includes(topic)))&&(!platform||norm(node.platform||'').includes(platform))&&(!verification||norm(node.truthStatus).replace(/_/g,'-')===verification.replace(/_/g,'-')));if(q)matches=matches.filter(node=>norm([node.id,node.kind,node.label,node.canonicalId||'',node.date||'',node.platform||'',...node.tags,JSON.stringify(node.data)].join(' ')).includes(q));matches=matches.slice(0,limit);const selected=new Set(matches.map(node=>node.id));const edges=graph.edges.filter(edge=>selected.has(edge.from)||selected.has(edge.to)).slice(0,Math.max(20,limit*8));const neighborIds=new Set<string>();for(const edge of edges){neighborIds.add(edge.from);neighborIds.add(edge.to)}const nodes=graph.nodes.filter(node=>selected.has(node.id)||neighborIds.has(node.id)).slice(0,Math.max(40,limit*8));return{release:graph.release,schemaVersion:graph.schemaVersion,count:matches.length,matches,nodes,edges,stats:graph.stats}}
