import type {Locale} from './locale';
export type CompanionMode='guide'|'reflect'|'build';
export type JourneyResonance={chapter:string;choice?:string;text?:string};
export type JourneyContext={visitedChapters:string[];resonances:JourneyResonance[];chosenDirection?:string;lastMeaningfulStep?:string;locale:Locale};
const key=(locale:Locale)=>'7ya.journey.context.v1.'+locale;
const clean=(value:unknown,max:number)=>String(value??'').trim().slice(0,max);
const empty=(locale:Locale):JourneyContext=>({visitedChapters:[],resonances:[],locale});
export function readJourneyContext(locale:Locale):JourneyContext{try{const raw=JSON.parse(sessionStorage.getItem(key(locale))||'null') as Partial<JourneyContext>|null;if(!raw)return empty(locale);return{visitedChapters:Array.isArray(raw.visitedChapters)?Array.from(new Set(raw.visitedChapters.map(item=>clean(item,80)).filter(Boolean))).slice(-12):[],resonances:Array.isArray(raw.resonances)?raw.resonances.map(item=>({chapter:clean(item?.chapter,80),choice:clean(item?.choice,180)||undefined,text:clean(item?.text,500)||undefined})).filter(item=>item.chapter).slice(-12):[],chosenDirection:clean(raw.chosenDirection,500)||undefined,lastMeaningfulStep:clean(raw.lastMeaningfulStep,500)||undefined,locale}}catch{return empty(locale)}}
export function writeJourneyContext(context:JourneyContext){try{sessionStorage.setItem(key(context.locale),JSON.stringify(context))}catch{}}
export function mergeJourneyContext(locale:Locale,patch:Partial<JourneyContext>):JourneyContext{const current=readJourneyContext(locale);const visited=Array.from(new Set([...current.visitedChapters,...(Array.isArray(patch.visitedChapters)?patch.visitedChapters:[])].map(item=>clean(item,80)).filter(Boolean))).slice(-12);const incoming=Array.isArray(patch.resonances)?patch.resonances:[];const resonances=[...current.resonances,...incoming.map(item=>({chapter:clean(item?.chapter,80),choice:clean(item?.choice,180)||undefined,text:clean(item?.text,500)||undefined}))].filter(item=>item.chapter).slice(-12);const next:JourneyContext={visitedChapters:visited,resonances,chosenDirection:patch.chosenDirection!==undefined?clean(patch.chosenDirection,500)||undefined:current.chosenDirection,lastMeaningfulStep:patch.lastMeaningfulStep!==undefined?clean(patch.lastMeaningfulStep,500)||undefined:current.lastMeaningfulStep,locale};writeJourneyContext(next);return next}
export function clearJourneyContext(locale:Locale):JourneyContext{try{sessionStorage.removeItem(key(locale))}catch{}return empty(locale)}
