import {useMemo} from 'react';
import {ArrowUpRight} from 'lucide-react';
import ArchiveVisual from './ArchiveVisual';
import {deepMedia,type DeepMediaItem} from './deep-media-data';
import {influenceArchiveItems} from './InfluenceMemory';
import {platformArchiveItems} from './PlatformUniverse';
import {webDiscoveryItems} from './web-discovery-data';
import {pageHref,useLocale} from './locale';
import './deep-archive-river.css';
const canonical=(url:string)=>url.trim().replace(/[?#].*$/,'').replace(/\/$/,'').toLowerCase();
const yearScore=(value:string)=>Math.max(...(value.match(/20\d{2}|19\d{2}/g)||['0']).map(Number));
const allRecords=(()=>{const seen=new Set<string>();return [...deepMedia,...influenceArchiveItems,...platformArchiveItems,...webDiscoveryItems].filter(item=>{if(!item.url)return false;const key=canonical(item.url);if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(b.featured?1:0)-(a.featured?1:0)||yearScore(b.year)-yearScore(a.year))})();
const copy={he:{eyebrow:'DEEP ARCHIVE / PUBLIC RECORD',title:'לא טעימה.\nעומק אמיתי.',body:'הבית מציג חלון ערוך מתוך המאגר הציבורי. העומק המלא ממשיך באותו 7YA דרך קאנון מאומת ומעליו שכבת Public Discovery רחבה — בלי לשלוח את המשתמש למיני־אתר נפרד.',records:'מקורות ייחודיים בשכבת הבית',shown:'עוגנים מוצגים כאן',all:'לכל התוכן + Public Discovery'},en:{eyebrow:'DEEP ARCHIVE / PUBLIC RECORD',title:'Not a sample.\nReal depth.',body:'The homepage is a curated window into the public record. Full depth continues inside the same 7YA experience through an audited canon plus a broader Public Discovery layer — without sending visitors to a separate mini-site.',records:'unique sources in the home layer',shown:'anchors shown here',all:'All content + Public Discovery'},ru:{eyebrow:'DEEP ARCHIVE / PUBLIC RECORD',title:'Не выборка.\nНастоящая глубина.',body:'Главная страница — отобранное окно в публичный архив. Полная глубина продолжается внутри того же 7YA: проверенный канон плюс широкий слой Public Discovery, без отдельного мини-сайта.',records:'уникальных источников в слое главной',shown:'опорных материалов здесь',all:'Весь контент + Public Discovery'}} as const;
const flow=[['01','LIFE','life-chronology'],['02','ECHO','echo'],['03','LAB','lab-research'],['04','STARTON','starton-return'],['05','BUILD','your-room'],['06','ARCHIVE','deep-archive']] as const;
export default function DeepArchiveRiver(){const {locale}=useLocale();const c=copy[locale];const visible=useMemo(()=>{const picked:DeepMediaItem[]=[];const categories=new Set<string>();const sources=new Set<string>();for(const item of allRecords){if(picked.length>=8)break;if(categories.has(item.category)||sources.has(item.source))continue;picked.push(item);categories.add(item.category);sources.add(item.source)}for(const item of allRecords){if(picked.length>=8)break;if(picked.includes(item)||sources.has(item.source))continue;picked.push(item);sources.add(item.source)}for(const item of allRecords){if(picked.length>=8)break;if(!picked.includes(item))picked.push(item)}return picked},[]);return <section className='deep-archive-wrap' id='deep-archive' aria-labelledby='deep-archive-title'><nav className='content-flow-rail' aria-label='7YA content flow'><span>FLOW / LIFE → ECHO → LAB → STARTON → BUILD → ARCHIVE</span><div>{flow.map(([n,label,id])=><a href={'#'+id} key={id}><small>{n}</small><b>{label}</b></a>)}</div></nav><div className='deep-archive-shell'><header><div><span>{c.eyebrow}</span><h2 id='deep-archive-title'>{c.title}</h2></div><div><p>{c.body}</p><dl><div><dt>{allRecords.length}</dt><dd>{c.records}</dd></div><div><dt>{visible.length}</dt><dd>{c.shown}</dd></div></dl></div></header><div className='deep-archive-grid'>{visible.map((item:DeepMediaItem,index)=><a href={item.url} target='_blank' rel='noreferrer' key={canonical(item.url)} data-archive-record={index+1} className='archive-source-object'><div className='deep-archive-meta'><span>{String(index+1).padStart(2,'0')}</span><b>{item.category}</b><time>{item.year}</time></div><div className='deep-archive-visual'><ArchiveVisual item={item} index={index}/></div><div className='deep-archive-copy'><small>{item.source}</small><h3>{item.title}</h3><p>{item.summary}</p><em>{item.status}</em></div><ArrowUpRight/></a>)}</div><a className='deep-archive-all' href={pageHref('search',locale)+'&scope=internet'}>{c.all}<ArrowUpRight/></a></div></section>}
