import {useMemo} from 'react';
import {ArrowUpRight} from 'lucide-react';
import ArchiveVisual from './ArchiveVisual';
import {deepMedia,type DeepMediaItem} from './deep-media-data';
import {influenceArchiveItems} from './InfluenceMemory';
import {platformArchiveItems} from './PlatformUniverse';
import {webDiscoveryItems} from './web-discovery-data';
import {pageHref,useLocale} from './locale';
import './deep-archive-river.css';
const canonical=(url:string)=>url.trim().replace(/[?#].*$/,'').replace(/\/$/,'').toLowerCase();
const yearScore=(value:string)=>Math.max(...(value.match(/20\d{2}|19\d{2}/g)||['0']).map(Number));
const allRecords=(()=>{const seen=new Set<string>();return [...deepMedia,...influenceArchiveItems,...platformArchiveItems,...webDiscoveryItems].filter(item=>{if(!item.url)return false;const key=canonical(item.url);if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(b.featured?1:0)-(a.featured?1:0)||yearScore(b.year)-yearScore(a.year))})();
const copy={he:{eyebrow:'DEEP ARCHIVE / PUBLIC RECORD',title:'לא טעימה.\nעומק אמיתי.',body:'הבית מציג עכשיו שכבה רחבה מתוך המאגר הציבורי: כתבות, ראיונות, פודקאסטים, כתיבה, ויראליות, מוזיקה, StartOn ומשטחי רשת. בלי למחזר את אותו פורטרט כשאין תמונת מקור אמיתית.',records:'רשומות ייחודיות במאגר',shown:'מוצגות כאן עכשיו',all:'לכל המאגר והחיפוש'},en:{eyebrow:'DEEP ARCHIVE / PUBLIC RECORD',title:'Not a sample.\nReal depth.',body:'The homepage now exposes a broad layer of the public record: press, interviews, podcasts, writing, viral work, music, StartOn and network surfaces. No repeated portrait tile when a real source visual does not exist.',records:'unique records in the register',shown:'shown here now',all:'Open the full searchable archive'},ru:{eyebrow:'DEEP ARCHIVE / PUBLIC RECORD',title:'Не выборка.\nНастоящая глубина.',body:'Главная страница теперь показывает широкий слой публичного архива: статьи, интервью, подкасты, тексты, вирусные публикации, музыку, StartOn и сетевые площадки. Без повторения одного портрета вместо реального источника.',records:'уникальных записей в архиве',shown:'показано здесь',all:'Открыть полный архив и поиск'}} as const;
const flow=[['01','NOW','right-now'],['02','LIFE','life'],['03','IMPACT','echo'],['04','CREATE','create'],['05','YOU','your-room']] as const;
export default function DeepArchiveRiver(){const {locale}=useLocale();const c=copy[locale];const visible=useMemo(()=>allRecords.slice(0,30),[]);return <section className='deep-archive-wrap' id='deep-archive' aria-labelledby='deep-archive-title'><nav className='content-flow-rail' aria-label='7YA content flow'><span>FLOW / NOW → ARCHIVE → STORY → IMPACT → CREATE</span><div>{flow.map(([n,label,id])=><a href={'#'+id} key={id}><small>{n}</small><b>{label}</b></a>)}</div></nav><div className='deep-archive-shell'><header><div><span>{c.eyebrow}</span><h2 id='deep-archive-title'>{c.title}</h2></div><div><p>{c.body}</p><dl><div><dt>{allRecords.length}</dt><dd>{c.records}</dd></div><div><dt>{visible.length}</dt><dd>{c.shown}</dd></div></dl></div></header><div className='deep-archive-grid'>{visible.map((item:DeepMediaItem,index)=><a href={item.url} target='_blank' rel='noreferrer' key={canonical(item.url)} data-archive-record={index+1} className='archive-source-object'><div className='deep-archive-meta'><span>{String(index+1).padStart(2,'0')}</span><b>{item.category}</b><time>{item.year}</time></div><div className='deep-archive-visual'><ArchiveVisual item={item} index={index}/></div><div className='deep-archive-copy'><small>{item.source}</small><h3>{item.title}</h3><p>{item.summary}</p><em>{item.status}</em></div><ArrowUpRight/></a>)}</div><a className='deep-archive-all' href={pageHref('media',locale)}>{c.all}<ArrowUpRight/></a></div></section>}
