export type EchoEvidenceState='verified'|'documented'|'estimated'|'recovery';
export type EchoResponseType='felt'|'thought'|'discussed'|'shared'|'acted'|'grew'|'challenged';
export type EchoNodeKind='origin'|'distribution'|'media'|'response'|'action';
export type EchoLocalized={he:string;en:string;ru:string};
export type EchoNode={id:string;kind:EchoNodeKind;label:EchoLocalized;date:string;source:string;url?:string;evidence:EchoEvidenceState;metric?:string;responses?:EchoResponseType[]};
export type EchoVisual={image?:string;source:string;url?:string;caption:EchoLocalized};
export type EchoStory={id:string;title:EchoLocalized;summary:EchoLocalized;visual:EchoVisual;nodes:EchoNode[]};

export const echoStories:EchoStory[]=[
 {id:'fatherhood',title:{he:'אבא ששם',en:'A father who is present',ru:'Отец, который рядом'},summary:{he:'סיפור אישי על אבהות יצא מהפיד, הופץ מחדש וצבר שיחה ציבורית שאפשר לפתוח ולבדוק.',en:'A personal fatherhood story left the original feed, was redistributed and accumulated a public conversation that remains checkable.',ru:'Личная история об отцовстве вышла за пределы исходной ленты, была распространена заново и стала публичным разговором, который можно проверить.'},visual:{image:'https://storage.hidabroot.org/articles_new/327351_tumb_730X500.jpg',source:'Hidabroot',url:'https://www.hidabroot.org/article/1179015',caption:{he:'כתבה חיצונית שנשאה את הסיפור מעבר לפוסט המקורי',en:'An external article that carried the story beyond the original post',ru:'Внешняя публикация, продолжившая историю за пределами исходного поста'}},nodes:[
  {id:'fatherhood-origin',kind:'origin',label:{he:'הסיפור האישי: “אבא מושלם — זה אבא ששם”',en:'The personal story: a present father',ru:'Личная история: отец, который рядом'},date:'2023',source:'Igor Vepretski',evidence:'recovery'},
  {id:'fatherhood-repost',kind:'distribution',label:{he:'הפצה חיצונית בסטטוסים מצייצים',en:'External redistribution by Statusim Metzaytzim',ru:'Внешнее распространение через Statusim Metzaytzim'},date:'2023',source:'סטטוסים מצייצים',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0icaS4EV3EFHPbtTaexx3X4Lo9UGQD22Nvm8xzkpJRqiJSLro9D3zNp1PX6SJ26iPl',evidence:'verified',metric:'4.1K reactions · 148 comments · 26 shares'},
  {id:'fatherhood-response',kind:'response',label:{he:'התגובה הציבורית נשארה גלויה על העותק המופץ',en:'Public response remained visible on the redistributed copy',ru:'Публичная реакция осталась видимой на распространённой копии'},date:'2023',source:'סטטוסים מצייצים',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0icaS4EV3EFHPbtTaexx3X4Lo9UGQD22Nvm8xzkpJRqiJSLro9D3zNp1PX6SJ26iPl',evidence:'verified',metric:'148 comments · 26 shares',responses:['discussed','shared']},
  {id:'fatherhood-media',kind:'media',label:{he:'הסיפור נשמר גם בפרסום חיצוני נוסף',en:'The story persisted in another external publication',ru:'История сохранилась и во внешней публикации'},date:'2023',source:'Hidabroot',url:'https://www.hidabroot.org/article/1179015',evidence:'documented'}
 ]},
 {id:'miel',title:{he:'כשהגננת מתקשרת',en:'When the kindergarten calls',ru:'Когда звонит воспитательница'},summary:{he:'פוסט הורי אחד עבר בין עמודי הפצה שונים; כל עותק נשמר כצומת נפרד כדי לא לספור את אותה תנועה פעמיים.',en:'One parenting post moved between multiple distribution pages; every copy stays a separate node so the same movement is not counted twice.',ru:'Один родительский пост прошёл через несколько страниц распространения; каждая копия остаётся отдельным узлом, чтобы не считать одно и то же движение дважды.'},visual:{source:'סטטוסים מצייצים / Hohavim',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid02FW4Q9ZWvN8K1Q6vpSy9ndnDiXPYgRbEs59JC2XANo2dSnhufQJbxRVWoXzdkcfa9l',caption:{he:'מסלול הפצה מתועד בין עמודים ציבוריים',en:'A documented distribution path across public pages',ru:'Документированный путь распространения между публичными страницами'}},nodes:[
  {id:'miel-origin',kind:'origin',label:{he:'הפוסט המקורי על מיאל',en:'The original post about Miel',ru:'Исходный пост о Миэле'},date:'ARCHIVE',source:'Igor Vepretski',evidence:'recovery'},
  {id:'miel-statusim',kind:'distribution',label:{he:'עותק חיצוני בסטטוסים מצייצים',en:'External copy on Statusim Metzaytzim',ru:'Внешняя копия в Statusim Metzaytzim'},date:'ARCHIVE',source:'סטטוסים מצייצים',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid02FW4Q9ZWvN8K1Q6vpSy9ndnDiXPYgRbEs59JC2XANo2dSnhufQJbxRVWoXzdkcfa9l',evidence:'verified'},
  {id:'miel-hohavim',kind:'distribution',label:{he:'הפצה כפולה בעמוד אוהבים / Hohavim',en:'Duplicate syndication on Hohavim',ru:'Повторное распространение на Hohavim'},date:'ARCHIVE',source:'אוהבים / Hohavim',url:'https://www.facebook.com/Hohavim/photos/%D7%AA%D7%97%D7%99%D7%9C%D7%AA-%D7%A9%D7%91%D7%95%D7%A2-%D7%94%D7%92%D7%A0%D7%A0%D7%AA-%D7%9E%D7%AA%D7%A7%D7%A9%D7%A8%D7%AA-%D7%90%D7%A0%D7%99-%D7%9E%D7%91%D7%A7%D7%A9%D7%AA-%D7%A9%D7%AA%D7%92%D7%99%D7%A2-%D7%9C%D7%A7%D7%97%D7%AA-%D7%90%D7%AA-%D7%9E%D7%99%D7%90%D7%9C-%D7%94%D7%95%D7%90-%D7%9E%D7%A8%D7%91%D7%99%D7%A5-%D7%9C%D7%9B%D7%95%D7%9C%D7%9D-%D7%95%D7%A4%D7%A9%D7%95%D7%98-%D7%9E%D7%A1%D7%A8%D7%91-/894091596665017/',evidence:'documented'},
  {id:'miel-response',kind:'response',label:{he:'תגובות ציבוריות נמדדו על העותק המופץ',en:'Public reactions were measured on the syndicated copy',ru:'Публичные реакции были зафиксированы на распространённой копии'},date:'ARCHIVE',source:'אוהבים / Hohavim',url:'https://www.facebook.com/Hohavim/photos/%D7%AA%D7%97%D7%99%D7%9C%D7%AA-%D7%A9%D7%91%D7%95%D7%A2-%D7%94%D7%92%D7%A0%D7%A0%D7%AA-%D7%9E%D7%AA%D7%A7%D7%A9%D7%A8%D7%AA-%D7%90%D7%A0%D7%99-%D7%9E%D7%91%D7%A7%D7%A9%D7%AA-%D7%A9%D7%AA%D7%92%D7%99%D7%A2-%D7%9C%D7%A7%D7%97%D7%AA-%D7%90%D7%AA-%D7%9E%D7%99%D7%90%D7%9C-%D7%94%D7%95%D7%90-%D7%9E%D7%A8%D7%91%D7%99%D7%A5-%D7%9C%D7%9B%D7%95%D7%9C%D7%9D-%D7%95%D7%A4%D7%A9%D7%95%D7%98-%D7%9E%D7%A1%D7%A8%D7%91-/894091596665017/',evidence:'documented',metric:'2,259 reactions'}
 ]},
 {id:'elder-fraud',title:{he:'מפוסט על הונאה לשיחה תקשורתית',en:'From an elder-fraud post to media discussion',ru:'От поста о мошенничестве к медиа-разговору'},summary:{he:'פוסט על הונאת קשישים עבר דרך הפצה חיצונית והמשיך לראיון טלוויזיוני. החיבור מוצג כנתיב מתועד, לא כהוכחת סיבתיות מלאה.',en:'A post about elder fraud moved through external distribution and continued into a television interview. The connection is shown as a documented path, not proof of full causality.',ru:'Пост о мошенничестве с пожилыми прошёл через внешнее распространение и продолжился телевизионным интервью. Связь показана как документированный путь, а не доказательство полной причинности.'},visual:{image:'https://i.ytimg.com/vi/3XxoBtSL2pg/hqdefault.jpg',source:'News 12 / YouTube',url:'https://www.youtube.com/watch?v=3XxoBtSL2pg',caption:{he:'ראיון המשך ציבורי בנושא הונאות קשישים',en:'A public follow-up interview on elder fraud',ru:'Публичное продолжение разговора о мошенничестве с пожилыми'}},nodes:[
  {id:'fraud-origin',kind:'origin',label:{he:'“סבתא שלי נפלה קורבן להונאה”',en:'“My grandmother fell victim to a scam”',ru:'«Моя бабушка стала жертвой мошенничества»'},date:'07.02.2023',source:'Igor Vepretski',evidence:'recovery'},
  {id:'fraud-repost',kind:'distribution',label:{he:'הפצה חיצונית של הסיפור',en:'External redistribution of the story',ru:'Внешнее распространение истории'},date:'07.02.2023',source:'סטטוסים מצייצים',url:'https://www.facebook.com/lan2lan.sta2sim/posts/igorvepretski-%D7%A1%D7%91%D7%AA%D7%90-%D7%A9%D7%9C%D7%99-%D7%A0%D7%A4%D7%9C%D7%94-%D7%A7%D7%95%D7%A8%D7%91%D7%9F-%D7%9C%D7%94%D7%95%D7%A0%D7%90%D7%94%D7%90%D7%91%D7%9C-%D7%9C%D7%A2%D7%95%D7%92%D7%9E%D7%AA-%D7%94%D7%A0%D7%A4%D7%A9-%D7%94%D7%A2%D7%99%D7%A7%D7%A8%D7%99%D7%AA-%D7%91%D7%9B%D7%95%D7%9C-%D7%94%D7%A1%D7%99%D7%A4%D7%95%D7%A8-%D7%94%D7%96%D7%94-/752380882924243/',evidence:'verified'},
  {id:'fraud-media',kind:'media',label:{he:'ראיון המשך על הונאות קשישים',en:'Follow-up interview on elder fraud',ru:'Продолжение интервью о мошенничестве с пожилыми'},date:'2023',source:'News 12',url:'https://www.youtube.com/watch?v=3XxoBtSL2pg',evidence:'documented'},
  {id:'fraud-response',kind:'response',label:{he:'הנושא המשיך לשיחה ציבורית מעבר לפוסט',en:'The issue continued as a public discussion beyond the post',ru:'Тема продолжилась как публичный разговор за пределами поста'},date:'2023',source:'Public media trail',url:'https://www.youtube.com/watch?v=3XxoBtSL2pg',evidence:'documented',responses:['discussed']}
 ]}
];
