import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,ExternalLink,Search,ShieldCheck} from 'lucide-react';
import {fetchGraphSearch,type ContentRecord} from './content-graph-client';
import EvidenceGraphExperience from './EvidenceGraphExperience';
import {pageHref,useLocale,type Locale} from './locale';
import './evidence-page-live.css';

type Truth='VERIFIED'|'STRONGLY_INFERRED'|'REQUIRES_CONFIRMATION';
type Filter='ALL'|Truth;
const filters:Filter[]=['ALL','VERIFIED','STRONGLY_INFERRED','REQUIRES_CONFIRMATION'];
const copy={he:{back:'חזרה לאיגור ופרצקי',eyebrow:'IGOR VEPRETSKI · EVIDENCE · LIVE CANON',title:'ראיה לפני טענה.',body:'זהו לא קיר קישורים ולא “עמוד הוכחות” שיווקי. זהו מבט ציבורי אל הקאנון: מה נחשב מאומת, מה נתמך או מוסק, מה עדיין דורש אימות, ואיזה מקור מחזיק כל רשומה.',all:'הכול',verified:'מאומת',inferred:'מוסק חזק',confirm:'דורש אימות',records:'רשומות קאנון',source:'פתיחת מקור',loading:'טוען את הקאנון החי…',failed:'הקאנון החי לא נטען כרגע. לא מוצגות רשומות גיבוי כאילו היו קאנון.',empty:'אין רשומות במעמד הזה כרגע.',more:'לכל התוכן + Public Discovery',boundary:'A/B/C/D מוצג רק כאשר הרשומה עצמה נושאת ציון Evidence מהמנוע.'},en:{back:'Back to Igor Vepretski',eyebrow:'IGOR VEPRETSKI · EVIDENCE · LIVE CANON',title:'Evidence before claims.',body:'This is not a link wall or a marketing “proof page”. It is a public view into the canon: what is verified, what is strongly inferred, what still requires confirmation, and which source supports each record.',all:'All',verified:'Verified',inferred:'Strongly inferred',confirm:'Requires confirmation',records:'canon records',source:'Open source',loading:'Loading the live canon…',failed:'The live canon is unavailable right now. Backup records are not presented as canon.',empty:'There are no records at this status right now.',more:'All content + Public Discovery',boundary:'A/B/C/D appears only when the record itself carries an Evidence grade from the ingestion engine.'},ru:{back:'Назад к Игорю Вепрецкому',eyebrow:'IGOR VEPRETSKI · EVIDENCE · LIVE CANON',title:'Доказательство до утверждения.',body:'Это не стена ссылок и не маркетинговая «страница доказательств». Это публичный вид канона: что проверено, что является сильным выводом, что ещё требует подтверждения и какой источник поддерживает каждую запись.',all:'Все',verified:'Проверено',inferred:'Сильный вывод',confirm:'Требует проверки',records:'записей канона',source:'Открыть источник',loading:'Загружаю живой канон…',failed:'Живой канон сейчас недоступен. Резервные записи не выдаются за канон.',empty:'Записей с таким статусом сейчас нет.',more:'Весь контент + Public Discovery',boundary:'A/B/C/D показывается только если сама запись получила Evidence-оценку от ingestion engine.'}} as const;
const label=(truth:Truth,locale:Locale,c:(typeof copy)[Locale])=>truth==='VERIFIED'?c.verified:truth==='STRONGLY_INFERRED'?c.inferred:c.confirm;
const grade=(record:ContentRecord)=>record.tags.find(tag=>/^EVIDENCE-[ABCD]$/.test(tag))?.slice(-1)||'';
export default function EvidencePage(){const {locale,dir}=useLocale();const c=copy[locale];const [records,setRecords]=useState<ContentRecord[]>([]);const [filter,setFilter]=useState<Filter>('ALL');const [state,setState]=useState<'loading'|'ready'|'failed'>('loading');useEffect(()=>{let live=true;fetchGraphSearch({limit:60}).then(result=>{if(!live)return;setRecords(result.results);setState('ready')}).catch(()=>{if(live)setState('failed')});return()=>{live=false}},[]);const visible=useMemo(()=>filter==='ALL'?records:records.filter(record=>record.truthStatus===filter),[records,filter]);const count=(truth:Filter)=>truth==='ALL'?records.length:records.filter(record=>record.truthStatus===truth).length;const filterText=(value:Filter)=>value==='ALL'?c.all:value==='VERIFIED'?c.verified:value==='STRONGLY_INFERRED'?c.inferred:c.confirm;return <main className='evidence-live-page' dir={dir}><header className='ev-hero'><div className='ev-shell'><a className='ev-back' href={pageHref('home',locale)}><ArrowRight/>{c.back}</a><span dir='ltr'>{c.eyebrow}</span><h1>{c.title}</h1><p>{c.body}</p><div className='ev-rule'><ShieldCheck/><b>CANON ≠ DISCOVERY</b><small>{c.boundary}</small></div></div></header><EvidenceGraphExperience surface='museum'/><section className='ev-ledger' aria-labelledby='ev-ledger-title'><div className='ev-shell'><header><div><span dir='ltr'>CANONICAL RECORDS · SOURCE STATUS</span><h2 id='ev-ledger-title'>{records.length} {c.records}</h2></div><a href={pageHref('search',locale)}><Search/>{c.more}</a></header><nav className='ev-filters' aria-label='Evidence status'>{filters.map(value=><button type='button' key={value} className={filter===value?'active':''} aria-pressed={filter===value} onClick={()=>setFilter(value)}><span>{filterText(value)}</span><b>{count(value)}</b></button>)}</nav>{state==='loading'?<div className='ev-state'>{c.loading}</div>:state==='failed'?<div className='ev-state ev-failed'>{c.failed}</div>:visible.length===0?<div className='ev-state'>{c.empty}</div>:<div className='ev-records'>{visible.map(record=>{const evidenceGrade=grade(record);return <article key={record.canonicalId} data-truth-status={record.truthStatus}><div className='ev-record-meta'><span className={'ev-status '+record.truthStatus.toLowerCase().replace(/_/g,'-')}><ShieldCheck/>{evidenceGrade&&<strong>{evidenceGrade}</strong>}{label(record.truthStatus,locale,c)}</span><time dir='ltr'>{record.canonicalDate}</time></div><h3>{record.title[locale]}</h3><p>{record.summary[locale]}</p><div className='ev-record-tags' dir='ltr'>{record.tags.slice(0,5).filter(tag=>!/^EVIDENCE-[ABCD]$/.test(tag)).map(tag=><span key={tag}>{tag}</span>)}</div><footer>{record.sources.slice(0,3).map(source=><a href={source.url} target='_blank' rel='noreferrer' key={source.url}>{source.label}<ExternalLink/></a>)}</footer></article>})}</div>}</div></section></main>}
