import {useEffect,useState} from 'react';
import {ArrowDown,BookOpen,Compass,HeartHandshake,Radio,ShieldCheck,Sparkles} from 'lucide-react';
import './life-map-flow.css';

type ChapterKey='origin'|'service'|'voice'|'mission'|'research'|'system';
const chapters=[
{key:'origin' as ChapterKey,target:'life',number:'01',years:'1990—2014',label:'מקור',title:'ללמוד להחזיק מעמד.',body:'עלייה, חולון, ילדות מורכבת והבחירה להפוך פצע ליכולת לראות אחרים.',signal:'הסיפור הציבורי מתחיל באדם, לא במותג.',icon:Compass},
{key:'service' as ChapterKey,target:'media',number:'02',years:'2011—2021',label:'שירות',title:'אחריות לפני כותרת.',body:'צבא, אבטחה, מודיעין ושטח כבית ספר למשמעת, גבולות וקריאת מערכות אנושיות.',signal:'שירות מוצג באחריות וללא חשיפת מידע מבצעי.',icon:ShieldCheck},
{key:'voice' as ChapterKey,target:'viral-albums',number:'03',years:'2015—היום',label:'קול',title:'סיפור שעובר מיד ליד.',body:'וידאו, פוסטים, טורים, מוזיקה ורגעים שהתגלגלו בין קהלים ופלטפורמות.',signal:'מדיה אמיתית, נגזרות וקישורי מקור — לא מספר חשיפה מומצא.',icon:Radio},
{key:'mission' as ChapterKey,target:'starton',number:'04',years:'2022—היום',label:'שליחות',title:'לחזור ולבנות.',body:'StartOn הופך ניסיון אישי למרחב של טכנולוגיה, יצירה, מנטורינג ושייכות.',signal:'הסיפור מפסיק להיות תוכן והופך למקום שאפשר להיכנס אליו.',icon:HeartHandshake},
{key:'research' as ChapterKey,target:'research',number:'05',years:'2025—היום',label:'מחקר',title:'לתת למעשים שפה.',body:'כתיבה על זהות דיגיטלית, כוח, מידע, ממשל ותיקון חברתי — עם תוויות פרסום מדויקות.',signal:'רעיון נשאר רעיון עד שהראיות והמעמד שלו ברורים.',icon:BookOpen},
{key:'system' as ChapterKey,target:'fulfillment',number:'06',years:'2026→',label:'המערכת',title:'עכשיו הדרך עוברת אליך.',body:'7YA מחבר את הזיכרון, הראיות, הבוט החברתי והכלים למסע הגשמה אישי של המבקר.',signal:'אדם לפני מערכת. אמת לפני הגברה. פעולה לפני הבטחה.',icon:Sparkles}
];
export function LifeChapterGate({chapter}:{chapter:ChapterKey}){const item=chapters.find(value=>value.key===chapter)!;const Icon=item.icon;return <section className={'life-chapter-gate gate-'+chapter} aria-label={'פרק '+item.label}><div className="gate-orbit" aria-hidden="true"><span>{item.number}</span></div><div className="gate-copy"><span>{item.number} / {item.label} · {item.years}</span><h2>{item.title}</h2><p>{item.body}</p><div><Icon/><b>{item.signal}</b></div><a href={'#'+item.target}>לרדת אל הפרק <ArrowDown/></a></div></section>}
export default function LifeMapNavigation(){const [active,setActive]=useState('life');const [show,setShow]=useState(false);useEffect(()=>{const onScroll=()=>setShow(window.scrollY>window.innerHeight*.65);onScroll();window.addEventListener('scroll',onScroll,{passive:true});const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id);},{rootMargin:'-28% 0px -58% 0px',threshold:[.08,.2,.4]});chapters.forEach(item=>{const node=document.getElementById(item.target);if(node)observer.observe(node)});return()=>{window.removeEventListener('scroll',onScroll);observer.disconnect()}},[]);return <section className="life-map-index" id="life-map" aria-labelledby="life-map-title"><aside className={show?'life-progress-rail visible':'life-progress-rail'} aria-label="התקדמות במפת החיים">{chapters.map(item=><a key={item.key} href={'#'+item.target} className={active===item.target?'active':''} aria-current={active===item.target?'step':undefined}><i>{item.number}</i><span>{item.label}</span></a>)}</aside><header><div><span><Compass/>THE SCROLLING LIFE MAP</span><h2 id="life-map-title">מפת החיים<br/><em>של איגור ופרצקי.</em></h2></div><p>גוללים בזמן. בכל תחנה פוגשים רגע, מדיה, ראיה והדבר שנולד ממנו. בסוף, המפה מפסיקה להיות רק של איגור והופכת לכלי לבניית הדרך שלך.</p></header><div className="map-reading-code" aria-label="קוד הקריאה של האתר">{[['01','חוויה'],['02','שאלה'],['03','עמדה'],['04','ראיה'],['05','פעולה']].map(([number,label])=><span key={label}><i>{number}</i><b>{label}</b></span>)}</div><div className="map-route" aria-label="ששת פרקי המסע">{chapters.map((item,index)=>{const Icon=item.icon;return <a key={item.key} href={'#'+item.target} className={'map-station station-'+item.key}><span className="station-year">{item.years}</span><div className="station-icon"><Icon/></div><div className="station-copy"><small>{item.number} / {item.label}</small><h3>{item.title}</h3><p>{item.body}</p><b>{item.signal}</b></div><i className="station-line" aria-hidden="true">{index<chapters.length-1&&<ArrowDown/>}</i></a>})}</div></section>}
