import {ArrowUpLeft,CheckCircle2,HeartHandshake,PlayCircle,Rocket,ShieldCheck,Sparkles} from 'lucide-react';
import './life-archive.css';

type Chapter={period:string;kicker:string;title:string;summary:string;meaning:string;evidence:string;status:string;href:string;external?:boolean};
const chapters:Chapter[]=[
  {period:'1990—2011',kicker:'ORIGIN',title:'מילד שנאבק על מקום — לסיפור ציבורי ראשון',summary:'העלייה לישראל, הילדות בבת ים ובחולון וההתמודדות עם אלימות, קשיי קשב ושייכות הן הרקע האנושי. באתר הציבורי נשמרת הגבול: מספרים את הדרך, לא חושפים קטינים או פרטי משפחה פרטיים.',meaning:'ב־2011 פורסמה כתבת ביוגרפיה מוקדמת שתיעדה את המעבר מילדות מורכבת לשירות משמעותי. זו נקודת העוגן הציבורית הראשונה של הסיפור.',evidence:'כתבת מקור ראשון / NRG מאונדקסת בתיק העבודה הקנוני',status:'VERIFIED PUBLISHER RECORD',href:'evidence/'},
  {period:'2011—2021',kicker:'SERVICE',title:'שירות, שטח והבנת מערכות אנושיות',summary:'שירות צבאי, אבטחה ציבורית ועבודה במודיעין משטרתי בנו משמעת, רגישות לסיכון ויכולת לקרוא מערכות. אין כאן חשיפת פרטים מבצעיים, תיקים או מידע שאינו ציבורי.',meaning:'השנים בשירות לא מוצגות כמדליה, אלא כבית ספר לאחריות: לראות אדם בתוך מערכת ולזהות איפה פעולה קטנה משנה תוצאה.',evidence:'ביוגרפיה ציבורית, ראיונות ופרופילים מתועדים',status:'PUBLIC BIOGRAPHY · SAFE BOUNDARY',href:'#media'},
  {period:'2022',kicker:'RETURN',title:'לחזור לשכונה — ולא רק לדבר עליה',summary:'המעבר משירות ציבורי ל־StartOn הפך חוויה אישית למודל פעולה: מרחב טכנולוגיה, יצירה, מנטורינג ושייכות לצעירים שצריכים התחלה אמיתית.',meaning:'הסיפור קיבל תיעוד ב־mynet חולון, חדשות 13, ערוץ 14, פודקאסטים ובמות חינוך. הנרטיב החזק הוא סגירת המעגל: לצאת — ואז לחזור לבנות.',evidence:'mynet חולון · חדשות 13 · ערוץ 14 · פודקאסטים',status:'MULTI-SOURCE VERIFIED',href:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',external:true},
  {period:'2022—2024',kicker:'VOICE',title:'אבהות, זהות, חינוך וקול ציבורי',summary:'פוסטים וטורים על נוכחות הורית, הגירה, שייכות, טכנולוגיה וחינוך עברו מהפיד לכתבות, שיתופים וטורי דעה. החוזקה לא הייתה “להיות מושלם” — אלא לדבר אמת שאנשים יכולים לקחת לחיים שלהם.',meaning:'הקול האישי התרחב לכתיבה בזמן ישראל, הפצה חיצונית בפייסבוק ושיחה מקצועית בלינקדאין. תגובות אוהדות מוצגות כדפוסי תהודה, לא כציטוטים מומצאים.',evidence:'זמן ישראל · הידברות · סטטוסים מצייצים · LinkedIn',status:'VERIFIED INDEXED CLUSTERS',href:'https://www.zman.co.il/writer/20815/',external:true},
  {period:'2023—2025',kicker:'CULTURE',title:'מוזיקה היא חלק מהזהות — לא נספח',summary:'תחת השם Ido Vepretski נוצרו שירים, קליפים ושיתופי פעולה. המוזיקה מחברת בין הומור, רגש, שפה וקהילה ומראה שהשפעה ציבורית יכולה לעבור גם דרך תרבות.',meaning:'הארכיון כולל וידאו מוזיקלי ציבורי, פרופילי אמן ויצירה שקיבלה הפצה אצל מפרסמים חיצוניים. מספרי צפייה מוצגים רק כשקיים צילום או אינדוקס מתוארך.',evidence:'YouTube · YouTube Music · Spotify · Apple Music',status:'PUBLIC ARTIST SURFACES',href:'https://www.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',external:true},
  {period:'2024—2026',kicker:'CIVIC STAGE',title:'בין עברית, רוסית ואנגלית — קול שמחבר עולמות',summary:'ראיונות ותוכן ציבורי עסקו בהגירה, ביטחון אישי, אחריות אזרחית, נוער בסיכון והחברה הישראלית אחרי 7 באוקטובר. האתר מפריד בין עדות, דעה ועובדה.',meaning:'הרב־לשוניות אינה קישוט. היא מאפשרת לאותו סיפור לנוע בין קהלים, דורות ופלטפורמות ולהישאר אנושי גם כשהנושא פוליטי או כואב.',evidence:'וידאו ציבורי · פודקאסטים · הפצה מפלגתית · ארכיון תקשורת',status:'SOURCE-LINKED PUBLIC RECORD',href:'#media'},
  {period:'2025—2026',kicker:'RESEARCH',title:'העשייה כמעבדה — הכתיבה כמסגרת',summary:'כתבי היד והמסות מחברים בין זהות דיגיטלית, כוח, מידע, ממשל ועמידות חברתית. כל פריט מסומן לפי מעמדו האמיתי: כתב יד, מונוגרפיה עצמאית או preprint רעיוני.',meaning:'אין באתר המרה של אינדוקס ציבורי לתואר אקדמי, מינוי מוסדי או ביקורת עמיתים. הסקרנות גדולה; השפה נשארת מדויקת.',evidence:'Academia.edu · אינדקס עבודות קנוני · תיק ראיות',status:'INDEPENDENT · LABELLED · NOT OVERCLAIMED',href:'https://igorvepretski.academia.edu/',external:true},
  {period:'2026→',kicker:'THE SYSTEM',title:'7YA — להפוך סיפור, השפעה וידע לפעולה',summary:'7YA מארגן את הזהות, התוכן, הראיות והליווי למערכת ציבורית אחת. איגור הוא המרכז האנושי; StartOn הוא שליחות השטח; 7YA הוא מנגנון החיבור.',meaning:'השלב הבא אינו “עוד אתר אישי”. זו תשתית שבה קורא יכול להבין את הדרך, לבדוק מקור, לזהות את עצמו בסיפור ולצאת עם צעד מעשי.',evidence:'66 רשומות נשלטות · מסלולי פעולה · Evidence-first publishing',status:'CANONICAL PUBLIC OPERATING LAYER',href:'evidence/'}
];

export default function LifeArchive(){return <section className="life-archive" id="life" aria-labelledby="life-title"><header className="life-header"><div><span className="life-kicker"><Sparkles/>THE WHOLE STORY</span><h2 id="life-title">הסיפור השלם.<br/><em>בגרסה ציבורית ומגובה.</em></h2></div><div className="life-manifesto"><p>לא קורות חיים שטוחים ולא מיתולוגיה. ציר חיים שמראה מאיפה איגור הגיע, מה נבנה, מה השפיע — ומה נשאר פרטי.</p><div><ShieldCheck/><span>כל תחנה מסומנת לפי מצב הראיה שלה. טענה לא מאומתת אינה הופכת לכותרת.</span></div></div></header><div className="life-boundary"><HeartHandshake/><div><b>האדם הוא העניין.</b><span>הטכנולוגיה מסדרת. הראיות מגנות. הסיפור מחבר. הפעולה נותנת משמעות.</span></div><CheckCircle2/></div><div className="life-rail">{chapters.map((chapter,index)=><article className="life-chapter" key={chapter.period}><div className="life-index"><span>{String(index+1).padStart(2,'0')}</span><i/></div><div className="life-card"><div className="life-meta"><small>{chapter.period}</small><b>{chapter.kicker}</b><em>{chapter.status}</em></div><h3>{chapter.title}</h3><p>{chapter.summary}</p><div className="life-meaning"><Rocket/><div><small>מה נולד מכאן</small><span>{chapter.meaning}</span></div></div><footer><span><PlayCircle/> {chapter.evidence}</span><a href={chapter.href} target={chapter.external?'_blank':undefined} rel={chapter.external?'noreferrer':undefined}>לפתיחת הראיה <ArrowUpLeft/></a></footer></div></article>)}</div><div className="life-privacy"><ShieldCheck/><div><b>גבול מכוון</b><p>הארכיון אינו מפרסם פרטי קטינים, כתובות, תיקים משפטיים או פיננסיים, תכתובות פרטיות, מידע מבצעי או טענות שלא עברו שער ראיה.</p></div></div></section>}
