import {rootHref,useLocale} from './locale';
import LifeContextLink from './life-album/LifeContextLink';
import './music-room.css';

const thumb=(id:string)=>`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
const videos=[
 {year:'2020',credit:'רון נשר & IGOR VEPRETSKI',title:'מת על אקסל',id:'2HGMUN2jDwQ',role:{he:'שיתוף פעולה',en:'Collaboration',ru:'Коллаборация'}},
 {year:'2022',credit:'IGOR VEPRETSKI',title:'פרח במדבר',id:'rQbAXagOZBU',role:{he:'קליפ רשמי',en:'Official video',ru:'Официальное видео'}},
 {year:'2025',credit:'NAWAN ft. VEPRETSKI',title:'BIZZI',id:'jRjZjpqAgEw',role:{he:'אמן אורח',en:'Featured artist',ru:'Приглашённый артист'}}
] as const;
const releases=[
 {year:'2020',title:'אני עידו',credit:'IDO VEPRETSKI',url:'https://open.spotify.com/track/73FXS0agbMO7T9xrF6MfHd'},
 {year:'2024',title:'СупаПорп',credit:'IGOR VEPRETSKI feat. NAWAN & PAPIPABLO',url:'https://open.spotify.com/album/4LjSps93LnMe1c1uYIfb2L',image:thumb('o8MgXeeLEpA')},
 {year:'2024',title:'חצופה',credit:'IDO VEPRETSKI · OFIR WAINBOIM · TAY LERNER',url:'https://open.spotify.com/track/3eVSdl8O4f6iTW3z5GnFtC'},
 {year:'CATALOG',title:'Ido Vepretski · Apple Music',credit:'OFFICIAL ARTIST SURFACE',url:'https://music.apple.com/il/artist/ido-vepretski/1527248864?l=he'}
] as const;
const text={he:{kicker:'LIFE ALBUM / 2020—2025 · CULTURE · MUSIC · ORIGINAL SOURCES',title:'קול.\nביט. סיפור.',lead:'המוזיקה אינה נספח לביוגרפיה. היא עוד דרך שבה איגור / עידו ופרצקי הופך חוויה, זהות, הומור ואנרגיה למשהו שאפשר לשמוע ולראות.',spotify:'Spotify · אמן',youtube:'YouTube · ערוץ',statement:'לא “תחביב בפוטר”.\nחלק מהחיים עצמם.',body:'כל פריט כאן נפתח במקור הרשמי. הקרדיט נשאר מדויק: אמן ראשי, אורח או שיתוף פעולה — בלי לנכס ערוץ, הפקה או יצירה שלא שייכים לאיגור.',watch:'לצפייה במקור ↗',releases:'עוד מהקטלוג.',releaseBody:'משטחי האזנה רשמיים בלבד. בלי נגן מומצא, בלי מספרים מומצאים, בלי ערבוב קרדיטים.',back:'חזרה לרשומה האישית ↗'},en:{kicker:'LIFE ALBUM / 2020—2025 · CULTURE · MUSIC · ORIGINAL SOURCES',title:'Voice.\nBeat. Story.',lead:'Music is not an appendix to the biography. It is another way Igor / Ido Vepretski turns experience, identity, humour and energy into something you can hear and see.',spotify:'Spotify · artist',youtube:'YouTube · channel',statement:'Not a footer hobby.\nPart of the life itself.',body:'Every object opens at its official source. Credits stay exact: lead artist, feature or collaboration — without claiming a channel, production or work that is not Igor’s.',watch:'Open source ↗',releases:'More from the catalog.',releaseBody:'Official listening surfaces only. No invented player, invented metrics or blended credits.',back:'Back to the living record ↗'},ru:{kicker:'LIFE ALBUM / 2020—2025 · CULTURE · MUSIC · ORIGINAL SOURCES',title:'Голос.\nБит. История.',lead:'Музыка — не приложение к биографии. Это ещё один способ, которым Игорь / Идо Вепрецки превращает опыт, идентичность, юмор и энергию в то, что можно услышать и увидеть.',spotify:'Spotify · артист',youtube:'YouTube · канал',statement:'Не хобби в подвале сайта.\nЧасть самой жизни.',body:'Каждый объект открывается в официальном источнике. Кредиты остаются точными: основной артист, гость или коллаборация — без присвоения чужого канала, продакшна или работы.',watch:'Открыть источник ↗',releases:'Ещё из каталога.',releaseBody:'Только официальные поверхности прослушивания. Без выдуманного плеера, метрик и смешанных кредитов.',back:'Назад к живому архиву ↗'}} as const;
export default function MusicRoom(){const {locale,dir}=useLocale();const t=text[locale];return <main className='music-room' dir={dir}>
 <section className='mr-hero'><div className='mr-shell mr-rail' dir='ltr'><span>MUSIC RECORD / CULTURE-004</span><span>IGOR / IDO VEPRETSKI · SOURCE LINKED</span></div><div className='mr-shell mr-hero-grid'><div className='mr-copy'><p className='mr-kicker' dir='ltr'>{t.kicker}</p><h1>{t.title}</h1><p className='mr-lead'>{t.lead}</p><div className='mr-actions'><a href='https://open.spotify.com/artist/0fgRoQ6PoCHlVCIr8a5d6u' target='_blank' rel='noreferrer'>{t.spotify} ↗</a><a href='https://www.youtube.com/@IgorVepretski' target='_blank' rel='noreferrer'>{t.youtube} ↗</a><LifeContextLink momentId='life-music-2025'/></div></div><a className='mr-hero-media' href='https://www.youtube.com/watch?v=jRjZjpqAgEw' target='_blank' rel='noreferrer'><img src={thumb('jRjZjpqAgEw')} alt='NAWAN ft. VEPRETSKI — BIZZI official video'/><span dir='ltr'>2025 / BIZZI / OFFICIAL VIDEO SOURCE</span></a></div></section>
 <section className='mr-manifest'><div className='mr-shell'><h2>{t.statement}</h2><p>{t.body}</p></div></section>
 <section className='mr-videos'><div className='mr-shell'><header><span dir='ltr'>OFFICIAL VIDEOS / 01—03</span><b>SOURCE {'>'} SIMULATION</b></header><div className='mr-video-list'>{videos.map((video,index)=><a href={`https://www.youtube.com/watch?v=${video.id}`} target='_blank' rel='noreferrer' key={video.id}><span className='mr-no' dir='ltr'>0{index+1}</span><img src={thumb(video.id)} alt={`${video.credit} — ${video.title}`}/><div><small dir='ltr'>{video.year} · {video.role[locale].toUpperCase()}</small><h3 dir='ltr'>{video.credit}<br/><em>{video.title}</em></h3></div><b>{t.watch}</b></a>)}</div></div></section>
 <section className='mr-releases'><div className='mr-shell'><div className='mr-release-head'><div><p className='mr-kicker' dir='ltr'>RELEASES · LISTENING SURFACES</p><h2>{t.releases}</h2></div><p>{t.releaseBody}</p></div><div className='mr-release-list'>{releases.map((item,index)=><a href={item.url} target='_blank' rel='noreferrer' key={item.url}><span dir='ltr'>0{index+1}</span>{'image' in item&&item.image?<img src={item.image} alt={item.title}/>:<div className='mr-record-mark' aria-hidden='true'>7YA</div>}<div><small dir='ltr'>{item.year} · {item.credit}</small><h3>{item.title}</h3></div><b>↗</b></a>)}</div><a className='mr-back' href={rootHref('?lang='+locale+'#room-culture')}>{t.back}</a></div></section>
 </main>}
