export type RelationshipStatus='BUILT_ACTIVE_SYSTEM'|'DOCUMENTED_WORKFLOW'|'ACTIVE_PARTNERSHIP'|'ECOSYSTEM_MEMBERSHIP'|'PROGRAM_PARTICIPATION'|'PILOT'|'PILOT_PROPOSAL'|'MEDIA_COVERAGE'|'PUBLIC_SOURCE'|'CO_CREATION'|'HOSTED_LONGFORM'|'AUTHORED_PUBLICATION'|'EXTERNAL_DISTRIBUTION'|'POLITICAL_DISTRIBUTION'|'PUBLIC_BROADCAST';
export type RelationshipRecord={id:string;name:string;status:RelationshipStatus;title:string;note:string;url:string;journeyChapter?:string;evidenceUrl?:string;asOf?:string};
export const relationshipStatusLabel:Record<RelationshipStatus,string>={BUILT_ACTIVE_SYSTEM:'BUILT · ACTIVE SYSTEM',DOCUMENTED_WORKFLOW:'DOCUMENTED WORKFLOW',ACTIVE_PARTNERSHIP:'ACTIVE PARTNERSHIP',ECOSYSTEM_MEMBERSHIP:'ECOSYSTEM / MEMBERSHIP',PROGRAM_PARTICIPATION:'PROGRAM PARTICIPATION',PILOT:'PILOT',PILOT_PROPOSAL:'PILOT PROPOSAL',MEDIA_COVERAGE:'MEDIA COVERAGE',PUBLIC_SOURCE:'PUBLIC SOURCE',CO_CREATION:'CO-CREATION',HOSTED_LONGFORM:'HOSTED LONGFORM',AUTHORED_PUBLICATION:'AUTHORED PUBLICATION',EXTERNAL_DISTRIBUTION:'EXTERNAL DISTRIBUTION',POLITICAL_DISTRIBUTION:'POLITICAL DISTRIBUTION',PUBLIC_BROADCAST:'PUBLIC BROADCAST'};
export const relationshipRegistry:RelationshipRecord[]=[
{id:'starton-7ya',name:'StartOn × 7YA',status:'BUILT_ACTIVE_SYSTEM',title:'Mission + public system',note:'StartOn is the field mission; 7YA organizes public memory, sources and the path from evidence to action.',url:'https://starton.org.il/',journeyChapter:'starton',asOf:'2026-08-15'},
{id:'presidents-residence',name:'בית הנשיא',status:'DOCUMENTED_WORKFLOW',title:'Documented workflow / launch event',note:'Shown as a documented workflow and event relationship — not as blanket institutional sponsorship.',url:'https://www.president.gov.il/',evidenceUrl:'https://www.linkedin.com/posts/vepretski_%D7%9C%D7%A4%D7%A0%D7%99%D7%99-%D7%9B%D7%A9%D7%A0%D7%AA%D7%99%D7%99%D7%9D-%D7%99%D7%A6%D7%90%D7%AA%D7%99-%D7%9C%D7%A9%D7%9C%D7%99%D7%97%D7%95%D7%AA-%D7%97%D7%91%D7%A8%D7%AA%D7%99%D7%AA-%D7%91%D7%9E%D7%98%D7%A8%D7%94-activity-7102556652943347712-bPfq',journeyChapter:'starton',asOf:'2022'},
{id:'microsoft-startups',name:'Microsoft for Startups',status:'ECOSYSTEM_MEMBERSHIP',title:'Ecosystem framework',note:'Membership or participation in an ecosystem framework; not presented as a commercial agreement.',url:'https://www.microsoft.com/en-us/startups',journeyChapter:'starton'},
{id:'ajcatalyst',name:'AJCatalyst Lab',status:'PILOT_PROPOSAL',title:'90-day pilot proposal',note:'A proposed pilot. It is not presented as approved or as an active partnership.',url:'https://www.ajc.org/',journeyChapter:'starton',asOf:'2026-07-17'},
{id:'ron-nesher',name:'רון נשר × Igor Vepretski',status:'CO_CREATION',title:'Music co-creation',note:'Official public music collaboration. Co-creation is shown as co-creation, not as an institutional partnership.',url:'https://www.youtube.com/watch?v=2HGMUN2jDwQ',journeyChapter:'culture',asOf:'2020'},
{id:'nawan-bizzi',name:'NAWAN × VEPRETSKI',status:'CO_CREATION',title:'BIZZI · official video',note:'Documented music collaboration with an official public video and creator credit.',url:'https://www.youtube.com/watch?v=jRjZjpqAgEw',journeyChapter:'culture',asOf:'2025'},
{id:'zman-israel-author',name:'זמן ישראל',status:'AUTHORED_PUBLICATION',title:'Author page / columns',note:'A public author surface containing owner-authored columns on parenting, education, networks and belonging.',url:'https://www.zman.co.il/writer/20815/',journeyChapter:'voice',asOf:'2022–2023'},
{id:'statuses-distribution',name:'סטטוסים מצייצים',status:'EXTERNAL_DISTRIBUTION',title:'External redistribution',note:'External publisher redistribution of owner-originated public stories. Redistribution is not sponsorship or partnership.',url:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0icaS4EV3EFHPbtTaexx3X4Lo9UGQD22Nvm8xzkpJRqiJSLro9D3zNp1PX6SJ26iPl',journeyChapter:'voice',asOf:'2023'},
{id:'hazinor-distribution',name:'הצינור',status:'EXTERNAL_DISTRIBUTION',title:'External viral distribution',note:'A public entertainment/video distribution trace involving Igor and other creators. It is classified as distribution rather than partnership.',url:'https://www.facebook.com/hazinor/videos/%D7%96%D7%94-%D7%9E%D7%AA%D7%97%D7%99%D7%9C-%D7%9C%D7%94%D7%A1%D7%AA%D7%9E%D7%9F-%D7%9B%D7%9C%D7%94%D7%99%D7%98-%D7%94%D7%97%D7%93%D7%A9dennis-charkov-igor-vepretski-david-goldenberg-vlad-jh/10153274636619662/',journeyChapter:'culture'},
{id:'beytenu-distribution',name:'ישראל ביתנו',status:'POLITICAL_DISTRIBUTION',title:'Party-page public distribution',note:'A public political distribution record. Appearance or distribution on a party surface is not presented as evidence that an audience, institution or third party endorses every statement.',url:'https://www.facebook.com/beytenu/videos/%D7%99%D7%95%D7%A6%D7%90-%D7%9B%D7%95%D7%97%D7%95%D7%AA-%D7%94%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%AA%D7%92%D7%99%D7%93-%D7%99%D7%90-%D7%91%D7%99%D7%91%D7%99-%D7%90%D7%99%D7%A4%D7%94-%D7%94%D7%A0%D7%99%D7%A6%D7%97%D7%95%D7%9F-%D7%94%D7%9E%D7%95%D7%97%D7%9C%D7%98/26702411802682636/',journeyChapter:'voice',asOf:'2026-01-29'},
{id:'ndi-longform',name:'פודקאסט NDI · ג׳ולי קייט',status:'HOSTED_LONGFORM',title:'Generation 1.5 / civic identity',note:'Verified Russian-language long-form conversation on immigration, identity, integration and civic participation.',url:'https://www.youtube.com/watch?v=EsaD-lVsKHc',journeyChapter:'voice',asOf:'2024-08-15'},
{id:'mindset-longform',name:'Mindset · שלומי חסטר',status:'HOSTED_LONGFORM',title:'Life journey / StartOn',note:'Long-form host relationship documenting the path from immigration and adversity through service to StartOn.',url:'https://mindset.org.il/%D7%9E%D7%A0%D7%A2%D7%A8-%D7%91%D7%A1%D7%99%D7%9B%D7%95%D7%9F-%D7%9C%D7%99%D7%96%D7%9D-%D7%97%D7%91%D7%A8%D7%AA%D7%99-%D7%90%D7%99%D7%92%D7%95%D7%A8-%D7%95%D7%A4%D7%A8%D7%A6%D7%A7%D7%99-%D7%A4/',journeyChapter:'starton',asOf:'2022-09-20'},
{id:'kaikov-longform',name:'מנפצי תקרות הזכוכית · שחר קאיקוב',status:'HOSTED_LONGFORM',title:'Repeat long-form conversations',note:'Documented repeat host relationship covering bureaucracy, protest, youth at risk, StartOn and persistence.',url:'https://kaikovshahar.podbean.com/e/%D7%A4%D7%95%D7%93%D7%A7%D7%90%D7%A1%D7%98-%D7%9E%D7%A0%D7%A4%D7%A6%D7%99-%D7%AA%D7%A7%D7%A8%D7%95%D7%AA%D7%94%D7%96%D7%9B%D7%95%D7%9B-1696109547/',journeyChapter:'voice',asOf:'2022–2023'},
{id:'kan-reka',name:'כאן רק״ע',status:'PUBLIC_BROADCAST',title:'Russian-language public radio',note:'Verified public-radio appearance in Russian about the personal journey and social work.',url:'https://omny.fm/shows/two-for-one/4-8-2022',journeyChapter:'voice',asOf:'2022-08-04'},
{id:'news13-fraud',name:'חדשות 13',status:'MEDIA_COVERAGE',title:'Elder-fraud public action',note:'Television coverage documenting the transition from a personal fraud story to public civic action.',url:'https://www.youtube.com/watch?v=AE5hDzLM5XU',journeyChapter:'voice',asOf:'2023'},
{id:'moving-minds',name:'מוחות בתנועה · אדר ואדיר',status:'HOSTED_LONGFORM',title:'Education and leadership',note:'Public long-form conversation on education, leadership, StartOn and changing expected life trajectories.',url:'https://podtail.com/podcast/092cc570/--18/',journeyChapter:'starton',asOf:'2024-01-23'},
{id:'nitzotzot',name:'ניצוצות',status:'PROGRAM_PARTICIPATION',title:'Digital creator / education surface',note:'Public educational-program record connecting viral creation with digital responsibility and learning.',url:'https://www.nitzotzot.org.il/spark/%D7%90%D7%99%D7%9A-%D7%9B%D7%95%D7%9B%D7%91-%D7%98%D7%99%D7%A7%D7%98%D7%95%D7%A7-%D7%9E%D7%A9%D7%A0%D7%94-%D7%90%D7%AA-%D7%94%D7%A2%D7%95%D7%9C%D7%9D/',journeyChapter:'voice'}
];
export const relationshipsForChapter=(chapter:string)=>relationshipRegistry.filter(item=>item.journeyChapter===chapter);