import type {DeepMediaItem} from './deep-media-data';
const hero='./resources/igor-hero.jpg';
export const webDiscoveryItems:DeepMediaItem[]=[
{id:'web-aboutme',category:'רשתות',source:'about.me',title:'Igor Vepretski — public profile',year:'Public surface',url:'https://about.me/vepretski',summary:'Public profile discovered through broad web search. Included as an external identity surface, not as independent press coverage.',status:'WEB DISCOVERY · PUBLIC PROFILE',image:hero,fallback:hero,language:'EN'},
{id:'web-gravatar',category:'רשתות',source:'Gravatar',title:'Igor Vepretski — verified-links profile',year:'Public surface',url:'https://gravatar.com/igorvepretski',summary:'Public profile connecting several owned accounts and StartOn references. Included as a discovery surface with no promoted reach claims.',status:'WEB DISCOVERY · PUBLIC PROFILE',image:hero,fallback:hero,language:'EN'},
{id:'web-slaps',category:'מוזיקה',source:'Slaps',title:'Igor Vepretski — creator profile',year:'Archive',url:'https://slaps.com/user/igor_vepretski',summary:'Older public creator profile preserving biographical and creative context. Treated as an external archive surface.',status:'WEB DISCOVERY · EXTERNAL PROFILE',image:hero,fallback:hero},
{id:'web-pixnoy',category:'רשתות',source:'Pixnoy',title:'@igor.vepretski — external Instagram index',year:'External snapshot',url:'https://www.pixnoy.com/ru/profile/igor.vepretski/',summary:'Third-party Instagram index found through visual/name discovery. Metrics are not promoted as authoritative; the record is retained only as an external discovery trace.',status:'WEB DISCOVERY · EXTERNAL INDEX · METRICS QUARANTINED',image:hero,fallback:hero,language:'RU'},
{id:'linkedin-articles-index',category:'כתיבה',source:'LinkedIn',title:'Five indexed long-form articles by Igor Vepretski',year:'2022–2024',url:'https://www.linkedin.com/in/vepretski/recent-activity/articles/',summary:'Public LinkedIn index surfaces five authored articles, including “נשאר רק דבר אחד להגשמת החלום”, “כללי המשחק השתנו”, “לבן שלי אין טיקטוק”, “תחיו כאילו הילדים שלכם מתבוננים בכם” and “במשבר החברתי ה״מצטיינים״ אשמים”.',status:'PUBLIC AUTHOR INDEX · WEB VERIFIED',image:hero,fallback:hero},
{id:'web-linktree',category:'רשתות',source:'Linktree',title:'Igor Vepretski — public link index',year:'Public surface',url:'https://linktr.ee/igor.vepretski',summary:'Owned public index connecting social profiles, interviews, media, music and project links. Used as a discovery seed, not as independent evidence for claims.',status:'WEB DISCOVERY · OWNED PUBLIC INDEX',image:hero,fallback:hero,language:'EN'},
{id:'web-izi',category:'רשתות',source:'IZI',title:'Igor Vepretski — IZI public profile',year:'Public surface',url:'https://www.izi.co.il/site/vepretski',summary:'Public profile and historical link surface used to recover legacy embeds and distribution traces.',status:'WEB DISCOVERY · PUBLIC PROFILE',image:hero,fallback:hero},
{id:'web-threads',category:'רשתות',source:'Threads',title:'@igor.vepretski — Threads public profile',year:'Public surface',url:'https://www.threads.net/@igor.vepretski',summary:'Public Threads identity surface retained as an entity-resolution seed and platform route.',status:'WEB DISCOVERY · OFFICIAL PROFILE',image:hero,fallback:hero,language:'EN'},
{id:'starton-guidestar-project',category:'StartOn',source:'GuideStar Israel',title:'STARTON — חללים אינטראקטיביים לנוער בסיכון',year:'2022',url:'https://www.guidestar.org.il/sfc/servlet.shepherd/document/download/0690800000fu29fAAA',summary:'מסמך מוסדי ציבורי בן שלושה עמודים המתאר את מטרות StartOn, מבנה שלושת החללים, מודל הכרטיס והנקודות, אוכלוסיית היעד, יעדי 2024 ושיתופי הפעולה שהוצגו במסמך. נשמר כמסמך תקופתי: הוא מעיד מה הוצהר ותוכנן בזמן הפרסום, לא שכל יעד או שיתוף פעולה אכן הושלם.',status:'INSTITUTIONAL PUBLIC DOCUMENT · VERIFIED',image:hero,fallback:hero},
{id:'starton-izi-archive',category:'StartOn',source:'IZI · StartOn',title:'מתחם נוער אינטראקטיבי — StartOn historical public page',year:'2022–2024',url:'https://www.izi.co.il/site/starton',summary:'עמוד ציבורי היסטורי של StartOn הכולל רקע אישי, הסבר על המיזם וקישורי מדיה. משמש מקור ארכיוני למסלול הפרויקט ול־embedded media, לא כאימות עצמאי של כל טענה בטקסט.',status:'HISTORICAL OFFICIAL PROJECT SURFACE · SUPPORTED',image:hero,fallback:hero}
];