import {forensicImpactLedger} from './media-impact';
export type ImpactLocal={he:string;en:string;ru:string};
export type ImpactSignal={id:string;value:string;label:ImpactLocal;note:ImpactLocal;date:string;scope:string;verification:string;sourceLabel:string;sourceUrl:string;tone:'primary'|'interaction'|'external'|'archive'};
export type ImpactEra={id:string;year:string;kicker:ImpactLocal;title:ImpactLocal;body:ImpactLocal;sourceLabel:string;sourceUrl:string;image?:string;metrics:Array<{value:string;label:ImpactLocal}>;boundary:ImpactLocal};
export type PlatformFootprint={platform:string;handle:string;date:string;sourceUrl:string;evidence:string;metrics:Array<{value:string;label:ImpactLocal}>};
export type QuarantinedImpactClaim={value:string;status:string;note:ImpactLocal};
const L=(he:string,en:string,ru:string):ImpactLocal=>({he,en,ru});
export const impactSignals:ImpactSignal[]=[
{id:'observed-floor',value:forensicImpactLedger.strictObservedExposure.display,label:L('רצפת חשיפה נצפית','Observed exposure floor','Наблюдаемый минимум экспозиции'),note:L('רצפה פורנזית מתוארכת · לא אנשים ייחודיים ולא reach מצטבר','Dated forensic floor · not unique people and not cumulative reach','Датированный форензический минимум · не уникальные люди и не общий reach'),date:'20.08.2026',scope:'STRICT OBSERVED · NON-UNIQUE',verification:'FORENSIC FREEZE',sourceLabel:'FINAL CENSUS FREEZE · 20.08.2026',sourceUrl:'https://7ya.io/evidence/',tone:'primary'},
{id:'engagement-floor',value:'353,829',label:L('רצפת אינטראקציות נראות','Visible engagement floor','Минимум видимых взаимодействий'),note:L('לייקים, תגובות, שיתופים ושמירות שנשמרו בנקודות מדידה · לא חשיפה','Likes, reactions, comments, shares and saves retained in dated measurements · not reach','Лайки, реакции, комментарии, репосты и сохранения в датированных измерениях · не reach'),date:'20.06.2026',scope:'ENGAGEMENT FLOOR · NOT REACH',verification:'EVIDENCE AUDIT',sourceLabel:'Exposure Audit · 20.06.2026',sourceUrl:'https://7ya.io/evidence/',tone:'interaction'},
{id:'external-nawan',value:'5.1M',label:L('צפיות ב־Short חיצוני','External Short views','Просмотры внешнего Short'),note:L('Nawan1 · חשיפה נגזרת אצל יוצר חיצוני · 82K לייקים · 717 תגובות','Nawan1 · derivative exposure on an external creator · 82K likes · 717 comments','Nawan1 · производная экспозиция у внешнего автора · 82K лайков · 717 комментариев'),date:'17.08.2026',scope:'EXTERNAL CREATOR · SOURCE-LOCAL',verification:'VERIFIED SNAPSHOT',sourceLabel:'Nawan1 / YouTube Shorts',sourceUrl:'https://www.youtube.com/shorts/k9haTADKG3M',tone:'external'},
{id:'public-span',value:'15',label:L('שנות עקבה ציבורית','Years of public trail','Лет публичного следа'),note:L('מ־2011 ועד 2026 · עיתונות, וידאו, פוסטים, מוזיקה, שיחות ויוזמות','2011 to 2026 · press, video, posts, music, conversations and initiatives','С 2011 по 2026 · пресса, видео, посты, музыка, разговоры и инициативы'),date:'2011—2026',scope:'PUBLIC RECORD SPAN',verification:'SOURCE-LINKED',sourceLabel:'7YA public canon',sourceUrl:'https://7ya.io/library/',tone:'archive'}
];
export const impactEras:ImpactEra[]=[
{id:'era-2011',year:'2011',kicker:L('נקודת האפס הציבורית','Public zero point','Публичная точка отсчёта'),title:L('לפני הפלטפורמות — הסיפור כבר יצא החוצה.','Before the platforms, the story was already public.','До платформ история уже стала публичной.'),body:L('כתבת מקור ראשון / NRG תיעדה את המסלול האישי שנים לפני TikTok, StartOn ו־7YA. ההשפעה מתחילה בזיכרון ציבורי, לא במספר עוקבים.','A Makor Rishon / NRG profile documented the personal path years before TikTok, StartOn and 7YA. The impact trail begins with public memory, not a follower count.','Публикация Makor Rishon / NRG зафиксировала личный путь задолго до TikTok, StartOn и 7YA. След влияния начинается с публичной памяти, а не со счётчика подписчиков.'),sourceLabel:'Makor Rishon / NRG · 26.04.2011',sourceUrl:'https://www.makorrishon.co.il/nrg/online/54/ART2/235/169.html',metrics:[],boundary:L('מקור עיתונאי מוקדם · ללא ייחוס נתוני reach שלא נמדדו','Early press source · no inferred reach metric','Ранний источник прессы · без выведенного reach')},
{id:'era-2022',year:'2022',kicker:L('תשומת לב → בנייה','Attention → build','Внимание → строительство'),title:L('הסיפור חזר לג׳סי כהן והפך ל־StartOn.','The story returned to Jesse Cohen and became StartOn.','История вернулась в Джесси Коэн и стала StartOn.'),body:L('החזרה לשכונה תועדה בעיתונות, בטלוויזיה ובפודקאסטים. זה הרגע שבו נוכחות ציבורית ניסתה להפוך לתשתית עבור צעירים.','The return to the neighborhood was documented in press, television and podcasts. This is where public attention began turning into infrastructure for young people.','Возвращение в район было зафиксировано в прессе, на телевидении и в подкастах. Здесь публичное внимание стало превращаться в инфраструктуру для молодёжи.'),sourceLabel:'mynet Holon · 13.05.2022',sourceUrl:'https://holon.mynet.co.il/local_news/article/hjxqegkiq',image:'https://pic1.yitweb.co.il/cdn-cgi/image/f%3Dauto%2Cw%3D740%2Cq%3D75/picserver/mynet/crop_images/2022/05/11/r1F0NeKU9/r1F0NeKU9_0_0_640_360_0_large.jpg',metrics:[],boundary:L('סיקור ציבורי מתועד · לא מדד השפעה סיבתי','Documented public coverage · not causal impact proof','Документированное освещение · не доказательство причинного эффекта')},
{id:'era-2023',year:'2023',kicker:L('פוסט → הפצה → שיחה','Post → distribution → conversation','Пост → распространение → разговор'),title:L('אבהות אישית חצתה פלטפורמות.','A personal fatherhood story crossed platforms.','Личная история об отцовстве пересекла платформы.'),body:L('״אבא מושלם — זה אבא ששם״ עבר להפצה חיצונית, יצר אלפי תגובות, הופיע גם ב־LinkedIn והמשיך לכתבה בהידברות. כל צומת נשמר בנפרד.','“A father who is present” moved into external distribution, accumulated thousands of reactions, appeared on LinkedIn and continued into a Hidabroot article. Every node remains separate.','История «Отец, который рядом» ушла во внешнее распространение, собрала тысячи реакций, появилась в LinkedIn и продолжилась публикацией Hidabroot. Каждый узел учитывается отдельно.'),sourceLabel:'Statusim Metzaytzim · external Facebook repost',sourceUrl:'https://www.facebook.com/lan2lan.sta2sim/posts/pfbid0icaS4EV3EFHPbtTaexx3X4Lo9UGQD22Nvm8xzkpJRqiJSLro9D3zNp1PX6SJ26iPl',metrics:[{value:'4.1K',label:L('תגובות רגש','reactions','реакций')},{value:'148',label:L('תגובות','comments','комментариев')},{value:'491',label:L('תגובות רגש במראה LinkedIn','LinkedIn mirror reactions','реакций в LinkedIn-зеркале')},{value:'80',label:L('תגובות במראה LinkedIn','LinkedIn mirror comments','комментариев в LinkedIn-зеркале')}],boundary:L('נתוני Facebook ו־LinkedIn הם snapshots נפרדים; shares נמצאים במחלוקת ולכן אינם מוצגים כאן','Facebook and LinkedIn are separate snapshots; conflicting share counts are intentionally omitted','Facebook и LinkedIn — отдельные снимки; спорное число репостов здесь не показывается')},
{id:'era-2024',year:'2024',kicker:L('יכולת לחזור על הקשב','Repeatable attention','Повторяемое внимание'),title:L('שנה של מיליוני צפיות — בחלון מדידה מוגדר.','A year with millions of views — inside a defined measurement window.','Год с миллионами просмотров — в определённом окне измерения.'),body:L('ריקאפ TikTok שפורסם על ידי איגור תיעד ביצועים שנתיים. הוא נשמר כ־owner analytics recap מתוארך, לא כאומדן של אנשים ייחודיים.','An Igor-published TikTok recap documented annual performance. It is kept as a dated owner analytics recap, not an estimate of unique people.','Опубликованный Игорем TikTok recap зафиксировал годовую динамику. Это датированная owner-analytics запись, а не оценка уникальных людей.'),sourceLabel:'TikTok 2024 recap · owner-published analytics',sourceUrl:'https://www.linkedin.com/posts/vepretski_%D7%98%D7%99%D7%A7%D7%98%D7%95%D7%A7-%D7%99%D7%A9%D7%A8%D7%90%D7%9C%D7%91%D7%99%D7%AA%D7%A0%D7%95-%D7%AA%D7%95%D7%9B%D7%9F%D7%93%D7%99%D7%92%D7%99%D7%98%D7%9C%D7%99-activity-7281298986928328705-ELZL',metrics:[{value:'3.8M',label:L('צפיות','views','просмотров')},{value:'129K',label:L('לייקים','likes','лайков')},{value:'20K',label:L('תגובות','comments','комментариев')},{value:'21K',label:L('שיתופים','shares','репостов')}],boundary:L('חלון שנתי עצמאי · אין לחבר אותו לחלונות אחרים ל־unique reach','Independent annual window · never summed with other windows into unique reach','Отдельное годовое окно · не складывается с другими окнами в unique reach')},
{id:'era-2025',year:'2025',kicker:L('מהירות יוצר','Creator velocity','Скорость автора'),title:L('14 ימים הראו שההשפעה אינה רגע חד־פעמי.','Fourteen days showed the attention was not a one-off moment.','Четырнадцать дней показали, что внимание не было разовым.'),body:L('חלון analytics פומבי שפורסם ב־LinkedIn תיעד 3,877,477 צפיות ו־181,849 אינטראקציות ב־14 ימים. הוא נשאר חלון עצמאי ואינו מצטרף לריקאפ השנתי.','A public analytics window shared on LinkedIn documented 3,877,477 views and 181,849 interactions in fourteen days. It remains its own window and is not added to the annual recap.','Публичное analytics-окно в LinkedIn зафиксировало 3 877 477 просмотров и 181 849 взаимодействий за 14 дней. Оно остаётся отдельным и не складывается с годовым recap.'),sourceLabel:'Owner analytics recap · LinkedIn · 2025',sourceUrl:'https://www.linkedin.com/posts/vepretski_tiktokmarketing-digitalinfluence-personalbranding-activity-7316474020063760384-0aAl',metrics:[{value:'3,877,477',label:L('צפיות · 14 ימים','views · 14 days','просмотров · 14 дней')},{value:'181,849',label:L('אינטראקציות','interactions','взаимодействий')},{value:'4.92%',label:L('שיעור אינטראקציה מדווח','reported interaction rate','заявленный interaction rate')}],boundary:L('Owner analytics · חלון נקודתי · לא total lifetime','Owner analytics · bounded window · not lifetime total','Owner analytics · ограниченное окно · не lifetime total')},
{id:'era-2026',year:'2026',kicker:L('ההשפעה יוצאת מהחשבונות שלך','Impact outside owned accounts','Влияние за пределами собственных аккаунтов'),title:L('5.1M צפיות אצל יוצר אחר — וה־attribution נשאר ברור.','5.1M views on another creator — with attribution intact.','5,1 млн просмотров у другого автора — с ясной атрибуцией.'),body:L('Short של Nawan1 שבו איגור מופיע ומתויג הגיע ל־5.1M צפיות, 82K לייקים ו־717 תגובות. זו חשיפה נגזרת אצל publisher חיצוני, לא צפיות בחשבון בבעלות איגור.','A Nawan1 Short featuring and tagging Igor reached 5.1M views, 82K likes and 717 comments. This is derivative exposure on an external publisher, not views on an Igor-owned account.','Short Nawan1 с участием и отметкой Игоря достиг 5,1 млн просмотров, 82K лайков и 717 комментариев. Это производная экспозиция у внешнего издателя, а не просмотры аккаунта Игоря.'),sourceLabel:'Nawan1 / YouTube Shorts · snapshot 17.08.2026',sourceUrl:'https://www.youtube.com/shorts/k9haTADKG3M',image:'https://i.ytimg.com/vi/k9haTADKG3M/hqdefault.jpg',metrics:[{value:'5.1M',label:L('צפיות חיצוניות','external views','внешних просмотров')},{value:'82K',label:L('לייקים','likes','лайков')},{value:'717',label:L('תגובות','comments','комментариев')}],boundary:L('External creator counter · נגזר, לא owned reach ולא מספר לחיבור למדדים אחרים','External creator counter · derivative, not owned reach and not additive to other metrics','Счётчик внешнего автора · производный, не owned reach и не складывается с другими метриками')}
];
export const platformFootprint:PlatformFootprint[]=[
{platform:'TikTok',handle:'@igor.vepretski',date:'02.06.2026',sourceUrl:'https://www.tiktok.com/@igor.vepretski',evidence:'OWNER EXPORT',metrics:[{value:'12,655',label:L('עוקבים','followers','подписчиков')},{value:'273,860',label:L('לייקים בחשבון','account likes','лайков аккаунта')},{value:'904',label:L('פריטים בייצוא','exported posts','объектов в экспорте')}]},
{platform:'Instagram',handle:'@igor.vepretski',date:'08.06.2026',sourceUrl:'https://www.instagram.com/igor.vepretski/',evidence:'PUBLIC SNAPSHOT',metrics:[{value:'8.2K',label:L('עוקבים','followers','подписчиков')},{value:'1,188',label:L('פוסטים','posts','постов')}]},
{platform:'Facebook',handle:'Igor Ido Vepretski',date:'08.06.2026',sourceUrl:'https://www.facebook.com/igor7vepretski/',evidence:'PUBLIC SNAPSHOT',metrics:[{value:'≈15.5K',label:L('לייקים לעמוד','page likes','лайков страницы')}]},
{platform:'LinkedIn',handle:'Igor Vepretski',date:'08.06.2026',sourceUrl:'https://www.linkedin.com/in/vepretski/',evidence:'PUBLIC SNAPSHOT',metrics:[{value:'4,285',label:L('עוקבים','followers','подписчиков')},{value:'325',label:L('פוסטים','posts','постов')},{value:'5',label:L('מהדורות ניוזלטר','newsletter editions','выпусков рассылки')}]},
{platform:'YouTube',handle:'@IgorVepretski',date:'08.06.2026',sourceUrl:'https://www.youtube.com/channel/UCyxk2AupRjm7KQ5EeWrV1Fw',evidence:'PUBLIC SNAPSHOT',metrics:[{value:'≈2.57K',label:L('מנויים','subscribers','подписчиков')},{value:'334',label:L('סרטונים באינדקס','indexed videos','видео в индексе')}]}];
export const quarantinedImpactClaims:QuarantinedImpactClaim[]=[
{value:'5.1B',status:'SOURCE-PENDING',note:L('טענה היסטורית תחת בדיקת חבילת מקור · לא total reach מאומת','Historical claim under source-package review · not verified total reach','Историческое утверждение на проверке пакета источников · не подтверждённый total reach')},
{value:'6.2B+',status:'SOURCE-PENDING',note:L('אין מתודולוגיית deduplication ציבורית שמאפשרת לפרסם כ־unique reach','No public deduplication methodology supports a unique-reach claim','Нет публичной методологии дедупликации для unique reach')},
{value:'7B',status:'QUARANTINED',note:L('נשמר כהיסטוריית טענה בלבד עד שיוצמד source package שמגן עליה','Retained only as claim history until a defensible source package is attached','Сохраняется только как история утверждения до появления защищаемого пакета источников')}
];
